### ISSUE TITLE
contact.say报错

### ISSUE THREAD

**Issue by leesolar** [wechaty/puppet-service-providers#164]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**
使用name查找到Contact之后，调用contact.say报如下错(puppet_workpro改成假的)
> send msg error Error: 13 INTERNAL: puppet_workpro_54XXXXXXXXXXXXXXXXa2a2b with invalid toUser: S:1688850544150844_0
    at callErrorFromStatus (/wechatydemo/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/wechatydemo/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/wechatydemo/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/wechatydemo/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /wechatydemo/node_modules/@grpc/grpc-js/build/src/resolving-call.js:93:78

代码如下：
> const contact = await bot.Contact.find({name: 'lee'});
   if(contact!=null&&contact!=undefined){
      await contact.say('hello world');
   }
find返回
> -----------find contact: WechatifiedContactSelfImpl {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id: '1688850544150844',
  payload: {
    address: '',
    alias: '',
    avatar: 'https://wework.qpic.cn/wwpic/..........0',
    city: '',
    corporation: '.......',
    coworker: true,
    description: '',
    friend: true,
    gender: 1,
    handle: 'lee',
    id: '1688850544150844',
    name: 'lee',
    phone: [ '' ],
    province: '',
    signature: '',
    star: false,
    title: 'lee',
    type: 3,
    weixin: 'lee'
  },
  [Symbol(kCapture)]: false
}

**Info**

 - Platform[e.g. Windows/Mac/Linux]: linux
 - Runtime version[e.g. node/JAVA]: node
 - Wechaty version: 1.20.2
 - Wechaty Puppet version: 1.19.8

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hcfw007** [comment]
这个是写在login listener里面的吗？

**Comment by hcfw007** [comment]
如果是，请移到ready listener里。workpro需要根据自己托管账号的id和目标id来生成对话id，但ready之前自己的id不一定能获取到，因此造成了对话id （1688850544150844_0）包含0的情况。

**Comment by leesolar** [comment]
> 
是的

**Comment by leesolar** [comment]
> 如果是，请移到ready listener里。workpro需要根据自己托管账号的id和目标id来生成对话id，但ready之前自己的id不一定能获取到，因此造成了对话id （1688850544150844_0）包含0的情况。

刚才发现我搜的好友好像是自己；这样会报错吗？

**Comment by hcfw007** [comment]
不是这个原因，可以搜索自己的。只是在ready之前数据可能没准备好，导致发送不一定能成功。

**Comment by hcfw007** [comment]
给自己发消息也是允许的

**Comment by leesolar** [comment]
>不是这个原因，可以搜索自己的。只是在ready之前数据可能没准备好，导致发送不一定能成功。

什么时候ready？
这个我后来放到httpserver里面手动来调用发消息给自己；还是一样报错

**Comment by hcfw007** [comment]
> > 不是这个原因，可以搜索自己的。只是在ready之前数据可能没准备好，导致发送不一定能成功。
> 
> 什么时候ready？ 这个我后来放到httpserver里面手动来调用发消息给自己；还是一样报错

可以通过 bot.on('ready')事件监听

**Comment by hcfw007** [comment]
> > 不是这个原因，可以搜索自己的。只是在ready之前数据可能没准备好，导致发送不一定能成功。
> 
> 什么时候ready？ 这个我后来放到httpserver里面手动来调用发消息给自己；还是一样报错

后来是多久？一般ready也就一两分钟（看账号大小）。如果过很久可能是有问题。给其他联系人发正常嘛？

**Comment by leesolar** [comment]
>后来是多久？一般ready也就一两分钟（看账号大小）。如果过很久可能是有问题。给其他联系人发正常嘛？

等了至少10分钟；发给其他人正常

**Comment by leesolar** [comment]
> > > 不是这个原因，可以搜索自己的。只是在ready之前数据可能没准备好，导致发送不一定能成功。
> > 
> > 
> > 什么时候ready？ 这个我后来放到httpserver里面手动来调用发消息给自己；还是一样报错
> 
> 可以通过 bot.on('ready')事件监听


我后来加了ready事件；我ready之后；给自己发消息还是同样报错

**Comment by hcfw007** [comment]
那应该是给自己发有点问题，需要看一下

**Comment by leesolar** [comment]
> 那应该是给自己发有点问题，需要看一下

好的，麻烦看一下 谢谢

**Comment by hcfw007** [comment]
这个已定位到问题，应该只会在对自己发消息的时候触发，且只有在从扫码状态登录的token上才会触发。（即如果这个token在服务器启动前（例如更新）就在线了，则不会有问题）。
预计下周二会上线修复。

**Comment by Hamlet626** [comment]
我也遇到同样问题，给任何contact发消息时会出错。但我报错如下
```
10:34:33 ERR Config Wechaty unhandledRejection: Error: 13 INTERNAL: Cannot read properties of null (reading 'isFriend')
    at Object.callErrorFromStatus (/Users/wenjianli/StudioProjects/wechaty/wechaty/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/Users/wenjianli/StudioProjects/wechaty/wechaty/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
    at Object.onReceiveStatus (/Users/wenjianli/StudioProjects/wechaty/wechaty/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/Users/wenjianli/StudioProjects/wechaty/wechaty/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /Users/wenjianli/StudioProjects/wechaty/wechaty/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) [object Promise]
10:34:33 ERR Config ###########################
10:34:33 ERR Config process.on(unhandledRejection) promise.catch(13 INTERNAL: Cannot read properties of null (reading 'isFriend'))
Config Error: 13 INTERNAL: Cannot read properties of null (reading 'isFriend')
    at Object.callErrorFromStatus (/Users/wenjianli/StudioProjects/wechaty/wechaty/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/Users/wenjianli/StudioProjects/wechaty/wechaty/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
    at Object.onReceiveStatus (/Users/wenjianli/StudioProjects/wechaty/wechaty/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/Users/wenjianli/StudioProjects/wechaty/wechaty/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /Users/wenjianli/StudioProjects/wechaty/wechaty/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 13,
  details: "Cannot read properties of null (reading 'isFriend')",
  metadata: Metadata {
    internalRepr: Map(3) {
      'content-type' => [Array],
      'date' => [Array],
      'authorization' => [Array]
    },
    options: {}
  }
}
```

发消息的代码如下
```
const sentMsg=async(contact,content,type)=>{
    switch (type) {
        case 1: const file = FileBox.fromUrl(content);
            await contact.say(file);break;
        case 2: const contactCard = bot.Contact.load(content);
            await contact.say(contactCard);break;
            ///todo:test urlLink
        case 3: const urlLink = bot.UrlLink({description : 'test description',
            thumbnailUrl: 'https://avatars0.githubusercontent.com/u/25162437?s=200&v=4',
            title: 'Profile',
            url: content,  });//await bot.UrlLink.create(content);
            // const urlLink = new UrlLink ({    description : 'WeChat Bot SDK for Individual Account, Powered by TypeScript, Docker, and Love',    thumbnailUrl: 'https://avatars0.githubusercontent.com/u/25162437?s=200&v=4',    title       : 'Welcome to Wechaty',    url         : 'https://github.com/wechaty/wechaty',  });
        await contact.say(urlLink)
            // const msg = await contact.say(urlLink);
            break;
        default: await contact.say(content);break;
    }
}
```

dependency是：
"wechaty": "^1.19.10",
"wechaty-plugin-contrib": "^0.14.23",
"wechaty-puppet": "^1.19.6",
"wechaty-puppet-service": "^1.18.2"

希望能帮组解决，十分感谢！

**Comment by hcfw007** [comment]
这个应该已经修复了，如果春节期间没遇到就关闭了。

**Comment by hcfw007** [comment]
看起来已解决，问题关闭。
