### ISSUE TITLE
[BUG]WorkPro: contactPayload() can not get contact payload by wrong id

### ISSUE THREAD

**Issue by chinacion** [wechaty/puppet-service-providers#166]
room-join 和 room-leave事件报错
13 INTERNAL: contactPayload() can not get contact payload by wrong id: R:10861000981617171

**Comment by hcfw007** [comment]
嗯，这是一个 wechaty 1.x 版本的bug，应该不怎么影响使用，只是会报错。我们正在推动社区版解决这个bug。
相关issue：https://github.com/wechaty/wechaty/issues/2410

**Comment by comeonzhj** [comment]
这是一个回调函数，没办法catch它，node 16下服务就直接重启了。有解么？

**Comment by comeonzhj** [comment]
> 这是一个回调函数，没办法catch它，node 16下服务就直接重启了。有解么？

错误信息可以用bot.on('error') catch 住

**Comment by huan** [comment]
@su-chang is this problem a bug or not? Could you please confirm it? 

CC @hcfw007

**Comment by hcfw007** [comment]
> @su-chang is this problem a bug or not? Could you please confirm it?
> 
> CC @hcfw007

Yes. When ROOM_JOIN or ROOM_LEAVE fires, there will also be dirty for room member. And that lead to https://github.com/wechaty/wechaty/issues/2410
