### ISSUE TITLE
Rock:  receive Room Message throw exception： authentication is empty

### ISSUE THREAD

**Issue by Jesn** [wechaty/puppet-service-providers#17]
## Question

receive Room Message throw exception： authentication is empty

```
Grpc.Core.RpcException:“Status(StatusCode="Aborted", Detail="{"code":19,"msg":"authentication is empty"}",
DebugException="Grpc.Core.Internal.CoreErrorDetailException: 
{"created":"@1607005716.665000000",
"description":"Error received from peer ipv4:114.215.83.32:7777","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\surface\call.cc","file_line":1062,
"grpc_message":"{"code":19,"msg":"authentication is empty"}","grpc_status":10}")”
```

**Comment by jcai** [comment]
I think the wechaty-csharp doesn't support rock !

**Comment by Jesn** [comment]
> 我认为wechaty-csharp不支持摇滚！

 wechaty-csharp for  rock token  running two days, is ok , But it's exception tonight 
and the exception Should be puppet service `T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\surface\call.cc`

**Comment by jcai** [comment]
try again!

**Comment by Jesn** [comment]
> try again!

now, it's working

**Comment by huan** [comment]
Congratulations!
