### ISSUE TITLE
WorkPro:如何判断接收文件的大小？

### ISSUE THREAD

**Issue by comeonzhj** [wechaty/puppet-service-providers#170]
接收到文件类型message时候好像msg.text()是空的，有其他方法可以来判断文件大小么？

**Comment by hcfw007** [comment]
大概是客户期待有一个不下载就能获取到文件基本信息的方式。使用`message.text()`来获取我觉得不是很妥当，社区版wecahty应该也没有`message.preview()`方法，可能需要考虑一下怎么提供。

**Comment by hcfw007** [comment]
https://github.com/wechaty/wechaty/issues/2479

**Comment by huan** [comment]
@hcfw007 You can set the `size` in the FileBox serialization to archive this feature.

See:

https://github.com/huan/file-box/blob/fcae3be890801283ec2790fd57f91d643391517a/src/file-box.ts#L435-L448

**Comment by hcfw007** [comment]
目前可以采用的方案是：
```ts
const fileBox = await message.toFileBox() // 获取 url 的 filebox
await fileBox.ready()
const size = fileBox.size
```

**Comment by hcfw007** [comment]
只要没有调用 `fileBox.toFile`，就没真正下载到bot本地（但其实已经下载到workpro）
