### ISSUE TITLE
No connection established

### ISSUE THREAD

**Issue by HuiminR** [wechaty/puppet-service-providers#172]
![image](https://user-images.githubusercontent.com/26614741/218027921-06c6b5c9-0606-491c-8bba-ec5842ad5c2d.png

**Comment by comeonzhj** [comment]
设置环境变量。目前我们尚不支持 TLS 链接。详情请参考 : https://github.com/wechaty/puppet-service/issues/160

**Comment by hcfw007** [comment]
因为长时间未收到后续回复，issue关闭。
