### ISSUE TITLE
[BUG]WorkPro:登陆成功后，无法接收message

### ISSUE THREAD

**Issue by tangweidali** [wechaty/puppet-service-providers#173]
操作步骤：
1. 测试账号T 加入A公司，扫码登录正常，message接收发送正常。
2. 测试账号T 再加入B公司，扫码登录正常，无message。
3. 测试账号T 退出A公司，扫码登录正常，无message。
4. 测试账号P 加入A公司，扫码登录正常，无message。

上述步骤按时间线依次执行，自从测试账号T加入B公司后，程序就再也没接收到message。

![image](https://user-images.githubusercontent.com/57385890/220584578-2d915c64-4c87-4bd5-93fb-55f321afdee2.png)

![image](https://user-images.githubusercontent.com/57385890/220586005-7699c0ec-b202-4614-8b05-b6f0dc3f1a03.png)

**Comment by hcfw007** [comment]
你有客服微信吗？请联系一下客服提供token，然后我们看看日志。另外可以提供一下没有消息事件的消息案例，最好包含对话时间、内容和联系人名字。

**Comment by hcfw007** [comment]
因为长时间未收到后续回复，issue关闭。
