### ISSUE TITLE
[FEAT]WorkPro: PuppetService Start() rejection: no endpoint

### ISSUE THREAD

**Issue by Garfield-yin** [wechaty/puppet-service-providers#175]
PuppetService Start() rejection: no endpoint

Runtime environment

OS: mac
ARCH: arm
go-wechaty v0.4.9
Console output
go run examples/ding-dong-bot.go
TRAC[2023-02-26 16:05:54.133] PuppetService Start() module=wechaty-puppet-service
ERRO[2023-02-26 16:05:54.941] discoverServiceEndPoint() err: http.Status:404 Not Found module=wechaty-puppet-service
ERRO[2023-02-26 16:05:54.941] puppet start err: PuppetService Start() rejection: no endpoint module=wechaty
panic: PuppetService Start() rejection: no endpoint

goroutine 1 [running]:
github.com/wechaty/go-wechaty/wechaty.(*Wechaty).DaemonStart(0x1400023e240?)
/Users/fei/go/pkg/mod/github.com/wechaty/go-wechaty@v0.4.9/wechaty/wechaty.go:294 +0xc0
main.main()
/Volumes/workspace/caixuan/cx-go-wechaty/examples/ding-dong-bot.go:44 +0xb4
exit status 2
make: *** [bot] Error 1

**Comment by su-chang** [comment]
请提供token给对应客服人员。

**Comment by su-chang** [comment]
@Garfield-yin 该问题是否被解决了？如果解决了请关闭issue，如果尚未解决可以再提供下问题的详细信息。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
