### ISSUE TITLE
[BUG]WorkPro:如何封装为独立发发消息接口（grpc or rest api），供其他服务调用

### ISSUE THREAD

**Issue by Garfield-yin** [wechaty/puppet-service-providers#176]
另一个服务使用了企业微信会话存档。
该服务需要使用 go-wechaty 发送消息。
所以如何只使用 go-wechat 发送消息，并封装接口供其他服务调用，不用来接收消息。
user.Message 能否自己构造直接调用 message.send 方法。

**Comment by su-chang** [comment]
可以选择不监听message事件，但是本质上服务端还是会推送接收到的消息。

可以直接调用message.send方法，但是需要处理好上下文环境，最好使用wechaty封装好的接口来调用。

例如：
```ts
const contact = await bot.Contact.find({id: 'xxx'})
contact.say('hello')
```

**Comment by su-chang** [comment]
@Garfield-yin 该问题是否被解决了？如果解决了请关闭issue，如果尚未解决可以再提供下问题的详细信息。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
