### ISSUE TITLE
[BUG]WorkPro:外部微信添加企业微信时，`friendship.hello()`无法获取到验证消息

### ISSUE THREAD

**Issue by zhegexiaohuozi** [wechaty/puppet-service-providers#177]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

**Info**

 - Platform[e.g. Windows/Mac/Linux]: Mac 
 - Runtime version[e.g. node/JAVA]: python 3.9
 - Wechaty version: 
 - Wechaty Puppet version: 
```
wechaty                0.10.7
wechaty-grpc           0.20.19
wechaty-puppet         0.4.23
wechaty-puppet-service 0.8.10
```

**To Reproduce**

1. 监听加好友事件,代码主体来源于示例，内容如下：
```
async def on_friendship(friendship: Friendship):
    room = await bot.Room.find("机器群测试-2")
    contact = friendship.contact()
    await contact.ready()
    log_msg = f'receive "friendship" message from {contact.name}'
    await room.say(log_msg)

    if friendship.type() == FriendshipType.FRIENDSHIP_TYPE_RECEIVE:
        if friendship.hello() == 'ding':
            log_msg = 'accepted automatically because verify messsage is "ding"'
            print('before accept ...')
            await friendship.accept()
            # if want to send msg, you need to delay sometimes
            print('waiting to send message ...')
            await asyncio.sleep(3)
            await contact.say('你好，欢迎你添加XXX客服号')
            print('after accept ...')
        else:
            log_msg = 'not auto accepted, because verify message is: ' + friendship.hello()

    elif friendship.type() == FriendshipType.FRIENDSHIP_TYPE_CONFIRM:
        log_msg = 'friend ship confirmed with ' + contact.name

    print(log_msg)
    await room.say(log_msg)
```
2. 运行后，用个人微信号添加企业微信好友，并添加验证消息为 `ding`
3. 监听器收到了好友事件，但是`friendship.hello()` 是 `None`
日志输出如下：
```
2023-02-27 11:52:07,836 - FriendShip - INFO - Friendship constructor 7dc8a9xxxx-xxxx-xxxxxxxxxx1a5d7
2023-02-27 11:52:07,836 - FriendShip - INFO - ready() sync the friendship payload
2023-02-27 11:52:07,871 - FriendShip - INFO - get hello message <> of friendship <<wechaty_grpc.wechaty.puppet.FriendshipPayloadResponse object at 0x1114e32e0>>
2023-02-27 11:52:07,872 - Room - INFO - Room find <机器群测试-2>
2023-02-27 11:52:07,872 - Room - INFO - Room find_all <机器群测试-2>
2023-02-27 11:52:07,901 - Room - INFO - Room say <receive "friendship" message from 无XXX, None>
2023-02-27 11:52:08,315 - FriendShip - INFO - get hello message <> of friendship <<wechaty_grpc.wechaty.puppet.FriendshipPayloadResponse object at 0x1114e32e0>>
2023-02-27 11:52:08,315 - FriendShip - INFO - get hello message <> of friendship <<wechaty_grpc.wechaty.puppet.FriendshipPayloadResponse object at 0x1114e32e0>>
not auto accepted, because verify message is: 
2023-02-27 11:52:08,316 - Room - INFO - Room say <not auto accepted, because verify message is: , None>

```
4. 以上

**Expected behavior**

`friendship.hello()`应该可以拿到 `"ding"` 而不是 `None`

**Screenshots**

![2911677479678_ pic](https://user-images.githubusercontent.com/2982325/221491801-76fe347e-3295-4ce3-bbc8-6da341ec6427.jpg)

**Additional context**

**Comment by su-chang** [comment]
@zhegexiaohuozi 请将对应的token提供给客服，我们这边排查下看看，这个功能在node版wechaty 是没有问题的。

还需要补全以下信息：
1. Friendship constructor 7dc8a9xxxx-xxxx-xxxxxxxxxx1a5d7
2. 对应好友的联系人id

**Comment by zhegexiaohuozi** [comment]
> 
@su-chang 
1，2023-02-27 16:35:02,716 - FriendShip - INFO - Friendship constructor aef03a8c-057a-4ab6-8537-510cd595e714

2，2023-02-27 16:35:02,934 - Room - INFO - Room say <receive "friendship" message from 无XXX,and id: 7881300072909116, None>

**Comment by zhegexiaohuozi** [comment]
日志都给你最新的吧

**Comment by su-chang** [comment]
> 2，2023-02-27 16:35:02,934 - Room - INFO - Room say <receive "friendship" message from 无XXX,and id: 7881300072909116, None>

这边看日志没有收到 ding 这样的验证申请消息。可以确认下发送的内容是什么嘛？

**Comment by zhegexiaohuozi** [comment]
> > 2，2023-02-27 16:35:02,934 - Room - INFO - Room say <receive "friendship" message from 无XXX,and id: 7881300072909116, None>
> 
> 这边看日志没有收到 ding 这样的验证申请消息。可以确认下发送的内容是什么嘛？

发送的内容就是截图里面的ding

**Comment by su-chang** [comment]
尝试双方互相删除好友后，在用联系人添加bot为好友试试。

**Comment by zhegexiaohuozi** [comment]
> 尝试双方互相删除好友后，在用联系人添加bot为好友试试。

也是一样的，我把一个完全新的帐号添加企业微信相关截图和日志发你们客服了，你可以看下，这里是公共空间不太方便直接传上来

**Comment by su-chang** [comment]
好的，我们这边内部测试下，今天晚些时候给你回复。

**Comment by zhegexiaohuozi** [comment]
> 好的，我们这边内部测试下，今天晚些时候给你回复。

好的，辛苦

**Comment by su-chang** [comment]
@zhegexiaohuozi 已定位问题，目前会将hello中的内容作为消息推送到客户端，调用`hello()`目前无法获取到具体内容，属于bug，感谢反馈。

我们这边会排期修复，预计下周三会修复上线。若有变动，我们再进行同步。

**Comment by su-chang** [comment]
@zhegexiaohuozi 该问题已修复，正在灰度更新中。

**Comment by su-chang** [comment]
@zhegexiaohuozi 已全量更新。可以测试下看看，如果验证没问题后，请关闭该issue。

**Comment by zhegexiaohuozi** [comment]
> @zhegexiaohuozi 已全量更新。可以测试下看看，如果验证没问题后，请关闭该issue。

没问题了，非常感谢
