### ISSUE TITLE
Rock: unexpected null in message text

### ISSUE THREAD

**Issue by huan** [wechaty/puppet-service-providers#18]
SEE: https://gitter.im/wechaty/wechaty?at=5fc911e6657e0c48225bf5e2

**Comment by jcai** [comment]
I think the bug is in `gitter.im`.The `null` is an emotion icon.

**Comment by huan** [comment]
Here's a screenshot from our WeChat room and it also includes the `null` in the end of the message.

![Screenshot_20201204-121640](https://user-images.githubusercontent.com/1361891/101128532-d71df580-363a-11eb-90c6-6f8bdb76026e.png)

However, I did not see it today anymore, so let's just monitor it and see if it can be reproduced.

**Comment by huan** [comment]
![Screenshot_20201206-095152](https://user-images.githubusercontent.com/1361891/101269327-df943e80-37a8-11eb-97dd-5d9ff7faaf71.png)

Today this issue has appeared again, see the above screenshot.

**Comment by jcai** [comment]
Can you post original message  content ?

**Comment by huan** [comment]
![Screenshot_20201206-141410](https://user-images.githubusercontent.com/1361891/101273088-838fe100-37cd-11eb-8973-a9891d0c691e.png)

I sent a thumb down on my android phone, by quoting the original message.

**Comment by huan** [comment]
I confirmed this issue has been solved with the help of jcai

**Comment by huan** [comment]
Link to #20
