### ISSUE TITLE
[BUG]WorkPro: Error: 14 UNAVAILABLE: Wechaty service discovery / resolution failed for target

### ISSUE THREAD

**Issue by onlylhf** [wechaty/puppet-service-providers#180]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

**Describe the bug**

**Info**

workpro | > wechaty-workpro@1.0.0 start
workpro | > cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node src/workpro.ts
workpro |
workpro | 09:26:13 WARN GrpcManager initClient() TLS: disabled (INSECURE)
workpro | 09:26:15 WARN ResolverWechaty updateResolution() address not found target wechaty://api.chatie.io/puppet_workpro_xxxxx: token does not exist
workpro | 09:26:15 INFO Bot error: Error: 14 UNAVAILABLE: Wechaty service discovery / resolution failed for target wechaty://api.chatie.io/puppet_workpro_xxxxx: token "puppet_workpro_xxx" does not exist
workpro | 09:26:15 WARN ServiceCtl stop() found that is starting...
workpro | 09:26:15 WARN ServiceCtl stop() found that is starting, waiting stable ... (max 5 seconds)
workpro | 09:26:16 WARN ResolverWechaty updateResolution() address not found target wechaty://api.chatie.io/puppet_workpro_xxx: token does not exist
workpro | 09:26:20 INFO Bot error: DEADLINE_EXCEEDED: Timeout after 5000 ms
workpro | 09:26:20 WARN ServiceCtl stop() found that is starting, waiting stable ... timeout
workpro | 09:26:21 WARN ResolverWechaty updateResolution() address not found target wechaty://api.chatie.io/puppet_workpro_xxx: token does not exist
workpro | 09:26:21 INFO Bot error: Error: 14 UNAVAILABLE: Wechaty service discovery / resolution failed for target wechaty://api.chatie.io/puppet_workpro_xxx token "puppet_workpro_xxx" does not exist
workpro | 09:26:21 INFO Bot error: Error: 14 UNAVAILABLE: Wechaty service discovery / resolution failed for target wechaty://api.chatie.io/puppet_workpro_xxx: token "puppet_workpro_xxxx" does not exist
workpro | 09:26:21 INFO StarterBot Starter Bot Started.

**To Reproduce**

设置了 WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true 依然无效
 token  在有效期

**Comment by su-chang** [comment]
把token提供给销售，然后我们看下具体问题。

**Comment by su-chang** [comment]
@onlylhf 该问题是否被解决了？如果解决了请关闭issue，如果尚未解决可以再提供下问题的详细信息。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
