### ISSUE TITLE
[BUG]WorkPro: 无法查找房间，显示“Room findAll() rejected: no grpc manager”

### ISSUE THREAD

**Issue by Hamlet626** [wechaty/puppet-service-providers#181]
**Describe the bug**

查找房间，Contact时显示“Room findAll() rejected: no grpc manager”，
return 回来是空的List []

**Info**

用的dependency：
"wechaty": "^1.19.10",
"wechaty-plugin-contrib": "^0.14.23",
"wechaty-puppet": "^1.19.6",
"wechaty-puppet-padlocal": "^1.20.1",
"wechaty-puppet-service": "^1.18.2"

**To Reproduce**

使用 bot.Room.findAll() 或者 Contact都会出现

**Expected behavior**

返回群组List

**Screenshots**

![Screen Shot 2023-03-03 at 12 01 51 PM](https://user-images.githubusercontent.com/26908521/222815513-b7164a1a-96d3-4db9-a2e7-d3cb693b20d9.png)

**Additional context**

之前一个月成功过，这个月刚续费token，然后bot显示也是登陆的，但出现这个问题。
希望可以解决，谢谢！

**Comment by su-chang** [comment]
重启下服务看看连接是否正常？最好把token发给客服，然后我们这边看下连接状态。

**Comment by su-chang** [comment]
已经定位到问题原因，等待排期修复。

可以先尝试使用@juzi/wechaty

**Comment by Hamlet626** [comment]
好的，谢了，之后问了下客服，说.env加上了一个WECHATY_PUPPET_SERVICE_AUTHORITY。之后重开一次暂时没出现过，谢了
