### ISSUE TITLE
[FEAT]WorkPro: room-join 事件，invitee.handle() 无法取到值

### ISSUE THREAD

**Issue by onlylhf** [wechaty/puppet-service-providers#183]
在room-join 事件中，invitee.handle() 存在获取不到值的情况，之前版本是可以获取到的，经观察该值和企业微信内的ueserid是一致的，这样可以基于企业微信开放平台进行后续开发动作，无法获取到值，导致无法与企业微信开放平台进行对接。

示例代码：

```

bot.on('room-join', async (room, inviteeList, inviter) => {

  const datetime = new Date().getTime()
  const list = []
  const roomId = room.id
  const topic = await room.topic()
  const roomHandle = room.handle()
  const inviterHandle = inviter.handle()
  const inviterId = inviter.id
  const inviterName = inviter.name()

  // log.info(JSON.stringify(inviteeList))

  for (const invitee of inviteeList) {

    const inviteeHandle = invitee.handle()
    const inviteeId = invitee.id
    const inviteeName = invitee.name()

    const invitationInformation = {
      chatId:roomHandle, // 群ID
      chatName:topic,  // 群名称
      invitorUserId:inviterHandle, // 邀请人userid
      invitorUserName:inviterName,  // 邀请人

      memberJoinTime:datetime,  // 时间
      memberUserId:inviteeHandle, //  受邀人userid
      memberUserName:inviteeName, // 受邀人昵称
    }
    list.push(invitationInformation)

    log.info('room-join', `本群名称: ${topic} 本群id: ${roomHandle} 受邀人昵称: ${inviteeName} 受邀人userid: ${inviteeHandle} 受邀人id: ${inviteeId} 邀请人昵称: ${inviterName} 邀请人userid: ${inviterHandle}邀请人id: ${inviterId}`)
  }

  log.info('room-join', JSON.stringify(list))
  await postMiddlePlatform(list)
})
```

期望值：
本群id: wr1TRDBgAAmq_xxxxxxxxxxx  受邀人昵称: 赵xxxx 受邀人userid: wm1TRDBgAAUrdqPW9Rxxxxxxxxxxx 受邀人id: 7881299779 邀请人昵称: aaaaaa 邀请人userid: wm1TRDBgAAGRTALIlxf11ymkt3KSEb0g邀请人id: 7881303304

现在取到的值：
本群id: wr1TRDBgAAmq_xxxxxxxxxxx 受邀人昵称: 依xxxx 受邀人userid:  受邀人id: 788130310 邀请人昵称: bbbbbbb 邀请人userid: wm1TRDBgAAocsoWxxxxxxxxx 邀请人id: 78812995

ID相关数据进行了删减

**Comment by su-chang** [comment]
@onlylhf 感谢反馈。近期由于企业微信官方对获取externalUserId（形如：wm1TRDBgAAUrdqPW9Rxxxxxxxxxxx）的逻辑做了调整，目前对于未建立好友关系的联系人，无法获取到对应的externalUserId。

故此，该问题暂时无解。

**Comment by onlylhf** [comment]
> @onlylhf 感谢反馈。近期由于企业微信官方对获取externalUserId（形如：wm1TRDBgAAUrdqPW9Rxxxxxxxxxxx）的逻辑做了调整，目前对于未建立好友关系的联系人，无法获取到对应的externalUserId。
> 
> 故此，该问题暂时无解。

哦哦，好的，了解了，多谢

**Comment by su-chang** [comment]
没事，如果针对该问题没有其他疑问，请关闭该issue

**Comment by hcfw007** [comment]
超过一周没有后续回复，issue关闭。
