### ISSUE TITLE
Other: 安装老报错

### ISSUE THREAD

**Issue by qlwbob** [wechaty/puppet-service-providers#187]
## Question
这个错误怎么解决
![image](https://user-images.githubusercontent.com/28225157/224929536-99458024-026c-4677-954f-576cf729b03b.png)
安装的时候老是报这个错误
npm ERR! code 1
npm ERR! path D:\getting-started-main\node_modules\frida
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
npm ERR! prebuild-install warn install read ECONNRESET
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.19.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.7.9 found at "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure

**Comment by windmemory** [comment]
Please read the error message carefully, it is telling you that you need to install the latest version of Visual Studio.
