### ISSUE TITLE
[BUG]WorkPro/wechaty: 发送多条信息时，顺序错乱

### ISSUE THREAD

**Issue by drjinying** [wechaty/puppet-service-providers#188]
是我们自己的coding bug，谢谢！

问题：
在onMessage里，使用一个for循环发送多条信息，每条使用await msg.say("xxx"). 但微信端收到的信息顺序是随机的。
这个目的是用来把一大段话打散成若干回复。

尝试在每个await msg.say()后面添加等待0.5秒，无效。

重现环境：
使用WorkPro的试用token，基于chatgpt的示例代码改写

**Comment by drjinying** [comment]
测试场景：bot在群里回复群聊。

**Comment by hcfw007** [comment]
请找客服提供token和issue编号，需要查询日志。

**Comment by drjinying** [comment]
已经提供给客服数日，请问bug有没有更新？试用期马上结束，在决定要不要转付费版。

**Comment by hcfw007** [comment]
目前没有更新。我们这里测试也没有复现这个问题。如果客服没有反应可能是被封了，麻烦加下这个企微再提供下token和issue号。

![img_v2_eb153a50-21c9-46c8-b249-b851a06b620g](https://user-images.githubusercontent.com/13669999/226230033-2fbad0bd-ec20-4f0d-a103-d254e6adebc0.png)

**Comment by hcfw007** [comment]
如果需要可以给你再续试用一周的

**Comment by drjinying** [comment]
谢谢响应，使我们自己的bug，打扰！

**Comment by Wangerya** [comment]
请问是如何解决的 我也遇到了同样的问题

**Comment by Wangerya** [comment]
@drjinying 请教一下是如何解决的 我也遇到了同样的问题
