### ISSUE TITLE
[BUG]WorkPro: 无法查找房间，显示“Room findAll() rejected: no grpc manager”

### ISSUE THREAD

**Issue by Hamlet626** [wechaty/puppet-service-providers#189]
Describe the bug

查找房间，Contact时显示“Room findAll() rejected: no grpc manager”，
return 回来是空的List []

同样问题，见之前post https://github.com/wechaty/puppet-supports/issues/181

**Comment by hcfw007** [comment]
这个说明你与服务器的连接断开了。建议用errorListener打印日志，看看是否有连接断开的日志。

**Comment by Hamlet626** [comment]
> 这个说明你与服务器的连接断开了。建议用errorListener打印日志，看看是否有连接断开的日志。

@hcfw007 Hello 老兄你好，error按时间顺序从早到最近有以下几个：
* Error: 1 CANCELLED: Call cancelled
* Error: WatchdogAgent reset: lastFood: "{"data":"regular heartbeat","timeoutMilliseconds":60000}"
* Error: 14 UNAVAILABLE: No connection established
* Error: 14 UNAVAILABLE: Wechaty service discovery / resolution failed for target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_MYTOKEN: token "puppet_workpro_MYTOKEN" does not exist
* DEADLINE_EXCEEDED: Timeout after 5000 ms 
* Error: no grpc manager

请问下能帮忙看下什么问题吗，谢了。然后问下为什么会与服务器断开吗（之中应该没做什么操作），谢了

**Comment by Hamlet626** [comment]
然后可以问下之前那个post那个老兄说的 “可以先尝试使用@juzi/wechaty” 是怎么用吗，或者现在有什么方法可以防止断开或者怎么断开后立即解决（重连？）吗，谢了？

**Comment by hcfw007** [comment]
使用@juzi/wechaty的方法：将所有wechaty的依赖替换为@juzi
例如：wechaty -> @juzi/wechaty, wechaty-puppet-service -> @juzi/wechaty-puppet-service

断开是指grpc长连接（stream）断开。这个是无法完全避免的。我们采取的方案是，在errorListener里对特定错误码进行监控，遇到之后重启bot。
参考-需要重启的错误列表
```ts
const resetErrorList = [
  '14 UNAVAILABLE',
  'no grpc manager',
  'NO CLIENT',
];
```
参考-重启的方法
```ts
await bot.reset()
```

**Comment by Hamlet626** [comment]
好的，谢了，我试下.
可以再问下，这个reset完是要wecom重新登陆吗，还是不用吗？

**Comment by hcfw007** [comment]
不需要扫码的，但对于client端相当于重新登录了（会有新的login和ready事件过来）。

**Comment by Hamlet626** [comment]
好的多谢了
