### ISSUE TITLE
WorkPro: 可以创建External群吗

### ISSUE THREAD

**Issue by Hamlet626** [wechaty/puppet-service-providers#191]
问下WorkPro可以创建external群吗，就是微信和企业微信用户都可以加的那种群，谢了？
可以的话怎么创建吗？

**Additional context**

我用bot.Room.create只能创建 一般的企业微信用户才能加的群。

**Comment by hcfw007** [comment]
可以，但是创建外部群聊需要初始就有外部成员才行，也就是创建的时候就必须包含一些个人微信联系人。

**Comment by Hamlet626** [comment]
好的了解，谢谢了
