### ISSUE TITLE
[BUG]WorkPro: Token does not exist

### ISSUE THREAD

**Issue by Yat3s** [wechaty/puppet-service-providers#192]
Just got a token from Juzibot but it shows "token does not exist”

![image](https://user-images.githubusercontent.com/14801837/227762193-9fb17de8-57cb-47e6-b2f5-a6ba61c7a044.png)

```
const bot = WechatyBuilder.build({
  name: 'Test',
  puppet: 'wechaty-puppet-service',
  puppetOptions: {
    token: process.env.WECHATY_TOKEN,
  }
})

bot.on('scan', onScan)
bot.on('login', onLogin)
bot.on('logout', onLogout)
bot.on('message', onMessage)

bot
  .start()
  .then(() => log.info('StarterBot', 'Starter Bot Started.'))
  .catch(e => log.error('StarterBot', e))
```

**Info**

 - Platform[e.g. Windows/Mac/Linux]: Mac
 - Runtime version[e.g. node/JAVA]: node
 - Wechaty version:  `1.20.2`
 - Wechaty Puppet version:  `1.20.2`

**Comment by Yat3s** [comment]
Tried `export WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true` and disabling TLS via `options.tls.disable = true` but still doesn't work.

**Comment by hcfw007** [comment]
Can you contact with customer service of Juzi ( you can find the contact detail in the pined issue) and provide the token and issue number so we can look into it please?

**Comment by Yat3s** [comment]
@hcfw007 I'm reaching out to Juzibot but seems like it's OOF now.

**Comment by su-chang** [comment]
@Yat3s If this issue has been resolved, please close it, thanks.

**Comment by wwz223** [comment]
我也遇到了同样的问题

**Comment by wwz223** [comment]
请问这是什么原因，如何解决

**Comment by Yat3s** [comment]
@wwz223 Seems like it's a service issue, you can reach out to Juzibot to address it.

**Comment by wwz223** [comment]
手动重启是可以解决的，但是不知道问题是怎么引起的

**Comment by Yat3s** [comment]
@wwz223 Try to disable `tls`
```
const bot = WechatyBuilder.build({
  name: 'Test',
  puppet: 'wechaty-puppet-service',
  puppetOptions: {
    token: process.env.WECHATY_TOKEN,
    tls: {
      disable: true,
    },
  },
});
```

**Comment by wwz223** [comment]
> @wwz223尝试禁用`tls`
> 
> ```
> const bot = WechatyBuilder.build({
>   name: 'Test',
>   puppet: 'wechaty-puppet-service',
>   puppetOptions: {
>     token: process.env.WECHATY_TOKEN,
>     tls: {
>       disable: true,
>     },
>   },
> });
> ```

我的程序也是这么配置的
