### ISSUE TITLE
WXWork: 某个企业微信账号用了几天不能登录

### ISSUE THREAD

**Issue by zhzhliang** [wechaty/puppet-service-providers#193]
Please make sure you have read the [Wechaty Puppet Service: WXWork](https://wechaty.js.org/docs/puppet-services/wxwork) from Wechaty Official Website before you continue writting this issue.

## Question

某个企业微信账号用了几天workpro后不能登录wechaty了。企业微信客户端/PC端登录均OK。

日志：
10:54:59 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_SCAN(22), payload(len:113)})
10:54:59 VERB StateSwitch <WechatyReady> inactive(true) <- (true)
10:54:59 INFO StarterBot onScan: Scanned(3)
10:55:00 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_SCAN(22), payload(len:113)})
10:55:00 VERB StateSwitch <WechatyReady> inactive(true) <- (true)
10:55:00 INFO StarterBot onScan: Confirmed(4)
10:55:01 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_SCAN(22), payload(len:113)})
10:55:01 VERB StateSwitch <WechatyReady> inactive(true) <- (true)
10:55:01 INFO StarterBot onScan: Waiting(2) - https://wechaty.js.org/qrcode/https%3A%2F%2F....

扫码Confirmed后，又收到了EVNET_TYPE_SCAN，不等登录。

**Comment by su-chang** [comment]
这个是workpro的问题，把token发给客服，我们处理后可以正常登录。

联系客服参见：https://github.com/wechaty/puppet-supports/issues/190

**Comment by hcfw007** [comment]
因为长时间没有回复，issue关闭。
