### ISSUE TITLE
[BUG]WorkPro:Error: 14 UNAVAILABLE: No connection established

### ISSUE THREAD

**Issue by ahujack** [wechaty/puppet-service-providers#194]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

**Info**

 - Platform[e.g. Windows/Mac/Linux]:  mac
 - Runtime version[e.g. node/JAVA]:node
 - Wechaty version: 1.20.2
 - Wechaty Puppet version: 1.18.4

**To Reproduce**

const bot =  WechatyBuilder.build({
  name: "wechat-assistant", // generate xxxx.memory-card.json and save login data for the next login
  puppet: "wechaty-puppet-wechat",
  //puppet: "wechaty-puppet-service",
  puppetOptions: {
    uos: true,
   // token: "puppet_workpro_xxxx"
  }
});
console.log(`init success`);

async function main() {
  const initializedAt = Date.now()
  bot
    .on("scan",async (qrcode, status) => {
      const url = `https://api.qrserver.com/v1/create-qr-code/?data=/${encodeURIComponent(qrcode)}`;
      console.log(`Scan QR Code to login: ${status}\n${url}`);
      console.log(
        await QRCode.toString(qrcode, { type: "terminal", small: true })
      );

**Expected behavior**
当我使用  puppet: "wechaty-puppet-wechat"的时候是可以连接上的，但是我换成puppet: "wechaty-puppet-service",以后就连接不上了，再bot.on("scan")这一步就会失败，是因为service没法访问https://api.qrserver.com/v1/create-qr-code/?data= 吗？

**Screenshots**

**Additional context**

**Comment by hcfw007** [comment]
这个报错一般是由于tls未正确配置导致的。需要添加环境变量 
```
export WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true
```
可以参考 https://github.com/wechaty/wechaty/issues/2462 tls相关部分。

**Comment by ahujack** [comment]
这个设置了的，还是不行

**Comment by hcfw007** [comment]
在你提供的代码中，token这一配置是注释的。实际代码也是这样吗？

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
