### ISSUE TITLE
[FEAT]WorkPro:FileBox

### ISSUE THREAD

**Issue by yangningmoojing** [wechaty/puppet-service-providers#196]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

**Info**

 - Platform[e.g. Windows/Mac/Linux]: 
 - Runtime version[e.g. node/JAVA]:
 - Wechaty version: 
 - Wechaty Puppet version: 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hcfw007** [comment]
Please describe your problem.

**Comment by hcfw007** [comment]
因为没有描述问题内容，关闭issue。
