### ISSUE TITLE
[FEAT]WorkPro:发送图片，发送不出去，文字可以发送

### ISSUE THREAD

**Issue by yangningmoojing** [wechaty/puppet-service-providers#198]
bot = Wechaty()

class MyBot(Wechaty):
    async def on_message(self, msg):
        # 文本消息内容
        text = msg.text()
        if text == "ding":
            file_box = FileBox.from_file('ding.jpg')
            await msg.say(file_box)

asyncio.run(MyBot().start())

**Comment by hcfw007** [comment]
这是什么语言的wechaty？这边建议使用TS版本的，其他版本的可能并未跟随最新版标准。

**Comment by yangningmoojing** [comment]
> 

python的，只能发送信息文本，图片文件，接收发送都报错，2023-04-13 17:35:07,908 - Wechaty - ERROR - internal error <>

**Comment by huan** [comment]
I'd like to file an issue at the Python Wechaty repo and link to this issue as well because it might be related to the Python code base.

**Comment by hcfw007** [comment]
非TS版的我们无法提供帮助，请理解。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
