### ISSUE TITLE
 Rock: A new puppet  hostie service provider

### ISSUE THREAD

**Issue by jcai** [wechaty/puppet-service-providers#2]
### 1. What is Rock?
  Rock  is a new puppet hostie service provider,so you can use  all features from wechaty-puppet-hostie.
 
 
 ### 2. What is Wechaty Puppet Rock Service Token
To use the rock puppet service,you can apply for rock token from Juzi.Bot (wechat:` juzibot`).

### 3. How to use rock token.

 To use the token with rock service, the following commands demonstrated how to use it under Linux/macOS:
 
### Example
```ts
import { Wechaty } from 'wechaty'
import { ScanStatus } from 'wechaty-puppet'
import QrcodeTerminal from 'qrcode-terminal';

const token = 'PUT_YOUR_TOKEN_HERE'

const bot = new Wechaty({
  puppet: 'wechaty-puppet-hostie',
  puppetOptions: {
    token
  }
});

bot
  .on('scan', (qrcode, status) => {
    if (status === ScanStatus.Waiting) {
      QrcodeTerminal.generate(qrcode, {
        small: true
      })
    }
  })
  .on('login', async user => {
    console.log(`user: ${JSON.stringify(user)}`)
  })
  .on('message', async message => {
    console.log(`message: ${JSON.stringify(message)}`)
  })
  .start()
```

 See:
 
 1. [Wechaty Starter Project Template that works out-of-the-box](https://github.com/wechaty/wechaty-getting-started)

### 4. Multi-language supported.

1. go:  need later version 0.2.0 (see https://github.com/wechaty/go-wechaty/issues/69 )
2. python:need later version 0.4.1 (see https://github.com/wechaty/python-wechaty-puppet-hostie/issues/35)  
3. java: see https://github.com/wechaty/java-wechaty/issues/77

### 5. How to get supports.
 Please ask your question by file an issue at https://github.com/wechaty/puppet-service-providers/issues/new?assignees=jcai&labels=rock&template=rock.md&title=Rock%3A+

**Comment by huan** [comment]
If you want to use pad protocol, the Rock puppet is a must-try!

Thank @jcai for providing this great WeChat Pad Protocol puppet service to our community!
