### ISSUE TITLE
[BUG]WorkPro:

### ISSUE THREAD

**Issue by 1061168609** [wechaty/puppet-service-providers#202]
测试token报错
WARN ResolverWechaty updateResolution() address not found target 
16:19:44 ERR StarterBot Error: 14 UNAVAILABLE: Wechaty service discovery / resolution failed for target

**Comment by hcfw007** [comment]
查询发现这个token的发现服务注册地址是token-service-discovery-test.juzibot.com，需要配合环境变量 WECHATY_PUPPET_SERVICE_AUTHORITY=token-service-discovery-test.juzibot.com使用。
另外不建议在issue中把完整token发出来。

**Comment by 1061168609** [comment]
好的 谢谢

**Comment by 1061168609** [comment]
已解决 谢谢
