### ISSUE TITLE
[FEAT]WorkPro:是否支持发送朋友圈

### ISSUE THREAD

**Issue by wwz223** [wechaty/puppet-service-providers#203]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

**Info**

 - Platform[e.g. Windows/Mac/Linux]: 
 - Runtime version[e.g. node/JAVA]:
 - Wechaty version: 
 - Wechaty Puppet version: 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hcfw007** [comment]
支持，但需要配合@juzi/scope下的wechaty使用。
方法是使用@juzi/wechaty和@juzi/wechaty-puppet-service替代wechaty和wechaty-puppet-service包。发送朋友圈的方法可以参考：https://juzihudong.feishu.cn/wiki/wikcnO7MyGoTUtlRTUnw708TRah

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。

**Comment by RolloTomasiii** [comment]
> 

您好，我想基于低版本的wechaty开发一下我朋友圈功能，如果您看到这条消息，麻烦联系我，有偿的，我微信AIYLWL

**Comment by RolloTomasiii** [comment]
> 支持，但需要配合@juzi/scope下的wechaty使用。 方法是使用@juzi/wechaty和@juzi/wechaty-puppet-service替代wechaty和wechaty-puppet-service包。发送朋友圈的方法可以参考：https://juzihudong.feishu.cn/wiki/wikcnO7MyGoTUtlRTUnw708TRah


您好，我想基于低版本的wechaty开发一下我朋友圈功能，如果您看到这条消息，麻烦联系我，有偿的，我微信AIYLWL

**Comment by RolloTomasiii** [comment]
> 支持，但需要配合@juzi/scope下的wechaty使用。 方法是使用@juzi/wechaty和@juzi/wechaty-puppet-service替代wechaty和wechaty-puppet-service包。发送朋友圈的方法可以参考：https://juzihudong.feishu.cn/wiki/wikcnO7MyGoTUtlRTUnw708TRah

基于wechaty v0.65.15

**Comment by RolloTomasiii** [comment]
> 支持，但需要配合@juzi/scope下的wechaty使用。 方法是使用@juzi/wechaty和@juzi/wechaty-puppet-service替代wechaty和wechaty-puppet-service包。发送朋友圈的方法可以参考：https://juzihudong.feishu.cn/wiki/wikcnO7MyGoTUtlRTUnw708TRah

以下为项目的仓库地址 https://github.com/wechaty/wechaty/tree/5ad6690951f59a6ed067ede40a967e7fd6cfb848

**Comment by hcfw007** [comment]
我们不建议使用低版本wechaty连接workpro token，已知的兼容性问题包括：发送文件类型消息一定会失败。在群成员数据更新上有问题等。

**Comment by RolloTomasiii** [comment]
> 我们不建议使用低版本wechaty连接workpro token，已知的兼容性问题包括：发送文件类型消息一定会失败。在群成员数据更新上有问题等。

业务场景很简单，不会有很复杂的消息类型，我只想在wechaty v0.65.15上增加一个发布朋友圈的功能，提供付费开发，或者希望您给我一些开发思路上的指导

**Comment by RolloTomasiii** [comment]
> 暂无反馈，关闭该issue。

我了解到wechaty的朋友圈功能是您主导设计并研发的，可以分享给我一些经验吗，或者我想请您帮我研发

**Comment by hcfw007** [comment]
再次建议使用 @juzi scope 的包，比较方便。
如果自己想实现的话，如果希望实现方式符合 wechaty 的风格，可以参考 @juzi/wechaty 包下面 publish 方法的实现。这些包也都是开源的。如果无所谓风格只是想快速实现，只要看 @juzi/wechaty-grpc 下面 moment 相关方法，构造符合 proto 的请求即可调用。

**Comment by RolloTomasiii** [comment]
> 再次建议使用 @juzi scope 的包，比较方便。 如果自己想实现的话，如果希望实现方式符合 wechaty 的风格，可以参考 @juzi/wechaty 包下面 publish 方法的实现。这些包也都是开源的。如果无所谓风格只是想快速实现，只要看 @juzi/wechaty-grpc 下面 moment 相关方法，构造符合 proto 的请求即可调用。

这是我微信AIYLWL，非常希望和您在wechaty项目上有价值探讨

**Comment by RolloTomasiii** [comment]
> 再次建议使用 @juzi scope 的包，比较方便。 如果自己想实现的话，如果希望实现方式符合 wechaty 的风格，可以参考 @juzi/wechaty 包下面 publish 方法的实现。这些包也都是开源的。如果无所谓风格只是想快速实现，只要看 @juzi/wechaty-grpc 下面 moment 相关方法，构造符合 proto 的请求即可调用。

我是一名python开发工程师，因为架构原因只能使用v0.65版本的wechaty，为此我学习了typescript，在二次开发了部分功能后，对于最后一个需求“发布朋友圈”碰壁，对我来说实在是太难了，但这是最后一个困难，实在不想放弃
