### ISSUE TITLE
[FEAT]WorkPro:用node.js安装官方的demo 依赖报错 

### ISSUE THREAD

**Issue by wsaisai** [wechaty/puppet-service-providers#209]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/wechaty/puppet-supports/assets/24635003/b132b298-e17f-450a-9bc9-9673dbca3a0e)
从github 将官方的demo地址colone到本，先将node版本从14升到16，npm i 的时候会报这个关于python的错误 我把本地的python版本升级到3.1还是安装不上，能帮忙看看是什么情况吗 让我本地先运行起来项目

**Comment by hcfw007** [comment]
这个是安装第三方依赖包时连接 192.30.253.112:443 超时造成的。
请尝试使用科学上网。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
