### ISSUE TITLE
[BUG]WorkPro:使用wechaty-puppet-service无法接收到语音消息

### ISSUE THREAD

**Issue by gzmasterpulse** [wechaty/puppet-service-providers#211]
项目环境采用TS开发，wechaty-puppet-service版本为1.18.2，语音消息发送过来后会触发事件，payload内容中filename为空，如下所示：
{
  filename: '',
  id: '1000477',
  listenerId: '',
  mentionIdList: [],
  roomId: 'R:10709689835021571',
  talkerId: '1688850661771514',
  text: '',
  timestamp: 1684739145477,
  type: 2
}
在代码中我使用 const fileName=(await msg.toFileBox()).name 控制台直接输出如下提示：
15:18:53 WARN PuppetService messageFile() rejection: 13 INTERNAL: WorkproErrorCode: 23020, messageFile(1000483) cannot get download stream for content type: 21
15:18:53 WARN PuppetService This might because you are using Wechaty v1.x with a Puppet Service v0.x
Contact your Wechaty Puppet Service provided to report this problem
Related issues:
 - https://github.com/wechaty/puppet-service/issues/179
 - https://github.com/wechaty/puppet-service/pull/170

**Comment by su-chang** [comment]
@gzmasterpulse 这个语音消息是通过什么方式发送的？有啥特殊的地方么？

目前是服务端针对 `contentType: 21` 这种情况的语音消息没有支持下载的操作。

希望能够提供复现的方式，以便我们排查定位问题。

**Comment by hcfw007** [comment]
因为没有收到后续反馈，issue关闭。
