### ISSUE TITLE
[BUG]WorkPro:使用企微报错

### ISSUE THREAD

**Issue by yinshipeng** [wechaty/puppet-service-providers#212]
11:09:05 WARN GrpcManager initClient() TLS: disabled (INSECURE)
{"code":1,"details":"Call cancelled","level":"error","message":"1 CANCELLED: Call cancelled","name":"Error","stack":"Error: 1 CANCELLED: Call cancelled\n    at callErrorFromStatus (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/call.ts:81:17)\n    at Object.onReceiveStatus (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client.ts:356:55)\n    at Object.onReceiveStatus (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client-interceptors.ts:455:34)\n    at Object.onReceiveStatus (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)\n    at /Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)\nfor call at\n    at ServiceClientImpl.makeUnaryRequest (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client.ts:326:30)\n    at ServiceClientImpl.start (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)\n    at node:internal/util:375:7\n    at new Promise (<anonymous>)\n    at bound  (node:internal/util:361:12)\n    at GrpcManager.start (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/wechaty-puppet-service@1.19.9_jkyvhh2danr4dcnhzsykeo22pa/node_modules/wechaty-puppet-service/src/client/grpc-manager.ts:170:6)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PuppetService.onStart (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/wechaty-puppet-service@1.19.9_jkyvhh2danr4dcnhzsykeo22pa/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:173:5)\n    at async PuppetService.start (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/state-switch@1.7.1_tcppfhatzsoz34uwt475ldw2ga/node_modules/state-switch/src/service-ctl/service-ctl.ts:89:9)\n    at async PuppetService.start (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/wechaty-puppet@1.20.2/node_modules/wechaty-puppet/src/mixins/service-mixin.ts:34:7)","timestamp":"2023-05-24 11:09:05"}
11:09:05 WARN ServiceCtl<PuppetServiceMixin> stop() found that is starting...
11:09:05 WARN ServiceCtl<PuppetServiceMixin> stop() found that is starting, waiting stable ... (max 5 seconds)
{"code":4,"details":"GError: Timeout after 5000 ms\n    at Function.from (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/gerror@1.0.16/node_modules/gerror/src/gerror/gerror.ts:69:17)\n    at Timeout._onTimeout (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/gerror@1.0.16/node_modules/gerror/src/timeout-promise/timeout-promise.ts:26:36)\n    at listOnTimeout (node:internal/timers:569:17)\n    at processTimers (node:internal/timers:512:7)","level":"error","message":"Timeout after 5000 ms","name":"DEADLINE_EXCEEDED","stack":"GError: Timeout after 5000 ms\n    at Function.from (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/gerror@1.0.16/node_modules/gerror/src/gerror/gerror.ts:69:17)\n    at Timeout._onTimeout (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/gerror@1.0.16/node_modules/gerror/src/timeout-promise/timeout-promise.ts:26:36)\n    at listOnTimeout (node:internal/timers:569:17)\n    at processTimers (node:internal/timers:512:7)","timestamp":"2023-05-24 11:09:10"}
11:09:10 WARN ServiceCtl<PuppetServiceMixin> stop() found that is starting, waiting stable ... timeout
{"code":1,"details":"Call cancelled","level":"error","message":"1 CANCELLED: Call cancelled","name":"Error","stack":"Error: 1 CANCELLED: Call cancelled\n    at callErrorFromStatus (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/call.ts:81:17)\n    at Object.onReceiveStatus (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client.ts:356:55)\n    at Object.onReceiveStatus (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client-interceptors.ts:455:34)\n    at Object.onReceiveStatus (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)\n    at /Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)\nfor call at\n    at ServiceClientImpl.makeUnaryRequest (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client.ts:326:30)\n    at ServiceClientImpl.stop (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)\n    at node:internal/util:375:7\n    at new Promise (<anonymous>)\n    at bound  (node:internal/util:361:12)\n    at GrpcManager.stop (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/wechaty-puppet-service@1.19.9_jkyvhh2danr4dcnhzsykeo22pa/node_modules/wechaty-puppet-service/src/client/grpc-manager.ts:194:8)\n    at PuppetService.onStop (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/wechaty-puppet-service@1.19.9_jkyvhh2danr4dcnhzsykeo22pa/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:199:25)\n    at PuppetService.stop (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/state-switch@1.7.1_tcppfhatzsoz34uwt475ldw2ga/node_modules/state-switch/src/service-ctl/service-ctl.ts:145:20)\n    at async PuppetService.stop (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/wechaty-puppet@1.20.2/node_modules/wechaty-puppet/src/mixins/service-mixin.ts:42:7)\n    at async PuppetService.stop (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/wechaty-puppet@1.20.2/node_modules/wechaty-puppet/src/mixins/ready-mixin.ts:47:7)","timestamp":"2023-05-24 11:09:11"}
{"code":1,"details":"Call cancelled","level":"error","message":"1 CANCELLED: Call cancelled","name":"Error","stack":"Error: 1 CANCELLED: Call cancelled\n    at callErrorFromStatus (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/call.ts:81:17)\n    at Object.onReceiveStatus (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client.ts:356:55)\n    at Object.onReceiveStatus (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client-interceptors.ts:455:34)\n    at Object.onReceiveStatus (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)\n    at /Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)\nfor call at\n    at ServiceClientImpl.makeUnaryRequest (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client.ts:326:30)\n    at ServiceClientImpl.start (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)\n    at node:internal/util:375:7\n    at new Promise (<anonymous>)\n    at bound  (node:internal/util:361:12)\n    at GrpcManager.start (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/wechaty-puppet-service@1.19.9_jkyvhh2danr4dcnhzsykeo22pa/node_modules/wechaty-puppet-service/src/client/grpc-manager.ts:170:6)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PuppetService.onStart (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/wechaty-puppet-service@1.19.9_jkyvhh2danr4dcnhzsykeo22pa/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:173:5)\n    at async PuppetService.start (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/state-switch@1.7.1_tcppfhatzsoz34uwt475ldw2ga/node_modules/state-switch/src/service-ctl/service-ctl.ts:89:9)\n    at async PuppetService.start (/Users/yinshipeng/Documents/workspace/baofu/wechat-chatgpt/node_modules/.pnpm/wechaty-puppet@1.20.2/node_modules/wechaty-puppet/src/mixins/service-mixin.ts:34:7)","timestamp":"2023-05-24 11:09:11"}

**Comment by su-chang** [comment]
@yinshipeng 麻烦描述下具体问题，上面提供的日志可读性较差，无法快速定位和解决问题。

**Comment by hcfw007** [comment]
因为没有收到后续反馈，issue关闭。
