### ISSUE TITLE
[FEAT]WorkPro:怎么发送小程序卡片啊

### ISSUE THREAD

**Issue by ArielZhu** [wechaty/puppet-service-providers#213]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by su-chang** [comment]
你可以参考下这个PR中message相关的示例：https://github.com/wechaty/docusaurus/pull/1520

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
