### ISSUE TITLE
[BUG]WorkPro:Warn PuppetWatchdogAgent start() reset() reason:{"data":" regular heartbeat"，"timeoutMilliseconds": 60000}

### ISSUE THREAD

**Issue by wwz223** [wechaty/puppet-service-providers#214]
报错之后重新登录失败

**Comment by wwz223** [comment]
<img width="1402" alt="image" src="https://github.com/wechaty/puppet-supports/assets/36815297/57f7816f-56e9-4d1d-bfbe-9b52b81e3384">

**Comment by su-chang** [comment]
@wwz223 你使用的puppet-service版本是哪个？是@juzi这个scope下的么？

看服务端没有异常，客户端主动发起重连。是否会存在一个token被多个进程使用的情况？

**Comment by wwz223** [comment]
"@juzi/wechaty": "^1.0.44",
"@juzi/wechaty-puppet": "^1.0.45",
"@juzi/wechaty-puppet-service": "^1.0.39",

客户端目前只有一个进程，主动发起重连是会重新启动当前进程
报错信息里面可以看到第一次重新启动触发了login事件，但是第二次报错之后重新启动只是触发了scan事件，没有走到login事件

**Comment by su-chang** [comment]
版本没有问题，可以先调整下心跳超时时间的设置后，再观察看看。

```ts
const puppet = new PuppetService({
  token: 'your-token',
  timeoutSeconds: 4 * 60, // 默认1分钟
  tls: {
    disable: true
  },
})
```

**Comment by wwz223** [comment]
> 版本没有问题，可以先调整下心跳超时时间的设置后，再观察看看。
> 
> ```ts
> const puppet = new PuppetService({
>   token: 'your-token',
>   timeoutSeconds: 4 * 60, // 默认1分钟
>   tls: {
>     disable: true
>   },
> })
> ```

OK，我试试

**Comment by su-chang** [comment]
@wwz223 这两天是否还有类似问题？

**Comment by wwz223** [comment]
改成四分钟之后也出现了几次断开的情况，但是都重连成功了，问题算是解决了

**Comment by hcfw007** [comment]
由于Grpc Stream的断开并不是都能被事件捕捉到的，所以我们用心跳来监控是否连接还正常工作。当一个阈值（超时时间）没收到事件的时候，就会尝试重连，如果能重连成功那就是正常情况。

如果问题已解决，请关闭issue。
