### ISSUE TITLE
WorkPro在监听到用户进群退群的消息报错

### ISSUE THREAD

**Issue by JAi-Li** [wechaty/puppet-service-providers#217]
运行平台：windows

问题描述：
一开始使用官方getting-started 购买token后按步骤配置运行。监听消息发送消息都正常。
但是一旦有用户进群退群后，就发生如下错误。麻烦大佬帮忙看一下怎么解决
![ccecee51fae80e5921fed8d9550402b](https://github.com/wechaty/puppet-supports/assets/45959826/0002c027-d07d-475b-a4cb-53d0955fbf66)

**Comment by hcfw007** [comment]
https://github.com/wechaty/wechaty/issues/2410

这个是wechaty的bug，可以通过添加errorListener的方法来绕过

**Comment by JAi-Li** [comment]
但是我需要监听进群退群事件呢，需要怎么监听呢

**Comment by JAi-Li** [comment]
上面诉求可以帮我看看吗？我需要监听进退群事件，请问需要如果来做呢

**Comment by su-chang** [comment]
@JAi-Li  正常监听即可，只不过加个errorListener处理异常。

或者可以使用 @juzi/wechaty 这个包里已经修复了这个问题。但是需要调整下项目代码中的依赖，业务代码不需要修改。

**Comment by hcfw007** [comment]
因为长时间没有反馈，Issue关闭。
