### ISSUE TITLE
[BUG]WorkPro:启动之后使用企业扫码提示二维码已过期,重新刷新PC二维码

### ISSUE THREAD

**Issue by mmotiy** [wechaty/puppet-service-providers#219]
<img width="913" alt="image" src="https://github.com/wechaty/puppet-supports/assets/14013214/41ae21e2-cc05-4862-a571-599d8c8a7be6">
每次启动生成的都是这个
 https://wx.work.weixin.qq.com/cgi-bin/crtx_auth?key=1AA5E73285FC69E0FD5BC33450D91F7C&wx=1  
 重启多次还是同一个链接

**Comment by su-chang** [comment]
@mmotiy 麻烦有空再试一下看看。对应时间段服务有点问题，没有正确返回二维码。
