### ISSUE TITLE
[BUG]WorkPro:发送图片，文件报错，文字消息可以发送，之前都是正常的

### ISSUE THREAD

**Issue by yangningmoojing** [wechaty/puppet-service-providers#220]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

**Info**

 - Platform[e.g. Windows/Mac/Linux]: 
 - Runtime version[e.g. node/JAVA]:
 - Wechaty version: 
 - Wechaty Puppet version: 

**To Reproduce**
<img width="1619" alt="截屏2023-06-25 19 06 46" src="https://github.com/wechaty/puppet-supports/assets/84449727/d9372e46-0cad-4308-93c0-4caa7adaba80">

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hcfw007** [comment]
这个找到原因了，我们最近引入了apm来监控性能，与我们原有的框架有些冲突。这个今晚给你更新。由于我们更新是灰度进行的，请 @yangningmoojing 私信客服（在置顶Issue中有）提供一下token吧。

**Comment by su-chang** [comment]
这个问题已经修复，可以验证下看看.

**Comment by hcfw007** [comment]
没有后续回复，Issue关闭。
