### ISSUE TITLE
微信群的修改群名称监听没有触发

### ISSUE THREAD

**Issue by jolyPan** [wechaty/puppet-service-providers#221]
使用的官网示例
// after logged in...
const room = await bot.Room.find({topic: 'topic of your room'}) // change `event-room` to any room topic in your wechat
if (room) {
  room.on('topic', (room, topic, oldTopic, changer) => {
    console.log(`Room topic changed from ${oldTopic} to ${topic} by ${changer.name()}`)
  })
}
修改群名称的时候会报错 并且不会触发回调

使用环境： Docker Container for Wechaty v1.20.2 with Node.js v16.15.0

**Comment by su-chang** [comment]
```ts
bot.on('room-topic', () => {})
```
@jolyPan  这样试下看看？

**Comment by hcfw007** [comment]
长时间没回复，Issue关闭。
