### ISSUE TITLE
[BUG]WorkPro:微信群名称修改之后监听的join和leave事件不会再触发

### ISSUE THREAD

**Issue by jolyPan** [wechaty/puppet-service-providers#222]
微信群名称修改之后监听的join和leave事件不会再触发并且topic事件在群名称修改后不会触发
<img width="860" alt="image" src="https://github.com/wechaty/puppet-supports/assets/40552479/58326ec1-166e-476f-80e6-3c42b8294036">

**Comment by su-chang** [comment]
建议使用wechaty实例中监听的群聊相关的事件

```ts
bot.on('room-topic', () => {})
bot.on('room-join', () => {})
bot.on('room-leave', () => {})
```

**Comment by jolyPan** [comment]
好的 谢谢回复

**Comment by hcfw007** [comment]
> 建议使用wechaty实例中监听的群聊相关的事件
> 
> ```ts
> bot.on('room-topic', () => {})
> bot.on('room-join', () => {})
> bot.on('room-leave', () => {})
> ```

按照wechaty的设计这样应该也是能work的。你说的这个群名称修改之后，是进程持续运行中还是指重新启动进程后？因为你的 room 是通过 topic 去 find 的，如果因为改名而没找到，就无法把事件监听器挂载上去，可能是这个原因？

**Comment by hcfw007** [comment]
长时间没回复，Issue关闭。
