### ISSUE TITLE
[BUG]WorkPro:用 docker 启动 Wechaty，我有三个 TOKEN 想启动三个企业微信，但是登陆第一个后，第二个就显示已登陆了

### ISSUE THREAD

**Issue by yangningmoojing** [wechaty/puppet-service-providers#223]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

我该怎么解决这个问题？

**Info**

 - Platform[e.g. Windows/Mac/Linux]: 
 - Runtime version[e.g. node/JAVA]:
 - Wechaty version: 
 - Wechaty Puppet version: 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yangningmoojing** [comment]
每个容器启动时都更改了 环境的 WECHATY_PUPPET_SERVICE_TOKEN

**Comment by su-chang** [comment]
感觉是配置的问题，可以看看docker内部配置的环境变量是否正确。

docker inspect xxx | grep WECHATY_PUPPET_SERVICE_TOKEN

**Comment by yangningmoojing** [comment]
> 感觉是配置的问题，可以看看docker内部配置的环境变量是否正确。
> 
> docker 检查 xxx | grep WECHATY_PUPPET_SERVICE_TOKEN

查看了，token是不同的

**Comment by yangningmoojing** [comment]
<img width="650" alt="截屏2023-07-03 10 23 43" src="https://github.com/wechaty/puppet-supports/assets/84449727/c5e7cbc1-59a6-4ecf-ac85-b90a3f2b467b">
是不同的token

**Comment by yangningmoojing** [comment]
<img width="993" alt="截屏2023-07-03 11 37 11" src="https://github.com/wechaty/puppet-supports/assets/84449727/f4a31935-cc3a-4e0a-b54b-c241e38eefd0">
第一个token登陆上，第二个token启动就显示这个

**Comment by hcfw007** [comment]
没有更多内容了吗？可以添加环境变量 WECHATY_LOG=silly 来设置日志等级看看。

**Comment by yangningmoojing** [comment]
> WECHATY_LOG=silly


> wechaty-getting-started@1.18.7 start
> cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node examples/ding-dong-bot.ts

16:08:21 SILL Puppet Config: WECHATY_LOG set level to silly
16:08:21 INFO Config registering process.on("unhandledRejection") for development/debug
16:08:21 VERB Config constructor()
16:08:21 VERB PoolifyMixin poolifyMixin(EventEmitter)
16:08:21 VERB WechatifyMixin wechatifyMixin(AbstractPoolifyMixin)
16:08:21 VERB ValidationMixin validationMixin(ContactMixin)
16:08:21 VERB ValidationMixin validationMixin(ContactImplBase)
16:08:21 VERB PoolifyMixin poolifyMixin(ContactImpl)
16:08:21 VERB ValidationMixin validationMixin(ContactSelfMixin)
16:08:21 VERB WechatifyMixin wechatifyMixin(EmptyBase)
16:08:21 VERB ValidationMixin validationMixin(FavoriteMixin)
16:08:21 VERB WechatifyMixin wechatifyMixin(EventEmitter)
16:08:21 VERB ValidationMixin validationMixin(FriendshipMixin)
16:08:21 VERB WechatifyMixin wechatifyMixin(EmptyBase)
16:08:21 VERB ValidationMixin validationMixin(ImageMixin)
16:08:21 VERB WechatifyMixin wechatifyMixin(EmptyBase)
16:08:21 VERB ValidationMixin validationMixin(LocationMixin)
16:08:21 VERB WechatifyMixin wechatifyMixin(EmptyBase)
16:08:21 VERB ValidationMixin validationMixin(PostMixin)
16:08:21 VERB WechatifyMixin wechatifyMixin(EventEmitter)
16:08:21 VERB ValidationMixin validationMixin(MessageMixin)
16:08:21 VERB ValidationMixin validationMixin(MessageImplBase)
16:08:21 VERB WechatifyMixin wechatifyMixin(EmptyBase)
16:08:21 VERB ValidationMixin validationMixin(MiniProgramMixin)
16:08:21 VERB WechatifyMixin wechatifyMixin(EmptyBase)
16:08:21 VERB ValidationMixin validationMixin(MomentMixin)
16:08:21 VERB WechatifyMixin wechatifyMixin(EmptyBase)
16:08:21 VERB ValidationMixin validationMixin(MoneyMixin)
16:08:21 VERB PoolifyMixin poolifyMixin(EventEmitter)
16:08:21 VERB WechatifyMixin wechatifyMixin(AbstractPoolifyMixin)
16:08:21 VERB ValidationMixin validationMixin(RoomMixin)
16:08:21 VERB WechatifyMixin wechatifyMixin(EmptyBase)
16:08:21 VERB ValidationMixin validationMixin(RoomInvitationMixin)
16:08:21 VERB WechatifyMixin wechatifyMixin(EmptyBase)
16:08:21 VERB PoolifyMixin poolifyMixin(AbstractWechatifyMixin)
16:08:21 VERB ValidationMixin validationMixin(TagMixin)
16:08:21 VERB WechatifyMixin wechatifyMixin(EmptyBase)
16:08:21 VERB ValidationMixin validationMixin(UrlLinkMixin)
16:08:21 VERB WechatifyMixin wechatifyMixin(EmptyBase)
16:08:21 VERB ValidationMixin validationMixin(DelayMixin)
16:08:21 VERB WechatyGErrorMixin gErrorMixin(WechatySkeleton)
16:08:21 VERB WechatifyUserModuleMixin wechatifyUserModuleMixin(GErrorMixin)
16:08:21 VERB WechatyIoMixin ioMixin(WechatifyUserModuleMixin)
16:08:21 VERB WechatyPuppetMixin puppetMixin(IoMixin)
16:08:21 VERB WechatyLoginMixin loginMixin(PuppetMixin)
16:08:21 VERB WechatyMiscMixin miscMixin(LoginMixin)
16:08:21 VERB WechatyPluginMixin pluginMixin(MiscMixin)
16:08:21 VERB ValidationMixin validationMixin(WechatyBase)
16:08:21 VERB ValidationMixin validationMixin(WechatyImplBase)
16:08:22 VERB wechaty-puppet-service monkeyPatchMetadataFromHttp2Headers()
16:08:22 VERB WechatyBuilder singleton()
16:08:22 VERB WechatyBuilder newInstance()
16:08:22 VERB WechatyLoginMixin constructor()
16:08:22 VERB WechatyPuppetMixin construct()
16:08:22 VERB WechatyIoMixin constructor()
16:08:22 VERB WechatifyUserModuleMixin constructor()
16:08:22 VERB WechatySkeleton constructor()
16:08:22 VERB StateSwitch constructor(WechatyReady, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
16:08:22 VERB ServiceCtl<Wechaty> constructor()
16:08:22 VERB StateSwitch constructor(Wechaty, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
16:08:22 VERB StateSwitch constructor(WechatyReset, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
16:08:22 VERB Wechaty constructor()
16:08:22 VERB WechatySkeleton on(scan, listener) registering... listenerCount: 0
16:08:22 VERB WechatySkeleton on(login, listener) registering... listenerCount: 0
16:08:22 VERB WechatySkeleton on(logout, listener) registering... listenerCount: 0
16:08:22 VERB WechatySkeleton on(message, listener) registering... listenerCount: 0
16:08:22 VERB WechatySkeleton on(error, listener) registering... listenerCount: 0
16:08:22 VERB Wechaty start()
16:08:22 VERB WechatyLoginMixin init()
16:08:22 VERB WechatyPuppetMixin init()
16:08:22 VERB WechatifyUserModuleMixin init()
16:08:22 VERB WechatySkeleton init()
16:08:22 VERB Wechaty init() Raven disabled (import("raven") failed)
16:08:22 VERB WechatifyUserModuleMixin init() initializing Wechaty User Module (WUM) ...
16:08:22 VERB WechatifyMixin wechatifyUserModule(ContactImpl)
16:08:22 VERB WechatifyMixin wechatifyUserModule(ContactImpl)(Wechaty#77d49da0-3906-4489-ad79-e45b0a15a013<wechaty-puppet-service>(ding-dong-bot))
16:08:22 VERB WechatifyMixin wechatifyUserModule(ContactSelfImpl)
16:08:22 VERB WechatifyMixin wechatifyUserModule(ContactSelfImpl)(Wechaty#77d49da0-3906-4489-ad79-e45b0a15a013<wechaty-puppet-service>(ding-dong-bot))
16:08:22 VERB WechatifyMixin wechatifyUserModule(DelayImpl)
16:08:22 VERB WechatifyMixin wechatifyUserModule(DelayImpl)(Wechaty#77d49da0-3906-4489-ad79-e45b0a15a013<wechaty-puppet-service>(ding-dong-bot))
16:08:22 VERB WechatifyMixin wechatifyUserModule(FriendshipImpl)
16:08:22 VERB WechatifyMixin wechatifyUserModule(FriendshipImpl)(Wechaty#77d49da0-3906-4489-ad79-e45b0a15a013<wechaty-puppet-service>(ding-dong-bot))
16:08:22 VERB WechatifyMixin wechatifyUserModule(ImageImpl)
16:08:22 VERB WechatifyMixin wechatifyUserModule(ImageImpl)(Wechaty#77d49da0-3906-4489-ad79-e45b0a15a013<wechaty-puppet-service>(ding-dong-bot))
16:08:22 VERB WechatifyMixin wechatifyUserModule(LocationImpl)
16:08:22 VERB WechatifyMixin wechatifyUserModule(LocationImpl)(Wechaty#77d49da0-3906-4489-ad79-e45b0a15a013<wechaty-puppet-service>(ding-dong-bot))
16:08:22 VERB WechatifyMixin wechatifyUserModule(MessageImpl)
16:08:22 VERB WechatifyMixin wechatifyUserModule(MessageImpl)(Wechaty#77d49da0-3906-4489-ad79-e45b0a15a013<wechaty-puppet-service>(ding-dong-bot))
16:08:22 VERB WechatifyMixin wechatifyUserModule(MiniProgramImpl)
16:08:22 VERB WechatifyMixin wechatifyUserModule(MiniProgramImpl)(Wechaty#77d49da0-3906-4489-ad79-e45b0a15a013<wechaty-puppet-service>(ding-dong-bot))
16:08:22 VERB WechatifyMixin wechatifyUserModule(PostImpl)
16:08:22 VERB WechatifyMixin wechatifyUserModule(PostImpl)(Wechaty#77d49da0-3906-4489-ad79-e45b0a15a013<wechaty-puppet-service>(ding-dong-bot))
16:08:22 VERB WechatifyMixin wechatifyUserModule(RoomImpl)
16:08:22 VERB WechatifyMixin wechatifyUserModule(RoomImpl)(Wechaty#77d49da0-3906-4489-ad79-e45b0a15a013<wechaty-puppet-service>(ding-dong-bot))
16:08:22 VERB WechatifyMixin wechatifyUserModule(RoomInvitationImpl)
16:08:22 VERB WechatifyMixin wechatifyUserModule(RoomInvitationImpl)(Wechaty#77d49da0-3906-4489-ad79-e45b0a15a013<wechaty-puppet-service>(ding-dong-bot))
16:08:22 VERB WechatifyMixin wechatifyUserModule(TagImpl)
16:08:22 VERB WechatifyMixin wechatifyUserModule(TagImpl)(Wechaty#77d49da0-3906-4489-ad79-e45b0a15a013<wechaty-puppet-service>(ding-dong-bot))
16:08:22 VERB WechatifyMixin wechatifyUserModule(UrlLinkImpl)
16:08:22 VERB WechatifyMixin wechatifyUserModule(UrlLinkImpl)(Wechaty#77d49da0-3906-4489-ad79-e45b0a15a013<wechaty-puppet-service>(ding-dong-bot))
16:08:22 VERB WechatifyUserModuleMixin init() initializing Wechaty User Module (WUM) ... done
16:08:22 VERB WechatyPuppetMixin init() instanciating puppet instance ...
16:08:22 VERB Puppet resolvePuppet({puppet: wechaty-puppet-service, puppetOptions: {"token":"puppet_workpro_a54fdc7da65a4df79a2436c0c845cd23"}})
16:08:22 VERB Puppet resolvePuppet() resolving name "wechaty-puppet-service" ...
16:08:22 VERB Puppet resolvePuppetName(wechaty-puppet-service)
16:08:22 VERB Puppet resolvePuppetName(wechaty-puppet-service): ESM resolved
16:08:22 VERB Puppet resolvePuppet() resolving name "wechaty-puppet-service" ... done
16:08:22 VERB Puppet resolvePuppet() instanciating puppet ...
16:08:22 VERB PuppetSkeleton constructor({"token":"puppet_workpro_a54fdc7da65a4df79a2436c0XXXXX"})
16:08:22 VERB PuppetMemoryMixin constructor()
16:08:22 VERB PuppetLoginMixin constructor()
16:08:22 VERB PuppetCacheMixin constructor()
16:08:22 VERB PuppetCacheAgent constructor()
16:08:22 VERB PuppetContactMixin constructor()
16:08:22 VERB PuppetRoomMemberMixin constructor()
16:08:22 VERB PuppetRoomMixin constructor()
16:08:22 VERB PuppetFriendshipMixin constructor()
16:08:22 VERB PuppetTagMixin constructor()
16:08:22 VERB PuppetRoomInvitationMixin constructor()
16:08:22 VERB PuppetMessageMixin constructor()
16:08:22 VERB PuppetMiscMixin constructor()
16:08:22 VERB ServiceCtl<PuppetServiceMixin> constructor()
16:08:22 VERB StateSwitch constructor(PuppetServiceMixin, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
16:08:22 VERB StateSwitch constructor(PuppetServiceMixinReset, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
16:08:22 VERB PuppetServiceMixin constructor() #0
16:08:22 VERB PuppetWatchdogAgent constructor(158a976e-c415-4293-9606-8bf418d4ab50)
16:08:22 VERB PuppetWatchdogAgent constructor() timeout 60 seconds
16:08:22 VERB ReadyMixin constructor()
16:08:22 VERB PuppetPostMixin constructor()
16:08:22 VERB PuppetSayableMixin constructor()
16:08:22 VERB TapMixin constructor()
16:08:22 VERB Puppet constructor({"token":"puppet_workpro_a54fdc7da65a4df79a2436c0XXXXX"})
16:08:22 VERB PayloadStore constructor({"token":"puppet_workpro_a54fdc7da65a4df79a2436c0XXXXX"})
16:08:22 SILL PayloadStore constructor() storeDir: "/share/home/yangning/.wechaty/wechaty-puppet-service/puppet_workpro_a54fdc7da65a4df79a2436c0XXXXX/v1.19"
16:08:22 VERB PuppetService hookPayloadStore()
16:08:22 VERB Puppet resolvePuppet() instanciating puppet ... done
16:08:22 VERB WechatyPuppetMixin init() instanciating puppet instance ... done
16:08:22 VERB WechatyPuppetMixin init() setting memory ...
16:08:22 VERB PuppetMemoryMixin setMemory(ding-dong-bot)
16:08:22 VERB WechatyPuppetMixin init() setting memory ... done
16:08:22 VERB WechatyPuppetMixin init() setting up events ...
16:08:22 VERB WechatyPuppetMixin __setupPuppetEvents(Puppet<PuppetService>(ding-dong-bot))
16:08:22 VERB PuppetMixin __setupPuppetEvents() puppet.on(friendship) (listenerCount:0) registering...
16:08:22 VERB PuppetMixin __setupPuppetEvents() puppet.on(login) (listenerCount:1) registering...
16:08:22 VERB PuppetMixin __setupPuppetEvents() puppet.on(logout) (listenerCount:1) registering...
16:08:22 VERB PuppetMixin __setupPuppetEvents() puppet.on(message) (listenerCount:0) registering...
16:08:22 VERB PuppetMixin __setupPuppetEvents() puppet.on(post) (listenerCount:0) registering...
16:08:22 VERB PuppetMixin __setupPuppetEvents() puppet.on(room-invite) (listenerCount:0) registering...
16:08:22 VERB PuppetMixin __setupPuppetEvents() puppet.on(room-join) (listenerCount:0) registering...
16:08:22 VERB PuppetMixin __setupPuppetEvents() puppet.on(room-leave) (listenerCount:0) registering...
16:08:22 VERB PuppetMixin __setupPuppetEvents() puppet.on(room-topic) (listenerCount:0) registering...
16:08:22 VERB PuppetMixin __setupPuppetEvents() puppet.on(scan) (listenerCount:0) registering...
16:08:22 VERB PuppetMixin __setupPuppetEvents() puppet.on(dirty) (listenerCount:0) registering...
16:08:22 VERB PuppetMixin __setupPuppetEvents() puppet.on(dong) (listenerCount:0) registering...
16:08:22 VERB PuppetMixin __setupPuppetEvents() puppet.on(error) (listenerCount:0) registering...
16:08:22 VERB PuppetMixin __setupPuppetEvents() puppet.on(heartbeat) (listenerCount:0) registering...
16:08:22 VERB PuppetMixin __setupPuppetEvents() puppet.on(ready) (listenerCount:0) registering...
16:08:22 VERB PuppetMixin __setupPuppetEvents() puppet.on(reset) (listenerCount:0) registering...
16:08:22 VERB WechatyPuppetMixin __setupPuppetEvents() ... done
16:08:22 VERB WechatyPuppetMixin init() setting up events ... done
16:08:22 VERB WechatyPuppetMixin init() emitting "puppet" event ...
16:08:22 VERB WechatyPuppetMixin init() emitting "puppet" event ... done
16:08:22 VERB ServiceCtl<Wechaty> start()
16:08:22 SILL StateSwitch <Wechaty> active() is false
16:08:22 SILL StateSwitch <Wechaty> inactive() is true
16:08:22 SILL StateSwitch <Wechaty> active() is false
16:08:22 VERB StateSwitch <Wechaty> active(pending) <- (false)
16:08:22 VERB ServiceCtl<Wechaty> start() super.start() ...
16:08:22 VERB WechatyPuppetMixin start()
16:08:22 VERB WechatyPuppetMixin start() super.start() ...
16:08:22 VERB WechatyIoMixin start()
16:08:22 VERB WechatySkeleton start()
16:08:22 VERB WechatyLoginMixin init()
16:08:22 VERB WechatyPuppetMixin init()
16:08:22 VERB WechatifyUserModuleMixin init()
16:08:22 VERB WechatySkeleton init()
16:08:22 VERB WechatifyUserModuleMixin init() Wechaty User Module (WUM)s have already wechatified: skip
16:08:22 VERB WechatyPuppetMixin init() skipped because this puppet has already been inited before.
16:08:22 VERB WechatyPuppetMixin start() super.start() ... done
16:08:22 SILL StateSwitch <WechatyReady> active() is false
16:08:22 VERB WechatyPuppetMixin start() starting puppet ...
16:08:22 VERB ReadyMixin start()
16:08:22 VERB PuppetServiceMixin start()
16:08:22 VERB ServiceCtl<PuppetServiceMixin> start()
16:08:22 SILL StateSwitch <PuppetServiceMixin> active() is false
16:08:22 SILL StateSwitch <PuppetServiceMixin> inactive() is true
16:08:22 SILL StateSwitch <PuppetServiceMixin> active() is false
16:08:22 VERB StateSwitch <PuppetServiceMixin> active(pending) <- (false)
16:08:22 VERB ServiceCtl<PuppetServiceMixin> start() super.start() ...
16:08:22 VERB PuppetCacheMixin start()
16:08:22 VERB PuppetLoginMixin start()
16:08:22 VERB PuppetMemoryMixin start()
16:08:22 VERB PuppetSkeleton start()
16:08:22 VERB PuppetCacheAgent start()
16:08:22 VERB PuppetCacheMixin start() "dirty" event listener added
16:08:22 VERB ServiceCtl<PuppetServiceMixin> start() super.start() ... done
16:08:22 VERB ServiceCtl<PuppetServiceMixin> start() this.onStart() ...
16:08:22 VERB PuppetService onStart()
16:08:22 VERB PuppetService start() instanciating GrpcManager ...
16:08:22 VERB GrpcManager constructor({"token":"puppet_workpro_a54fdc7da65a4df79a2436c0XXXXX"})
16:08:22 VERB GrpcManager constructor() tlsRootCert(hash): "88ab8b62777f0fb1179ec567c5019c31d646428cc0a3fdb007fcffa1e9fac5a8"
16:08:22 VERB GrpcManager constructor() token: "puppet_workpro_a54fdc7da65a4df79a2436c0XXXXX"
16:08:22 VERB GrpcManager constructor() endpoint: "wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_a54fdc7da65a4df79a2436c0c845cd23"
16:08:22 VERB GrpcManager constructor() disableTls: "true"
16:08:22 VERB GrpcManager constructor() serverName(SNI): "puppet_workpro"
16:08:22 VERB PuppetService start() instanciating GrpcManager ... done
16:08:22 VERB PuppetService start() setting up bridge grpc event stream ...
16:08:22 VERB PuppetService bridgeGrpcEventStream(client)
16:08:22 VERB PuppetService start() setting up bridge grpc event stream ... done
16:08:22 VERB PuppetService start() starting grpc manager...
16:08:22 VERB GrpcManager start()
16:08:22 VERB GrpcManager start() initializing client ...
16:08:22 VERB GrpcManager initClient()
16:08:22 WARN GrpcManager initClient() TLS: disabled (INSECURE)
16:08:22 VERB GrpcManager initClient() ... done
16:08:22 VERB GrpcManager start() initializing client ... done
16:08:22 VERB GrpcManager startStream()
16:08:22 VERB GrpcManager startStream() grpc -> event() ...
16:08:22 VERB GrpcManager startStream() grpc -> event() ... done
16:08:22 VERB GrpcManager startStream() grpc -> event peeking data or timeout ...
16:08:22 VERB GrpcManager startStream() grpc -> event peeking data or timeout ... timeout
16:08:22 VERB GrpcManager startStream() grpc -> event peeking data or timeout ... data peeked
16:08:22 VERB GrpcManager startStream() initializing event stream ...
16:08:22 VERB GrpcManager startStream() initializing event stream ... done
16:08:22 VERB GrpcManager startStream() ... done
16:08:22 VERB GrpcManager start() starting stream ... done
16:08:22 VERB GrpcManager start() calling grpc server: start() ...
16:08:22 VERB GrpcManager start() calling grpc server: start() ... done
16:08:22 VERB GrpcManager start() ... done
16:08:22 VERB PuppetService start() starting grpc manager... done
16:08:22 VERB PuppetService onStart() ... done
16:08:22 VERB ServiceCtl<PuppetServiceMixin> start() this.onStart() ... done
16:08:22 SILL StateSwitch <PuppetServiceMixin> active() is pending
16:08:22 VERB StateSwitch <PuppetServiceMixin> active(true) <- (pending)
16:08:22 VERB ServiceCtl<PuppetServiceMixin> start() ... done
16:08:22 VERB PuppetWatchdogAgent start() "heartbeat" event listener added
16:08:22 VERB PuppetWatchdogAgent start() "reset" event listener added
16:08:22 VERB WechatyPuppetMixin start() starting puppet ... done
16:08:22 VERB ServiceCtl<Wechaty> start() super.start() ... done
16:08:22 VERB ServiceCtl<Wechaty> start() this.onStart() ...
16:08:22 VERB Wechaty onStart()
16:08:22 VERB Wechaty <wechaty-puppet-service>(ding-dong-bot) onStart() v1.20.2 is starting...
16:08:22 VERB Wechaty id: 77d49da0-3906-4489-ad79-e45b0a15a013
16:08:22 VERB Wechaty onStart() ... done
16:08:22 VERB ServiceCtl<Wechaty> start() this.onStart() ... done
16:08:22 SILL StateSwitch <Wechaty> active() is pending
16:08:22 VERB StateSwitch <Wechaty> active(true) <- (pending)
16:08:22 VERB ServiceCtl<Wechaty> start() ... done

**Comment by hcfw007** [comment]
后续还有吗？目前看起来都很正常没报错啊

**Comment by yangningmoojing** [comment]
> 后续还有吗？目前看起来都很正常没报错啊

17:16:24 SILL Wechaty onStart() setInterval() this timer is to keep Wechaty running...
18:16:24 SILL Wechaty onStart() setInterval() this timer is to keep Wechaty running...
19:16:24 SILL Wechaty onStart() setInterval() this timer is to keep Wechaty running...
但是怎么登陆其他企业微信呢，不出登陆的二维码

**Comment by hcfw007** [comment]
puppet_workpro_a54fdc7da65a4df79a2436c0XXXXX 这个token目前是登录微 杨宁
puppet_workpro_25b73f8 这个我没有找到这个前缀的token
puppet_workpro_a2cc2ce 这个token于7月2日过期。

请与客服确认一下token信息吧。

**Comment by yangningmoojing** [comment]
> puppet_workpro_a54fdc7da65a4df79a2436c0XXXXX 这个token目前是登录微 杨宁 puppet_workpro_25b73f8 这个我没有找到这个前缀的token puppet_workpro_a2cc2ce 这个token于7月2日过期。
> 
> 请与客服确认一下token信息吧。

加账号测试的token，6号过期

**Comment by hcfw007** [comment]
这个客服跟我说已经提供了新的token了，现在还有问题吗？

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
