### ISSUE TITLE
WorkPro: 重复调用同一个token登录如何删除登录凭证？

### ISSUE THREAD

**Issue by zhongyufan** [wechaty/puppet-service-providers#224]
Please make sure you have read the [Wechaty Puppet Service: WXWork](https://wechaty.js.org/docs/puppet-services/wxwork) from Wechaty Official Website before you continue writting this issue.

## Question
重启服务，token的登陆状态没有清除会导致无法自动重连，一直显示在加载中，如何直接清空登录凭证然后重新扫码登录？

**Comment by hcfw007** [comment]
没太理解你的意思。
如果你是指本地的状态，可以尝试删除 ~/.wechaty 的缓存。
如果你是指远程的状态，可以调用 bot.logout()。

**Comment by zhongyufan** [comment]
同一个token，start两次，第二次会显示一直在加载，没有任何报错。上一个bot已经丢失了，我想释放token有什么方法吗？就直接删除~/.wechaty 的缓存即可？
const bot = WechatyBuilder.build({
      name: 'wechat-puppet',
      puppet: 'wechaty-puppet-service',
      puppetOptions: {
        token: clientToken,
        tls: {
          disable: true,
        },
      },
    });
    bot.start()

**Comment by zhongyufan** [comment]
第二个问题，如果我只是想删除这个机器人的登陆信息，具体要删除哪个文件

**Comment by su-chang** [comment]
删除本地文件无法修改机器人的登录信息，需要执行 bot.logout() 方法。

**Comment by zhongyufan** [comment]
使用一个token登陆后，再次使用该token去调用登陆，没有提示机器人token被占用，要如何识别这种情况？

**Comment by hcfw007** [comment]
你这个场景是两个客户端调用同一个token，还是同一个客户端进行重启操作？

**Comment by zhongyufan** [comment]
应该是两个客户端去调用同一个token，我本地重启服务了，WechatyBuilder.build调用了两次，还有个问题，我调用了bot.logout()，但是手机上还是现实win客户端在线，这种要怎么解决实现强制下线。

**Comment by hcfw007** [comment]
第一个问题，两个客户端调用同一个token，第二个会无法连接，表现应该是启动超时（内部是有错误的，但被wecahty隐藏了）。
第二个问题，最快的方式是点手机左上角的win登录然后点下线。

**Comment by zhongyufan** [comment]
第二个问题，需要等待多久，因为我们提供了下线的功能给用户，调用了bot.logout() 这个时候token是否已经释放，可以给别的用户用了吗？

**Comment by hcfw007** [comment]
你们监听了logout事件吗？调用了logout之后应该能接收到logout事件和scan事件，这时候就有新的二维码了可以给其他用户使用。

**Comment by hcfw007** [comment]
从我们的实践来看很快，基本在2秒以内。

**Comment by zhongyufan** [comment]
有监听logout，但是logout之后直接关闭bot实例，我们的逻辑是，用户去授权才去build一个机器人，这样才去占用的，如果按照你们的实践，那就是说我的机器人客户端在服务启动的时候就一直挂载，是扫码的就一直维持在扫码的，这个时候去分配的意思吗？ 主动调用logout事件有延迟（还很久），机器人的客户端一直在线，这个时候我保存的状态是机器人已经下线了，token 空出来了，但是实际上并没有。我重新去build就会挂掉

**Comment by zhongyufan** [comment]
你们的实践是bot实例一直不关闭吗？ 那首次启动服务的时候是直接登陆所有的token吗？ 例如10 / 20 我全开了等待扫码这样子吗？

**Comment by hcfw007** [comment]
你的意思是logout调用到logout事件有很久吗？这是不符合预期的，可以联系客服提供一下token和大概的时间点我们来查看看。

**Comment by zhongyufan** [comment]
客服排查说没有问题，但是实际上我调用logout并不能退出账号

**Comment by hcfw007** [comment]
额？我去打听下，没反馈到我这啊。。

**Comment by zhongyufan** [comment]
刚解决了 logout 要和 stop 一起使用才能真正退出，我看了文档没找到已读未读的操作，这个操作或者状态有得修改或者获取吗？

**Comment by hcfw007** [comment]
这是两码事，logout做的事情是退出当前企微账号，stop做的事是停止当前机器人。

这个功能在社区版尚未实现，如果要使用，需要用@juzi scope下的wechaty依赖。

**Comment by zhongyufan** [comment]
我如果只调用了logout，手机上的客户端还在线，只有同时调用才能下线。

**Comment by hcfw007** [comment]
那是不太应该的——手机左上角的那个是有延迟的（2分钟左右），可以等2分钟看看。

**Comment by zhongyufan** [comment]
主动发送消息只通过find群名称然后筛选id的方式吗？有没有直接通过id进行发送的？

**Comment by zhongyufan** [comment]
11:05:24 WARN PuppetWatchdogAgent start() reset() reason: {"data":"regular heartbeat","timeoutMilliseconds":60000}
11:05:24 ERR Bot Error clientId: 1679014354412998658
11:05:24 INFO Bot 用户主动退出
心跳会出现这个问题，断线会去触发logout
11:05:24 WARN GrpcManager initClient() TLS: disabled (INSECURE)
❤️ 1679014354412998658 gRPC event stream connected
❤️ 1679014354412998658 onGrpcStreamEvent(EVENT_TYPE_LOGIN)
11:05:24 ERR PuppetService onGrpcStreamEvent() this.login() rejection must logout first before login again!

**Comment by hcfw007** [comment]
> 主动发送消息只通过find群名称然后筛选id的方式吗？有没有直接通过id进行发送的？

可以直接用id来获取群:
```ts
const room = bot.Room.find({id: roomId})
await room.say(something)
```

**Comment by hcfw007** [comment]
> ❤️ 1679014354412998658 gRPC event stream connected

心跳断开的重连应该不会导致主动退出，连接恢复后你需要扫码吗？

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
