### ISSUE TITLE
[BUG]WorkPro:消息发送提交成功以后没有发送到企业微信群

### ISSUE THREAD

**Issue by boboli611** [wechaty/puppet-service-providers#226]
项目已经平稳跑了半年了，今天发生异常
目前接受消息正常
发送群消息的时候，提交给远程托管服务是正常的，返回成功
但是托管服务没有转发到响应的微信群

**Comment by hcfw007** [comment]
意思是发送消息返回成功但是实际上手机上没收到吗？可以联系客服提供一下token、发送消息后返回的消息id，如果没有消息id了，则需要发送的群聊Id和内容。最后是手机上对应时间的截图。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
