### ISSUE TITLE
[BUG]WorkPro:

### ISSUE THREAD

**Issue by mzzdliya** [wechaty/puppet-service-providers#229]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**
Wechaty启动时出现 the network is not good, token是有效的 

**Info**

 - Platform[e.g. Windows/Mac/Linux]: mac
 - Runtime version[e.g. node/JAVA]: python3.8
 - Wechaty version: 0.65
 - Wechaty Puppet version: 

**Screenshots**

![2631688978912_ pic](https://github.com/wechaty/puppet-supports/assets/25047974/a8604cb4-d977-488b-9347-4762633a8441)

<img width="1022" alt="企业微信截图_4f3d7555-11f7-431d-9d68-75a89ad1fea6" src="https://github.com/wechaty/puppet-supports/assets/25047974/12dbaa4e-ebcf-4a01-ab58-bba649953c87">
**Additional context**

**Comment by hcfw007** [comment]
请尝试在部署环境上访问 https://token-service-discovery.juzibot.com/v0/hosties/${token} 看看是否能获取到ip和port

**Comment by mzzdliya** [comment]
![image](https://github.com/wechaty/puppet-supports/assets/25047974/35e77d29-0cfc-40b2-a6fc-435b334358d8)

返回的
{
"host": "0.0.0.0",
"ip": "0.0.0.0",
"port": 0
}

**Comment by hcfw007** [comment]
那请联系客服提供一下token和issue号，我们看一下吧。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
