### ISSUE TITLE
[BUG]WorkPro: 无法获取分享链接的url

### ISSUE THREAD

**Issue by ZhangRaymond** [wechaty/puppet-service-providers#230]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**
在用测试token进行开发时，在登录过程中报Warning：there is not registed blueprint in the plugins, so bot will not start the web service。导致在对URL和小程序信息提取url过程中会报错，即 await msg.to_url_link() 和 to_mini_program() 时报错，traceback如下图，无法获取message_url对应的pyload，怀疑原因为前面warning信息对应的blueprint无法被注册导致未能联网。
请问该如何解决？

**Info**

 - Platform[e.g. Windows/Mac/Linux]:  Mac和linux均有这个问题
 - Runtime version[e.g. node/JAVA]: python
 - Wechaty version:   0.10.7
 - Wechaty Puppet version: 0.4.23

**Screenshots**
![WechatIMG208](https://github.com/wechaty/puppet-supports/assets/16101490/f35d4278-4469-4379-8c29-c0034c5d5eed)

**Comment by su-chang** [comment]
@ZhangRaymond 接收到卡片链接消息后，在nodejs中需要调用`message.toUrlLink()`来获取对应的数据。

你可以参考python-wechaty的调用方法。

如果怀疑`blueprint`有疑问，可以在对应的repo中提issue哈。

**Comment by ZhangRaymond** [comment]
@su-chang  感谢回复~ 实际上我也是这么做的，在调用msg.to_url_link() 和 msg.to_mini_program() 提取数据时报错。我在python-wechaty里提了issue，目前还没有回复，如果方便的话，辛苦提醒下相关开发同学吧，比较急
https://github.com/wechaty/python-wechaty/issues/411

**Comment by su-chang** [comment]
获取卡片链接和小程序的消息数据属于相对基础的功能，建议你用简单的python-wechaty的代码启动项目，并仅做这两类消息处理，看看是否仍存在报错。

不要安装一些其他插件，这样更容易定位问题。

BTW, python-wechaty是由社区开发者来维护的，一切交流都在issue中进行。我们这边也没有特殊的沟通渠道。

**Comment by LLSean** [comment]
请问解决了吗？我在解析公众号的链接的时候也遇到了同样的问题

**Comment by ZhangRaymond** [comment]
> 请问解决了吗？我在解析公众号的链接的时候也遇到了同样的问题

没人解决，准备弃了。。。

**Comment by ZhangRaymond** [comment]
> 获取卡片链接和小程序的消息数据属于相对基础的功能，建议你用简单的python-wechaty的代码启动项目，并仅做这两类消息处理，看看是否仍存在报错。
> 
> 不要安装一些其他插件，这样更容易定位问题。
> 
> BTW, python-wechaty是由社区开发者来维护的，一切交流都在issue中进行。我们这边也没有特殊的沟通渠道。

@su-chang 照做了，还是不行，始终无法成功执行msg.to_url_link() 。开源社区也发了issue也没有反馈

**Comment by hcfw007** [comment]
如果可能建议使用node开发wechaty相关项目。

**Comment by su-chang** [comment]
@ZhangRaymond node中是否有遇到类似问题？

**Comment by LLSean** [comment]
使用node版本是没有问题的，建议用node版本吧

**Comment by hcfw007** [comment]
长时间没有后续回复，问题关闭。
