### ISSUE TITLE
Other: 

### ISSUE THREAD

**Issue by dususu** [wechaty/puppet-service-providers#231]
Please make sure you have read the [Wechaty Puppet Service](https://wechaty.js.org/docs/puppet-services/) from Wechaty Official Website before you continue writting this issue.

## Question

bot.puppet.room_create（） 函数创建群聊，contact_ids的用户id怎么获取。

**Comment by su-chang** [comment]
从好友列表中获取

```
const contactList = await bot.Contact.findAll()
const friendList = contactList.filter(c => c.friend())
```

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
