### ISSUE TITLE
[BUG]WorkPro: 机器人无法操作，显示 Error: no grpc manager 

### ISSUE THREAD

**Issue by Hamlet626** [wechaty/puppet-service-providers#232]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

机器人查找房间，发消息 等操作均无法完成，操作时会显示 Error: no grpc manager。

几天前曾经报错如下（之后应该就出现了上述问题）：
Error: 14 UNAVAILABLE: Wechaty service discovery / resolution failed for target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_...: token "puppet_workpro_..." does not exist 

**Info**

dependency 版本如下：
    "qrcode-terminal": "^0.12.0",
    "wechaty": "^1.19.10",
    "wechaty-plugin-contrib": "^0.14.23",
    "wechaty-puppet": "^1.19.6",
    "wechaty-puppet-padlocal": "^1.20.1",
    "wechaty-puppet-service": "^1.18.2"
    
然后有用“WECHATY_PUPPET_SERVICE_AUTHORITY=token-service-discovery-test.juzibot.com”，具体见Additional context

**Expected behavior**

token照理应该可以正常用，各种操作应该可以执行

**Screenshots**

<img width="530" alt="Screen Shot 2023-07-18 at 10 48 13 AM" src="https://github.com/wechaty/puppet-supports/assets/26908521/04a47441-f915-4624-b4d5-9009faa9e1f2">

**Additional context**

之前几个月可以正常运行，然后有过另外问题及处理，见https://github.com/wechaty/puppet-supports/issues/189。

然后现在又出现这个问题，在机器人reset过暂时可以正常操作，但不清楚为什么会显示token not exist。
问下这个问题为什么会发生，然后有临时/永久 或方便的解决办法吗，谢了！

**Comment by su-chang** [comment]
提示这个报错 `token not exist` 的时间信息麻烦提供下。

**Comment by Hamlet626** [comment]
@su-chang token not exist 是在北京时间 7月 14号 03:46 AM

**Comment by su-chang** [comment]
@Hamlet626 麻烦提供下bot的wxid或者该账号最近接收到的消息，我们通过日志查一下对应的账号情况。

**Comment by Hamlet626** [comment]
> @Hamlet626 麻烦提供下bot的wxid或者该账号最近接收到的消息，我们通过日志查一下对应的账号情况。

不确定wxid怎么查，可能是1688851984628822。然后我现在发消息HamletTestHamletTestHamletTest给了该账号。

**Comment by su-chang** [comment]
@Hamlet626 感谢反馈。

经过排查，该token所在服务器于2023-07-14 03:40:03 ~ 2023-07-14 03:46:47 出现故障，导致客户端失去响应，且尝试重连会提示查找不到token。

暂时还未定位到具体问题，还需要些时间进行排查。

**Comment by Hamlet626** [comment]
好的谢了！
