### ISSUE TITLE
[BUG]WorkPro:企业微信显示登录，但是发消息没有回复，退出登录，重新扫码才能正常，最近三天都是这样，什么原因呢？

### ISSUE THREAD

**Issue by yangningmoojing** [wechaty/puppet-service-providers#233]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

**Info**

 - Platform[e.g. Windows/Mac/Linux]: 
 - Runtime version[e.g. node/JAVA]:
 - Wechaty version: 
 - Wechaty Puppet version: 

**To Reproduce**

有三个微信机器人，都放在一个群里，代码都是用的一个代码，docker 启动的
发送   &获取所有微信群 ，然后就有两个微信机器人可以接受消息，回复消息，另一个就不行，显示在线，但是接收不到指令
代码是这个：
    if (msg.text() === '&获取所有微信群'){
        const roomList = await bot.Room.findAll();
        const topicList = [];
        for await (const room of roomList) {
          const topic = await room.topic();
          const topic_id = await room.id;
          topicList.push(topic+':'+topic_id);
        }

        log.info('所有微信群:', topicList);
        const topicString = topicList.join('\n');
        await msg.say(topicString)
                            }
**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yangningmoojing** [comment]
机器人都在这个 微信Bot总控,R:92243602791066 这个群里，token是 puppet_workpro_0efd6dbeed944973**********

**Comment by su-chang** [comment]
这边看日志，该token最近收到的消息
ID: 8d56ebc6fb1159f9b617cea3f53b4fb2
时间: 2023-07-22 @ 13:56:40.199	
内容: @分析师-王星皓David 好的收到谢谢

@yangningmoojing  可以确认下现在该token是否能正常使用？

**Comment by yangningmoojing** [comment]
可以正常使用

> 这边看日志，该token最近收到的消息 ID: 8d56ebc6fb1159f9b617cea3f53b4fb2 时间: 2023-07-22 @ 13:56:40.199 内容: @分析师-王星皓David 好的收到谢谢
> 
> @yangningmoojing 可以确认下现在该token是否能正常使用？

确认，可以正常使用

**Comment by su-chang** [comment]
好的，后续如果还有问题可以携带对应的客户端错误日志一起发来看看。目前看服务端日志没有发现异常。

**Comment by yangningmoojing** [comment]
> 好的，后续如果还有问题可以携带对应的客户端错误日志一起发来看看。目前看服务端日志没有发现异常。

没有报错，就是当时重启可以正常使用，放一晚，第二天这个号就不能服务了，看不到日志，也没报错信息，就是收不到消息，重启就会好，就这一个号有问题，其他两个号就正常，代码也都是一样的

**Comment by su-chang** [comment]
是不是手机端开启了休息模式？该模式下，是无法接收到任何消息的。 @yangningmoojing

**Comment by yangningmoojing** [comment]
> 是不是手机端开启了休息模式？该模式下，是无法接收到任何消息的。 @yangningmoojing

休息模式是什么，在哪里设置

**Comment by yangningmoojing** [comment]
> 是不是手机端开启了休息模式？该模式下，是无法接收到任何消息的。 @yangningmoojing

这个没有开启

**Comment by yangningmoojing** [comment]
> 是不是手机端开启了休息模式？该模式下，是无法接收到任何消息的。 @yangningmoojing

显示电脑登录是离开模式，这个是什么情况，接收不到消息

**Comment by su-chang** [comment]
@yangningmoojing 可能和这个有关系。最近还有这样的情况么？

**Comment by yangningmoojing** [comment]
> 

昨天出现了，今天没发现这问题，明天在看看

**Comment by hcfw007** [comment]
长时间没有后续回复，问题关闭。
