### ISSUE TITLE
Other: 购买之后未开发票，客服无回复

### ISSUE THREAD

**Issue by LLSean** [wechaty/puppet-service-providers#235]
购买之后未开发票，客服无回复，啥时候能回复一下啊，购买了就没服务了吗

**Comment by su-chang** [comment]
@LLSean  购买的是哪个puppet的token？

**Comment by LLSean** [comment]
@su-chang 
企业微信

**Comment by su-chang** [comment]
@LLSean 了解，稍等我帮你问下看看，待会客服会联系你。

**Comment by su-chang** [comment]
@LLSean 客服联系你了，麻烦再看下？

**Comment by LLSean** [comment]
@su-chang 并没有收到任何消息

**Comment by su-chang** [comment]
你询问的是哪个客服？或者你和客服聊天的昵称提供下，以便于我们查找。或者你再发一条消息，把这个issue链接附上。

**Comment by LLSean** [comment]
@su-chang 昵称是Sean，然后发了issue链接

**Comment by su-chang** [comment]
好的，我们这边收到了。后续等客服和你沟通吧。 @LLSean

**Comment by su-chang** [comment]
@LLSean 这个问题如果已经处理完了，麻烦关闭该issue哈。
