### ISSUE TITLE
[FEAT]WorkPro:访问chatgpt出错

### ISSUE THREAD

**Issue by ccgulan** [wechaty/puppet-service-providers#236]
访问chatgpt出错，错误如下：
retry 1 times, error: TypeError: fetch failed
retry 2 times, error: TypeError: fetch failed
retry 3 times, error: TypeError: fetch failed
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:14152:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///E:/wechat-robot-worpro/node_modules/chatgpt/build/index.js:265:25 {
  cause: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
chatgpt的key是有效能用的

**Comment by su-chang** [comment]
@ccgulan 这个问题超出我们这边的解答范围。

**Comment by ccgulan** [comment]
@su-chang 你好：


请问企业微信不支持chatgpt吗，因为同样的代码同样的chatgpt key 在普通微信上是没问题的
