### ISSUE TITLE
[BUG]WorkPro:the network is not good

### ISSUE THREAD

**Issue by donhac** [wechaty/puppet-service-providers#238]
**Describe the bug**

python wechaty启动时出现 the network is not good

**Info**

 - Platform[e.g. Windows/Mac/Linux]: Mac
 - Runtime version[e.g. node/JAVA]: python 3.10
 - Wechaty version: 0.10.7
 - Wechaty Puppet version: 0.4.23

**Screenshots**
![CleanShot 2023-08-08 at 16 12 56@2x](https://github.com/wechaty/puppet-supports/assets/9813324/86c4901c-b628-4d9d-a04e-67f088fcde1a)

**Additional context**

调用 https://token-service-discovery-test.juzibot.com/v0/hosties/puppet_workpro_xxxx 返回结果：
`{
    "host": "68.79.54.36",
    "ip": "68.79.54.36",
    "port": 4002
}`

运行代码：
https://github.com/wechaty/python-wechaty-getting-started

在 `bot.py` 指定了 endpoint，通过环境变量配置的 token
`
    options = WechatyOptions(
        endpoint='token-service-discovery-test.juzibot.com'
    )
`

**Comment by hcfw007** [comment]
对于 python 版本我们所能提供的支持有限，如果在部署环境能访问到发现服务并获得返回，那按道理是没有问题的。

**Comment by donhac** [comment]
我用 nodejs 版本的 demo 跑了下是正常的，可能是 python 版本哪里配置有问题吧，python-wechaty 那边看了下也有人提了相同 issue 但作者没回复，还是用 node 版的吧
