### ISSUE TITLE
[BUG]WorkPro: 刚申请的token 提示token does not exit

### ISSUE THREAD

**Issue by ccgulan** [wechaty/puppet-service-providers#241]
刚申请的token 提示token does not exit:

10:31:58 WARN ResolverWechaty updateResolution() address not found target wechaty://api.chatie.io/puppet_workpro_de1************************************: token does not exist
10:31:58 ERR StarterBot Error: 14 UNAVAILABLE: Wechaty service discovery / resolution failed for target wechaty://api.chatie.io/puppet_workpro_de1************************************: token "puppet_workpro_de1************************************" does not exist
10:31:59 WARN ResolverWechaty updateResolution() address not found target wechaty://api.chatie.io/puppet_workpro_de1************************************: token does not exist

**Comment by hcfw007** [comment]
因为之前出现了社区发现服务不稳定的问题，现在我们的token都默认采用我们私有的发现服务。
请配置环境变量：
WECHATY_PUPPET_SERVICE_AUTHORITY=token-service-discovery-test.juzibot.com

**Comment by chinacion** [comment]
> token does not exit

修改完环境变量依然 token does not exit，token有生效时间吗？

**Comment by chinacion** [comment]
> 

应该去掉http://

**Comment by hcfw007** [comment]
哦是的，这是复制富文本的时候自动加上的，我没注意。
