### ISSUE TITLE
[求助]WorkPro: python version run the bot failed

### ISSUE THREAD

**Issue by lspbeyond** [wechaty/puppet-service-providers#242]
1. web ide可以跑通
gitpod
wechaty-gettingstarted
Env: WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true
Env: WECHATY_PUPPET_SERVICE_AUTHORITY=token-service-discovery-test.juzibot.com
===如上场景下，我的token可以跑通ding-dong test

2. 求助：python-wechaty折腾不出来
调试环境：mac,python 3.10, 
wechaty                       0.10.7
wechaty-grpc                  0.20.19
wechaty-puppet                0.4.23
wechaty-puppet-service        0.8.10

错误信息：
2023-08-14 15:48:35,921 - PuppetService - INFO - init puppet ...
2023-08-14 15:48:35,921 - PuppetService - INFO - fetching endpoint from chatie-server: https://api.chatie.io/v0/hosties/xxxx

推测：
跟环境变量WECHATY_PUPPET_SERVICE_AUTHORITY有关。

一些尝试的办法：
(a) 通过系统命令设置环境变量
(b) 在代码中设置环境变量
错误依旧，推测PuppetService没有读取到环境变量。
(c）尝试查看PuppetService源码，未果，只找到wechaty.py的相关代码：
def _load_puppet(options: WechatyOptions) -> Puppet:
            #
            # wechaty-puppet-service
            #
            puppet_service_module = __import__('wechaty_puppet_service')
            if not hasattr(puppet_service_module, 'PuppetService'):
                raise WechatyConfigurationError('PuppetService not exist in '
                                                'wechaty-puppet-service')

            puppet_service_class = getattr(puppet_service_module, 'PuppetService')
            if not issubclass(puppet_service_class, Puppet):
                raise WechatyConfigurationError(f'Type {puppet_service_class} '
                                                f'is not correct')

            return puppet_service_class(options.puppet_options)

**Comment by hcfw007** [comment]
我们对非node版本的wechaty无法提供支持，很抱歉。如果可能请尽量使用node进行开发。

**Comment by lspbeyond** [comment]
哭晕，我购买token的时候，还特意check了是否支持python版本

**Comment by hcfw007** [comment]
理论上是支持的，但我们这边做开发的基本都不懂Python。

**Comment by hcfw007** [comment]
如果是因为WECHATY_PUPPET_SERVICE_AUTHORITY无法生效，可以联系客服把发现服务改为社区版应该就行了。但可能面临的问题还有：社区发现服务不稳定、可能无法发送图片和文件。

**Comment by lspbeyond** [comment]
好，我试试

**Comment by lspbeyond** [comment]
> 如果是因为WECHATY_PUPPET_SERVICE_AUTHORITY无法生效，可以联系客服把发现服务改为社区版应该就行了。但可能面临的问题还有：社区发现服务不稳定、可能无法发送图片和文件。

技术人员帮我切换发现服务，目前通了，多谢。
