### ISSUE TITLE
[FEAT]WorkPro: 如何拿到raw msg

### ISSUE THREAD

**Issue by lspbeyond** [wechaty/puppet-service-providers#244]
【问题】
封装的Message缺少字段，我需要用到原始消息中的字段，请问如何获取？ 或者最原始的payload也可以，我试试自己分析。

【参考itchat】
e.g. 
公众号名片：
{'UserName': '@c7c61344364f2e3649349f459b997a8f3c800a0d25068462006fddabd7f1820d', 
'NickName': '钱江晚报', 'QQNum': 0, 'Province': '浙江', 'City': '中国大陆', 'Content': '', 'Signature': '', 'Alias': '', 'Scene': 17, 'VerifyFlag': 24, 'AttrStatus': 98307, 'Sex': 0, 'Ticket': '', 'OpCode': 0}

**Comment by hcfw007** [comment]
你需要什么字段？wechaty是不提供原始消息的。

**Comment by lspbeyond** [comment]
MessageType.MESSAGE_TYPE_CONTACT
我需要VerifyFlag 字段。

目的是能区分微信名片or公众号卡片

**Comment by hcfw007** [comment]
这个应该可以通过先获取到联系人，message.toContact()，然后根据联系人的属性判断吧。

**Comment by lspbeyond** [comment]
> 这个应该可以通过先获取到联系人，message.toContact()，然后根据联系人的属性判断吧。
没找到能区分公众号和个人的属性。
从官网API文档看到了希望，但实测没法区分，麻烦确认下是否为bug。如下：
https://wechaty.gitbook.io/wechaty/v/zh/api/contact
中提及：
contact.type() ⇒ ContactType.Unknown | ContactType.Personal | ContactType.Official
获取好友的类型，是公众号还是普通还有。

实际测试：不管是个人还是公众号卡片，都是 ContactType.Personal

**Comment by su-chang** [comment]
> 实际测试：不管是个人还是公众号卡片，都是 ContactType.Personal

这个目前workpro还不支持区分

```ts
enum ContactType {
  Unknown     = 0,
  Individual  = 1,
  Official    = 2, // workpro暂不支持
  Corporation = 3,
}
```

**Comment by lspbeyond** [comment]
有排期计划吗？

**Comment by su-chang** [comment]
目前没有，这个属于小众需求，我们会先进行记录。具体排期还需要看整体时间规划。

**Comment by lspbeyond** [comment]
这个功能对我比较重要，希望能提高优先级。

另外还有一个糟糕的问题，我是需要拿到公众号名称。为什么下面代码拿到的是一个邮箱？
contact = await wechaty_msg.to_contact()
print(contact.name)

请问如何获取公众号名称？

**Comment by su-chang** [comment]
@lspbeyond 提供下对应公众号的信息，我们这边查日志看下。

**Comment by lspbeyond** [comment]
<img width="268" alt="image" src="https://github.com/wechaty/puppet-supports/assets/6042121/008dc96c-2831-40d0-bf32-6fcae17ca0cc">
公众号：奇绩创坛

contact = await wechaty_msg.to_contact()
print(contact.name)
输出为：kehan@miracleplus.com

**Comment by su-chang** [comment]
@lspbeyond 接收到这个名片消息的时间和ID能提供下吗？

**Comment by su-chang** [comment]
@lspbeyond ping

**Comment by lspbeyond** [comment]
我找人问了，这是企业微信本身的问题，他们没有考虑到公众号名片的支持。

**Comment by hcfw007** [comment]
问题已解决，Issue关闭。
