### ISSUE TITLE
[FEAT]WorkPro: 企业微信机器人如何发送别的消息类型

### ISSUE THREAD

**Issue by zhongyufan** [wechaty/puppet-service-providers#245]
1、可以发送地址消息吗？可以的话用哪个api。目前接收到地址消息，消息类型为8，如何解析改消息的内容。
2、可以发送小程序吗？

**Comment by su-chang** [comment]
@zhongyufan 

**发送位置消息**
```ts
const location = new Location ({
   accuracy  : 15,
   address   : '北京市北京市海淀区45 Chengfu Rd',
   latitude  : 39.995120999999997,
   longitude : 116.334154,
   name      : '东升乡人民政府(海淀区成府路45号)',
})
await contact.say(location)
```

**接收位置消息**
```ts
await message.toLocation()
```

**Comment by zhongyufan** [comment]
描述：
二维码生成后，用户扫码了点击取消，scan返回的是ScanStatus.Timeout 然后继续ScanStatus.Waiting
疑问：
1、ScanStatus.Cancel这个状态什么时候触发？ 
2、二维码是多少分钟失效的，失效返回是什么状态？

**Comment by su-chang** [comment]
1. 点击取消/点击关闭
2. 10分钟，失效后会重新推送新的二维码

**Comment by zhongyufan** [comment]
Location 这个是从哪里导入的？

**Comment by zhongyufan** [comment]
![image](https://github.com/wechaty/puppet-supports/assets/26425772/28b223ee-78ff-498a-990c-bcf0cc09f2a2)

**Comment by zhongyufan** [comment]
还有小程序是哪儿导入MiniProgram

**Comment by hcfw007** [comment]
如果使用的是juzi的包或者wechaty 1.0的包，location和miniProgram都不需要导入。
应该使用 
```ts
const location = new bot.Location({})
const miniProgram = new bot.MiniProgram({})
```
的形式

**Comment by zhongyufan** [comment]
可以发送语音消息吗？

**Comment by hcfw007** [comment]
> 可以发送语音消息吗？

可以的，发送 silk 类型的文件就会自动识别为语音

**Comment by hcfw007** [comment]
问题已解决，Issue关闭。
