### ISSUE TITLE
[求助]WorkPro: 关于python版本的调试

### ISSUE THREAD

**Issue by lspbeyond** [wechaty/puppet-service-providers#246]
这两天调试python版本，python版本因为更新慢，有一些地方跟最新的协议不兼容了。
目前还是想尝试在python版本上修兼容性bug，求助如下：

1. wechaty_grpc的python版本源码在哪？
https://pypi.org/project/wechaty-grpc/0.33.dev6/#history
通过这个链接看到这个包是在更新，而且新版的确有效。但git上未找到对应源码。
2. 新版的wechaty_grpc包有效，但python_wechaty, python_wechat_puppet库的代码有不少兼容性问题，举例如下：
        #fixme: wechaty-grpc                  0.33.dev6 不支持
        #self.create_time = wechaty_msg.payload.timestamp

PuppetStub.message_send_text() got an unexpected keyword argument 'mentonal_ids'

求助：哪里能看到PuppetStub接收和发送消息体格式的参考文档。

**Comment by huan** [comment]
See: https://github.com/wechaty/grpc

You can read the polyglot directory for python related code, and GitHub actions for python pypi package ci/cd

**Comment by lspbeyond** [comment]
多谢，我看下

**Comment by lspbeyond** [comment]
> See: https://github.com/wechaty/grpc
> 
> You can read the polyglot directory for python related code, and GitHub actions for python pypi package ci/cd

多谢指引，不过我没看到里面有python的源码，如下的setuptools代码中指向的src文件夹没找到。
   

 setuptools.setup(
        name='wechaty-grpc',
        version=version,
        author='Huan LI (李卓桓)',
        author_email='zixia@zixia.net',
        description='Wechaty Puppet Service gRPC API',
        long_description=long_description,
        long_description_content_type='text/markdown',
        license='Apache-2.0',
        url='https://github.com/wechaty/grpc',
        packages=setuptools.find_packages("src"),
        package_dir={'': 'src'},
        classifiers=[
            'Programming Language :: Python :: 3.7',
            'License :: OSI Approved :: Apache Software License',
            'Operating System :: OS Independent',
        ],
        install_requires=[
            'betterproto',
            'grpclib',
        ]
    )

**Comment by huan** [comment]
The script will generate the Python source code under `src/` when running GitHub Actions.

You can find the GitHub Action at https://github.com/wechaty/grpc/blob/main/.github/workflows/python.yml

**Comment by lspbeyond** [comment]
多谢指引，我试一下

**Comment by hcfw007** [comment]
长期没有回复，Issue关闭。
