### ISSUE TITLE
[BUG]WorkPro:dingdong示例代码运行报错

### ISSUE THREAD

**Issue by miloira** [wechaty/puppet-service-providers#247]
python版本：3.8
wechaty版本：最新版本0.10.7
报错原因：运行示例代码时报错urllib3模块中找不到get_host
![image](https://github.com/wechaty/puppet-supports/assets/51477120/5578c9b4-41fe-466e-b02a-6fc266c0455a)

**Comment by su-chang** [comment]
python版本的我们这边无法提供技术支持，请到对应的repo发issue提问题。或者请使用typescript版本的wechaty。

**Comment by jyys01** [comment]
@miloira 重新安装urllib3，可以解决get_host这个错误
pip uninstall urllib3
pip install 'urllib3<2.0'

**Comment by hcfw007** [comment]
问题已解决，Issue关闭。
