### ISSUE TITLE
[BUG]WorkPro:企业版微信无法接收到消息事件

### ISSUE THREAD

**Issue by miloira** [wechaty/puppet-service-providers#248]
python版本：3.8.0
wechaty网关镜像版本：wechaty/wechaty:0.65
wechaty版本：0.8.0
![image](https://github.com/wechaty/puppet-supports/assets/51477120/3fbac84f-7b6b-478d-8050-80ef28e22a69)

![891566509bab278e0f7b623b9dd369b](https://github.com/wechaty/puppet-supports/assets/51477120/367cb2c9-720e-416d-8d0b-e55ba7c00449)

**Comment by su-chang** [comment]
@miloira  请升级wechaty版本到latest的，0.65版本有点太久远了。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
