### ISSUE TITLE
[求助]WorkPro: WorkPro如何发送「UrlLink」消息？

### ISSUE THREAD

**Issue by Moveharder** [wechaty/puppet-service-providers#251]
WorkPro如何发送「UrlLink」消息？文档都是旧的导入方式`const { UrlLink } = require("wechaty");` 这样UrlLink是undefined。

版本信息：
wechaty：^1.20.2

**Comment by su-chang** [comment]
可以参考以下示例：
```ts
const link = new bot.UrlLink({
  description: 'description',
  thumbnailUrl: 'image url',
  title: 'title',
  url: 'url link'
})
await message.say(link)
```

**Comment by Moveharder** [comment]
> 可以参考以下示例：
> 
> ```ts
> const link = new bot.UrlLink({
>   description: 'description',
>   thumbnailUrl: 'image url',
>   title: 'title',
>   url: 'url link'
> })
> await message.say(link)
> ```

谢谢，我后面在GPT上查到了新用法。请问最新的官方文档地址是 https://wechaty.js.org/docs/ 吗？我之前找遍了也没看到最新用法。
