### ISSUE TITLE
[BUG]WorkPro:监听不到friendship事件

### ISSUE THREAD

**Issue by Moveharder** [wechaty/puppet-service-providers#253]
在测试的过程中，当用户的微信第一次添加我的企业微信为好友的时候，可以触发[friendship]事件。但是，如果双方互相删除好友关系后，微信再次添加企业微信为好友，这时无法触发[friendship]事件。试了好几个帐号都是这样，从今天开始出现的这个问题。

而且 `bot.Friendship.Type`里其实只有四中状态[0,1,2,3] 但是实际上 通过`friendship.type()` 可以拿到还可以拿到 [4,5]，经验证在双方删除好友的时候会触发。这个是什么情况？

## 系统环境：
- MacOS
- Node v16.16.0
- Wechaty ^1.20.2
- wechaty-puppet-service ^1.19.9

代码如下：
```js
const onfriendship = async (friendship, bot) => {
  try {
    let type = friendship.type();
    let name = await friendship.contact().name();
    let hello = await friendship.hello() || 'null';

    console.log(
      "\n[onfriendship] type(%s) name(%s) hello(%s)",
      type,
      name,
      hello
    );

    switch (type) {
      // 确认好友请求(无需我确认) - 1
      case bot.Friendship.Type.Confirm:
        log.info("[onfriendship]", "Confirm.....");

        await sendAcceptMsgs(friendship, bot, "Confirm");

        break;

      // 收到好友请求(需要我确认) - 2
      case bot.Friendship.Type.Receive:
        log.info("[onfriendship]", "Receive.....");

        await friendship.accept();
        log.info("[onfriendship]", "自动接受好友请求");

        await sendAcceptMsgs(friendship, bot, "Receive");

        break;

      case 4:
        log.info("\n[主动删]", name);
        break;

      case 5:
        log.info("\n[被删除]", name);
        break;

      default:
        await sendAcceptMsgs(friendship, bot, "default");

        break;
    }
  } catch (err) {
    log.error("[onfriendship]", "出错了");
    console.log(err);
  }
};


```

**Comment by su-chang** [comment]
@Moveharder 4,5这两个状态是在 @juzi/wechaty 这个项目中适配的功能，分别表示bot删除联系人和联系人删除bot的状态。

如果想体验可以使用 @juzi/wechaty 替换 wechaty

**Comment by su-chang** [comment]
@Moveharder 关于你上面提到的双向删除好友后，再次添加bot为好友没有好友事件触发的问题，可以提供下触发的时间信息，以及添加的联系人信息，便于我这边在没有token的情况下检索日志，定位问题。

**Comment by Moveharder** [comment]
> @Moveharder 关于你上面提到的双向删除好友后，再次添加bot为好友没有好友事件触发的问题，可以提供下触发的时间信息，以及添加的联系人信息，便于我这边在没有token的情况下检索日志，定位问题。

好的，不过在这之前我想先确认另一个可能会造成影响的问题：关于Bot代理的企业微信账户是否开启了「添加我为联系人时-需要验证」对friendship事件的触发影响。

开启了：会先触发 case bot.Friendship.Type.Receive ，如果在此时通过代码 `await friendship.accept()` 自动接受好友请求后，接下来会触发 `case bot.Friendship.Type.Confirm` 事件。这样是正常的对吗？

未开启：如果是「双向删除过好友」，不触发friendship事件（⚠️这是今天出现的问题：操作时间 2023.8.24 11:48，由「Believer」添加「发条猿」）；如果「首次添加Bot」，只触发 `bot.Friendship.Type.Confirm`，这样是正常的对吧？

**Comment by Moveharder** [comment]
在bot再次启动或登录的时候，偶尔会出现过这个错误，导致无法触发 `case bot.Friendship.Type.Confirm`：
```js
ERR Error: 13 INTERNAL: WorkproErrorCode: 22010, friendshipAccept(d83b74d5-5b80-42d4-b4b1-a526697f75bc) failed, error info: {"errorCode":-3515,"errorMessage":""}
```

**Comment by Moveharder** [comment]
@su-chang 帮忙看下👆

**Comment by su-chang** [comment]
> 好的，不过在这之前我想先确认另一个可能会造成影响的问题：关于Bot代理的企业微信账户是否开启了「添加我为联系人时-需要验证」对friendship事件的触发影响。

是的，有影响，必须要开启「添加我为联系人时-需要验证」

**Comment by su-chang** [comment]
> 未开启：如果是「双向删除过好友」，不触发friendship事件（⚠️这是今天出现的问题：操作时间 2023.8.24 11:48，由「Believer」添加「发条猿」）；如果「首次添加Bot」，只触发 `bot.Friendship.Type.Confirm`，这样是正常的对吧？

对的，这个符合预期。

**Comment by Moveharder** [comment]
@su-chang 感谢回答。
如果是「双向删除过好友」，再次添加Bot时，不触发friendship事件。但是当我重新登录Bot，会在登录后收到之前的friendship事件的confirm。这很奇怪，有点像数据不同步！

操作时间 2023.8.24 15:59，由「Believer」添加「发条猿」

麻烦你们那边排查下问题，我现在用的是7daysfree token。

以下是我再次登陆后的日志：
`onscan: Waiting(2) - https://wechaty.js.org/qrcode/https%3A%2F%2Fwx.work.weixin.qq.com%2Fcgi-bin%2Fcrtx_auth%3Fkey%3D5EE1F3F7EAB9CA72D8B75A022AC83495%26wx%3D1
16:00:55 INFO 扫码登录： 3
- onScan: Scanned(3)
16:00:58 INFO 扫码登录： 4
- onScan: Confirmed(4)
16:01:01 INFO 出错了： Error: not logged in, no this.__currentUserId yet.
16:01:01 INFO 登录了： Contact<发条猿>

[onfriendship] type(1) name(Believer) hello(null)
16:01:02 INFO [onfriendship] Confirm.....
16:01:04 INFO [机器人回复了] 常见问题H5链接
16:01:04 INFO [onfriendship] Confirm`

**Comment by su-chang** [comment]
这个应该是添加好友10分钟内又重新登录了，拉取的新增添加好友列表中处理的不够好，导致多触发了一次 Receive 事件，这种情况下调用 accept() 后会抛出异常，错误码：-3515。


2023-08-24 @ 16:00:44.226 已在手机端退出登录
2023-08-24 @ 16:01:01.307	 token: puppet_workpro_099fac2b06544eb591d06827725bffef emitting grpc event EVENT_TYPE_LOGIN: {"contactId":"1688855129545241"}, seq: undefined

推送登录事件，和某些请求有时序冲突，即在登录状态还未变更时，进行了请求，会提示如下报错：
Error: not logged in, no this.__currentUserId yet.

**Comment by Moveharder** [comment]
@su-chang 👌 “再次添加Bot时，不触发friendship事件” 我这边的代码可以从哪些方面优化一下吗？

**Comment by su-chang** [comment]
@Moveharder 建议你在手机端不主动退出的windows登录的前提下，再尝试复现下看看。

如果复现了，请描述复现步骤（尽可能详细）。

**Comment by Moveharder** [comment]
@su-chang 

step1: node端启动Bot `17:51:32 INFO 登录了： Contact<企业微信名>`
step2: 之前互删的微信用户扫码添加Bot为好友（Bot账户没有不开启「加我需验证」）

就没有后续了，Bot这边没有触发 `friendship` 事件。

操作时间大致为：2023.8.24 17:51:32（或33）

其它的还需要提供啥吗？

**Comment by su-chang** [comment]
根据提供的时间信息没有检索到有效信息，你添加的好友名称是小卤蛋么？

```
2023-08-24 @ 17:59:00.851	 "你已在手机端切换企业"
```

确认在手机端开启了 「加我需验证」 这个吧？最好截个图。

BTW, `Bot账户没有不开启「加我需验证」` 你这个双重否定是认真的么？

**Comment by Moveharder** [comment]
@su-chang 
1. 由“小卤蛋”添加Bot；

2.手机端没有开启「加我需验证」（之前手抖打错了），业务上客服号不开启这个；

你们那边按照我上面的流程测试过吗，没遇到「互删之后微信在添加Bot，Bot监听不到friendship事件」的问题吗？

**Comment by su-chang** [comment]
需要开启「加我需验证」才行，否则我们这边无法准确接收到相关事件。

**Comment by Moveharder** [comment]
@su-chang 呃，这样啊。

那如果开启「加我需验证」后遇到了另一个问题：
「微信添加Bot，Bot自动接受请求」这个过程中会触发3次`message`事件，分别是：
- 微信添加Bot的打招呼信息。如：你好，我是xxx（也可能是任意输入的内容）
- 以上是打招呼内容
- 你已添加了xxx，现在可以开始聊天了。

这3次`message`会直接Bot的`message`业务处理，因为微信用户和Bot的对话都是在`message`事件里根据自定义的业务逻辑触发自动回复微信用户的。

目前我只能根据关键字去忽略，官方有什么好的办法去规避这3次非真实聊天的message呢？请给个优雅的思路

**Comment by su-chang** [comment]
消息类型不一样，你可以根据类型进行区分。

以下两条消息是的类型是系统消息
- 以上是打招呼内容
- 你已添加了xxx，现在可以开始聊天了。

**Comment by Moveharder** [comment]
@su-chang 
你说的类型应该就是发送人的类型对吧，一开始考虑过。但是我这边根据`contact.type()`拿到的联系人类型都是 `1` (`Individual`)。我应该通过哪个方法判断呢？文档没找到相关内容！

具体可以看「微信添加Bot，Bot自动接受请求」这个过程的日志：

```shell
[onfriendship] type(2) name(1721) hello(我是1721)
11:59:31 WARN [onfriendship] Receive.....

11:59:36 INFO [onmessage] 👼[1721] 说 以上是打招呼内容 
11:59:36 INFO 【contact.type()】  1

11:59:36 INFO [onmessage] 👼[1721] 说 我是1721 
11:59:36 INFO 【contact.type()】  1

11:59:36 INFO [onmessage] 👼[1721] 说 你已添加了1721，现在可以开始聊天了。 
11:59:36 INFO 【contact.type()】  1

11:59:36 INFO 【bot.Contact.Type】 {
  "0": "Unknown",
  "1": "Individual",
  "2": "Official",
  "3": "Corporation",
  "Unknown": 0,
  "Individual": 1,
  "Official": 2,
  "Corporation": 3
}

11:59:36 WARN [onfriendship] 自动接受好友请求



12:02:50 INFO [onmessage] 👼[1721] 说 我想问个问题 
12:02:50 INFO 【contact.type()】  1


```

**Comment by Moveharder** [comment]
@su-chang 好吧，我试了下 ，有`message.type()` 这个方法，你说的「根据类型判断」指的是这个对吧？

用户发送的文本消息类型：`12:26:06 INFO 【message.type()】  7`

添加好友的系统消息类型：`12:26:06 INFO 【message.type()】  18`

但是 `bot.Message.Type` 里面并没有 `18`。难道也是因为没有使用 `@juzibot/wechaty` 吗？
```shell
12:26:06 INFO 【bot.Message.Type】 {
  "0": "Unknown",
  "1": "Attachment",
  "2": "Audio",
  "3": "Contact",
  "4": "ChatHistory",
  "5": "Emoticon",
  "6": "Image",
  "7": "Text",
  "8": "Location",
  "9": "MiniProgram",
  "10": "GroupNote",
  "11": "Transfer",
  "12": "RedEnvelope",
  "13": "Recalled",
  "14": "Url",
  "15": "Video",
  "16": "Post",

  "Unknown": 0,
  "Attachment": 1,
  "Audio": 2,
  "Contact": 3,
  "ChatHistory": 4,
  "Emoticon": 5,
  "Image": 6,
  "Text": 7,
  "Location": 8,
  "MiniProgram": 9,
  "GroupNote": 10,
  "Transfer": 11,
  "RedEnvelope": 12,
  "Recalled": 13,
  "Url": 14,
  "Video": 15,
  "Post": 16
}

```

**Comment by su-chang** [comment]
> 但是 `bot.Message.Type` 里面并没有 `18`。难道也是因为没有使用 `@juzi/wechaty` 吗？

是的

**Comment by Moveharder** [comment]
😅 npm install @juzibot/wechaty 404 了，这不是一个公共包吗？我应该如何安装使用它

**Comment by su-chang** [comment]
> 😅 npm install @juzibot/wechaty 404 了，这不是一个公共包吗？我应该如何安装使用它

@juzi/wechaty 这个

**Comment by Moveharder** [comment]
@su-chang 
好的，这样安装成功了。我将引入方式改为：`const { WechatyBuilder, log } = require("@juzi/wechaty");`，其他不做修改的情况下出现了新的问题，「⚠️无法监听到`message`」，以下是我用微信给Bot发消息时的报错：

```shell
3:56:06 INFO [出错了] GError: message not found for id: cd327374820afe82d89d7f1c9ebd7277

13:56:06 INFO 
[事件 (onerror) 上报] {"data":{"code":2,"details":"GError: message not found for id: cd327374820afe82d89d7f1c9ebd7277\n    at Function.from (/Users/lucia/wc_web/nina/fitness_wechat_bot/node_modules/gerror/dist/cjs/src/gerror/gerror.js:86:23)\n    at PuppetService.<anonymous> (/Users/lucia/wc_web/nina/fitness_wechat_bot/node_modules/@juzi/wechaty/dist/cjs/src/wechaty-mixins/puppet-mixin.js:253:72)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","message":"message not found for id: cd327374820afe82d89d7f1c9ebd7277","name":"GError","stack":"GError: message not found for id: cd327374820afe82d89d7f1c9ebd7277\n    at Function.from (/Users/lucia/wc_web/nina/fitness_wechat_bot/node_modules/gerror/dist/cjs/src/gerror/gerror.js:86:23)\n    at PuppetService.<anonymous> (/Users/lucia/wc_web/nina/fitness_wechat_bot/node_modules/@juzi/wechaty/dist/cjs/src/wechaty-mixins/puppet-mixin.js:253:72)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}}

```

最后，贴上我的 `dependencies`，是否需要把所有用到的puppet都换成 `@juzi/ ` 的。
```js
"dependencies": {
    "@juzi/wechaty": "^1.0.65",
    "dotenv": "^16.3.1",
    "file-box": "^1.5.5",
    "joi": "^17.9.2",
    "qrcode-terminal": "^0.12.0",
    "save": "^2.9.0",
    "wechaty": "^1.20.2",
    "wechaty-cqrs": "^0.12.5",
    "wechaty-plugin-contrib": "^1.12.1",
    "wechaty-puppet-padlocal": "^1.20.1",
    "wechaty-puppet-service": "^1.19.9",
    "wechaty-puppet-wechat": "^1.18.4",
    "wechaty-puppet-wechat4u": "^1.14.1",
    "wechaty-puppet-xp": "^1.12.7"
  }
```

**Comment by su-chang** [comment]
> 最后，贴上我的 `dependencies`，是否需要把所有用到的puppet都换成 `@juzi/ ` 的。

是的

**Comment by Moveharder** [comment]
@su-chang 
🤷 假如要使用 `@juzi/wechaty` 具体都应该做哪些适配（安装包、代码），有说明手册吗？我这样一点一点试太费劲了。

刚刚先把 `wechaty-puppet-service` 换成了 `@juzi/wechaty-puppet-service`，依然是那个报错。

**Comment by su-chang** [comment]
@Moveharder 提供下你目前的package信息，和对应的报错信息（最好能提供下报错的相关代码）。

**Comment by Moveharder** [comment]
> @su-chang 好的，这样安装成功了。我将引入方式改为：`const { WechatyBuilder, log } = require("@juzi/wechaty");`，其他不做修改的情况下出现了新的问题，「⚠️无法监听到`message`」，以下是我用微信给Bot发消息时的报错：
> 
> ```shell
> 3:56:06 INFO [出错了] GError: message not found for id: cd327374820afe82d89d7f1c9ebd7277
> 
> 13:56:06 INFO 
> [事件 (onerror) 上报] {"data":{"code":2,"details":"GError: message not found for id: cd327374820afe82d89d7f1c9ebd7277\n    at Function.from (/Users/lucia/wc_web/nina/fitness_wechat_bot/node_modules/gerror/dist/cjs/src/gerror/gerror.js:86:23)\n    at PuppetService.<anonymous> (/Users/lucia/wc_web/nina/fitness_wechat_bot/node_modules/@juzi/wechaty/dist/cjs/src/wechaty-mixins/puppet-mixin.js:253:72)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","message":"message not found for id: cd327374820afe82d89d7f1c9ebd7277","name":"GError","stack":"GError: message not found for id: cd327374820afe82d89d7f1c9ebd7277\n    at Function.from (/Users/lucia/wc_web/nina/fitness_wechat_bot/node_modules/gerror/dist/cjs/src/gerror/gerror.js:86:23)\n    at PuppetService.<anonymous> (/Users/lucia/wc_web/nina/fitness_wechat_bot/node_modules/@juzi/wechaty/dist/cjs/src/wechaty-mixins/puppet-mixin.js:253:72)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}}
> ```
> 
> 最后，贴上我的 `dependencies`，是否需要把所有用到的puppet都换成 `@juzi/ ` 的。
> 
> ```js
> "dependencies": {
>     "@juzi/wechaty": "^1.0.65",
>     "dotenv": "^16.3.1",
>     "file-box": "^1.5.5",
>     "joi": "^17.9.2",
>     "qrcode-terminal": "^0.12.0",
>     "save": "^2.9.0",
>     "wechaty": "^1.20.2",
>     "wechaty-cqrs": "^0.12.5",
>     "wechaty-plugin-contrib": "^1.12.1",
>     "wechaty-puppet-padlocal": "^1.20.1",
>     "wechaty-puppet-service": "^1.19.9",
>     "wechaty-puppet-wechat": "^1.18.4",
>     "wechaty-puppet-wechat4u": "^1.14.1",
>     "wechaty-puppet-xp": "^1.12.7"
>   }
> ```

这个就是我这边用了「@juzi/wechaty」以后的报错以及的package.json目前的情况。

**Comment by hcfw007** [comment]
请再提供一下你bot 初始化那段代码（wechatyBuilder build那段）注意隐藏敏感信息。

**Comment by Moveharder** [comment]
@hcfw007 好的，代码如下：

```js
let options = {
  puppet: "wechaty-puppet-service",
  puppetOptions: {
    tls: {
      disable: true
    },
    token: process.env.WECHATY_PUPPET_WORKPRO_TOKEN, //workpro token
  },
};

let bot = createBot(options);

```

```js
const { WechatyBuilder, log } = require("@juzi/wechaty"); // [⚠️ 这里在用wechaty时不会报错 ⚠️]
const createBot = (options = {}) => {
  const botOptions = {
    ...options,
  };
  const bot = WechatyBuilder.build(botOptions);

  try {
    bot
      .on("scan", onscan)
      .on("login", onlogin)
      .on("logout", (user) => onlogout(user, bot))
      .on("friendship", (friendship) => onfriendship(friendship, bot))
      .on("message", (message) => onmessage(message, bot))
      .on("heartbeat", (heartbeat) => onheartbeat(heartbeat, bot))
      .on("error", onerror)
      .start();
  } catch (err) {
    // TODO 上报机器人异常状态
    log.error("[机器人主程序报错]", err);
    eventReport("apperror", { data: err });
  }

  return bot;
};

```

**Comment by hcfw007** [comment]
将 ```  puppet: "wechaty-puppet-service",``` 改为 ```  puppet: "@juzi/wechaty-puppet-service",``` 试试吧

**Comment by Moveharder** [comment]
@hcfw007 试了，但是这次在启动Bot的时候报错了。

### 以下是Bot执行代码
```js

let options = {
  puppet: "@juzi/wechaty-puppet-service",
  puppetOptions: {
    tls: {
      disable: true,
    },
    token: process.env.WECHATY_PUPPET_WORKPRO_TOKEN, //workpro token
  },
};

let bot = createBot(options);
```

```js
const { WechatyBuilder, log } = require("@juzi/wechaty");

const createBot = (options = {}) => {
  const botOptions = {
    ...options,
  };
  const bot = WechatyBuilder.build(botOptions);

  try {
    bot
      .on("scan", onscan)
      .on("login", onlogin)
      .on("logout", (user) => onlogout(user, bot))
      .on("friendship", (friendship) => onfriendship(friendship, bot))
      .on("message", (message) => onmessage(message, bot))
      .on("heartbeat", (heartbeat) => onheartbeat(heartbeat, bot))
      .on("error", onerror)
      .start();
  } catch (err) {
    log.error("[机器人主程序报错]", err);
    eventReport("apperror", { data: err });
  }

  return bot;
};

```

### 以下是「启动Bot」报错信息：
```shell
11:34:33 INFO [出错了] NotFoundError: Key not found in database [eventTimestamp]
11:34:33 INFO 
[事件 (onerror) 上报] {"data":{"code":2,"details":"NotFoundError: Key not found in database [eventTimestamp]\n    at /Users/lucia/wc_web/nina/fitness_wechat_bot/node_modules/_levelup@5.1.1@levelup/lib/levelup.js:188:15\n    at /Users/lucia/wc_web/nina/fitness_wechat_bot/node_modules/_encoding-down@7.1.0@encoding-down/index.js:75:21","message":"Key not found in database [eventTimestamp]","name":"NotFoundError","stack":"NotFoundError: Key not found in database [eventTimestamp]\n    at /Users/lucia/wc_web/nina/fitness_wechat_bot/node_modules/_levelup@5.1.1@levelup/lib/levelup.js:188:15\n    at /Users/lucia/wc_web/nina/fitness_wechat_bot/node_modules/_encoding-down@7.1.0@encoding-down/index.js:75:21"}}
11:34:33 WARN ServiceCtl<PuppetServiceMixin> stop() found that is starting...
11:34:33 WARN ServiceCtl<PuppetServiceMixin> stop() found that is starting, waiting stable ... (max 5 seconds)
11:34:38 INFO [出错了] DEADLINE_EXCEEDED: Timeout after 5000 ms

```

### 以下是依赖项情况：
```js
"dependencies": {
    "@juzi/wechaty": "^1.0.65",
    "@juzi/wechaty-puppet": "^1.0.61",
    "@juzi/wechaty-puppet-service": "^1.0.69",
    "dotenv": "^16.3.1",
    "file-box": "^1.5.5",
    "joi": "^17.9.2",
    "qrcode-terminal": "^0.12.0",
    "wechaty": "^1.20.2",
    "wechaty-cqrs": "^0.12.5",
    "wechaty-plugin-contrib": "^1.12.1",
    "wechaty-puppet-padlocal": "^1.20.1",
    "wechaty-puppet-service": "^1.19.9",
    "wechaty-puppet-wechat": "^1.18.4",
    "wechaty-puppet-wechat4u": "^1.14.1",
    "wechaty-puppet-xp": "^1.12.7"
  }

```

**Comment by hcfw007** [comment]
请尝试清空一下wechaty的缓存，默认应该是在 ~/.wechaty 目录下

**Comment by Moveharder** [comment]
@hcfw007 我尝试删除了.wechaty目录，重新运行代码，同样的报错。

```shell
14:39:54 INFO [出错了] NotFoundError: Key not found in database [eventTimestamp]
14:39:54 INFO 
[事件 (onerror) 上报] {"data":{"code":2,"details":"NotFoundError: Key not found in database [eventTimestamp]\n    at /Users/lucia/wc_web/nina/fitness_wechat_bot/node_modules/_levelup@5.1.1@levelup/lib/levelup.js:188:15\n    at /Users/lucia/wc_web/nina/fitness_wechat_bot/node_modules/_encoding-down@7.1.0@encoding-down/index.js:75:21","message":"Key not found in database [eventTimestamp]","name":"NotFoundError","stack":"NotFoundError: Key not found in database [eventTimestamp]\n    at /Users/lucia/wc_web/nina/fitness_wechat_bot/node_modules/_levelup@5.1.1@levelup/lib/levelup.js:188:15\n    at /Users/lucia/wc_web/nina/fitness_wechat_bot/node_modules/_encoding-down@7.1.0@encoding-down/index.js:75:21"}}
14:39:54 WARN ServiceCtl<PuppetServiceMixin> stop() found that is starting...
14:39:54 WARN ServiceCtl<PuppetServiceMixin> stop() found that is starting, waiting stable ... (max 5 seconds)

```

这个报错代表了什么？token的问题吗？我这个token是申请的7天免费试用的。

**Comment by hcfw007** [comment]
看起来是初始化一个本地缓存组件的时候报的错，我这还真没遇到过。我这边测一测，到时候可以再给续上测试时间。

**Comment by hcfw007** [comment]
可以拿token和issue号去联系客服。

**Comment by Moveharder** [comment]
> 看起来是初始化一个本地缓存组件的时候报的错，我这还真没遇到过。我这边测一测，到时候可以再给续上测试时间。

好的，早上的时候已经问客服续过了。

**Comment by Moveharder** [comment]
> 看起来是初始化一个本地缓存组件的时候报的错，我这还真没遇到过。我这边测一测，到时候可以再给续上测试时间。

@hcfw007 哈喽，这个你们试过之后怎么样啦？

**Comment by hcfw007** [comment]
我在本地没有遇到这个问题。——你们是否会在一个机器或者一个容器里启动多个进程？

**Comment by Moveharder** [comment]
目前只安装以下wechaty相关的依赖的情况下，服务可以正常运行了。感觉之前是被非@juzi/的某个wechaty依赖包给影响了。

"@juzi/wechaty": "^1.0.65",
"@juzi/wechaty-puppet": "^1.0.61",
"@juzi/wechaty-puppet-service": "^1.0.69"

**Comment by hcfw007** [comment]
> 目前只安装以下wechaty相关的依赖的情况下，服务可以正常运行了。感觉之前是被非@juzi/的某个wechaty依赖包给影响了。
> 
> "@juzi/wechaty": "^1.0.65", "@juzi/wechaty-puppet": "^1.0.61", "@juzi/wechaty-puppet-service": "^1.0.69"

嗯，有的情况是虽然引用了 @juzi/wechaty-puppet-service ，但实际创建 bot 的时候还是用了社区的 wechaty-puppet-service。

既然问题已经解决，Issue关闭。
