### ISSUE TITLE
[BUG]WorkPro: 同步群聊异常，扫码登陆二次校验异常

### ISSUE THREAD

**Issue by zhongyufan** [wechaty/puppet-service-providers#255]
问题一：
使用@juzi/wechaty@1.0.65 同步群聊报错， bot.on('ready')后调用await bot.Room.findAll();

报错信息：
Error: 13 INTERNAL: Request message serialization failure: Expected argument of type wechaty.puppet.RoomListRequest

使用wechaty@1.20.2 则是正常拉取。为什么要使用@juzi/wechaty@1.0.65 ，因为部分账户出现扫码后需要二次校验

问题二：
使用@juzi/wechaty@1.0.65 监听verify-code没有生效，该账户出现了二次校验码，但是可以点击左上角的关闭按钮，显示的是win端已登陆。

**Comment by su-chang** [comment]
问题一，麻烦提供下当前的package.json截图，确认下依赖版本。

问题二，已经处理了，可以再试下看看。
