### ISSUE TITLE
[BUG]WorkPro:退出登陆重新创建异常

### ISSUE THREAD

**Issue by zhongyufan** [wechaty/puppet-service-providers#256]
环境：@juzi/wechaty@1.0.65

使用 
```javascript
await bot.logout();
await bot.stop();
```
然后重新调用创建
```javascript
const bot = WechatyBuilder.build({
      name: `wechat-puppet`,
      puppet: '@juzi/wechaty-puppet-service',
      puppetOptions: {
        token: clientToken,
        tls: {
          disable: true,
        },
      },
    });
```
导致以下错误
/Users/zhong/Desktop/code/qiaoying-server/node_modules/.pnpm/deferred-leveldown@7.0.0/node_modules/deferred-leveldown/deferred-leveldown.js:49
      return callback(err || new Error('Database is not open'))
             ^
OpenError: IO error: lock /Users/zhong/.wechaty/wechaty-puppet-service/puppet_workpro_2331a90602904082920f054c13a9db7c/v1.0/miscellaneous/LOCK: already held by process
    at /Users/zhong/Desktop/code/qiaoying-server/node_modules/.pnpm/levelup@5.1.1/node_modules/levelup/lib/levelup.js:127:23
    at /Users/zhong/Desktop/code/qiaoying-server/node_modules/.pnpm/abstract-leveldown@7.2.0/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at onopen (/Users/zhong/Desktop/code/qiaoying-server/node_modules/.pnpm/deferred-leveldown@7.0.0/node_modules/deferred-leveldown/deferred-leveldown.js:49:14)
    at /Users/zhong/Desktop/code/qiaoying-server/node_modules/.pnpm/abstract-leveldown@7.2.0/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at /Users/zhong/Desktop/code/qiaoying-server/node_modules/.pnpm/abstract-leveldown@7.2.0/node_modules/abstract-leveldown/abstract-leveldown.js:41:14

**Comment by hcfw007** [comment]
退出登录之后 bot 并没有被销毁，不应该重新创建。直接 ```bot.start()``` 应该就可以了。

**Comment by zhongyufan** [comment]
如何销毁bot？

**Comment by zhongyufan** [comment]
我们的token是随机分配给用户，并没有一直启动着bot，需要彻底销毁bot

**Comment by hcfw007** [comment]
我研究了一下，wechaty似乎没有提供类似destroy之类的方法。但单纯stop()是不能彻底销毁的。你的使用场景能介绍一下吗。

**Comment by zhongyufan** [comment]
创建机器人的时候
let client= bot
存起来
然后调用退出逻辑
await bot.logout();
await bot.stop();
client = null
这个时候再去用同样的token创建机器人
会出现上面的错误，
在使用wechaty@1.20.2运行上述逻辑则是正常的。

**Comment by zhongyufan** [comment]
跑在pm2环境，饱了io错误重启又恢复

**Comment by hcfw007** [comment]
好的。能提供一下依赖版本吗，主要是 wechaty，wechaty-puppet 和 wechaty-puppet-service 的版本。

**Comment by zhongyufan** [comment]
没有主动安装wechaty-puppet 和 wechaty-puppet-service，只装了wechaty@1.20.2

**Comment by zhongyufan** [comment]
用的这个puppet创建
```javascript
const bot = WechatyBuilder.build({
      name: `wechat-puppet`,
      puppet: 'wechaty-puppet-service',
      puppetOptions: {
        token: clientToken,
        tls: {
          disable: true,
        },
      },
    });
```
是没有报io错误的

**Comment by hcfw007** [comment]
额你上面说1.20.2是正常的？

**Comment by zhongyufan** [comment]
是的 ，我原先就是这么运行的，是因为加了授权校验码才换的版本

**Comment by hcfw007** [comment]
> 是的 ，我原先就是这么运行的，是因为加了授权校验码才换的版本

你现在用的是 @juzi/wechaty 吗？

**Comment by zhongyufan** [comment]
是的

**Comment by zhongyufan** [comment]
[wechaty.zip](https://github.com/wechaty/puppet-supports/files/12449516/wechaty.zip)
一样的代码，不一样的依赖

**Comment by hcfw007** [comment]
```ts
  await bot.start()
  await bot.stop()
  await (bot.puppet as any)._payloadStore.miscellaneous.close()
  let puppet2 = new PuppetService({
  })
  bot = WechatyBuilder.build({
    puppet: puppet2
  })
```
在 stop 后加上   await (bot.puppet as any)._payloadStore.miscellaneous.close() 处理一下。

**Comment by zhongyufan** [comment]
可以了

**Comment by hcfw007** [comment]
这个是因为当时设计时没考虑到你们这种部署方式，一些磁盘上的缓存没关掉。这是一个临时的解决方案。
