### ISSUE TITLE
WXWork:  const room_list_q = await bot.Room.findAll() 会无响应，发消息也收不到，跟掉线一样

### ISSUE THREAD

**Issue by yangningmoojing** [wechaty/puppet-service-providers#258]
Please make sure you have read the [Wechaty Puppet Service: WXWork](https://wechaty.js.org/docs/puppet-services/wxwork) from Wechaty Official Website before you continue writting this issue.

## Question
        if (data_master_list.length > 0) {
        console.log('进来了!')
        const room_list_q = await bot.Room.findAll()
        console.log('获取所有微信群:', room_list_q)
        

代码是这样的，进来了可以打印出来，但是到 const room_list_q = await bot.Room.findAll() 这里就不走了，三个账号放在一个群里。同时命令的，一个账号正常，两个账号无响应，卡住，发消息什么的都不显示了，重启账号就会正常

**Comment by su-chang** [comment]
@yangningmoojing  有问题的账号有多少群聊？可以把token的后5位提供下。

**Comment by yangningmoojing** [comment]
> @yangningmoojing 有问题的账号有多少群聊？可以把token的后5位提供下。
319e4  194个，可能稍微会多几个
fede1  69个，也可能稍微会多几个

**Comment by hcfw007** [comment]
什么时候可以其中一个账号不用的时候可以让我连接试试吗？

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
