### ISSUE TITLE
[FEAT]WorkPro: token does not exist

### ISSUE THREAD

**Issue by jmjoy** [wechaty/puppet-service-providers#259]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

早上还好好的，用着用着就报token does not exist，换成了token-service-discovery-test.juzibot.com也不行。

日志：

没设置WECHATY_PUPPET_SERVICE_AUTHORITY前：
```
UNAVAILABLE: Wechaty service discovery / resolution failed for target wechaty://api.chatie.io/puppet_workpro_xxx: token "puppet_workpro_xxx" does not exist
```

设置后：
```
PuppetService Start() rejection: rpc error: code = Unavailable desc = Wechaty service discovery / resolution failed for target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_xxx: token "puppet_workpro_xxx" does not exist
```

**Info**

 - Platform[e.g. Windows/Mac/Linux]: Linux
 - Runtime version[e.g. node/JAVA]: node
 - Wechaty version: 1.20
 - Wechaty Puppet version:

**Comment by jmjoy** [comment]
使用docker： wechaty/wechaty:1.20

环境变量

 ```ini
WECHATY_LOG=verbose
WECHATY_PUPPET_SERVER_PORT="9001"
WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_SERVER="true"
WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT="true"
WECHATY_PUPPET=wechaty-puppet-service
WECHATY_PUPPET_SERVICE_TOKEN="puppet_workpro_xxx"
WECHATY_TOKEN="xxx"
WECHATY_PUPPET_SERVICE_AUTHORITY=token-service-discovery-test.juzibot.com
```

**Comment by hcfw007** [comment]
请确认一下token到期时间，如果没到期，请联系客服提供一下具体token

**Comment by jmjoy** [comment]
没有过期，已联系客服

**Comment by jmjoy** [comment]
请帮忙处理一下

**Comment by jmjoy** [comment]
@hcfw007 token上个月已经购买了，已经将issue号和token发送给客服，请帮忙处理一下

**Comment by hcfw007** [comment]
处理了

**Comment by jmjoy** [comment]
@hcfw007 还是一样的错误

**Comment by jmjoy** [comment]
可以了
