### ISSUE TITLE
[FEAT]WorkPro:

### ISSUE THREAD

**Issue by Henryyijun** [wechaty/puppet-service-providers#260]
使用***Python-wechaty-getting-started***项目中的***ding-dong-bot.py***启动企业微信，然后报如下错误
![image](https://github.com/wechaty/puppet-supports/assets/26760101/ea878aa2-13cf-4282-8a7c-1ba3876441f0)

**Comment by hcfw007** [comment]
你好，如果可能的话请使用node版本的wechaty，对于Python我们无法提供更多支持。

**Comment by Henryyijun** [comment]
刚刚我使用了node版本的WeChaty,现在一直开在启动界面，无法弹出二维码
![image](https://github.com/wechaty/puppet-supports/assets/26760101/a53e559c-ff45-4f55-b6bf-11ac0bfaeb5d)

**Comment by Henryyijun** [comment]
> 你好，如果可能的话请使用node版本的wechaty，对于Python我们无法提供更多支持。
刚刚使用了node版本的，还是卡在了启动界面，没有弹出二维码
![image](https://github.com/wechaty/puppet-supports/assets/26760101/cfa9cd09-9c35-4300-8d83-25de58707db9)

**Comment by hcfw007** [comment]
为什么要指定endpoint？指定endpoint代表指定了token的终端地址，token-service-discovery实际是发现服务的地址。

如果希望使用社区包，可以尝试这个在线编辑器提供的示例
https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=581586825&machine=basicLinux32gb&devcontainer_path=.devcontainer%2Fdevcontainer.json&location=SouthEastAsia

如果希望使用@juzi包，可以尝试这个
https://github.com/codespaces/new?hide_repo_select=true&ref=latest-features&repo=581586825&machine=basicLinux32gb&devcontainer_path=.devcontainer%2Fdevcontainer.json&location=SouthEastAsia

**Comment by hcfw007** [comment]
长期无回复，问题关闭。
