### ISSUE TITLE
[BUG]WorkPro:企业微信发送1.4版本的PDF文件，提示下载失败

### ISSUE THREAD

**Issue by ccgulan** [wechaty/puppet-service-providers#261]
1.4版本的PDF文件，在普通微信里头没有问题，能发送成功
但是在企业微信里头，提示下载失败。

**Comment by hcfw007** [comment]
没懂什么意思，是成功发送接收方无法下载吗？提示了什么？手机上是否可以下载？如果用手机发送该文件呢？

**Comment by ccgulan** [comment]
> 没懂什么意思，是成功发送接收方无法下载吗？提示了什么？手机上是否可以下载？如果用手机发送该文件呢？
@hcfw007 

代码如下，发送成功了，后台没有提示错误，但是手机上显示下载失败，用手机发送该文件是可以的。文件为PDF格式，版本为1.4

const file = FileBox.fromFile(filePath_local);            
await q.reqObj.say(file);

**Comment by hcfw007** [comment]
可以联系客服提供一下token和时间点，以及pdf源文件（如果方便）。还有这个Issue编号给他。

**Comment by hcfw007** [comment]
这个文件我这边本地发是正常的，我看你这个token还发了其他很多pdf，其他文件正常吗？

**Comment by ccgulan** [comment]
我们也遇到这个情况了 @hcfw007  还有些.md文件也会这样

**Comment by ccgulan** [comment]
这个问题有查出来什么原因吗，还有部分.md文件也会这样 @hcfw007

**Comment by hcfw007** [comment]
不太清楚原因。。因为我拿你这个pdf是能发成功能下载的，然后你这边其他文件我理解也是大部分成功小概率失败，这种问题有些难以处理。

**Comment by ccgulan** [comment]
> 不太清楚原因。。因为我拿你这个pdf是能发成功能下载的，然后你这边其他文件我理解也是大部分成功小概率失败，这种问题有些难以处理。

@hcfw007 其他的pdf文件都能发送成功，有些发送失败，我查看了一下，发送失败的pdf文件版本都是1.4，是不是我相关的包太老了，哪里可以下载到最新的相关的包文件？

**Comment by hcfw007** [comment]
> > 不太清楚原因。。因为我拿你这个pdf是能发成功能下载的，然后你这边其他文件我理解也是大部分成功小概率失败，这种问题有些难以处理。
> 
> @hcfw007 其他的pdf文件都能发送成功，有些发送失败，我查看了一下，发送失败的pdf文件版本都是1.4，是不是我相关的包太老了，哪里可以下载到最新的相关的包文件？

你是指 1.4 版本的PDF？不太清楚这个 1.4 说的是什么的版本。 我们底层企业微信的版本应该是 4.1.8。

**Comment by ccgulan** [comment]
> 



> > > 不太清楚原因。。因为我拿你这个pdf是能发成功能下载的，然后你这边其他文件我理解也是大部分成功小概率失败，这种问题有些难以处理。
> > 
> > 
> > @hcfw007 其他的pdf文件都能发送成功，有些发送失败，我查看了一下，发送失败的pdf文件版本都是1.4，是不是我相关的包太老了，哪里可以下载到最新的相关的包文件？
> 
> 你是指 1.4 版本的PDF？不太清楚这个 1.4 说的是什么的版本。 我们底层企业微信的版本应该是 4.1.8。


> > > 不太清楚原因。。因为我拿你这个pdf是能发成功能下载的，然后你这边其他文件我理解也是大部分成功小概率失败，这种问题有些难以处理。
> > 
> > 
> > @hcfw007 其他的pdf文件都能发送成功，有些发送失败，我查看了一下，发送失败的pdf文件版本都是1.4，是不是我相关的包太老了，哪里可以下载到最新的相关的包文件？
> 
> 你是指 1.4 版本的PDF？不太清楚这个 1.4 说的是什么的版本。 我们底层企业微信的版本应该是 4.1.8。



> > > 不太清楚原因。。因为我拿你这个pdf是能发成功能下载的，然后你这边其他文件我理解也是大部分成功小概率失败，这种问题有些难以处理。
> > 
> > 
> > @hcfw007 其他的pdf文件都能发送成功，有些发送失败，我查看了一下，发送失败的pdf文件版本都是1.4，是不是我相关的包太老了，哪里可以下载到最新的相关的包文件？
> 
> 你是指 1.4 版本的PDF？不太清楚这个 1.4 说的是什么的版本。 我们底层企业微信的版本应该是 4.1.8。

@hcfw007  底层企业微信的版本信息在哪里查看的？

**Comment by hcfw007** [comment]
> > 
> 
> > > > 不太清楚原因。。因为我拿你这个pdf是能发成功能下载的，然后你这边其他文件我理解也是大部分成功小概率失败，这种问题有些难以处理。
> > > 
> > > 
> > > @hcfw007 其他的pdf文件都能发送成功，有些发送失败，我查看了一下，发送失败的pdf文件版本都是1.4，是不是我相关的包太老了，哪里可以下载到最新的相关的包文件？
> > 
> > 
> > 你是指 1.4 版本的PDF？不太清楚这个 1.4 说的是什么的版本。 我们底层企业微信的版本应该是 4.1.8。
> 
> > > > 不太清楚原因。。因为我拿你这个pdf是能发成功能下载的，然后你这边其他文件我理解也是大部分成功小概率失败，这种问题有些难以处理。
> > > 
> > > 
> > > @hcfw007 其他的pdf文件都能发送成功，有些发送失败，我查看了一下，发送失败的pdf文件版本都是1.4，是不是我相关的包太老了，哪里可以下载到最新的相关的包文件？
> > 
> > 
> > 你是指 1.4 版本的PDF？不太清楚这个 1.4 说的是什么的版本。 我们底层企业微信的版本应该是 4.1.8。
> 
> > > > 不太清楚原因。。因为我拿你这个pdf是能发成功能下载的，然后你这边其他文件我理解也是大部分成功小概率失败，这种问题有些难以处理。
> > > 
> > > 
> > > @hcfw007 其他的pdf文件都能发送成功，有些发送失败，我查看了一下，发送失败的pdf文件版本都是1.4，是不是我相关的包太老了，哪里可以下载到最新的相关的包文件？
> > 
> > 
> > 你是指 1.4 版本的PDF？不太清楚这个 1.4 说的是什么的版本。 我们底层企业微信的版本应该是 4.1.8。
> 
> @hcfw007 底层企业微信的版本信息在哪里查看的？

额没地方看，我们实现的就是的。

**Comment by ccgulan** [comment]
@hcfw007 所有的包都更新到了最新版本，pdf文件(1.4文件版本）偶尔会成功，基本是系统刚启动会成功，两三次访问之后就失败了，md文件基本没有成功过，文件已经发给客服

**Comment by hcfw007** [comment]
两三次访问之后就失败是指什么？微信接收文件是有有效期的，是否是过期了？

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
