### ISSUE TITLE
企业微信客服回复过慢，超过2天

### ISSUE THREAD

**Issue by LLSean** [wechaty/puppet-service-providers#263]
想再买一个账号，结果没有任何的回复，太难了

**Comment by hcfw007** [comment]
我帮你催了

**Comment by hcfw007** [comment]
可以带着Issue编号联系客服

**Comment by LLSean** [comment]
已经带上issue链接联系客服了，期待回复

**Comment by LLSean** [comment]
@hcfw007 一天过去了，还是没有任何回复

**Comment by hcfw007** [comment]
额，你买的是workpro的token吗？

**Comment by LLSean** [comment]
对啊。想再买一个，企业的不能自助服务

**Comment by hcfw007** [comment]
我昨天帮你问了下客服，他说最近联系的都回复了。。。要不你确认下加的客服是否是https://github.com/wechaty/puppet-supports/issues/190中的？另外我们过两周应该会上线自助系统。

**Comment by LLSean** [comment]
![image](https://github.com/wechaty/puppet-supports/assets/1560188/b7952ea5-053d-49cd-ab86-3f4056d774c3)
完全没回复好吧

**Comment by LLSean** [comment]
看到请回复一下，再买一个企微账号

**Comment by hcfw007** [comment]
我又催了一下，现在有回复吗。

**Comment by LLSean** [comment]
回复了

**Comment by devtalker** [comment]
> 我昨天帮你问了下客服，他说最近联系的都回复了。。。要不你确认下加的客服是否是[https://github.com/wechaty/puppet-supports/issues/190中的？另外我们过两周应该会上线自助系统。](https://github.com/wechaty/puppet-supports/issues/190%E4%B8%AD%E7%9A%84%EF%BC%9F%E5%8F%A6%E5%A4%96%E6%88%91%E4%BB%AC%E8%BF%87%E4%B8%A4%E5%91%A8%E5%BA%94%E8%AF%A5%E4%BC%9A%E4%B8%8A%E7%BA%BF%E8%87%AA%E5%8A%A9%E7%B3%BB%E7%BB%9F%E3%80%82)

自助系统上线了吗

**Comment by hcfw007** [comment]
在做了...
