### ISSUE TITLE
[BUG]WorkPro:Error: 14 UNAVAILABLE: Wechaty service discovery / resolution failed for target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_xxxxxxxxx: token "puppet_workpro_xxxxxx" does not exist

### ISSUE THREAD

**Issue by atorber** [wechaty/puppet-service-providers#265]
存在很长时间的一个问题了，不知道现在有没有解决或者有没有在业务侧处理这个问题最佳实践

> WechatGPT@0.14.3 start
> cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node src/index.ts
17:07:21 INFO env [object Object]
17:07:21 INFO puppet: wechaty-puppet-service
17:07:21 INFO http server running on http://127.0.0.1:9503 
17:07:21 WARN GrpcManager initClient() TLS: disabled (INSECURE)
17:07:21 INFO WebSocket server running on ws://127.0.0.1:9504 
17:07:22 WARN ResolverWechaty updateResolution() address not found target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_xxxxxx: token does not exist
17:07:22 ERR StarterBot Error: 14 UNAVAILABLE: Wechaty service discovery / resolution failed for target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_xxxxxxxxx: token "puppet_workpro_xxxxxx" does not exist
17:07:23 WARN ResolverWechaty updateResolution() address not found target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_xxxxx

**Comment by hcfw007** [comment]
如果采用了私有发现服务（token-service-discovery-test.juzibot.com），目前很少接到这样的反馈。请联系客服确认一下你的发现服务地址和到期时间。

**Comment by hcfw007** [comment]
长时间未回复，Issue关闭。
