### ISSUE TITLE
[BUG]WorkPro: [Emergency]Paid token not working

### ISSUE THREAD

**Issue by Cliffe97** [wechaty/puppet-service-providers#266]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

We paid for a workpro token and today when we logout and login again the service is down.
**wechaty_puppet.exceptions.WechatyPuppetGrpcError: WechatyPuppetGrpcError('can"t fetch endpoint from chatie server. You can try it later, or make sure that your pc can connect to heroku server ', None, None)**
The token used to work fine but recently it failed a few times.

Also if we ping api.chatie.io/v0/hosties/ and token-service-discovery-test.juzibot.com/v0/hosties with the token in the url, they would return "host":"0.0.0.0","ip":"0.0.0.0","port":0}
**Info**

 - Platform[e.g. Windows/Mac/Linux]:  Linux
 - Runtime version[e.g. node/JAVA]: Python
 - Wechaty version: 
 - Wechaty Puppet version: 
wechaty                        0.10.7      
wechaty-grpc                   0.20.19     
wechaty-puppet                 0.4.23      
wechaty-puppet-service         0.8.10  

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hcfw007** [comment]
正常情况下，购买的token默认会采用我们私有的发现服务（因为社区的不够稳定），但如果你是Python开发者，请联系客服让他给你换成社区的发现服务，因为Python似乎无法连接私有的发现服务。

**Comment by hcfw007** [comment]
长时间未回复，Issue关闭。
