### ISSUE TITLE
[BUG]WorkPro: 今天开始fetching endpoint异常

### ISSUE THREAD

**Issue by lspbeyond** [wechaty/puppet-service-providers#269]
错误信息如下：
2023-08-31 21:26:44,528 - Wechaty - INFO - starting puppet ...
2023-08-31 21:26:44,528 - PuppetService - INFO - init puppet ...
2023-08-31 21:26:44,528 - PuppetService - INFO - fetching endpoint from chatie-server: https://api.chatie.io/v0/hosties/puppet_workpro_xxx
Traceback (most recent call last):
  File "/Users/wechaty/wechaty.py", line 453, in start
    await self.puppet.start()
  File "/Users/wechaty_puppet_service/puppet.py", line 919, in start
    self._init_puppet()
  File "/Users/wechaty_puppet_service/puppet.py", line 884, in _init_puppet
    raise WechatyPuppetGrpcError(
lib.wechaty_puppet.exceptions.WechatyPuppetGrpcError: WechatyPuppetGrpcError('can"t fetch endpoint from chatie server. You can try it later, or make sure that your pc can connect to heroku server ', None, None)

之前是重试3-5次就能成功，今天上午开始一直异常。

**Comment by hcfw007** [comment]
这个需要提供一下token，在这里提供后面6位就可以。

**Comment by lspbeyond** [comment]
69e71c1

**Comment by lspbeyond** [comment]
> 

查过了吗？

**Comment by hcfw007** [comment]
这个已经处理过了。你是使用node还是其他语言？使用node的话可以把发现服务转为我们私有的，社区的不太稳定。

**Comment by lspbeyond** [comment]
我用的是python，还是连不上啊

**Comment by lspbeyond** [comment]
token-service-discovery-test.juzibot.com 这个是社区版？
api.chatie.io 这个是私有版？

**Comment by hcfw007** [comment]
反了，api.chatie.io是社区版，社区版不太稳定，但Python据我所知没法配置发现地址。你这个应该本来也是社区版的。

**Comment by hcfw007** [comment]
![image](https://github.com/wechaty/puppet-supports/assets/13669999/f73dfd12-91c5-4317-8285-1a81035367e4)

你可以自己访问这个地址看看能否找到。

**Comment by lspbeyond** [comment]
好，我试试

**Comment by lspbeyond** [comment]
> ![image](https://user-images.githubusercontent.com/13669999/265275202-f73dfd12-91c5-4317-8285-1a81035367e4.png)
> 
> 你可以自己访问这个地址看看能否找到。

写死这个ip是可以通的。那我怎么搞？

**Comment by lspbeyond** [comment]
可否提供私有版的服务发现的接口说明，我估计是之前python版本的接口调用代码没更新

**Comment by hcfw007** [comment]
> 可否提供私有版的服务发现的接口说明，我估计是之前python版本的接口调用代码没更新

对于 node 版本设置一个环境变量即可，但Python版本我不太了解，其他客户反馈说环境变量设置无效。这里强烈建议可能的话使用 node 版本。Python 版本的 wechaty 我们没在维护，也缺失了很多新功能。

**Comment by lspbeyond** [comment]
我知道node设置环境变量即可。我是要改动python对应的代码，我需要确认下面的url是否准确，其中self.options.token为私有token
            url = f'https://token-service-discovery-test.juzibot.com/{self.options.token}'
            log.info('fetching endpoint from chatie-server: %s', url)
            response = requests.get(url)

**Comment by lspbeyond** [comment]
改成：https://token-service-discovery-test.juzibot.com/v0/hosties/{self.options.token}
返回结果是：
{
    "host": "0.0.0.0",
    "ip": "0.0.0.0",
    "port": 0
}

**Comment by hcfw007** [comment]
> 改成：[https://token-service-discovery-test.juzibot.com/v0/hosties/{self.options.token}](https://token-service-discovery-test.juzibot.com/v0/hosties/%7Bself.options.token%7D) 返回结果是： { "host": "0.0.0.0", "ip": "0.0.0.0", "port": 0 }

是这个地址，需要把你的token进行切换吗？

**Comment by lspbeyond** [comment]
> > 改成：[https://token-service-discovery-test.juzibot.com/v0/hosties/{self.options.token}](https://token-service-discovery-test.juzibot.com/v0/hosties/%7Bself.options.token%7D) 返回结果是： { "host": "0.0.0.0", "ip": "0.0.0.0", "port": 0 }
> 
> 是这个地址，需要把你的token进行切换吗？

需要，谢谢

**Comment by hcfw007** [comment]
![image](https://github.com/wechaty/puppet-supports/assets/13669999/c48f5fd4-6390-4772-a203-97070b7cc788)

已切换。

**Comment by lspbeyond** [comment]
可以了，多谢

**Comment by hcfw007** [comment]
> 可以了，多谢

你是Python语言的使用者吗？如果有时间欢迎写一个Issue或者blog来介绍下你是如何解决这个问题的？
