### ISSUE TITLE
[BUG]WorkPro:旧token显示不存在

### ISSUE THREAD

**Issue by LLSean** [wechaty/puppet-service-providers#270]
上周五登记了2个token之后，旧的token显示不存在，周五到现在有几个客户发消息完全没回复。

wechaty://api.chatie.io/puppet_workpro显示token不存在

**Comment by hcfw007** [comment]
提供一下token的后6位看一下

**Comment by LLSean** [comment]
350b42

**Comment by hcfw007** [comment]
已经处理了。社区的发现服务不是很稳定，有时候需要我们这边重连。如果你是node用户可以给你换成私有发现服务（需要配合环境变量使用。）
