### ISSUE TITLE
[FEAT]WorkPro: 关于消息发送速度

### ISSUE THREAD

**Issue by lspbeyond** [wechaty/puppet-service-providers#271]
如下文本消息的发送，需要400ms, 请问这个是目前服务器转发的正常水平，还是我个人使用的问题？

after find 2023-09-06 17:18:39.713673

发送消息代码段：
        response = await self.puppet_stub.message_send_text(
            conversation_id=conversation_id,
            text=message)

after send 2023-09-06 17:18:40.147391

**Comment by hcfw007** [comment]
这是正常水平。

**Comment by su-chang** [comment]
@lspbeyond 还有其他问题么？如果没有的话，麻烦关闭该issue。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
