### ISSUE TITLE
[BUG]WorkPro: 拼接字符串方式@某人无效

### ISSUE THREAD

**Issue by tentacle-pro** [wechaty/puppet-service-providers#274]
**Info**

 - Platform[e.g. Windows/Mac/Linux]: Mac/Linux复现
 - Runtime version[e.g. node/JAVA]: node v20.6.0
 - Wechaty version: 1.20.2
 - Wechaty Puppet version: Unknown

**To Reproduce**

1. 在群中使用room.say()通过拼接字符串方式 `at` 某人无效，体现在他的微信端的群列表项上没有标红高亮
2. 手动在手机端App输入 `at` 某人，他能在微信端的群列表项上看到标红高亮`有人@你`

**Expected behavior**

被@的人在他的微信端的群列表项上没有标红高亮

**Screenshots**

**Additional context**

**Comment by su-chang** [comment]
这样试下看看。

```ts
const member = await room.memberAll()
message.say('hello', member)
```

**Comment by hcfw007** [comment]
长时间未回复，issue关闭。
