### ISSUE TITLE
[BUG]WorkPro:

### ISSUE THREAD

**Issue by tentacle-pro** [wechaty/puppet-service-providers#275]
**Info**

 - Platform[e.g. Windows/Mac/Linux]: Mac/Linux复现
 - Runtime version[e.g. node/JAVA]: node v20.6.0
 - Wechaty version: 1.20.2
 - Wechaty Puppet version: Unknown

**To Reproduce**

1. bot.on('room-invite')事件不生效，无法调用对应的异步函数

**Expected behavior**

当bot被邀请进群时，对应的异步函数被调用，以便进行“进群后自动打招呼”的操作

**Screenshots**

**Additional context**

**Comment by su-chang** [comment]
有人进入群聊会触发 `room-join` 事件

`room-invite`事件是bot接收到入群邀请链接消息时，会触发的事件。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
