### ISSUE TITLE
[BUG]WorkPro: 调用 user.signature(str) 时出现错误：Error: 12 UNIMPLEMENTED: Wechaty gRPC unsupported API error

### ISSUE THREAD

**Issue by KroMiose** [wechaty/puppet-service-providers#277]
**Describe the bug**

调用 `user.signature(str)` 时出现错误：`Error: 12 UNIMPLEMENTED: Wechaty gRPC unsupported API error.`

**Info**

 - Platform[e.g. Windows/Mac/Linux]: linux
 - Runtime version[e.g. node/JAVA]: node
 - Wechaty version: "@juzi/wechaty": "^1.0.65"
 - Wechaty Puppet version: "@juzi/wechaty-puppet": "^1.0.61"
 - Wechaty Puppet Serice version: "@juzi/wechaty-puppet-service": "^1.0.69"

**To Reproduce**

在机器人onLogin回调中调用修改签名

```typescript
async function onLogin(user: ContactSelf) {
  let signature = `当前版本: ${process.env.npm_package_version} | 运行环境: ${process.env.NODE_ENV}`
  try {
    log.info("启动 Puppet", `正在修改签名: "${signature}" ...`);
    await user.signature(signature)
  } catch (err) {
    log.error("启动 Puppet", `修改签名失败: ${err}`);
  }
  log.info("启动 Puppet", "[%s] %s 登录成功", user.id, user.name());
}

bot.on("login", onLogin);
```

日志信息: 

```
14:51:17 INFO 启动 Puppet 正在修改签名: "当前版本: 1.0.0 | 运行环境: development" ...
14:51:17 ERR 启动 Puppet 修改签名失败: Error: 12 UNIMPLEMENTED: Wechaty gRPC unsupported API error
14:51:17 INFO 启动 Puppet [16************00] *** 登录成功
```

**Expected behavior**

成功修改签名

**Additional context**

日志信息可看出修改签名似乎是一个未实现的api，请问是否有支持该功能的计划呢？

**Comment by hcfw007** [comment]
雀食暂不支持。这个需求比较小众，暂时没有这个计划。

**Comment by KroMiose** [comment]
感谢回复，这边的需求场景主要是在签名动态地展示一些机器人的运行状态之类的信息，方便查看机器人运行状态不用每次都发送消息来触发查询，希望未来可以支持一下哈 (*/ω＼*)

**Comment by hcfw007** [comment]
好的。这个先关闭了。
