### ISSUE TITLE
[BUG]WorkPro: 扫码登录时需要在设备上输入验证码，怎么破？

### ISSUE THREAD

**Issue by liuyaxin** [wechaty/puppet-service-providers#278]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

写的nodejs程序来调用wechaty的WorkPro puppet service，现在用企业微信扫码登陆时手机上提示要在新设备上输入六位验证码，怎么办？具体看图

![企业微信截图_20c9e84e-5604-4b50-b646-5eb41f7b8e80](https://github.com/wechaty/puppet-supports/assets/3119496/e3280bed-b52d-4e27-837d-d6f1128e97d2)

**Info**

 - Platform[e.g. Windows/Mac/Linux]: 
 - Runtime version[e.g. node/JAVA]:
 - Wechaty version: 
 - Wechaty Puppet version: 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hcfw007** [comment]
请参考置顶Issue https://github.com/wechaty/puppet-supports/issues/267

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
