### ISSUE TITLE
[BUG]WorkPro: 扫码登录出现了错误 PuppetService onGrpcStreamEvent() got unknown event

### ISSUE THREAD

**Issue by liuyaxin** [wechaty/puppet-service-providers#279]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**
具体情况是在扫码登录的时候，提示要在远端输入验证码，添加了'verify-code'时间的监听，也没有回调
详细LOG如下：

15:24:53 WARN PuppetService onGrpcStreamEvent() got unknown event
this may be caused by puppet-server using later version of wechaty-puppet-service
Related issues:
 - https://github.com/wechaty/puppet-service/issues/216

看了那个issue也没找到解决方案，是puppet server部署的版本问题么？

**Info**

 - Platform[e.g. Windows/Mac/Linux]: 
 - Runtime version[e.g. node/JAVA]:
 - Wechaty version: 
 - Wechaty Puppet version: 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hcfw007** [comment]
出现这个报错是因为你使用的 puppet-service 版本不支持验证码事件。请参考置顶 issue 安装合适的版本。

**Comment by liuyaxin** [comment]
发现你们还需要这么用  '@juzi/wechaty-puppet-service'  这个用法太隐蔽了

**Comment by hcfw007** [comment]
社区想合一个PR太难了，没办法。。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。

**Comment by crazywu-lab** [comment]
现在应该用哪个版本。。。以下是我现在用的，还是有问题。。
`"@juzi/wechaty": "1.0.93",`
 `"@juzi/wechaty-puppet": "1.0.82",`
 `"@juzi/wechaty-puppet-service": "1.0.90",`

**Comment by su-chang** [comment]
> 现在应该用哪个版本。。。以下是我现在用的，还是有问题。。

版本没问题，具体有啥报错？

**Comment by GiockL** [comment]
> > 现在应该用哪个版本。。。以下是我现在用的，还是有问题。。
> 
> 版本没问题，具体有啥报错？
启动的时候报这个错
file:///C:/Users/25819/Desktop/wechaty/getting-started/node_modules/@juzi/wechaty/src/wechaty-mixins/puppet-mixin.ts:54
        throw new Error('NOPUPPET')
              ^
Error: NOPUPPET
    at WechatyImpl.get puppet [as puppet] (file:///C:/Users/25819/Desktop/wechaty/getting-started/node_modules/@juzi/wechaty/src/wechaty-mixins/puppet-mixin.ts:54:15)        
    at WechatyImpl.cancelVerifyCode (file:///C:/Users/25819/Desktop/wechaty/getting-started/node_modules/@juzi/wechaty/src/wechaty/wechaty-base.ts:320:17)
    at file:///C:/Users/25819/Desktop/wechaty/getting-started/examples/ding-dong-bot.ts:62:11
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
