### ISSUE TITLE
[BUG]WorkPro:WorkPro:dingdong示例代码运行报错

### ISSUE THREAD

**Issue by chenmingqiang01** [wechaty/puppet-service-providers#282]
WorkPro运行dingdong示例代码时出现错误
错误如下：
![image](https://github.com/wechaty/puppet-supports/assets/45379395/2c49b9fc-d28d-40e0-9efc-1208d09fd86c)
系统环境：
MacOS
Node v18.17.1
Wechaty ^1.20.2
wechaty-puppet-service ^1.19.8
@swc/core ^1.3.84

**Comment by su-chang** [comment]
```
"@swc/core": "1.3.39",
```

这个版本需要锁定下，重新安装。即可解决。

**Comment by chenmingqiang01** [comment]
好的，非常感谢，问题解决！
