### ISSUE TITLE
PadLocal: 为什么企业微信的版本监听不到verify-code事件

### ISSUE THREAD

**Issue by jackzhangrunze** [wechaty/puppet-service-providers#283]
按照文档中介绍https://juzihudong.feishu.cn/wiki/ThQcwYvjwiQbs7ke3Y5cTMIYnjE 给机器人添加了verify-code的监听 ,手机扫码后显示了需要输入验证码的界面,,为什么verify-code中的事件没有触发呢?是我写的监听有问题吗 还是版本问题?
![image](https://github.com/wechaty/puppet-supports/assets/60767954/41c93e49-8d04-4acd-b637-8ebd11bbc91a)
![image](https://github.com/wechaty/puppet-supports/assets/60767954/a459425d-7076-432b-b4e9-7af48c910a3b)

**Comment by liuyaxin** [comment]
需要用这个  @juzi/wechaty-puppet-service

**Comment by su-chang** [comment]
@jackzhangrunze  如果用的是padlocal的个微的token是不支持这个功能的，这个是新版本企业微信特有的功能。

**Comment by jackzhangrunze** [comment]
其他的依赖不用换吗?这样?
![image](https://github.com/wechaty/puppet-supports/assets/60767954/ab2623b0-c0c7-43d9-ae66-4fb7b8076fb2)

**Comment by su-chang** [comment]
@jackzhangrunze 首先要确认你用的token是哪类的？`puppet_workpro`还是`puppet_padlocal`？

**Comment by jackzhangrunze** [comment]
@su-chang 用的puppet_padlocal的token

**Comment by su-chang** [comment]
那不需要用这个功能，这个功能是针对企微的。

**Comment by jackzhangrunze** [comment]
我们用的就是企微...puppet_padlocal ,我们购买的时候 厂商说根据token来区分个人微信还是企业微信........ @su-chang

**Comment by su-chang** [comment]
OK 那这个信息我们也是才知道，padlocal应该没有适配@juzi这个scope下的新功能。

**Comment by jackzhangrunze** [comment]
@su-chang 你们是开发人员吗?

**Comment by su-chang** [comment]
是的，但是不是padlocal的开发人员。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
