### ISSUE TITLE
[BUG]WorkPro: 如何获取引用消息的原文

### ISSUE THREAD

**Issue by liuyaxin** [wechaty/puppet-service-providers#284]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

有不少消息是用户发的，但是引用了之前的某条消息，目前看是能拿到消息体，但是被引用的那条消息如何获取到呢？

**Info**

 - Platform[e.g. Windows/Mac/Linux]: 
 - Runtime version[e.g. node/JAVA]:
 - Wechaty version: 
 - Wechaty Puppet version: 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by su-chang** [comment]
使用 @juzi/wechaty 包可以使用该功能。

```ts
await message.getQuotedMessage()
```

**Comment by liuyaxin** [comment]
问一下有juzi版的文档么？wechaty的文档貌似不全

**Comment by hcfw007** [comment]
这个暂时没有，正在制作中。
