### ISSUE TITLE
[BUG]WorkPro:starterbot 卡住了没有扫码也没有其他提示

### ISSUE THREAD

**Issue by CauseMyLove** [wechaty/puppet-service-providers#285]
在ding-dont机器人中配置了以下配置：

```ts
const bot = WechatyBuilder.build({
  name: "ding-dong-bot",
  puppet: "wechaty-puppet-service",
  puppetOptions: {
    endpoint: "token-service-**.**.com",
    token: "puppet_workpro_**",
    tls: {
      disable: true,
    },
    uos: true,
  },
});
bot.on("scan", onScan);
bot.on("login", onLogin);
bot.on("logout", onLogout);
bot.on("message", onMessage);

bot
  .start()
  .then(() => log.info("StarterBot", "Starter Bot Started."))
  .catch((e) => log.error("StarterBot", e));
  
```
  **卡在以下info**
![image](https://github.com/wechaty/puppet-supports/assets/74802213/9364d174-0788-4402-90ee-8033c2da7c71)

以下是我的package.json
```json
  "dependencies": {
    "dotenv": "^16.3.1",
    "qrcode-terminal": "^0.12.0",
    "wechaty": "^1.20.2",
    "wechaty-cqrs": "^0.7.5",
    "wechaty-plugin-contrib": "^1.12.1"
  },
  "devDependencies": {
    "@chatie/eslint-config": "^1.0.4",
    "@chatie/git-scripts": "^0.6.2",
    "@chatie/tsconfig": "^4.6.3",
    "@swc/core": "1.3.83",
    "@types/qrcode-terminal": "^0.12.0",
    "check-node-version": "^4.2.1",
    "is-pr": "^2.0.0",
    "ts-node": "^10.8.1",
    "wechaty-puppet-mock": "^1.18.2"
  },
```

**Comment by su-chang** [comment]
@CauseMyLove 每次都是可以稳定复现的么？

如果可以的话，可以联系售后把token发给我们看下，或者把token的后6位发在这里。我这边测试下看看。

**Comment by CauseMyLove** [comment]
稳定复现，并且团队的小伙伴试了也不行，一样卡在这里；
目前有三个token的后六位:
629187
e525d8
413739

**Comment by CauseMyLove** [comment]
@su-chang 请问测试有结果嘛

**Comment by su-chang** [comment]
我们这边测试没有复现出这种卡住的情况。

我们这边通过售后给到你一个测试token，可以使用下看看是否存在一样的问题。

**Comment by su-chang** [comment]
@CauseMyLove 建议使用 https://github.com/RPAChat/workpro-getting-started/tree/latest-features 这个demo运行上述几个token看看是否有类似问题？

**Comment by CauseMyLove** [comment]
使用该demo在cmd中配置发现地址可以正常运行，但在powershell中配置发现地址后无法应用该配置地址，加上endpoint则会卡住

**Comment by su-chang** [comment]
建议可以使用 @juzi/wechaty 试试，这个scope下的新功能更多一些。

**Comment by hcfw007** [comment]
长时间未回复，issue关闭。

**Comment by CauseMyLove** [comment]
@su-chang  有 juzi/wechaty 的相关api文档吗？

**Comment by su-chang** [comment]
和wechaty的文档是一样的，有一些新增的功能，目前还没有文档，可以参考wechaty的api自行了解下。

**Comment by CauseMyLove** [comment]
好的，主要是一些新增的功能需要翻代码看。感谢你的回答。

**Comment by CauseMyLove** [comment]
@su-chang 你好，我原本使用 [@juzi/wechaty进行企微操作，可以正常使用
![image](https://github.com/wechaty/puppet-supports/assets/74802213/e725a9a5-b3e2-49b3-987a-67ea961fb09f)

后改为个人版，发现卡在某个地方，是juzi/wechaty不支持个人版吗？
![image](https://github.com/wechaty/puppet-supports/assets/74802213/b0bac452-58c6-49ae-97bc-e2c319042160)
![image](https://github.com/wechaty/puppet-supports/assets/74802213/e9046185-6e7d-49ee-a15a-55c988153da1)
