### ISSUE TITLE
[BUG]WorkPro: 机器人程序在运行过程中出现了下面的错误日志，然后就不能工作了，谁能来看看？

### ISSUE THREAD

**Issue by liuyaxin** [wechaty/puppet-service-providers#286]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

日志如下(用 **** 替换了敏感信息)：
03:36:03 WARN PuppetWatchdogAgent start() reset() reason: {"data":"regular heartbeat","timeoutMilliseconds":60000}
03:36:03 INFO StarterBot Error Error: WatchdogAgent reset: lastFood: "{"data":"regular heartbeat","timeoutMilliseconds":60000}"
03:36:03 WARN last event was 10822.769 seconds ago, will not request event cache 
03:36:03 INFO getEventData() timestamp: 1694882140434, seq: undefined 
03:36:03 INFO GrpcManager startStream() connecting event stream with account ***** and seq undefined
03:36:38 WARN PuppetService waiting for event reset login error, will perform regular reset
03:37:23 INFO StarterBot Error GError: no grpc manager
03:37:23 INFO StartBot uncaughtException Error: no grpc manager
03:38:23 INFO StarterBot Error GError: no grpc manager
03:38:23 INFO StartBot uncaughtException Error: no grpc manager
03:39:23 INFO StarterBot Error GError: no grpc manager
03:39:23 INFO StartBot uncaughtException Error: no grpc manager
03:40:23 INFO StarterBot Error GError: no grpc manager
03:40:23 INFO StartBot uncaughtException Error: no grpc manager
03:41:23 INFO StarterBot Error GError: no grpc manager
03:41:23 INFO StartBot uncaughtException Error: no grpc manager
03:42:23 INFO StarterBot Error GError: no grpc manager
03:42:23 INFO StartBot uncaughtException Error: no grpc manager
03:43:23 INFO StarterBot Error GError: no grpc manager
03:43:23 INFO StartBot uncaughtException Error: no grpc manager
03:44:23 INFO StarterBot Error GError: no grpc manager
03:44:23 INFO StartBot uncaughtException Error: no grpc manager
03:45:23 INFO StarterBot Error GError: no grpc manager
03:45:23 INFO StartBot uncaughtException Error: no grpc manager
03:45:38 INFO StarterBot Contact<******> logout
03:45:38 WARN last event was 11397.662 seconds ago, will not request event cache 
03:45:38 INFO getEventData() timestamp: 1694882140434, seq: undefined 
03:45:38 WARN GrpcManager initClient() TLS: disabled (INSECURE)
03:45:38 INFO GrpcManager startStream() connecting event stream with account ***** and seq undefined
03:45:38 WARN ResolverWechaty updateResolution() address not found target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_*****: token does not exist
03:45:38 INFO StarterBot Error Error: 14 UNAVAILABLE: Wechaty service discovery / resolution failed for target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_*****: token "puppet_workpro_*****" does not exist
03:45:38 WARN ServiceCtl<PuppetServiceMixin> stop() found that is starting...
03:45:38 WARN ServiceCtl<PuppetServiceMixin> stop() found that is starting, waiting stable ... (max 5 seconds)
03:45:39 WARN ResolverWechaty updateResolution() address not found target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_*****: token does not exist
03:45:43 INFO StarterBot Error DEADLINE_EXCEEDED: Timeout after 5000 ms
03:45:43 WARN ServiceCtl<PuppetServiceMixin> stop() found that is starting, waiting stable ... timeout
03:45:43 INFO StarterBot Error Error: 14 UNAVAILABLE: Wechaty service discovery / resolution failed for target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_*****: token "puppet_workpro_*****" does not exist
03:45:43 WARN ServiceCtl<PuppetServiceMixin> reset() ... rejection: 14 UNAVAILABLE: Wechaty service discovery / resolution failed for target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_*****: token "puppet_workpro_*****" does not exist
03:45:43 INFO StarterBot Error Error: 1 CANCELLED: Call cancelled

**Info**

 - Platform[e.g. Windows/Mac/Linux]: 
 - Runtime version[e.g. node/JAVA]:
 - Wechaty version: 
 - Wechaty Puppet version: 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hcfw007** [comment]
属于正常网络波动导致长连接断开，请参考这个 issue 配置合理的重启策略。
https://github.com/wechaty/puppet-supports/issues/262

**Comment by hcfw007** [comment]
长时间未回复，issue关闭。
