### ISSUE TITLE
WXWork: token not exist

### ISSUE THREAD

**Issue by dchaofei** [wechaty/puppet-service-providers#287]
Please make sure you have read the [Wechaty Puppet Service: WXWork](https://wechaty.js.org/docs/puppet-services/wxwork) from Wechaty Official Website before you continue writting this issue.

## Question
使用  api.chatie.io 和 token-service-discovery-test.juzibot.com 都报 token 不存在~

我的 token 过期了很久，没有续期，然后 8月份续期了一下，怀疑 token 没有被迁移到 token-service-discovery-test.juzibot.com 服务发现里

**Comment by su-chang** [comment]
@dchaofei 确认下使用的token是`puppet_wxwork`么？这个服务已经停用。 目前对开发者开放的是`puppet_workpro`的企微token。

**Comment by su-chang** [comment]
@dchaofei 刚才和售后沟通了下，找到对应的token了，现在检查状态都没问题，发现服务地址是 token-service-discovery-test.juzibot.com 可以再试下看看。

**Comment by dchaofei** [comment]
已解决，感谢
