### ISSUE TITLE
[BUG]WorkPro: not logged in, no this.__currentUserId yet

### ISSUE THREAD

**Issue by guangzhengyu** [wechaty/puppet-service-providers#288]
## bug描述

在更新了下面这三个包后， 
```js
"@juzi/wechaty": "^1.0.69",
"@juzi/wechaty-puppet": "^1.0.62",
"@juzi/wechaty-puppet-service": "^1.0.71",
```
启动扫码登录就会报这个错误：`not logged in, no this.__currentUserId yet.`

**Info**

- ubuntu
- node v16
- 版本：
 ```js
"@juzi/wechaty": "^1.0.69",
"@juzi/wechaty-puppet": "^1.0.62",
"@juzi/wechaty-puppet-service": "^1.0.71",
"wechaty": "^1.20.2",
"wechaty-puppet-padlocal": "^1.20.1",
"wechaty-puppet-service": "^1.18.2"
```

**Comment by su-chang** [comment]
已知问题，目前不影响使用，最近会更新修复。

**Comment by guangzhengyu** [comment]
> 已知问题，目前不影响使用，最近会更新修复。
@su-chang 

那目前收消息会报错，上面的错误无关吗？

我自己给别人发送消息，看日志报错是这个  `GError: message not found for id: xxxxxxxx`

**Comment by su-chang** [comment]
是否有收到login事件？能否提供下日志信息。我们看下具体的流程和报错。

**Comment by su-chang** [comment]
@guangzhengyu 也可以把收到的消息ID提供下

**Comment by guangzhengyu** [comment]
> @guangzhengyu 也可以把收到的消息ID提供下

@su-chang 我刚才尝试打一下日志，结果发现扫码的时候企业微信会谈“登录失败”的toast

状态是 Scanned。 我刚才扫码之后没有点击确认登录，而是点了返回，就变成scanned状态了

**Comment by guangzhengyu** [comment]
@su-chang 强制调用了一下`logout`, `scanned`状态解除了。 

然后看了一下日志，发现没有收到`'login'`事件

**Comment by su-chang** [comment]
@guangzhengyu 可以把你的token提供给客服么？ 我们看下服务端的日志。

顺便也可以关注下token是否过期了？

**Comment by guangzhengyu** [comment]
> @guangzhengyu 可以把你的token提供给客服么？ 我们看下服务端的日志。
> 
> 顺便也可以关注下token是否过期了？

@su-chang 已经提供了

**Comment by su-chang** [comment]
@guangzhengyu 我们这边看服务端的日志是有推送login事件的，可以看看对应的时间点，你那边是否有收到login事件。

```
2023-09-19 @ 11:14:25.238 emitting grpc event EVENT_TYPE_LOGIN: {"contactId":"1688855861466096"}

2023-09-19 @ 11:22:39.440 emitting grpc event EVENT_TYPE_LOGIN: {"contactId":"1688855861466096"}

2023-09-19 @ 11:23:25.786 emitting grpc event EVENT_TYPE_LOGIN: {"contactId":"1688855861466096"}

2023-09-19 @ 11:24:05.200 emitting grpc event EVENT_TYPE_LOGIN: {"contactId":"1688855861466096"}
```

目前看 417e1 尾号的token是离线状态，服务端在持续给客户端推送二维码事件。

**Comment by guangzhengyu** [comment]
> @guangzhengyu 我们这边看服务端的日志是有推送login事件的，可以看看对应的时间点，你那边是否有收到login事件。
> 
> ```
> 2023-09-19 @ 11:14:25.238 emitting grpc event EVENT_TYPE_LOGIN: {"contactId":"1688855861466096"}
> 
> 2023-09-19 @ 11:22:39.440 emitting grpc event EVENT_TYPE_LOGIN: {"contactId":"1688855861466096"}
> 
> 2023-09-19 @ 11:23:25.786 emitting grpc event EVENT_TYPE_LOGIN: {"contactId":"1688855861466096"}
> 
> 2023-09-19 @ 11:24:05.200 emitting grpc event EVENT_TYPE_LOGIN: {"contactId":"1688855861466096"}
> ```
> 
> 目前看 417e1 尾号的token是离线状态，服务端在持续给客户端推送二维码事件。

@su-chang 嗯嗯 我现在启动一下

**Comment by su-chang** [comment]
@guangzhengyu 好的，如果还有问题，最好把启动的日志也提供下，这样便于定位问题。

```
WECHATY_LOG=silly ts-node index.ts
```

配置 WECHATY_LOG 环境变量后启动可以看到更详细的日志。

**Comment by su-chang** [comment]
@guangzhengyu 这边看服务端的日志已经是扫码登录成功了，你那边有啥异常么？

**Comment by guangzhengyu** [comment]
> @guangzhengyu 这边看服务端的日志已经是扫码登录成功了，你那边有啥异常么？

扫码登录异常，但是给企微号发送消息，在`on('message')`里都收不到事件回调

**Comment by su-chang** [comment]
@guangzhengyu 
扫码登录异常具体指什么？能提供日志么？

**Comment by guangzhengyu** [comment]
@su-chang 就是这个issue的标题，`GError: not logged in, no this.__currentUserId yet.`

你说没问题，不影响.

但我发送消息，就从'error'里收到错误了：`GError: message not found for id: cc9c0a79796ae6f4d84c6f1ed7c84b0c`

**Comment by su-chang** [comment]
你能提供完整的日志么？比如这条消息是啥时候接收到的，这些信息都可以从日志中看到，目前你反馈的信息比较少，不好判断问题。

你遇到的`message not found`问题和标题是没有关系的。

**Comment by su-chang** [comment]
@guangzhengyu 你变更依赖后建议把下面这两个都移除，避免混用。造成一些不可预知的问题。

"wechaty": "^1.20.2",
"wechaty-puppet-service": "^1.18.2"

**Comment by guangzhengyu** [comment]
我尝试过删除，但是删除之后就报别的错了，我删除完跑一下再贴一下日志

**Comment by su-chang** [comment]
如果环境涉及依赖比较乱，建议使用这个代码示例运行下看看。可以排除一些干扰项。

https://github.com/RPAChat/workpro-getting-started/tree/latest-features

**Comment by guangzhengyu** [comment]
![image](https://github.com/wechaty/puppet-supports/assets/46769446/c3b6f02c-20d9-49a5-96ec-d283b74eb102)

删除后启动就报错的

**Comment by su-chang** [comment]
@guangzhengyu  你项目里引入的wechaty-puppet-service是用的@juzi这个scope中的么？

**Comment by guangzhengyu** [comment]
我大概知道哪儿有问题了，options里面也要改？`puppet: "@juzi/wechaty-puppet-service"`

**Comment by su-chang** [comment]
@guangzhengyu 问题解决了么？

**Comment by charleyCC** [comment]
> @guangzhengyu 问题解决了么？

你们能提供一个带有verify-code监听事件的get-started吗，按照文档【https://github.com/wechaty/puppet-supports/issues/267】加上去这个事件，没有上下文（对于新手来说）好难弄啊

**Comment by hcfw007** [comment]
长时间未回复，问题关闭。
