### ISSUE TITLE
输入验证码verify-code事件监听无效

### ISSUE THREAD

**Issue by charleyCC** [wechaty/puppet-service-providers#290]
https://github.com/wechaty/puppet-supports/issues/267 根据这个issue去安装依赖，注册verify-code事件后没有触发

我的环境
机器：mac
node：v18.18.0
npm：9.8.1

用的是https://github.com/wechaty/getting-started 起的项目，安装的依赖为
![image](https://github.com/wechaty/puppet-supports/assets/39627896/0d390337-b870-4f29-8877-863830dc9f37)

相关代码：
![image](https://github.com/wechaty/puppet-supports/assets/39627896/fdf0ad7c-a58d-423a-9565-433e20062601)

注册的verify-code

![image](https://github.com/wechaty/puppet-supports/assets/39627896/59ef95f0-98ef-4441-b72f-269e2d689d0f)

![image](https://github.com/wechaty/puppet-supports/assets/39627896/b20a6be1-36f7-46b2-a91b-1c7fad00e995)

扫描二维码后就一直提示
![image](https://github.com/wechaty/puppet-supports/assets/39627896/b6375b29-fa19-4410-9279-5d87ed0e4b36)

**Comment by su-chang** [comment]
@charleyCC 需要把手机端收到的验证码，输入到 enterVerifyCode 方法中。

**Comment by charleyCC** [comment]
> @charleyCC 需要把手机端收到的验证码，输入到 enterVerifyCode 方法中。

你好，要从enterVerifyCode这里获取到验证码我是知道的，只是你看我onVerifyCode的方法打印的信息都没有执行到呢，是压根就没有进来onVerifyCode这个方法呢，也就是没有触发到verify-code事件呢
<img width="1258" alt="image" src="https://github.com/wechaty/puppet-supports/assets/39627896/16dca7af-7805-477d-aa8c-ddd1608732a6">

**Comment by su-chang** [comment]
@charleyCC 你手机端的企业微信的版本是多少？

**Comment by charleyCC** [comment]
> @charleyCC 你手机端的企业微信的版本是多少？

4.1.9呢

![image](https://github.com/wechaty/puppet-supports/assets/39627896/1d2c2250-b5a1-4dc0-b564-0e022ff9d95a)

**Comment by su-chang** [comment]
OK 版本没有问题，建议把 @juzi/wechaty 和 wechaty 依赖包只保留 @juzi/wechaty

其他的类似，有@juzi的就都用这个。然后删除依赖重新安装下。

有可能虽然依赖更新了@juzi的，但是代码中还保留了原来的依赖引用。

**Comment by charleyCC** [comment]
> OK 版本没有问题，建议把 @juzi/wechaty 和 wechaty 依赖包只保留 @juzi/wechaty
> 
> 其他的类似，有@juzi的就都用这个。然后删除依赖重新安装下。
> 
> 有可能虽然依赖更新了@juzi的，但是代码中还保留了原来的依赖引用。

![image](https://github.com/wechaty/puppet-supports/assets/39627896/753b9bf4-383d-4cf4-997b-39e6a9a51708)
我都有去掉重复的依赖，重新安装呢，还是不行，你帮我看看还需要去掉啥的，感谢

**Comment by hcfw007** [comment]
关键的问题不是旧的依赖有没有卸载，是你在实际使用过程中实例化的时候使用的是哪个包。

比如你本来创建实例的时候用的是 
```ts
import { WechatyBuilder } from 'wechaty'

const bot = WechatyBuilder.build({
  puppet: 'wechaty-puppet-service',
  puppetOptions: {
    token,
    tls: {
      disable: true
    }
  }
})
```

那对应的就要修改为

```ts
import { WechatyBuilder } from '@juzi/wechaty'

const bot = WechatyBuilder.build({
  puppet: '@juzi/wechaty-puppet-service',
  puppetOptions: {
    token,
    tls: {
      disable: true
    }
  }
})
```

**Comment by su-chang** [comment]
@charleyCC 也可以考虑使用 https://github.com/RPAChat/workpro-getting-started/tree/latest-features 这个repo中的代码尝试复现下问题。

**Comment by charleyCC** [comment]
> 关键的问题不是旧的依赖有没有卸载，是你在实际使用过程中实例化的时候使用的是哪个包。
> 
> 比如你本来创建实例的时候用的是
> 
> ```ts
> import { WechatyBuilder } from 'wechaty'
> 
> const bot = WechatyBuilder.build({
>   puppet: 'wechaty-puppet-service',
>   puppetOptions: {
>     token,
>     tls: {
>       disable: true
>     }
>   }
> })
> ```
> 
> 那对应的就要修改为
> 
> ```ts
> import { WechatyBuilder } from '@juzi/wechaty'
> 
> const bot = WechatyBuilder.build({
>   puppet: '@juzi/wechaty-puppet-service',
>   puppetOptions: {
>     token,
>     tls: {
>       disable: true
>     }
>   }
> })
> ```

![image](https://github.com/wechaty/puppet-supports/assets/39627896/d5f0f894-913f-40d1-974b-0838b609460c)
可以监听到事件了，原来我改了绿框的，没改红框，不好意思，我是新手==，没注意这个点，如果你们能提供比较傻瓜式接入验证码事件的demo对我们新手来说就更友好了

**Comment by hcfw007** [comment]
有的，就是上面su-chang提供的那个地址，可以利用github codespace直接运行的

**Comment by hcfw007** [comment]
问题已解决，Issue关闭。

**Comment by wcljava2018** [comment]
> > 关键的问题不是旧的依赖有没有卸载，是你在实际使用过程中实例化的时候使用的是哪个包。
> > 比如你本来创建实例的时候用的是
> > ```ts
> > import { WechatyBuilder } from 'wechaty'
> > 
> > const bot = WechatyBuilder.build({
> >   puppet: 'wechaty-puppet-service',
> >   puppetOptions: {
> >     token,
> >     tls: {
> >       disable: true
> >     }
> >   }
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 那对应的就要修改为
> > ```ts
> > import { WechatyBuilder } from '@juzi/wechaty'
> > 
> > const bot = WechatyBuilder.build({
> >   puppet: '@juzi/wechaty-puppet-service',
> >   puppetOptions: {
> >     token,
> >     tls: {
> >       disable: true
> >     }
> >   }
> > })
> > ```
> 
> ![image](https://private-user-images.githubusercontent.com/39627896/269248311-d5f0f894-913f-40d1-974b-0838b609460c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NzAwOTIsIm5iZiI6MTcxNzQ2OTc5MiwicGF0aCI6Ii8zOTYyNzg5Ni8yNjkyNDgzMTEtZDVmMGY4OTQtOTEzZi00MGQxLTk3NGItMDgzOGI2MDk0NjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDAyNTYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMTVkY2YyZjVkY2VkMTAwYzg1NjYyZjI3OWQ4NjYxMGM5MzM1ZWViYzA5N2ZjNjhhM2FiZDkxOTUyN2JmNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wCqCfXDAM8WerRmWIevFrmyemZpSg6Vnf3TeJCe_fbo) 可以监听到事件了，原来我改了绿框的，没改红框，不好意思，我是新手==，没注意这个点，如果你们能提供比较傻瓜式接入验证码事件的demo对我们新手来说就更友好了

有没有demo工程，能不能发一下，问题太多了
