### ISSUE TITLE
[BUG]WorkPro:输入验证码verify-code事件，报错”authorization":["Wechaty undefined"]

### ISSUE THREAD

**Issue by xronghui** [wechaty/puppet-service-providers#291]
新设备需要验证码，在verify-code时间中输入验证吗并打印错误信息，代码如下：
.on('verify-code', async (id: string, message: string, scene: types.VerifyCodeScene, status: types.VerifyCodeStatus) => {
        console.log("\n-------------------------------verify-code-----------------------------------");
        console.log(`receive verify-code event, id: ${id}`)
        console.log(`receive verify-code event, message: ${message}`)
        console.log(`receive verify-code event, scene: ${types.VerifyCodeScene[scene]}`)
        console.log(`receive verify-code event, status: ${types.VerifyCodeStatus[status]}`)
        if (status === types.VerifyCodeStatus.WAITING && scene === types.VerifyCodeScene.LOGIN && id === store.qrcodeKey) {
            console.log(`start read verifyCode`)
            await sleep(8000)
            let verifyCode = fs.readFileSync(conf.wxVerifyCodeFile).toString();
            console.log(`bot.config id:${id}, verifyCode: ${verifyCode}`)
            try {
                await bot.enterVerifyCode(id, verifyCode) // 如果没抛错，则说明输入成功，会推送登录事件
                return
            } catch (e) {
                console.log(`enterVerifyCode error : ${JSON.stringify(e)}`)
            }
        }
        console.log("\n-------------------------------verify-code-----------------------------------\n");
    })

错误日志：
-------------------------------verify-code-----------------------------------
receive verify-code event, id: 4F7FF48A80F9F92D1CB40DDCBF2A6802
receive verify-code event, message: 请输入企业微信手机端展示的验证码，以继续登录
receive verify-code event, scene: LOGIN
receive verify-code event, status: WAITING
start read verifyCode
bot.config id:4F7FF48A80F9F92D1CB40DDCBF2A6802, verifyCode: 617653

enterVerifyCode error : {"code":13,"details":"Invalid verify code!","metadata":{"content-type":["application/grpc+proto"],"date":["Wed, 20 Sep 2023 09:02:10 GMT"],"authorization":["Wechaty undefined"]}}

-------------------------------verify-code-----------------------------------

**Comment by hcfw007** [comment]
Invalid verify code 说明验证码错误

**Comment by xronghui** [comment]
但我输入的验证码确实是扫码后图片上的，尝试过了好几次，而且还把日志打印出来了，比如上面日志中的，617653

**Comment by hcfw007** [comment]
![image](https://github.com/wechaty/puppet-supports/assets/13669999/bf436e33-693c-401e-b347-9387ababe1cb)
从我们的日志看，你的验证码多了一个 \n
你的日志上也有多一个换行的。

**Comment by xronghui** [comment]
牛逼，确实是这个问题

**Comment by hcfw007** [comment]
OK，那问题关闭了。
