### ISSUE TITLE
新手小白问一下，在本地开发好要怎么在云服务器上运行起来或者怎么部署上云服务器的呢

### ISSUE THREAD

**Issue by charleyCC** [wechaty/puppet-service-providers#292]
就是我在本地电脑上已经开发好了一个demo，想要部署到云服务器上，是以守护进程的方式运行这个demo吗，因为在本地都是跑npm start后一直挂着这个服务跑起来的，但是在云服务器上是怎么运行方式呢，前端小白真心请教

**Comment by su-chang** [comment]
这个不在我们的解答范围内，可以自行 google 搜索。加油！

**Comment by charleyCC** [comment]
> 这个不在我们的解答范围内，可以自行 google 搜索。加油！

好的 感谢你
