### ISSUE TITLE
[BUG]WorkPro:自动加好友事件报错

### ISSUE THREAD

**Issue by jackzhangrunze** [wechaty/puppet-service-providers#294]
代码
![image](https://github.com/wechaty/puppet-supports/assets/60767954/8191f2d2-b536-4182-83c8-866bb8294bbc)

报错
![image](https://github.com/wechaty/puppet-supports/assets/60767954/7496553f-04af-4166-a8e1-a66198b12d34)
依赖

![image](https://github.com/wechaty/puppet-supports/assets/60767954/88e43fe9-acf8-4b16-9819-d827c3042bbe)
按照文档来的为什么报错
https://wechaty.gitbook.io/wechaty/v/zh/api/friendship

**Comment by hcfw007** [comment]
这个请提供一下token后6位和出错时间点，我来查一下日志。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
