### ISSUE TITLE
[BUG]WorkPro:按文档配置有问题

### ISSUE THREAD

**Issue by HongliangCai** [wechaty/puppet-service-providers#297]
根据下面文档链接部署配置不成功
https://wechaty.js.org/2022/12/23/introducing-workpro-puppet/
是否可以更新下最新的文档
部署步骤

本地部署报错详情
![image](https://github.com/wechaty/puppet-supports/assets/18377041/d027fbc1-6e73-4bcd-a94e-704cbf511458)

**Comment by hcfw007** [comment]
我这边全新安装没有出现这种情况。
建议使用 @juzi/wechaty 进行尝试。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。

**Comment by lizihao001** [comment]
> 我这边全新安装没有出现这种情况。 建议使用 @juzi/wechaty 进行尝试。

怎么使用 @juzi/wechaty

**Comment by lizihao001** [comment]
> 我这边全新安装没有出现这种情况。 建议使用 @juzi/wechaty 进行尝试。



> 根据下面文档链接部署配置不成功 https://wechaty.js.org/2022/12/23/introducing-workpro-puppet/ 是否可以更新下最新的文档 部署步骤
> 
> 本地部署报错详情 ![image](https://private-user-images.githubusercontent.com/18377041/274127521-d027fbc1-6e73-4bcd-a94e-704cbf511458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MDQ0MjcsIm5iZiI6MTcxMTYwNDEyNywicGF0aCI6Ii8xODM3NzA0MS8yNzQxMjc1MjEtZDAyN2ZiYzEtNmU3My00YmNkLWE5NGUtNzA0Y2JmNTExNDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA1MzUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1MDBmYTZhYzFhMDNmYWU0OTUwOWJkZjQ1YTNmOTI2Yzk3OWViYmE5YjU3NzE3M2M5ZDI4OTY5ZTQ3OTNhM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.58FEbI-RTRux8-rdVBlDo2sNTJyOnBTW6piJV9Qvn-E)

问题解决了嘛 我也遇到类似问题
