### ISSUE TITLE
如何给企业微信群(未活跃的群)自动推送消息呢

### ISSUE THREAD

**Issue by charleyCC** [wechaty/puppet-service-providers#298]
业务场景是希望自动给客户群推送消息，有没有相应的API哦

**Comment by su-chang** [comment]
@charleyCC 可以在这里查看API文档：https://wechaty.js.org/docs/api/

**Comment by charleyCC** [comment]
> @charleyCC 可以在这里查看API文档：https://wechaty.js.org/docs/api/

你好，我看了文档，没有找到怎么往群里主动推送消息的呢，我现在实现方式是往一个特定群注册一个message事件，然后通过这个群的消息再转发给我想要通知的群呢，就是有没有一个方式或API可以让我直接往想要通知的群发送消息呢
![image](https://github.com/wechaty/puppet-supports/assets/39627896/27afb427-5024-4986-a9dd-c9e6464cf50b)

**Comment by su-chang** [comment]
参考下这个示例吧

```ts
const room = await bot.Room.find({id: ROOM_ID})
await room.say(`hello world`)
```

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
