### ISSUE TITLE
Other: workpro获取到的用户id（Contact.id）是什么规则呢？

### ISSUE THREAD

**Issue by sowhut** [wechaty/puppet-service-providers#300]
我在开发过程中发现，从企微外部群可以获取到所有用户的Contact实例，包括外部微信用户（非企业客户），而Contact.id是否可以认为是该用户的微信生态唯一id？即使用户修改了微信昵称、微信号等信息？

**Comment by binsee** [comment]
是的，生态中唯一

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
