### ISSUE TITLE
[BUG]WorkPro:Python版自动拉群报错

### ISSUE THREAD

**Issue by JackLi529** [wechaty/puppet-service-providers#301]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

Python版自动拉群报错：
2023-10-16 15:28:12,090 - Wechaty - ERROR - internal error <(<Status.INTERNAL: 13>, 'WorkproErrorCode: 25041, can not add (7881302798256708) to room 234907840177377! cgi error code: (-2001) message: 由于系统升级，该功能无法使用，请升级版本.', None)>

**Info**

 - Platform[e.g. Windows/Mac/Linux]: Mac
 - Runtime version[e.g. node/JAVA]: Python
 - Wechaty version: 0.10.7
 - wechaty-plugin-contrib version: 0.0.25

 - Wechaty Puppet version: 0.8.10

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by su-chang** [comment]
这个可能是被限制的提示，可以过段时间再试试看看能否拉群，或者也可以在手机端试下。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
