### ISSUE TITLE
[BUG]WorkPro:Python发送FileBox报错

### ISSUE THREAD

**Issue by JackLi529** [wechaty/puppet-service-providers#302]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

FileBox
image_url = "https://github.githubassets.com/favicons/favicon.png"
box = FileBox.from_url(image_url, name='李白')
conversation.say(box)
Wechaty - ERROR - internal error <(<Status.INTERNAL: 13>, 'no url', None)>

**Info**

 - Platform[e.g. Windows/Mac/Linux]: Mac
 - Runtime version[e.g. node/JAVA]: Python
 - Wechaty version: 
 - Wechaty Puppet version: 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by su-chang** [comment]
建议使用node版本的wechaty，不确定是否为python版本内部的问题。但是使用node版本一定没有问题。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
