### ISSUE TITLE
[FEAT]WorkPro: bot.Message.Type增加对分享“文章标注/片段”类型的支持

### ISSUE THREAD

**Issue by tentacle-pro** [wechaty/puppet-service-providers#303]
操作过程：
在微信内打开任意公众号文章，长按选中一段文字，点分享，到托管给wechaty的企业微信账号。

结果：
企业微信端收到的消息类型是bot.Message.Type.Image。

预期：
收到的消息应该包括文章URL：既有Image，也有文章URL。

截图：
![666 (2)](https://github.com/wechaty/puppet-supports/assets/252310/fb69b13a-8215-4424-a8a1-6200e3dd4737)

运行环境:
"dependencies": {
        "@juzi/wechaty": "^1.0.66",
}

**Comment by su-chang** [comment]
这个是企业微信的机制，转发出去的内容就是一张图片。不支持识别到原url的内容。

**Comment by tentacle-pro** [comment]
确认企业微信端收到消息后无法显示“阅读原文”链接。关闭issue了
