### ISSUE TITLE
room.say()需要@人报错

### ISSUE THREAD

**Issue by charleyCC** [wechaty/puppet-service-providers#304]
如果我需要@的人是企业微信号就会报错，但是如果是个人微信号就不会
代码如下：
<img width="837" alt="image" src="https://github.com/wechaty/puppet-supports/assets/39627896/6a4ccac2-e783-4c72-882e-158d6f444355">

报错信息如下
![image](https://github.com/wechaty/puppet-supports/assets/39627896/8525af0c-111a-4d6c-998d-9bfe51e29b6d)

**Comment by su-chang** [comment]
需要确认mentionMemberLists返回的是Contact数组。
