### ISSUE TITLE
[BUG]WorkPro:如何注销登录一直出 ERR PuppetService onGrpcStreamEvent() this.login() rejection must logout first before login again!

### ISSUE THREAD

**Issue by yangningmoojing** [wechaty/puppet-service-providers#305]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

发送指令没有回应，然后重启后，当时有回应，在发第二条就没有回应了，查看日志就会出现 
07:11:05 WARN PuppetWatchdogAgent start() reset() reason: {"data":"regular heartbeat","timeoutMilliseconds":60000}
07:11:05 INFO StarterBot Contact<镜镜4号> logout
07:11:05 WARN GrpcManager initClient() TLS: disabled (INSECURE)
07:11:05 ERR PuppetService onGrpcStreamEvent() this.login() rejection must logout first before login again!
如何解决

**Info**

 - Platform[e.g. Windows/Mac/Linux]: 
 - Runtime version[e.g. node/JAVA]:
 - Wechaty version: 
 - Wechaty Puppet version: 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yangningmoojing** [comment]
用的是 docker 启动的

**Comment by yangningmoojing** [comment]
换了服务器，启动后就不正常了

**Comment by yangningmoojing** [comment]
把docker重新创建，手机上电脑登录退出，然后扫码登录，还是不行，还是会出现 
07:39:50 WARN PuppetWatchdogAgent start() reset() reason: {"data":"regular heartbeat","timeoutMilliseconds":60000}
07:39:50 INFO StarterBot Contact<镜镜11号> logout
07:39:50 WARN GrpcManager initClient() TLS: disabled (INSECURE)
07:39:51 ERR PuppetService onGrpcStreamEvent() this.login() rejection must logout first before login again!

**Comment by su-chang** [comment]
```
// 调用该方法可以主动登出bot
await bot.logout()
```

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
