### ISSUE TITLE
[BUG]WorkPro: 使用Contact.findAll()获取到了已经被删除的成员

### ISSUE THREAD

**Issue by jansen-s** [wechaty/puppet-service-providers#311]
@juzi/wechaty 1.0.75
@juzi/wechaty-puppet 1.0.68
@juzi/wechaty-puppet-service 1.0.80
使用bot.Contact.findAll()时，会把已经删除的成员也返回。请问如何过滤掉已经删除的成员？

**Comment by hcfw007** [comment]
contact.findAll()并不是获取所有好友，是获取所有联系人，群成员、单向好友，都是联系人。具体是不是好友，需要用contact.isFriend()判断。

**Comment by jansen-s** [comment]
> contact.findAll()并不是获取所有好友，是获取所有联系人，群成员、单向好友，都是联系人。具体是不是好友，需要用contact.isFriend()判断。

你可能理解错了。我说的是企微成员，而且是已经删除的成员。这里的“成员”指与企微组织职员。实际情况中，职员会离职，离职后，他在企微组织内的账号会被删除。这些被删除的账号如何过滤？

**Comment by hcfw007** [comment]
> > contact.findAll()并不是获取所有好友，是获取所有联系人，群成员、单向好友，都是联系人。具体是不是好友，需要用contact.isFriend()判断。
> 
> 你可能理解错了。我说的是企微成员，而且是已经删除的成员。这里的“成员”指与企微组织职员。实际情况中，职员会离职，离职后，他在企微组织内的账号会被删除。这些被删除的账号如何过滤？

通过coworker进行判断
