### ISSUE TITLE
[BUG]WorkPro:如何让wechaty的say方法支持富文本

### ISSUE THREAD

**Issue by JackLi529** [wechaty/puppet-service-providers#312]
使用企微版的wechaty，需要发送富文本到客户端，但是调用say方法时，直接讲所有的内容当成了文本。

问题：
如何能够正常的显示富文本的内容，而不是输出网页标签。
<img width="335" alt="image" src="https://github.com/wechaty/puppet-supports/assets/41407129/89b636c5-8bea-488c-865a-68db2efd1466">

**Comment by hcfw007** [comment]
> 使用企微版的wechaty，需要发送富文本到客户端，但是调用say方法时，直接讲所有的内容当成了文本。
> 
> 问题： 如何能够正常的显示富文本的内容，而不是输出网页标签。 <img alt="image" width="335" src="https://user-images.githubusercontent.com/41407129/279616267-89b636c5-8bea-488c-865a-68db2efd1466.png">

这个目前应该还不支持。

**Comment by hcfw007** [comment]
你在企微手机上能发出这样的消息吗？

**Comment by hcfw007** [comment]
能介绍下如何操作吗，我没发出来过这样的。

**Comment by JackLi529** [comment]
富文本内容是通过程序生成的，假设我们后台程序生成了以下内容 ：
咨询人身份
<a href= weixin:/bizmsgmenu?
msgmenucontent=本人&msgmenuid=0'>本人</a>
<a href='weixin://bizmsgmenu?msgmenucontent=家属&msgmenuid=1'>家属</a>

然后通过wechaty的say方法发送到客户端。

现在的效果是say方法识别不了富文本，所以将所有的内容直接输出了，而不是像上图的那样本人和家属是高亮的，网页标签是看不到的。

**Comment by JackLi529** [comment]
> 你在企微手机上能发出这样的消息吗？

富文本内容是通过程序生成的，假设我们后台程序生成了以下内容 ：
咨询人身份
<a href= weixin:/bizmsgmenu?
msgmenucontent=本人&msgmenuid=0'>本人
家属

然后通过wechaty的say方法发送到客户端。

现在的效果是say方法识别不了富文本，所以将所有的内容直接输出了，而不是像上图的那样本人和家属是高亮的，网页标签是看不到的。

**Comment by JackLi529** [comment]
receiver.say(msg)

<img width="758" alt="image" src="https://github.com/wechaty/puppet-supports/assets/41407129/9da6003c-6752-431e-8b34-b4993b5a1f90">

<img width="665" alt="image" src="https://github.com/wechaty/puppet-supports/assets/41407129/ce4e1637-a0c9-4a0a-bf94-8efa6d7d4069">
<img width="608" alt="image" src="https://github.com/wechaty/puppet-supports/assets/41407129/dc2281d5-df39-4fd3-94d0-1fac9aa67e61">

**Comment by hcfw007** [comment]
你这个富文本，要首先能用手机企微发出来，我们才有可能实现。
我现在需要的是，如何用手机发出富文本消息，请你教学一下。

**Comment by binsee** [comment]
无论是用手机或者电脑，请确保使用官方客户端能发出来，我们这边才能看。
另外这个不算 bug，微信官方对这种消息就有限制和过滤

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
