### ISSUE TITLE
How to enter the verification code when scanning the QR code for the first time

### ISSUE THREAD

**Issue by wyying** [wechaty/puppet-service-providers#313]
Please make sure you have read the [Wechaty Puppet Service](https://wechaty.js.org/docs/puppet-services/) from Wechaty Official Website before you continue writting this issue.

## Question
![image](https://github.com/wechaty/puppet-supports/assets/15809193/52d6969c-fe6a-4b7f-a8e7-65f34a7a0bc2)
How to fill in the verification code

**Comment by hcfw007** [comment]
Please checkout the pined issue.

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
