### ISSUE TITLE
[BUG]WorkPro: 企业微信的room是区分内部群和外部群的。通过Room.findAll()获取时，怎么区分内部群和外部群？

### ISSUE THREAD

**Issue by jansen-s** [wechaty/puppet-service-providers#314]
在企业微信中，群聊分为内部群和外部群。
内部群（全员群、部门群等）里的成员均为同组织的成员，外部群则包含组织外的联系人。
我使用Room.findAll()获取企业微信的所有群聊列表，返回的数据无法区分群聊的类型（内部群、外部群）

**Comment by su-chang** [comment]
@jansen-s  试试这个字段： `room.payload.external` 目前没有封装为函数，先直接从payload获取吧。

**Comment by jansen-s** [comment]
@juzi/wechaty 1.0.75
@juzi/wechaty-puppet 1.0.68
@juzi/wechaty-puppet-service 1.0.80
@su-chang 刚刚使用room.findAll()获取，在room.payload里并没有返回external字段，是我引用的包版本太低了吗？

**Comment by hcfw007** [comment]
没有字段可以直接判断出来。可以通过数字id进行判断。

**Comment by su-chang** [comment]
> 没有字段可以直接判断出来。可以通过数字id进行判断。

这个我看底层和puppet层都有这个字段，后续咱们把puppet-service层接入这个字段就可以用了吧。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
