### ISSUE TITLE
WXWork:  全员群收不到消息

### ISSUE THREAD

**Issue by ing670** [wechaty/puppet-service-providers#315]
Please make sure you have read the [Wechaty Puppet Service: WXWork](https://wechaty.js.org/docs/puppet-services/wxwork) from Wechaty Official Website before you continue writting this issue.

## Question
RT

**Comment by su-chang** [comment]
请提供详细内容以便排查。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
