### ISSUE TITLE
[BUG]WorkPro:在friendship事件中使用await room.add(friendship.contact());报错

### ISSUE THREAD

**Issue by ghost** [wechaty/puppet-service-providers#317]
@juzi/wechaty 1.0.79
@juzi/wechaty-puppet 1.0.69
@juzi/wechaty-puppet-service 1.0.81
在friendship事件中，使用await room.add(friendship.contact())出现错误。

Error: 13 INTERNAL: WorkproErrorCode: 25041, can not add (7881300995981368) to room 1970325006531050! cgi error code: (-2001) message: 由于系统升级，该功能无法使用，请升级版本.

**Comment by su-chang** [comment]
这个是被企业微信限制了，可以尝试在手机端拉人进这个群聊试试。

BTW，看起来这个群是企业全员群，是无法拉取个人微信进群的。

**Comment by ghost** [comment]
> 这个是被企业微信限制了，可以尝试在手机端拉人进这个群聊试试。
> 
> BTW，看起来这个群是企业全员群，是无法拉取个人微信进群的。

好的，这个确实是企业全员群，无法拉入外部人员。
另外，您在 #314  中提到的字段，有计划实现吗？

**Comment by su-chang** [comment]
@wechaty002  暂时还没有，不过做起来会比较快。估计在12月可以支持。
