### ISSUE TITLE
WXWork: contact.tags 获取不到tag

### ISSUE THREAD

**Issue by CauseMyLove** [wechaty/puppet-service-providers#318]
## Question
我已知在企微上创建了标签，且将人添加进了该标签，在获取时，标签列表获取不到，联系人的标签也获取不到

![image](https://github.com/wechaty/puppet-supports/assets/74802213/3e98c93a-3401-4db5-91e0-2cc33229a905)

![image](https://github.com/wechaty/puppet-supports/assets/74802213/275732c7-6650-4aff-86c5-150a83391727)
![image](https://github.com/wechaty/puppet-supports/assets/74802213/d4b1bdb5-114c-4169-8575-cf1f40d64336)

另外，有给联系人添加标签的使用方法吗？
![image](https://github.com/wechaty/puppet-supports/assets/74802213/e7ddfc34-8deb-4444-83ec-b85e2786aa6d)
直接使用contact.tag({id:""})会给我报错

**Comment by su-chang** [comment]
参考以下示例：
```ts
// 获取标签列表
const list = await bot.Tag.list()

// 获取联系人的标签
const tags = await contact.tags()
```

**Comment by CauseMyLove** [comment]
请问这个标签对应的是企微哪个地方的呢？

**Comment by CauseMyLove** [comment]
好的，已解决，感谢
