### ISSUE TITLE
[BUG]WorkPro: TypeError [Error]: state.conditions.includes is not a function

### ISSUE THREAD

**Issue by hl123-123** [wechaty/puppet-service-providers#321]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

我按照客服给我的文档https://wechaty.js.org/2022/12/23/introducing-workpro-puppet/ ，然后按照这上面运行报了这个错误：

TypeError [Error]: state.conditions.includes is not a function

![微信图片_20231128110532](https://github.com/wechaty/puppet-supports/assets/75974455/4dddbb0a-2b2e-4df4-a72f-69f015ce5bff)

**Info**

 - Platform[e.g. Windows/Mac/Linux]: codespace
 - Runtime version[e.g. node/JAVA]:node 20.9.0
 - Wechaty version: 
 - Wechaty Puppet version: 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hcfw007** [comment]
你好，这个demo项目已经过时，请尝试这个

https://github.com/RPAChat/workpro-getting-started

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
