### ISSUE TITLE
[FEAT]WorkPro:某些类型的消息能否像padlocal一样获取到原始消息的xml,比如红包

### ISSUE THREAD

**Issue by hejuntt1014** [wechaty/puppet-service-providers#323]
某些类型的消息能否像padlocal一样获取到原始消息的xml,比如红包,我看workpro对于类似红包这种消息类型text字段直接是空的,但是padlocal是原始xml,我希望能有办法看到一些例如转账,红包,表情等的原始xml,因为可以读取到转账后或者红包金额来做一些处理

**Comment by hcfw007** [comment]
我们有这个能力，但钱相关的信息比较敏感，我们选择不去解析。如有需求，可与客服联系。

**Comment by hejuntt1014** [comment]
> 我们有这个能力，但钱相关的信息比较敏感，我们选择不去解析。如有需求，可与客服联系。

麻烦提供一下客服或者相关技术的联系方式哦

**Comment by hcfw007** [comment]
请查看pined issue
