### ISSUE TITLE
[BUG]WorkPro:服务突然中断，不再接收消息

### ISSUE THREAD

**Issue by chenag** [wechaty/puppet-service-providers#324]
项目在正常运行中时，在凌晨突然报错异常“ResolverWechaty updateResolution() address not found target”，连续提示两次之后程序正常运行，企微显示任然在线，但是不再接收任何消息。以下是程序运行时的异常消息：
![异常反馈1](https://github.com/wechaty/puppet-supports/assets/28559189/0fe61ab0-9b67-426e-9c04-a0f2ae57b0da)
![异常反馈2](https://github.com/wechaty/puppet-supports/assets/28559189/a874721e-6cf9-4d29-a646-12683401c2d2)
希望帮忙查询一下

**Comment by hcfw007** [comment]
应该是我们例行更新导致的，一般更新会持续5分钟左右，可以考虑监控error事件并重连。

**Comment by chenag** [comment]
> 应该是我们例行更新导致的，一般更新会持续5分钟左右，可以考虑监控error事件并重连。

有没有示例代码，监控什么类型的错误来尝试重连？

**Comment by hcfw007** [comment]
```
const resetErrorList = [
  '14 UNAVAILABLE',
  'no grpc manager',
  'NO CLIENT',
];
```
我们实践中监控的错误关键词是这几个。需要防抖，因为如果你在这段时间有操作，可能产生多个相同错误。

```
const throttleQueue = new ThrottleQueue(10 * 1000);
throttleQueue.subscribe(async () => {
  if (wechatyBot.puppet.isLoggedIn) {
    wechatyBot.puppet.emit('logout', {
      contactId: wechatyBot.puppet.currentUserId,
      data: '与服务端断开连接，将要尝试重连...',
    }); // 否则reason将是puppet stop()

    await new Promise<void>(resolve => setImmediate(() => {
      (wechatyBot.puppet as any).__currentUserId = undefined;
      resolve();
    }));

  }

  await new Promise(resolve => setTimeout(resolve, 1 * 1000));
  log.warn(PRE, 'throttleQueue reset triggered');
  await wechatyBot.reset();
  await new Promise(resolve => setTimeout(resolve, 12 * 1000));
  await wechatyBot.puppet.ding(BotDongEventType.HEALTH_CHECK);
});
```

**Comment by wyying** [comment]
> ```
> const resetErrorList = [
>   '14 UNAVAILABLE',
>   'no grpc manager',
>   'NO CLIENT',
> ];
> ```
> 
> 我们实践中监控的错误关键词是这几个。需要防抖，因为如果你在这段时间有操作，可能产生多个相同错误。
> 
> ```
> const throttleQueue = new ThrottleQueue(10 * 1000);
> throttleQueue.subscribe(async () => {
>   if (wechatyBot.puppet.isLoggedIn) {
>     wechatyBot.puppet.emit('logout', {
>       contactId: wechatyBot.puppet.currentUserId,
>       data: '与服务端断开连接，将要尝试重连...',
>     }); // 否则reason将是puppet stop()
> 
>     await new Promise<void>(resolve => setImmediate(() => {
>       (wechatyBot.puppet as any).__currentUserId = undefined;
>       resolve();
>     }));
> 
>   }
> 
>   await new Promise(resolve => setTimeout(resolve, 1 * 1000));
>   log.warn(PRE, 'throttleQueue reset triggered');
>   await wechatyBot.reset();
>   await new Promise(resolve => setTimeout(resolve, 12 * 1000));
>   await wechatyBot.puppet.ding(BotDongEventType.HEALTH_CHECK);
> });
> ```

其中，BotDongEventType.HEALTH_CHECK表示的是什么

**Comment by chenag** [comment]
> ```
> const resetErrorList = [
>   '14 UNAVAILABLE',
>   'no grpc manager',
>   'NO CLIENT',
> ];
> ```
> 
> 我们实践中监控的错误关键词是这几个。需要防抖，因为如果你在这段时间有操作，可能产生多个相同错误。
> 
> ```
> const throttleQueue = new ThrottleQueue(10 * 1000);
> throttleQueue.subscribe(async () => {
>   if (wechatyBot.puppet.isLoggedIn) {
>     wechatyBot.puppet.emit('logout', {
>       contactId: wechatyBot.puppet.currentUserId,
>       data: '与服务端断开连接，将要尝试重连...',
>     }); // 否则reason将是puppet stop()
> 
>     await new Promise<void>(resolve => setImmediate(() => {
>       (wechatyBot.puppet as any).__currentUserId = undefined;
>       resolve();
>     }));
> 
>   }
> 
>   await new Promise(resolve => setTimeout(resolve, 1 * 1000));
>   log.warn(PRE, 'throttleQueue reset triggered');
>   await wechatyBot.reset();
>   await new Promise(resolve => setTimeout(resolve, 12 * 1000));
>   await wechatyBot.puppet.ding(BotDongEventType.HEALTH_CHECK);
> });
> ```

![image](https://github.com/wechaty/puppet-supports/assets/28559189/8f3dfc21-3a5a-490a-a683-2c1ab33a953b)
12月5号又出现一次，但是这次的错误类型好像不是之前定义的那些

**Comment by hcfw007** [comment]
这个错误是重启后没找到token——可能是token这时候还没更新完成

**Comment by chenag** [comment]
> 这个错误是重启后没找到token——可能是token这时候还没更新完成
那这个异常属于上面之前定义的几个异常范围吗？还有就是这个常量BotDongEventType.HEALTH_CHECK，没有定义，代码无法跑起来，还望解惑

**Comment by chenag** [comment]
> 这个错误是重启后没找到token——可能是token这时候还没更新完成

那这个异常属于上面之前定义的几个异常范围吗？还有就是这个常量BotDongEventType.HEALTH_CHECK，没有定义，代码无法跑起来，还望解惑

**Comment by hcfw007** [comment]
这个不属于，应该等底层服务恢复会自动连接，不用处理。

这个常量随便定义一个字符串即可，没有含义。

**Comment by chenag** [comment]
> 这个不属于，应该等底层服务恢复会自动连接，不用处理。
> 
> 这个常量随便定义一个字符串即可，没有含义。

但我们从我们这个就过看来是没有重连的，所以就直接掉线了，需要我们手动重启。然后之前的那个问题用示例代码也跑不起来，这个常量“BotDongEventType.HEALTH_CHECK”不知道是什么

**Comment by hcfw007** [comment]
那个代码是示例，不是说你原样就能立刻使用的。
本质上就是有一些错误码需要reset bot才能使用，包括我上面说的几个。
```
const resetErrorList = [
  '14 UNAVAILABLE',
  'no grpc manager',
  'NO CLIENT',
  'Call cancelled'
];
```
然后示例代码做的事就是当错误码包含这些内容的时候，用一个 10秒的 throttleQueue 去重新连接，重新链接建立后完成后用 wechatyBot.puppet.ding(BotDongEventType.HEALTH_CHECK) 去检查是否链接成功。上面说了 ding 接收任意字符串都行，随便定义一个即可。

**Comment by wyying** [comment]
> 那个代码是示例，不是说你原样就能立刻使用的。 本质上就是有一些错误码需要reset bot才能使用，包括我上面说的几个。
> 
> ```
> const resetErrorList = [
>   '14 UNAVAILABLE',
>   'no grpc manager',
>   'NO CLIENT',
>   'Call cancelled'
> ];
> ```
> 
> 然后示例代码做的事就是当错误码包含这些内容的时候，用一个 10秒的 throttleQueue 去重新连接，重新链接建立后完成后用 wechatyBot.puppet.ding(BotDongEventType.HEALTH_CHECK) 去检查是否链接成功。上面说了 ding 接收任意字符串都行，随便定义一个即可。

谢谢您的回复，这个错误码会在on("error"，onError)事件监听到吗？还是从其他地方监听

**Comment by hcfw007** [comment]
> > 那个代码是示例，不是说你原样就能立刻使用的。 本质上就是有一些错误码需要reset bot才能使用，包括我上面说的几个。
> > ```
> > const resetErrorList = [
> >   '14 UNAVAILABLE',
> >   'no grpc manager',
> >   'NO CLIENT',
> >   'Call cancelled'
> > ];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后示例代码做的事就是当错误码包含这些内容的时候，用一个 10秒的 throttleQueue 去重新连接，重新链接建立后完成后用 wechatyBot.puppet.ding(BotDongEventType.HEALTH_CHECK) 去检查是否链接成功。上面说了 ding 接收任意字符串都行，随便定义一个即可。
> 
> 谢谢您的回复，这个错误码会在on("error"，onError)事件监听到吗？还是从其他地方监听

是的，就在 'error' 事件注册监听器。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
