### ISSUE TITLE
[BUG]WorkPro: 半夜突然报o connection established，希望能帮忙排查下是什么原因导致的

### ISSUE THREAD

**Issue by fangkunhhh** [wechaty/puppet-service-providers#325]
![image](https://github.com/wechaty/puppet-supports/assets/152241993/5c26a26a-16b3-45a6-982c-5aa592867c72)

**Comment by hcfw007** [comment]
应该是我们例行更新导致的，一般更新会持续5分钟左右，可以考虑监控error事件并重连。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
