### ISSUE TITLE
机器人如何检查当前状态

### ISSUE THREAD

**Issue by fangkunhhh** [wechaty/puppet-service-providers#329]
1、首先我机器人已经调用了start()方法，然后我又重复调用了一个start()方法，那有什么方法可以检测当前机器人已经start了，这样我就可以避免重复start了
2、机器人登录成功后，调用哪个接口查看机器人已在线？

**Comment by hcfw007** [comment]
不需要检查，已经start的bot不会再次start，内部做了拦截。
可以调用 bot.currentUser，能获取到值就是已登录。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
