### ISSUE TITLE
[BUG]WorkPro: 没有找到如何发送语音(voice)的接口

### ISSUE THREAD

**Issue by guangzhengyu** [wechaty/puppet-service-providers#331]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

如何发送voice消息？有没有相关文档？是不是在这里https://wechaty.js.org/查看文档？

**Info**
ubuntu，nodejs平台，使用了npm上最新的包

**Comment by guangzhengyu** [comment]
有相关的使用示例吗？我在代码类型中只看到发送string、url、location、小程序，剩下就是filebox那类的了

**Comment by hcfw007** [comment]
直接发送silk文件就是语音。

**Comment by foxeet** [comment]
> 直接发送silk文件就是语音。

这个silk文件怎么得到，我们目前没有在文档里找到？方便给下文档链接？

**Comment by foxeet** [comment]
我们的需求场景是：能够通过企业微信的语音能力，当用户提问时，能主动给用户发语音。对应文档里的 ‘send voice message’   https://wechaty.js.org/zh/docs/puppet-services/compatibility?_highlight=compa#compatibility 。

目前没有找到这个能力的开发文档，给我们个说明文档也可以。（不是下载语音）

**Comment by guangzhengyu** [comment]
> 直接发送silk文件就是语音。

@hcfw007 

在https://wechaty.js.org/ 没有找到相关描述。

查看`sayable`的类型，全局搜索了整个类型文件，没有和**"silk"**相关的内容
![image](https://github.com/wechaty/puppet-supports/assets/46769446/cb46648f-a89e-406a-b70f-7ed8b43037f8)

**Comment by hcfw007** [comment]
接收语音消息获得的文件就是silk类型的。

**Comment by hcfw007** [comment]
使用的就是发文件的接口。

**Comment by hejuntt1014** [comment]
> 使用的就是发文件的接口。

我发送过去语音消息时间长度显示不对(固定5秒),一样的代码在padlocal下显示是正常的,下面是我的代码
```
const fileBox = FileBox.fromFile(`${fileName}.sil`);
//fileBox.mimeType = 'audio/silk';
fileBox.metadata = {
  duration: voiceLength,
  voiceLength: voiceLength
};
await receiver.say(fileBox);
```

**Comment by su-chang** [comment]
metadata中的duration如果没有设置对的话，默认就显示5秒。

可以提供下具体发送案例，我们这边查日志看看。

**Comment by hejuntt1014** [comment]
> metadata中的duration如果没有设置对的话，默认就显示5秒。
> 
> 可以提供下具体发送案例，我们这边查日志看看。

duration的单位毫秒或者秒我都测试过,效果都一样哦,下面是发送案例
```08:10:30 INFO PuppetService messageSendFile(7881302047951414, FileBox#File<1702339828052.sil>) about to call grpc```

**Comment by su-chang** [comment]
@hejuntt1014 你用的@juzi/wechaty @juzi/wechaty-puppet @juzi/wechaty-puppet-service 的版本提供下吧。

**Comment by hejuntt1014** [comment]
> @hejuntt1014 你用的@juzi/wechaty @juzi/wechaty-puppet @juzi/wechaty-puppet-service 的版本提供下吧。

@su-chang 

└─┬ @juzi/wechaty@1.0.81
  └─┬ @juzi/wechaty-puppet-service@1.0.84
    └── @juzi/wechaty-puppet@1.0.73

**Comment by su-chang** [comment]
@hejuntt1014 已确认问题，FileBox.fromFile() 方法目前还不支持指定 duration，可以尝试通过文件的url加载filebox文件的方式来进行发送。

```ts
const fileBox = FileBox.fromUrl(voiceUrl)
fileBox.metadata = {
  duration: voiceLength,
};
await receiver.say(fileBox);
```

**Comment by hejuntt1014** [comment]
> @hejuntt1014 已确认问题，FileBox.fromFile() 方法目前还不支持指定 duration，可以尝试通过文件的url加载filebox文件的方式来进行发送。
> 
> ```ts
> const fileBox = FileBox.fromUrl(voiceUrl)
> fileBox.metadata = {
>   duration: voiceLength,
> };
> await receiver.say(fileBox);
> ```

问题解决,但是还是希望早点支持 fromFile,谢谢哦

**Comment by su-chang** [comment]
好的

**Comment by huan** [comment]
I'm curious about why only `fromUrl` supports the `duration` metadata, but not `fromFile`?

**Comment by tentacle-pro** [comment]
> @hejuntt1014 已确认问题，FileBox.fromFile() 方法目前还不支持指定 duration，可以尝试通过文件的url加载filebox文件的方式来进行发送。
> 
> ```ts
> const fileBox = FileBox.fromUrl(voiceUrl)
> fileBox.metadata = {
>   duration: voiceLength,
> };
> await receiver.say(fileBox);
> ```

请教怎么“通过文件的url加载filebox文件”？谢谢 @su-chang @hejuntt1014

**Comment by su-chang** [comment]
@huozhong-in  你引用的内容就是问题的答案。

**Comment by tentacle-pro** [comment]
@su-chang voiceUrl必须是公网能访问的有效网址对吗？本机临时搭建的http server不行，如：
`http://127.0.0.1:5000/api/voice/5e1f366f-169a-4366-a050-4b48a6595005.silk`

日志为
```
23:59:09 INFO PuppetService messageSendFile(R:10951889178429173, FileBox#Url<5e1f366f-169a-4366-a050-4b48a6595005.silk>) about to call grpc
/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/call.ts:82
  const error = new Error(message);
                ^
Error: 13 INTERNAL: connect ECONNREFUSED 127.0.0.1:5000
    at callErrorFromStatus (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/call.ts:82:17)
    at Object.onReceiveStatus (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/client.ts:360:55)
    at Object.onReceiveStatus (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
    at Object.onReceiveStatus (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
    at /Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/resolving-call.ts:132:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/client.ts:325:42)
    at ServiceClientImpl.messageSendFile (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:428:12)
    at PuppetService.messageSendFile (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@juzi+wechaty-puppet-service@1.0.89_@juzi+wechaty-puppet@1.0.79_brolog@1.14.2_redux@4.2.1/node_modules/@juzi/wechaty-puppet-service/src/client/puppet-service.ts:1389:6)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/dio/workspace/python/x/api/node_modules/.pnpm/@juzi+wechaty@1.0.90_@juzi+wechaty-puppet@1.0.79_brolog@1.14.2_redux@4.2.1_rxjs@7.8.1/node_modules/@juzi/wechaty/src/sayable/deliver-sayable.ts:46:13
    at async WechatifiedUserClass.say (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@juzi+wechaty@1.0.90_@juzi+wechaty-puppet@1.0.79_brolog@1.14.2_redux@4.2.1_rxjs@7.8.1/node_modules/@juzi/wechaty/src/user-modules/room.ts:570:15)
    at async chatWithLLMInRoom (/Users/dio/workspace/python/x/api/bot.ts:384:11) {
  code: 13,
  details: 'connect ECONNREFUSED 127.0.0.1:5000',
  metadata: Metadata {
    internalRepr: Map(3) {
      'content-type' => [Array],
      'date' => [Array],
      'authorization' => [Array]
    },
    options: {}
  }
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by binsee** [comment]
> @su-chang voiceUrl必须是公网能访问的有效网址对吗？本机临时搭建的http server不行，如： `http://127.0.0.1:5000/api/voice/5e1f366f-169a-4366-a050-4b48a6595005.silk`
> 
> 日志为
> 
> ```
> 23:59:09 INFO PuppetService messageSendFile(R:10951889178429173, FileBox#Url<5e1f366f-169a-4366-a050-4b48a6595005.silk>) about to call grpc
> /Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/call.ts:82
>   const error = new Error(message);
>                 ^
> Error: 13 INTERNAL: connect ECONNREFUSED 127.0.0.1:5000
>     at callErrorFromStatus (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/call.ts:82:17)
>     at Object.onReceiveStatus (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/client.ts:360:55)
>     at Object.onReceiveStatus (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
>     at Object.onReceiveStatus (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
>     at /Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/resolving-call.ts:132:24
>     at processTicksAndRejections (node:internal/process/task_queues:77:11)
> for call at
>     at ServiceClientImpl.makeUnaryRequest (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/client.ts:325:42)
>     at ServiceClientImpl.messageSendFile (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
>     at node:internal/util:442:7
>     at new Promise (<anonymous>)
>     at bound  (node:internal/util:428:12)
>     at PuppetService.messageSendFile (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@juzi+wechaty-puppet-service@1.0.89_@juzi+wechaty-puppet@1.0.79_brolog@1.14.2_redux@4.2.1/node_modules/@juzi/wechaty-puppet-service/src/client/puppet-service.ts:1389:6)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async /Users/dio/workspace/python/x/api/node_modules/.pnpm/@juzi+wechaty@1.0.90_@juzi+wechaty-puppet@1.0.79_brolog@1.14.2_redux@4.2.1_rxjs@7.8.1/node_modules/@juzi/wechaty/src/sayable/deliver-sayable.ts:46:13
>     at async WechatifiedUserClass.say (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@juzi+wechaty@1.0.90_@juzi+wechaty-puppet@1.0.79_brolog@1.14.2_redux@4.2.1_rxjs@7.8.1/node_modules/@juzi/wechaty/src/user-modules/room.ts:570:15)
>     at async chatWithLLMInRoom (/Users/dio/workspace/python/x/api/bot.ts:384:11) {
>   code: 13,
>   details: 'connect ECONNREFUSED 127.0.0.1:5000',
>   metadata: Metadata {
>     internalRepr: Map(3) {
>       'content-type' => [Array],
>       'date' => [Array],
>       'authorization' => [Array]
>     },
>     options: {}
>   }
> }
>  ELIFECYCLE  Command failed with exit code 1.
> ```

你的报错信息中 `Error: 13 INTERNAL: connect ECONNREFUSED 127.0.0.1:5000` 已经表明了你的程序无法访问 `http://127.0.0.1:5000`
请确保 bot 能通过 url 访问到文件，你可以在跑代码前先在终端里用 `curl http://127.0.0.1:5000/api/voice/5e1f366f-169a-4366-a050-4b48a6595005.silk` 试一下 url 能否访问

**Comment by hcfw007** [comment]
无后续回复，issue关闭。

**Comment by tentacle-pro** [comment]
> > @su-chang voiceUrl必须是公网能访问的有效网址对吗？本机临时搭建的http server不行，如： `http://127.0.0.1:5000/api/voice/5e1f366f-169a-4366-a050-4b48a6595005.silk`
> > 日志为
> > ```
> > 23:59:09 INFO PuppetService messageSendFile(R:10951889178429173, FileBox#Url<5e1f366f-169a-4366-a050-4b48a6595005.silk>) about to call grpc
> > /Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/call.ts:82
> >   const error = new Error(message);
> >                 ^
> > Error: 13 INTERNAL: connect ECONNREFUSED 127.0.0.1:5000
> >     at callErrorFromStatus (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/call.ts:82:17)
> >     at Object.onReceiveStatus (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/client.ts:360:55)
> >     at Object.onReceiveStatus (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
> >     at Object.onReceiveStatus (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
> >     at /Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/resolving-call.ts:132:24
> >     at processTicksAndRejections (node:internal/process/task_queues:77:11)
> > for call at
> >     at ServiceClientImpl.makeUnaryRequest (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/client.ts:325:42)
> >     at ServiceClientImpl.messageSendFile (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
> >     at node:internal/util:442:7
> >     at new Promise (<anonymous>)
> >     at bound  (node:internal/util:428:12)
> >     at PuppetService.messageSendFile (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@juzi+wechaty-puppet-service@1.0.89_@juzi+wechaty-puppet@1.0.79_brolog@1.14.2_redux@4.2.1/node_modules/@juzi/wechaty-puppet-service/src/client/puppet-service.ts:1389:6)
> >     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> >     at async /Users/dio/workspace/python/x/api/node_modules/.pnpm/@juzi+wechaty@1.0.90_@juzi+wechaty-puppet@1.0.79_brolog@1.14.2_redux@4.2.1_rxjs@7.8.1/node_modules/@juzi/wechaty/src/sayable/deliver-sayable.ts:46:13
> >     at async WechatifiedUserClass.say (/Users/dio/workspace/python/x/api/node_modules/.pnpm/@juzi+wechaty@1.0.90_@juzi+wechaty-puppet@1.0.79_brolog@1.14.2_redux@4.2.1_rxjs@7.8.1/node_modules/@juzi/wechaty/src/user-modules/room.ts:570:15)
> >     at async chatWithLLMInRoom (/Users/dio/workspace/python/x/api/bot.ts:384:11) {
> >   code: 13,
> >   details: 'connect ECONNREFUSED 127.0.0.1:5000',
> >   metadata: Metadata {
> >     internalRepr: Map(3) {
> >       'content-type' => [Array],
> >       'date' => [Array],
> >       'authorization' => [Array]
> >     },
> >     options: {}
> >   }
> > }
> >  ELIFECYCLE  Command failed with exit code 1.
> > ```
> 
> 你的报错信息中 `Error: 13 INTERNAL: connect ECONNREFUSED 127.0.0.1:5000` 已经表明了你的程序无法访问 `http://127.0.0.1:5000` 请确保 bot 能通过 url 访问到文件，你可以在跑代码前先在终端里用 `curl http://127.0.0.1:5000/api/voice/5e1f366f-169a-4366-a050-4b48a6595005.silk` 试一下 url 能否访问

按照我对wechaty的在“协议反向工程”服务器端进行协议解密的设计看，拉取silk格式语音文件的功能是公网实现，而不是本机sdk，所以肯定无法访问localhost上的服务端口。

**Comment by nicholasDxy** [comment]
> > 使用的就是发文件的接口。
> 
> 我发送过去语音消息时间长度显示不对(固定5秒),一样的代码在padlocal下显示是正常的,下面是我的代码
> 
> ```
> const fileBox = FileBox.fromFile(`${fileName}.sil`);
> //fileBox.mimeType = 'audio/silk';
> fileBox.metadata = {
>   duration: voiceLength,
>   voiceLength: voiceLength
> };
> await receiver.say(fileBox);
> ```



> > 使用的就是发文件的接口。
> 
> 我发送过去语音消息时间长度显示不对(固定5秒),一样的代码在padlocal下显示是正常的,下面是我的代码
> 
> ```
> const fileBox = FileBox.fromFile(`${fileName}.sil`);
> //fileBox.mimeType = 'audio/silk';
> fileBox.metadata = {
>   duration: voiceLength,
>   voiceLength: voiceLength
> };
> await receiver.say(fileBox);
> ```

你好,想请教下你是如何生成silk文件的呢,是将mp3转化为silk文件吗

**Comment by hejuntt1014** [comment]
> > > 使用的就是发文件的接口。
> > 
> > 
> > 我发送过去语音消息时间长度显示不对(固定5秒),一样的代码在padlocal下显示是正常的,下面是我的代码
> > ```
> > const fileBox = FileBox.fromFile(`${fileName}.sil`);
> > //fileBox.mimeType = 'audio/silk';
> > fileBox.metadata = {
> >   duration: voiceLength,
> >   voiceLength: voiceLength
> > };
> > await receiver.say(fileBox);
> > ```
> 
> > > 使用的就是发文件的接口。
> > 
> > 
> > 我发送过去语音消息时间长度显示不对(固定5秒),一样的代码在padlocal下显示是正常的,下面是我的代码
> > ```
> > const fileBox = FileBox.fromFile(`${fileName}.sil`);
> > //fileBox.mimeType = 'audio/silk';
> > fileBox.metadata = {
> >   duration: voiceLength,
> >   voiceLength: voiceLength
> > };
> > await receiver.say(fileBox);
> > ```
> 
> 你好,想请教下你是如何生成silk文件的呢,是将mp3转化为silk文件吗

使用[silk-sdk](https://github.com/laysent/silk-sdk)
```
async function silkToPcm(fileName: string) {
  return new Promise<string>((resolve, reject) => {
    const readStream = fs.createReadStream(fileName);
    const pcmFileName = fileName.replace(/\.silk$|\.sil$/, '.pcm');
    const writeStream = fs.createWriteStream(pcmFileName);

    readStream
      .pipe(silk.decode({ tencent: true }))
      .pipe(writeStream)
      .on('finish', () => {
        // console.log('File conversion completed.');
        resolve(pcmFileName);
      })
      .on('error', (err: any) => {
        console.log('An error occurred during file conversion.');
        reject(err);
      });
  });
}
```

**Comment by nicholasDxy** [comment]
谢谢你!

**Comment by nicholasDxy** [comment]
> > > > 使用的就是发文件的接口。
> > > 
> > > 
> > > 我发送过去语音消息时间长度显示不对(固定5秒),一样的代码在padlocal下显示是正常的,下面是我的代码
> > > ```
> > > const fileBox = FileBox.fromFile(`${fileName}.sil`);
> > > //fileBox.mimeType = 'audio/silk';
> > > fileBox.metadata = {
> > >   duration: voiceLength,
> > >   voiceLength: voiceLength
> > > };
> > > await receiver.say(fileBox);
> > > ```
> > 
> > 
> > > > 使用的就是发文件的接口。
> > > 
> > > 
> > > 我发送过去语音消息时间长度显示不对(固定5秒),一样的代码在padlocal下显示是正常的,下面是我的代码
> > > ```
> > > const fileBox = FileBox.fromFile(`${fileName}.sil`);
> > > //fileBox.mimeType = 'audio/silk';
> > > fileBox.metadata = {
> > >   duration: voiceLength,
> > >   voiceLength: voiceLength
> > > };
> > > await receiver.say(fileBox);
> > > ```
> > 
> > 
> > 你好,想请教下你是如何生成silk文件的呢,是将mp3转化为silk文件吗
> 
> 使用[silk-sdk](https://github.com/laysent/silk-sdk)
> 
> ```
> async function silkToPcm(fileName: string) {
>   return new Promise<string>((resolve, reject) => {
>     const readStream = fs.createReadStream(fileName);
>     const pcmFileName = fileName.replace(/\.silk$|\.sil$/, '.pcm');
>     const writeStream = fs.createWriteStream(pcmFileName);
> 
>     readStream
>       .pipe(silk.decode({ tencent: true }))
>       .pipe(writeStream)
>       .on('finish', () => {
>         // console.log('File conversion completed.');
>         resolve(pcmFileName);
>       })
>       .on('error', (err: any) => {
>         console.log('An error occurred during file conversion.');
>         reject(err);
>       });
>   });
> }
> ```

谢谢!

**Comment by nicholasDxy** [comment]
> > > > 使用的就是发文件的接口。
> > > 
> > > 
> > > 我发送过去语音消息时间长度显示不对(固定5秒),一样的代码在padlocal下显示是正常的,下面是我的代码
> > > ```
> > > const fileBox = FileBox.fromFile(`${fileName}.sil`);
> > > //fileBox.mimeType = 'audio/silk';
> > > fileBox.metadata = {
> > >   duration: voiceLength,
> > >   voiceLength: voiceLength
> > > };
> > > await receiver.say(fileBox);
> > > ```
> > 
> > 
> > > > 使用的就是发文件的接口。
> > > 
> > > 
> > > 我发送过去语音消息时间长度显示不对(固定5秒),一样的代码在padlocal下显示是正常的,下面是我的代码
> > > ```
> > > const fileBox = FileBox.fromFile(`${fileName}.sil`);
> > > //fileBox.mimeType = 'audio/silk';
> > > fileBox.metadata = {
> > >   duration: voiceLength,
> > >   voiceLength: voiceLength
> > > };
> > > await receiver.say(fileBox);
> > > ```
> > 
> > 
> > 你好,想请教下你是如何生成silk文件的呢,是将mp3转化为silk文件吗
> 
> 使用[silk-sdk](https://github.com/laysent/silk-sdk)
> 
> ```
> async function silkToPcm(fileName: string) {
>   return new Promise<string>((resolve, reject) => {
>     const readStream = fs.createReadStream(fileName);
>     const pcmFileName = fileName.replace(/\.silk$|\.sil$/, '.pcm');
>     const writeStream = fs.createWriteStream(pcmFileName);
> 
>     readStream
>       .pipe(silk.decode({ tencent: true }))
>       .pipe(writeStream)
>       .on('finish', () => {
>         // console.log('File conversion completed.');
>         resolve(pcmFileName);
>       })
>       .on('error', (err: any) => {
>         console.log('An error occurred during file conversion.');
>         reject(err);
>       });
>   });
> }
> ```

打扰下大佬,这个silk-sdk我试了下现在可以把mp3音频转换成silk发送语音了但是有概率生成的silk语音发送到微信播放不出来,上面你回复的代码是decode的代码, 想请教下这里的encode代码应该怎么写的呀,我现在是用的他文档中的方法生成的silk:
```python
const fs = require('fs');
const {
    decode,
    encode,
    compare,
} = require('silk-sdk');
fs.createReadStream('speech.mp3')
    .pipe(encode({ quiet: true, tencent: true, fsHz: 16000, rate: 16, bit: 16}))
    .pipe(fs.createWriteStream('speech.silk'))
    .on('error', (err: any) => {
        console.log('An error occurred during file conversion.');
    });
```

**Comment by hejuntt1014** [comment]
> > > > > 使用的就是发文件的接口。
> > > > 
> > > > 
> > > > 我发送过去语音消息时间长度显示不对(固定5秒),一样的代码在padlocal下显示是正常的,下面是我的代码
> > > > ```
> > > > const fileBox = FileBox.fromFile(`${fileName}.sil`);
> > > > //fileBox.mimeType = 'audio/silk';
> > > > fileBox.metadata = {
> > > >   duration: voiceLength,
> > > >   voiceLength: voiceLength
> > > > };
> > > > await receiver.say(fileBox);
> > > > ```
> > > 
> > > 
> > > > > 使用的就是发文件的接口。
> > > > 
> > > > 
> > > > 我发送过去语音消息时间长度显示不对(固定5秒),一样的代码在padlocal下显示是正常的,下面是我的代码
> > > > ```
> > > > const fileBox = FileBox.fromFile(`${fileName}.sil`);
> > > > //fileBox.mimeType = 'audio/silk';
> > > > fileBox.metadata = {
> > > >   duration: voiceLength,
> > > >   voiceLength: voiceLength
> > > > };
> > > > await receiver.say(fileBox);
> > > > ```
> > > 
> > > 
> > > 你好,想请教下你是如何生成silk文件的呢,是将mp3转化为silk文件吗
> > 
> > 
> > 使用[silk-sdk](https://github.com/laysent/silk-sdk)
> > ```
> > async function silkToPcm(fileName: string) {
> >   return new Promise<string>((resolve, reject) => {
> >     const readStream = fs.createReadStream(fileName);
> >     const pcmFileName = fileName.replace(/\.silk$|\.sil$/, '.pcm');
> >     const writeStream = fs.createWriteStream(pcmFileName);
> > 
> >     readStream
> >       .pipe(silk.decode({ tencent: true }))
> >       .pipe(writeStream)
> >       .on('finish', () => {
> >         // console.log('File conversion completed.');
> >         resolve(pcmFileName);
> >       })
> >       .on('error', (err: any) => {
> >         console.log('An error occurred during file conversion.');
> >         reject(err);
> >       });
> >   });
> > }
> > ```
> 
> 谢谢!

mp3转silk我没测试过,你试试pcm转吧,需要注意码率要一致
```
ffmpeg -y -i ${fileName} -acodec pcm_s16le -f s16le -ac 1 -ar 24000 ${pmcFileName}
```

```
export async function pcmToSilk(fileName: string) {
  return new Promise<string>((resolve, reject) => {
    const silFileName = fileName.replace('.pcm', '.sil');
    const readStream = fs.createReadStream(fileName);
    const writeStream = fs.createWriteStream(silFileName);

    readStream
      .pipe(silk.encode({ tencent: true }))
      .pipe(writeStream)
      .on('finish', () => {
        // console.log('File conversion completed.');
        resolve(silFileName);
      })
      .on('error', (err: any) => {
        console.log('An error occurred during file conversion.');
        reject(err);
      });
  });
}
```

**Comment by hejuntt1014** [comment]
> > > > > 使用的就是发文件的接口。
> > > > 
> > > > 
> > > > 我发送过去语音消息时间长度显示不对(固定5秒),一样的代码在padlocal下显示是正常的,下面是我的代码
> > > > ```
> > > > const fileBox = FileBox.fromFile(`${fileName}.sil`);
> > > > //fileBox.mimeType = 'audio/silk';
> > > > fileBox.metadata = {
> > > >   duration: voiceLength,
> > > >   voiceLength: voiceLength
> > > > };
> > > > await receiver.say(fileBox);
> > > > ```
> > > 
> > > 
> > > > > 使用的就是发文件的接口。
> > > > 
> > > > 
> > > > 我发送过去语音消息时间长度显示不对(固定5秒),一样的代码在padlocal下显示是正常的,下面是我的代码
> > > > ```
> > > > const fileBox = FileBox.fromFile(`${fileName}.sil`);
> > > > //fileBox.mimeType = 'audio/silk';
> > > > fileBox.metadata = {
> > > >   duration: voiceLength,
> > > >   voiceLength: voiceLength
> > > > };
> > > > await receiver.say(fileBox);
> > > > ```
> > > 
> > > 
> > > 你好,想请教下你是如何生成silk文件的呢,是将mp3转化为silk文件吗
> > 
> > 
> > 使用[silk-sdk](https://github.com/laysent/silk-sdk)
> > ```
> > async function silkToPcm(fileName: string) {
> >   return new Promise<string>((resolve, reject) => {
> >     const readStream = fs.createReadStream(fileName);
> >     const pcmFileName = fileName.replace(/\.silk$|\.sil$/, '.pcm');
> >     const writeStream = fs.createWriteStream(pcmFileName);
> > 
> >     readStream
> >       .pipe(silk.decode({ tencent: true }))
> >       .pipe(writeStream)
> >       .on('finish', () => {
> >         // console.log('File conversion completed.');
> >         resolve(pcmFileName);
> >       })
> >       .on('error', (err: any) => {
> >         console.log('An error occurred during file conversion.');
> >         reject(err);
> >       });
> >   });
> > }
> > ```
> 
> 打扰下大佬,这个silk-sdk我试了下现在可以把mp3音频转换成silk发送语音了但是有概率生成的silk语音发送到微信播放不出来,上面你回复的代码是decode的代码, 想请教下这里的encode代码应该怎么写的呀,我现在是用的他文档中的方法生成的silk:
> 
> ```python
> const fs = require('fs');
> const {
>     decode,
>     encode,
>     compare,
> } = require('silk-sdk');
> fs.createReadStream('speech.mp3')
>     .pipe(encode({ quiet: true, tencent: true, fsHz: 16000, rate: 16, bit: 16}))
>     .pipe(fs.createWriteStream('speech.silk'))
>     .on('error', (err: any) => {
>         console.log('An error occurred during file conversion.');
>     });
> ```

mp3转silk我没测试过,你试试pcm转吧,需要注意码率要一致
```
ffmpeg -y -i ${fileName} -acodec pcm_s16le -f s16le -ac 1 -ar 24000 ${pmcFileName}
```

```
export async function pcmToSilk(fileName: string) {
  return new Promise<string>((resolve, reject) => {
    const silFileName = fileName.replace('.pcm', '.sil');
    const readStream = fs.createReadStream(fileName);
    const writeStream = fs.createWriteStream(silFileName);

    readStream
      .pipe(silk.encode({ tencent: true }))
      .pipe(writeStream)
      .on('finish', () => {
        // console.log('File conversion completed.');
        resolve(silFileName);
      })
      .on('error', (err: any) => {
        console.log('An error occurred during file conversion.');
        reject(err);
      });
  });
}
```
