### ISSUE TITLE
[FEAT]WorkPro:怎么通过一些途径输入二维码

### ISSUE THREAD

**Issue by myllq** [wechaty/puppet-service-providers#333]
console.log(`receive verify-code event, id: ${id}, message: ${message}, scene: ${types.VerifyCodeScene[scene]} status: ${types.VerifyCodeStatus[status]}`)
    const verifyCode = '123456' // 通过一些途径输入验证码

**Comment by myllq** [comment]
03:03:07 INFO PuppetService received grpc event EVENT_TYPE_VERIFY_CODE on Thu Dec 14 2023 03:03:07 GMT+0000 (Coordinated Universal Time), content: "{\"id\":\"xxxxx\",\"message\":\"请输入企业微信手机端展示的验证码，以继续登录\",\"scene\":1,\"status\":1}", seq: 0, timestamp: 1702522987448
receive verify-code event, id: xxxxxx, message: 请输入企业微信手机端展示的验证码，以继续登录, scene: LOGIN status: WAITING

**Comment by myllq** [comment]
从数据库动态获取到验证码了，但是一直提示错误，是数字，没有空格和换行

11:37:27 INFO PuppetService received grpc event EVENT_TYPE_VERIFY_CODE on Thu Dec 14 2023 11:37:27 GMT+0800 (中国标准时间), content: "{\"id\":\"xxxxxx\",\"message\":\"请输入企业微信手机端展示的验证码，以继续登录\",\"scene\":1,\"status\":1}", seq: 0, timestamp: 1702525047114
receive verify-code event, id: xxxxxx, message: 请输入企业微信手机端展示的验证码，以继续登录, scene: LOGIN status: WAITING
========
484670
enterVerifyCode error : {"code":13,"details":"Invalid verify code!","metadata":{"content-type":["application/grpc+proto"],"date":["Thu, 14 Dec 2023 03:44:31 GMT"],"authorization":["Wechaty undefined"]}}

**Comment by myllq** [comment]
问题解决了，通过查询数据库动态获取的手机验证码，有问题的可以私信我v：jitasanshao

**Comment by majorbird-team** [comment]
Hello @myllq ,

I face the same issue. Where do you input the verification code ?
