### ISSUE TITLE
[BUG]WorkPro: 尝试扫码登录，企微被强制下线，然后提示：当前账号存在盗号/买卖号风险，请规范使用企业微信，避免账号被限制，请验证实名信息后重新登陆

### ISSUE THREAD

**Issue by cheweili** [wechaty/puppet-service-providers#337]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

**Info**

 - Platform[e.g. Windows/Mac/Linux]: 
 - Runtime version[e.g. node/JAVA]:
 - Wechaty version: 
 - Wechaty Puppet version: 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by su-chang** [comment]
这个是企微的安全机制，需要重新扫码登录。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
