### ISSUE TITLE
[FEAT]WorkPro: 获取不到外部contact的微信ID

### ISSUE THREAD

**Issue by Wangerya** [wechaty/puppet-service-providers#338]
获取不到外部contact的微信ID，怎么实现与通过微信授权获取到的信息匹配，目前能拿到昵称、头像、性别等，但是都不能确保唯一性，有什么其他字段可以与微信唯一匹配的吗

**Comment by su-chang** [comment]
可以提供数据进行举例说明么？这里提到的 `外部contact的微信ID` 是指什么？wechaty中的contact.id可以获取到788开头的微信联系人ID

**Comment by Wangerya** [comment]
> 可以提供数据进行举例说明么？这里提到的 `外部contact的微信ID` 是指什么？wechaty中的contact.id可以获取到788开头的微信联系人ID

例如拿到正在对话的个人微信联系人的信息如下：
payload: {
    address: '',
    alias: '',
    avatar: 'http://wx.qlogo.cn/mmhead/Q3auHgzwzM5ia0fia6V1HfLv6PxiazWvgpXXib4O4wJSIOQKK0a0cWYnnQ/0',
    city: '',
    corporation: '',
    coworker: false,
    description: '',
    friend: true,
    gender: 2,
    handle: 'wmJdxtaAAAIgRq3O-vHLN0NsXXxEPa8w',
    id: '7881303041005749',
    name: '💃🏻',
    phone: [],
    province: '',
    signature: '',
    star: false,
    title: 'wmJdxtaAAAIgRq3O-vHLN0NsXXxEPa8w',
    type: 1,
    weixin: 'wmJdxtaAAAIgRq3O-vHLN0NsXXxEPa8w',
    additionalInfo: '{"corpId":"1970325134026788","sCorpId":"wwc7c9f32a3160d4dc","addCustomerTime":1702811472,"status":2}',
    tags: [],
    realName: '',
    aka: ''
  },
  [Symbol(kCapture)]: false
}
我在微信公众号通过微信oauth2授权拿到了用户的openid、unionid、昵称等信息并存入我的数据库，我想要在上述获取到的payload中使用某个字段进行数据库查询，看用户是否存在。
也就是说payload的字段有没有跟我通过微信授权拿到的字段一样的，可以识别跟正在与机器人聊天的用户是否是数据库中已存在的已授权用户

**Comment by su-chang** [comment]
没有，handle这个字段对应的是externalUserId，看看你能否获取到这个。

**Comment by Wangerya** [comment]
> 没有，handle这个字段对应的是externalUserId，看看你能否获取到这个。

个人微信没加企微bot成为好友之前是没有externalUserId的。
请问contact.id获取到788开头的id是什么呀，我发现bot.Friendship.search({ phone: "xxx" })方法返回的contact也有这个id，是否意味着我只要在bot启动后维持一个ws长链接，再我另一个项目获取到用户手机号后，通过ws发送给bot然后执行bot.Friendship.search({ phone: "xxx" })方法，再将得到的id存下来作为两个项目用户验证的唯一标识

**Comment by su-chang** [comment]
这个针对少量联系人是可行的，由于search方法是有频率限制的，如果处理大量的联系人是不可行的。

**Comment by su-chang** [comment]
788开头的id是企业微信内部的id，全局唯一。

**Comment by Wangerya** [comment]
为什么调用search方法就能得到这个788开头的企业微信内部的id呀，是用的企微提供的哪个接口吗

**Comment by su-chang** [comment]
search是调用企微的搜索好友接口，搜索到的数据中就会包含企微的这种788开头的id

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
