### ISSUE TITLE
on('logout')收到回调，reason是”你正在一台新设备上使用企业微信，需通过手机企业微信扫码进行安全验证“

### ISSUE THREAD

**Issue by guangzhengyu** [wechaty/puppet-service-providers#340]
这个reason是什么情况下会触发呢？

我尝试用A手机登录并绑定token，之后用B手机登录，on('logout')回调的reason是”你已在其他设备上登录“。

不能复现”你正在一台新设备上使用企业微信，需通过手机企业微信扫码进行安全验证“

**Comment by su-chang** [comment]
这个是企微的安全验证，需要在5分钟内及时扫码登录。

**Comment by guangzhengyu** [comment]
@su-chang 
收到这条通知，应该扫描什么二维码呢？还是`on('scan')`里返回的那个二维码么？

**Comment by guangzhengyu** [comment]
> 这个是企微的安全验证，需要在5分钟内及时扫码登录。

@su-chang 另外我发现，我们一些绑定账户不会触发这个状态，其他一些会，这里有什么避免触发这种情况的最佳实践么？

**Comment by su-chang** [comment]
> @su-chang 收到这条通知，应该扫描什么二维码呢？还是`on('scan')`里返回的那个二维码么？

是的

**Comment by su-chang** [comment]
> @su-chang 另外我发现，我们一些绑定账户不会触发这个状态，其他一些会，这里有什么避免触发这种情况的最佳实践么？

新账号首次扫码登录或者异地登录会有这种问题，解决过一次后就可以了。

**Comment by guangzhengyu** [comment]
> > @su-chang 收到这条通知，应该扫描什么二维码呢？还是`on('scan')`里返回的那个二维码么？
> 
> 是的

@su-chang 发现一个情况，我看打印了日志：  
` INFO PuppetService received grpc event EVENT_TYPE_SCAN on Wed Dec 27 2023 21:36:53 GMT+0800 (China Standard Time), content: "{\"status\":2,\"qrcode\":\"https://work.weixin.qq.com/webapp/secondaryEquipment/index?bar_style_type=2&for_native=true&code=A791E2EA8C51788B7959F94FEF393769\"}", seq: 0, timestamp: 1703684213671
`
看起来是收到这个二维码，但是扫描后却报错。

同时企微的PC登录状态也没有的。

只能通过主动调用`bot.logout()`才返回平常可扫的二维码

**Comment by su-chang** [comment]
扫码后报错内容是什么？

二维码可以通过url的前缀来区分：
- 普通登录二维码  https://wx.work.weixin.qq.com/cgi-bin/crtx_auth
- 安全验证二维码  https://work.weixin.qq.com/webapp/secondaryEquipment/index

看你提供的二维码链接，确实是安全验证码。

**Comment by guangzhengyu** [comment]
> 扫码后报错内容是什么？
> 
> 二维码可以通过url的前缀来区分：
> 
> * 普通登录二维码  https://wx.work.weixin.qq.com/cgi-bin/crtx_auth
> * 安全验证二维码  https://work.weixin.qq.com/webapp/secondaryEquipment/index
> 
> 看你提供的二维码链接，确实是安全验证码。  

@su-chang 扫码后报错截图
![image](https://github.com/wechaty/puppet-supports/assets/46769446/19ff8cc4-2f54-4eb1-a7b0-89fbc23db022)

**Comment by su-chang** [comment]
按提示操作下吧，看看你手机端你的企微客户端的版本是多少，建议升级到最新版。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
