### ISSUE TITLE
在运行着的机器人偶尔会报No connection established，触发自动重启后又会报token does not exist

### ISSUE THREAD

**Issue by charleyCC** [wechaty/puppet-service-providers#342]
![image](https://github.com/wechaty/puppet-supports/assets/39627896/3872cdd4-b5b4-40ac-8eb9-999cfe68018c)
![image](https://github.com/wechaty/puppet-supports/assets/39627896/331bae23-a683-4313-8ae6-76c75068afd7)

**Comment by hcfw007** [comment]
请提供一下具体时间点？

**Comment by hcfw007** [comment]
看起来可能是遇到我们今天早上服务回滚了。

**Comment by charleyCC** [comment]
![image](https://github.com/wechaty/puppet-supports/assets/39627896/9b69cc2f-908f-4874-a85e-d6b14d15580c)
这几天都特别频繁，最近一次是今天凌晨08分的时候，之前也会有这样不稳定的情况，只是没有这几天这么频繁

**Comment by charleyCC** [comment]
![image](https://github.com/wechaty/puppet-supports/assets/39627896/42a1aaa2-2d32-4f10-8039-3edcb2b9a900)
有人能解答下不 昨晚又报错了

**Comment by binsee** [comment]
这几天晚上对服务进行了多次更新，更新时服务会暂时中断。

**Comment by billtt** [comment]
目前好像只能通过检测token not exist消息来重启服务

**Comment by charleyCC** [comment]
有办法能确保运行稳定一点吗？

**Comment by su-chang** [comment]
后续我们会控制更新频次，这种情况一般会在我们更新服务期间会遇到。

暂无反馈，关闭该issue。
