### ISSUE TITLE
await toRoom.member('群成员') 这个方法传的是群成员昵称还是备注呢

### ISSUE THREAD

**Issue by charleyCC** [wechaty/puppet-service-providers#346]
企业微信上看群成员列表看到的是改成员的群昵称是【小明】，于是我在调用await toRoom.member('小明')传的是群昵称，但是运行后发现找不到对应的成员的contact，用await toRoom.memberAll()打印所有群成员的列表发现该成员的name为【陈小明】，我要怎么确认传哪个昵称呢，是因为该成员改了昵称，然后await toRoom.memberAll()里面读取的还是缓存吗

**Comment by su-chang** [comment]
可以调用 room.sync() 同步群信息，建议登录后同步一次，之后可以定时每天固定时间同步群信息。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
