### ISSUE TITLE
[BUG]WorkPro: ERR PuppetServiceImpl grpcError() messageSendMiniProgram() rejection: 13 INTERNAL: Invalid URL

### ISSUE THREAD

**Issue by chapterBegin** [wechaty/puppet-service-providers#349]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

**Info**

 - Platform[e.g. Windows/Mac/Linux]: Windows
 - Runtime version[e.g. node/JAVA]: node
 - Wechaty version: 1.0.85
 - Wechaty Puppet version: 1.0.75

**To Reproduce**

response mini program

**Expected behavior**

normal send

**Screenshots**
![image](https://github.com/wechaty/puppet-supports/assets/32804473/b45d3773-4859-4865-a970-2fec08cb95f0)

**Additional context**

**Comment by su-chang** [comment]
请提供发送小程序所用的具体参数。看上面报错内容，是没有正确使用小程序的参数。

参考示例如下：
```ts
const miniProgram = new bot.MiniProgram({
  "appid": "GH_XXXXXX",
  "description": "XXXXXX",
  "pagePath": "PATH_PAGE",
  "thumbUrl": "IMAGE_URL",
  "title": "XXXXXXX",
  "username": "XXXXXXXXXXX"
})
```

**Comment by chapterBegin** [comment]
{'appid': 'wxcb8dba3853713da8', 'description': '美年臻选', 'pagePath': 'pagesNiwo/index.html?ad=cbd3&combinationId=573&price=1198&storeid=1002&refereeId=2300316&refereeName=小美', 'thumbKey': '019ae1d249ec6cea3718b84d4facd599', 'iconUrl': 'http://mmbiz.qpic.cn/mmbiz_png/Q09RKKiaMib139vLNx4nCafwgPO52kia16uFcnrELsWKhyQ4ddibl5F1pGgYmvbQSnuYoGpCGIZ4WPlXTjna07KW1w/640?wx_fmt=png&wxfrom=200', 'thumbUrl': '3057020100044b3049020100020481e83efd02032f7efd02046f66d83a02046585535e042430633837613864662d373138652d343566392d613166632d3066393931616438626561310204051408030201000405004c4dfd00', 'shareId': '0_wxcb8dba3853713da8_2607652b5c508ca9e4addd75b6ba43e6_1703236445_0', 'title': '2024亲情卡(新春版)1198套餐 两人同行 一人免单', 'username': 'gh_c021b6d6435b@app'}

**Comment by chapterBegin** [comment]
将小程序卡片发给企业微信账号 获得最新的json后用来发送没问题了  新的json：
`{'code': '0', 'message': 'Success', 'result': {'role': 'assistant', 'content': '发你的链接里下单就可以啦~', 'imgUrl': None, 'imgUrlList': None, 'wechatUrls': "{'appid': 'gh_c021b6d6435b@app', 'description': '2024亲情卡(新春版)1198套餐 两人同行 一人 免单', 'pagePath': 'pagesNiwo/index.html?ad=cbd3&combinationId=573&price=1198&storeid=1002&refereeId=2300316&refereeName=小美', 'thumbKey': '', 'iconUrl': 'http://mmbiz.qpic.cn/mmbiz_png/Q09RKKiaMib139vLNx4nCafwgPO52kia16uFcnrELsWKhyQ4ddibl5F1pGgYmvbQSnuYoGpCGIZ4WPlXTjna07KW1w/640?wx_fmt=png&wxfrom=200', 'thumbUrl': 'https://workpro.s3.cn-northwest-1.amazonaws.com.cn/link_msg/70a856b7-0ef1-4b65-80f5-ae5b9c3a28f4/1ccdd104-6103-48ff-a74a-e1147e3b07ae.jpg', 'shareId': '', 'title': '美年臻选', 'username': 'wxcb8dba3853713da8'}"}}`
跟个人微信的json有差别

**Comment by su-chang** [comment]
是的，企微和个微的数据有差异。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
