### ISSUE TITLE
FileBox没有fromUrl方法

### ISSUE THREAD

**Issue by wailliai** [wechaty/puppet-service-providers#350]
@juzi/wechaty version 1.0.87

const { FileBox } = require('@juzi/wechaty')
sendText = FileBox.fromUrl(path)

按照文档示例，使用FileBox.fromUrl将文件转发给其他人时，提示错误“TypeError:Cannot read properties of undefined (reading ’fromUrl')“，@juzi/wechaty中貌似也没有FileBox类

![image](https://github.com/wechaty/puppet-supports/assets/132058144/82948282-ebb5-4797-a244-8989fbde24f0)

**Comment by su-chang** [comment]
需要安装依赖包

示例代码如下：
```ts
import { FileBox, FileBoxInterface } from 'file-box'

const fileBox = FileBox.fromFile(`./resources/test.pdf`)
const msg = await message.say(fileBox)
```

**Comment by wailliai** [comment]
> 需要安装依赖包
> 
> 示例代码如下：
> 
> ```ts
> import { FileBox, FileBoxInterface } from 'file-box'
> 
> const fileBox = FileBox.fromFile(`./resources/test.pdf`)
> const msg = await message.say(fileBox)
> ```

正解，已解决， 感谢
