### ISSUE TITLE
[BUG]WorkPro: 最近Grpc error也太多了

### ISSUE THREAD

**Issue by tentacle-pro** [wechaty/puppet-service-providers#353]
日志里不停的出：
> 12:16:41 WARN PuppetWatchdogAgent start() reset() reason: {"data":"onGrpcStreamEvent(EVENT_TYPE_DONG)","timeoutMilliseconds":60000}
> Bot error: GError: WatchdogAgent reset: lastFood: "{"data":"onGrpcStreamEvent(EVENT_TYPE_DONG)","timeoutMilliseconds":60000}"
>     at Watchdog.reset (/root/x/api/node_modules/@juzi/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
>     at Watchdog.emit (node:events:514:28)
>     at Watchdog.emit (node:domain:488:12)
>     at Timeout._onTimeout (/root/x/api/node_modules/watchdog/src/watchdog.ts:115:12)
>     at listOnTimeout (node:internal/timers:573:17)
>     at processTimers (node:internal/timers:514:7) {
>   code: 2,
>   details: 'Error: WatchdogAgent reset: lastFood: "{"data":"onGrpcStreamEvent(EVENT_TYPE_DONG)","timeoutMilliseconds":60000}"\n' +
>     '    at Watchdog.reset (/root/x/api/node_modules/@juzi/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
>     '    at Watchdog.emit (node:events:514:28)\n' +
>     '    at Watchdog.emit (node:domain:488:12)\n' +
>     '    at Timeout._onTimeout (/root/x/api/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
>     '    at listOnTimeout (node:internal/timers:573:17)\n' +
>     '    at processTimers (node:internal/timers:514:7)'
> }

**Comment by su-chang** [comment]
尝试重连下服务看看？如果仍有问题，麻烦提供下关键日志的上下文。
