### ISSUE TITLE
[BUG]WorkPro:WorkproErrorCode: 23060, the contact: xxx has deleted the bot 这个异常导致程序退出

### ISSUE THREAD

**Issue by wailliai** [wechaty/puppet-service-providers#354]
try {
            const contact = await bot.Contact.find({ id: id });
            contact.say(msg);
            return "发送成功"
        } catch (e) {
            log.info('sendMessage Exception:%s,%s', e.code, e.message)
            return "发送失败，" + e.code
        }
代码如上，当id不存在或非好友时，抛出WorkproErrorCode: 23060异常，导致程序退出，好像捕获不到该异常
![image](https://github.com/wechaty/puppet-supports/assets/132058144/90289588-90c2-4d66-a7e7-06bcd61a1370)

**Comment by su-chang** [comment]
promise方法需要await，再试下看看，或者 .cache 试下。

**Comment by wailliai** [comment]
有加await,在catch 里面捕获不到,换下面的写法也捕获不到..
bot.Contact.find({ id: id })
                .then(contact => {
                    // 处理成功情况
                    contact.say(msg);
                    return "发送成功"
                })
                .catch(error => {
                    // 处理失败情况
                    log.info('sendMessage Exception:%s',error)
                    return "发送失败"
                });

**Comment by su-chang** [comment]
额。。 报错的函数是 `contact.say(msg)` 这里。注意看下错误栈哟

**Comment by wailliai** [comment]
啊  大意了  感谢..
