### ISSUE TITLE
2024-01-16 17:50:29,929 - Wechaty - ERROR - internal error <>

### ISSUE THREAD

**Issue by Jicming** [wechaty/puppet-service-providers#355]
在运行wechaty官方例子时，总会报这个问题，导致二维码不断刷新，并有时候不能正常显示

```
## Question
from wechaty import Wechaty
import asyncio
import os

os.environ["WECHATY_PUPPET"] = 'wechaty-puppet-service'
os.environ["WECHATY_PUPPET_SERVICE_TOKEN"] = '我的token'



async def main():
    bot = Wechaty()
    bot.on('scan', lambda status, qrcode, data: print('Scan QR Code to login: {}\nhttps://wechaty.js.org/qrcode/{}'.format(status, qrcode)))
    bot.on('login', lambda user: print('User {} logged in'.format(user)))
    bot.on('message', lambda message: print('Message: {}'.format(message)))
    await bot.start()

asyncio.run(main())
```

**Comment by su-chang** [comment]
尝试用typescript试试看是否有一样的问题？

**Comment by Jicming** [comment]
可能没有，是现在对python的不是很支持吗&nbsp;


守望者
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月16日(星期二) 晚上6:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wechaty/puppet-supports] 2024-01-16 17:50:29,929 - Wechaty - ERROR - internal error <&gt; (Issue #355)





 
尝试用typescript试试看是否有一样的问题？

**Comment by Jicming** [comment]
使用python这样，没有使用其他的解释器，而且可能是因为报错刷新的问题，我使用的是企业微信的token, 使用企业微信扫描时也没有登录提示

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
