### ISSUE TITLE
[BUG]WorkPro: 调用msg.room().say()，但是微信端消息没有显示消息

### ISSUE THREAD

**Issue by Norwa9** [wechaty/puppet-service-providers#356]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

调用msg.room().say()，但是微信端消息没有显示消息，但是换一个企微账号登录后却能在微信端发出消息。
请问是企微账号被微信限制了吗？应该如何排查

**Info**

 - Platform[e.g. Windows/Mac/Linux]: Linux
 - Runtime version[e.g. node/JAVA]: node v20.10.0
 - Wechaty version: 1.0.66
 - Wechaty Puppet version: 

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/wechaty/puppet-supports/assets/59719098/db73e0a3-749b-4ace-8284-387597f97a0d)
已调用grpc请求发送消息，但是微信端没有显示这条

**Additional context**

**Comment by su-chang** [comment]
发不出去的账号在手机端可以正常往这个群聊里发送消息么？

上面结果看起来是拿到了企微服务端推送的消息ID，这种情况下，一般是发送成功了。

**Comment by Norwa9** [comment]
> 发不出去的账号在手机端可以正常往这个群聊里发送消息么？
> 
> 上面结果看起来是拿到了企微服务端推送的消息ID，这种情况下，一般是发送成功了。

还真是账号异常了，目前这个机器人只是在两个群聊里被使用。。请问这种情况应该如何解决，如何规避呢。

**Comment by su-chang** [comment]
注意养号，注意别太频繁操作，每个账号的权重不太一样，需要根据账号情况来调整。
