### ISSUE TITLE
[FEAT]WorkPro:为什么我登录了以后过了没多久就会被登出呢

### ISSUE THREAD

**Issue by ahujack** [wechaty/puppet-service-providers#358]
![1706002460333](https://github.com/wechaty/puppet-supports/assets/4875636/69eaf0cc-a97c-4358-9440-3bcf41ef87f0)

如截图所示，我登录大概20分钟以后会登出，是不是我需要把手机端的企业微信退出啊？

**Comment by su-chang** [comment]
这个是企微安全验证，需要在2分钟内及时扫码登录，验证后即可不会再掉线了。

url链接中包含 secondaryEquipment 这个表示为验证二维码。

**Comment by yangsai7** [comment]
关键是我如何才知道这个二次验证的二维码什么时候弹出

**Comment by yangsai7** [comment]
> 这个是企微安全验证，需要在2分钟内及时扫码登录，验证后即可不会再掉线了。
> 
> url链接中包含 secondaryEquipment 这个表示为验证二维码。
关键是我如何才知道这个二次验证的二维码什么时候弹出？

**Comment by yangsai7** [comment]
> 这个是企微安全验证，需要在2分钟内及时扫码登录，验证后即可不会再掉线了。
> 
> url链接中包含 secondaryEquipment 这个表示为验证二维码。

关键是我如何才知道这个二次验证的二维码什么时候弹出

**Comment by hcfw007** [comment]
可以监听logout事件做提醒
