### ISSUE TITLE
PadLocal: Apply for new token

### ISSUE THREAD

**Issue by Yinetsrl** [wechaty/puppet-service-providers#36]
## Wechaty Puppet PadLocal

- Repo: <https://github.com/padlocal/wechaty-puppet-padlocal>
- Provider: [PadLocal](https://github.com/padlocal)
- Support: <https://github.com/padlocal/wechaty-puppet-padlocal/issues>

## Question
I need a token for my first use, thank you

**Comment by padlocal** [comment]
@Yinetsrl Can you send an email to oxddoxdd@gmail.com? Then I can send you related materials.
