### ISSUE TITLE
[BUG]WorkPro:企业微信主体名称修改后，通过wechaty.currentUser.corporation()方法获取到的主体信息还是旧的，如何获得新的主体信息？

### ISSUE THREAD

**Issue by ghost** [wechaty/puppet-service-providers#360]
企业微信通过官方后台修改了主体名称，在wechaty的onlogin事件中，通过bot.currentUser.corporation()方法获取到的主体信息还是旧的，如何获得最新的主体名称？

**Comment by hcfw007** [comment]
如果是在运行中修改，可以尝试在代码中用bot.currentUser.sync()更新一下信息，看看能不能获取到最新的。

如果是重启后的行为，可以尝试删除~/.wechaty（默认缓存路径）再启动

**Comment by ghost** [comment]
> 如果是在运行中修改，可以尝试在代码中用bot.currentUser.sync()更新一下信息，看看能不能获取到最新的。
> 
> 如果是重启后的行为，可以尝试删除~/.wechaty（默认缓存路径）再启动

您说的两种方法均使用过，获取的还是旧的主体信息。
1、我在bot.currentUser.corporation()之前，先调用了 bot.currentUser.sync()，取到的是旧主体信息
2、我停止了bot，然后手动删除了~/.wechaty目录内的所有文件和文件夹，再启动bot，获取到的依然是旧主体信息

**Comment by hcfw007** [comment]
可以提供下token后6位，我查下底层获取到的主体信息

**Comment by ghost** [comment]
> 可以提供下token后6位，我查下底层获取到的主体信息

245781

**Comment by hcfw007** [comment]
这个已经过期了，如果你还需要试用，我可以给你延长一下时间来继续测试。

**Comment by hcfw007** [comment]
无后续反馈，问题关闭。
