### ISSUE TITLE
WorkPro: token does not exist

### ISSUE THREAD

**Issue by Emirateyang** [wechaty/puppet-service-providers#361]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

use windows local environment

set WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true
set WECHATY_PUPPET_SERVICE_AUTHORITY=token-service-discovery-test.juzibot.com
set WECHATY_SERVICE_DISCOVERY_ENDPOINT=https://token-service-discovery-test.juzibot.com

after npm start

it got token does not exist

Wechaty service discovery / resolution failed for target wechaty://api.chatie.io/puppet_workpro_XXXXXX

why the endpoint still api.chatie.io, how can i change it, I use the trial token, thx

**Info**

 - Platform[e.g. Windows/Mac/Linux]:  Windows
 - Runtime version[e.g. node/JAVA]: Node 16.20
 - Wechaty version:  1.18.1
 - Wechaty Puppet version: 

Use the code clone from https://github.com/wechaty/getting-started 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hcfw007** [comment]
Your log

> Wechaty service discovery / resolution failed for target wechaty://api.chatie.io/puppet_workpro_XXXXXX

shows that it's still using the community discover endpoint api.chatie.io.

You can add the line `console.log(process.env.WECHATY_PUPPET_SERVICE_AUTHORITY)`  in your code to see if you set your env correctly.

You can also provide the lase 6 characters of your token and I can changed back to api.chatie.io and extend some trial time for you.

**Comment by Emirateyang** [comment]
@hcfw007 
really, thank you so much, i just need the verify the functionality, the last 6 characters of my token is 993eac
btw, if i use the long term token when company making the decision, the endpoint is still the  api.chatie.io?

**Comment by hcfw007** [comment]
> @hcfw007 really, thank you so much, i just need the verify the functionality, the last 6 characters of my token is 993eac btw, if i use the long term token when company making the decision, the endpoint is still the api.chatie.io?

done.

Our private discover service is more sound and stable. So if you sue the long term token, I'll suggest you to use the private discover service.

**Comment by Emirateyang** [comment]
@hcfw007 thank you. But when I get started, and scan the qrcode, it get "新设备登录提醒",so i think the function is not work correctly in 社区版.
I am sorry,  it would be possible to change my token to token-service-discovery-test.juzibot.com, I fixed the environment.

**Comment by hcfw007** [comment]
The new device alert will trigger no matter which discover service you use. It's a security mech introduced by wecom.

**Comment by lizihao001** [comment]
本地运行不了 在docker上出现 WECHATY_PUPPET_SERVICE_TOKEN not found的问题 望解惑
![1](https://github.com/wechaty/puppet-supports/assets/155125269/59a8a667-5d23-498c-a1c7-cf9c4f10fc9b)

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
