### ISSUE TITLE
WXWork:登录企业微信。进行扫码、扫码之后需要输入验证码、输入验证码之后一直提示验证码错误 三次之后就重新扫码  望大佬求解

### ISSUE THREAD

**Issue by lizihao001** [wechaty/puppet-service-providers#362]
Please make sure you have read the [Wechaty Puppet Service: WXWork](https://wechaty.js.org/docs/puppet-services/wxwork) from Wechaty Official Website before you continue writting this issue.
运行index.ts 
首先输入
export WECHATY_PUPPET_SERVICE_AUTHORITY=token-service-discovery-test.juzibot.com
其次
ts-node index.ts
1：可以提供一个docker拉取wechaty镜像的实例嘛
## Question

![1706768954693](https://github.com/wechaty/puppet-supports/assets/155125269/df9e3c57-81c5-4004-8dde-cb7d44669541)

**Comment by lizihao001** [comment]
![1706768954693](https://github.com/wechaty/puppet-supports/assets/155125269/422aaaf7-a092-4170-9410-2e442cc00a4d)

**Comment by su-chang** [comment]
@lizihao001 参考下这个 https://github.com/wechaty/puppet-supports/issues/267

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
