### ISSUE TITLE
[BUG]WorkPro: 【token-service-discovery-test.juzibot.com】报错无法登录

### ISSUE THREAD

**Issue by xuwancheng** [wechaty/puppet-service-providers#364]
我是解决登录验证码的问题的，参阅了这个帖子【https://github.com/wechaty/puppet-supports/issues/267】，由于之前的稳定性问题，我的一批token使用的是token-service-discovery-test.juzibot.com，于是我增加了authority的设定，如下：
const bot = WechatyBuilder.build({
  puppet: '@juzi/wechaty-puppet-service',
  puppetOptions: {
    token,
    authority:'token-service-discovery-test.juzibot.com',
    tls: {
      disable: true
    }
  }
})
但是运行npm start 的时候，系统报错，如下，请问该如何处理？
14:34:35 INFO PuppetSkeleton start()
node_modules/brolog/dist/cjs/src/brolog.js:193
14:34:35 INFO PuppetService start() instanciating GrpcManager ...
node_modules/brolog/dist/cjs/src/brolog.js:193
14:34:35 INFO PuppetService start() instanciating GrpcManager ... done
node_modules/brolog/dist/cjs/src/brolog.js:193
14:34:35 INFO PuppetService start() setting up bridge grpc event stream ...
node_modules/brolog/dist/cjs/src/brolog.js:193
14:34:35 INFO PuppetService start() setting up bridge grpc event stream ... done
node_modules/brolog/dist/cjs/src/brolog.js:193
14:34:35 INFO PuppetService start() starting grpc manager...
node_modules/brolog/dist/cjs/src/brolog.js:193
14:34:35 WARN last event was 1708238075.123 seconds ago, will not request event cache 
node_modules/brolog/dist/cjs/src/brolog.js:188
14:34:35 WARN GrpcManager initClient() TLS: disabled (INSECURE)
node_modules/brolog/dist/cjs/src/brolog.js:188
14:34:35 INFO GrpcManager startStream() connecting event stream with account undefined and seq undefined
node_modules/brolog/dist/cjs/src/brolog.js:193
D:\P-WeRobot\00.LoginDemo\node_modules\@grpc\grpc-js\src\subchannel-address.ts:40
    return 'port' in address;
               ^
c:\Users\wancheng\AppData\Roaming\npm\node_modules\ts-node\node_modules\@cspotcode\source-map-support\source-map-support.js:590
TypeError: Cannot use 'in' operator to search for 'port' in undefined
    at isTcpSubchannelAddress (D:\P-WeRobot\00.LoginDemo\node_modules\@grpc\grpc-js\src\subchannel-address.ts:40:16)
    at interleaveAddressFamilies (D:\P-WeRobot\00.LoginDemo\node_modules\@grpc\grpc-js\src\load-balancer-pick-first.ts:145:27)
    at PickFirstLoadBalancer.updateAddressList (D:\P-WeRobot\00.LoginDemo\node_modules\@grpc\grpc-js\src\load-balancer-pick-first.ts:520:25)
    at ChildLoadBalancerHandler.updateAddressList (D:\P-WeRobot\00.LoginDemo\node_modules\@grpc\grpc-js\src\load-balancer-child-handler.ts:137:19)
    at onSuccessfulResolution (D:\P-WeRobot\00.LoginDemo\node_modules\@grpc\grpc-js\src\resolving-load-balancer.ts:298:34)
    at processTicksAndRejections (node:internal/process/task_queues:86:22)

**Comment by xuwancheng** [comment]
可以回复一下怎么解决吗，谢谢了！

**Comment by mojo-bo-coder** [comment]
之前运行还没有问题，重启了一下就不行了
遇到了相同的报错
`> workpro-getting-started@1.0.0 start
> ts-node server.ts

Server is running on port 3000
16:42:38 INFO PuppetSkeleton start()
16:42:38 INFO PuppetService start() instanciating GrpcManager ...
16:42:38 INFO PuppetService start() instanciating GrpcManager ... done
16:42:38 INFO PuppetService start() setting up bridge grpc event stream ...
16:42:38 INFO PuppetService start() setting up bridge grpc event stream ... done
16:42:38 INFO PuppetService start() starting grpc manager...
16:42:38 WARN last event was 31071.293 seconds ago, will not request event cache 
16:42:38 WARN GrpcManager initClient() TLS: disabled (INSECURE)
16:42:38 INFO GrpcManager startStream() connecting event stream with account 1688853261735552 and seq undefined
/home/ubuntu/wechatagent/node_modules/@grpc/grpc-js/src/subchannel-address.ts:40
  return 'port' in address;
               ^
TypeError: Cannot use 'in' operator to search for 'port' in undefined
    at isTcpSubchannelAddress (/home/ubuntu/wechatagent/node_modules/@grpc/grpc-js/src/subchannel-address.ts:40:16)
    at interleaveAddressFamilies (/home/ubuntu/wechatagent/node_modules/@grpc/grpc-js/src/load-balancer-pick-first.ts:145:27)
    at PickFirstLoadBalancer.updateAddressList (/home/ubuntu/wechatagent/node_modules/@grpc/grpc-js/src/load-balancer-pick-first.ts:520:25)
    at ChildLoadBalancerHandler.updateAddressList (/home/ubuntu/wechatagent/node_modules/@grpc/grpc-js/src/load-balancer-child-handler.ts:137:19)
    at onSuccessfulResolution (/home/ubuntu/wechatagent/node_modules/@grpc/grpc-js/src/resolving-load-balancer.ts:298:34)
    at processTicksAndRejections (node:internal/process/task_queues:85:22)
`

**Comment by mojo-bo-coder** [comment]
补充下依赖
`   "@juzi/wechaty": "^1.0.65",
    "@juzi/wechaty-puppet": "^1.0.61",
    "@juzi/wechaty-puppet-service": "^1.0.69",`

**Comment by mojo-bo-coder** [comment]
> 可以回复一下怎么解决吗，谢谢了！

好像是因为token没有下线不能被再次使用。貌似是BUG

**Comment by hcfw007** [comment]
![img_v3_0287_b1324062-75b8-401d-ab1f-c680c41dd14g](https://github.com/wechaty/puppet-supports/assets/13669999/dbdec54f-9225-4f91-9d34-359782b4c36a)

@groc/grpc-js包读地址的方法有点变化，目前还不清楚这是他们的bug还是升级后有相关逻辑变化。

有一个简单的临时解决办法

修改 node_modules/@grpc/grpc-js/build/src/load-balancer-pick-first.js的411行

从 
const rawAddressList = [].concat(...endpointList.map(endpoint => endpoint.addresses));
改为
const rawAddressList = endpointList;

**Comment by xronghui** [comment]
我这边做了如下尝试：

1.修改 node_modules/@grpc/grpc-js/build/src/load-balancer-pick-first.js的411行

2.指定版本： "@grpc/grpc-js": "1.8.12"

都可以解决这个问题，但出现同样的错误：

GError: 14 UNAVAILABLE: Failed to parse DNS address dns:wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_xxxxxxxxx

不知道这个问题是上面的问题导致的还是别的原因导致的，麻烦再看看

**Comment by hcfw007** [comment]
你运行的环境直接curl https://token-service-discovery-test.juzibot.com/v0/hosties/puppet_workpro_xxx 能访问吗？

**Comment by xronghui** [comment]
curl https://token-service-discovery-test.juzibot.com/v0/hosties/puppet_workpro_xxx 可以访问

问题已解决，对比代码发现导致上面问题的原因：
   
修改 package.json 中的name 导致，将name字段改回去就能正常启动了 

是什么原因导致这个name字段不能修改呢，好像文档里面也没有说明

**Comment by hcfw007** [comment]
你修改的是你这个项目package.json中的name？没道理啊

那再修改下还能启动吗

**Comment by xronghui** [comment]
是的，修改了就会报错：Failed to parse DNS address dns:wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_xxxxxxxxx

改回去了就能正常使用了

**Comment by hcfw007** [comment]
我没遇到过这样的情况，我这里测试修改name也可以正常运行。

**Comment by xuwancheng** [comment]
通过你说的临时解决办法，确实是可以登录了，非常感谢！！！

修改 node_modules/@grpc/grpc-js/build/src/load-balancer-pick-first.js的411行

从
const rawAddressList = [].concat(...endpointList.map(endpoint => endpoint.addresses));
改为
const rawAddressList = endpointList;

**Comment by lizihao001** [comment]
> 我没遇到过这样的情况，我这里测试修改name也可以正常运行。

你好，我在网页端Github Codespace使用官方的实例仓库: Wechaty getting-started 项目，更换了7天试用wxwork token，也运行了export WECHATY_PUPPET_SERVICE_AUTHORITY=token-service-discovery-test.juzibot.com

会报类似路径的错误
日志如下:
10:46:13 INFO PuppetSkeleton start()
10:46:13 INFO PuppetService start() instanciating GrpcManager ...
10:46:13 INFO PuppetService start() instanciating GrpcManager ... done
10:46:13 INFO PuppetService start() setting up bridge grpc event stream ...
10:46:13 INFO PuppetService start() setting up bridge grpc event stream ... done
10:46:13 INFO PuppetService start() starting grpc manager...
10:46:13 WARN last event was 1711622773.979 seconds ago, will not request event cache 
10:46:13 WARN GrpcManager initClient() TLS: disabled (INSECURE)
10:46:13 INFO GrpcManager startStream() connecting event stream with account undefined and seq undefined
/workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/subchannel-address.ts:40
  return 'port' in address;
               ^
TypeError: Cannot use 'in' operator to search for 'port' in undefined
    at isTcpSubchannelAddress (/workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/subchannel-address.ts:40:16)
    at interleaveAddressFamilies (/workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/load-balancer-pick-first.ts:145:27)
    at PickFirstLoadBalancer.updateAddressList (/workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/load-balancer-pick-first.ts:533:25)
    at ChildLoadBalancerHandler.updateAddressList (/workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/load-balancer-child-handler.ts:137:19)
    at onSuccessfulResolution (/workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/resolving-load-balancer.ts:302:34)
    at processTicksAndRejections (node:internal/process/task_queues:85:22)

**Comment by YinanZhaoXometry** [comment]
搞了半天调通了，希望对后面的同学有用：

![image](https://github.com/user-attachments/assets/b04aeb0d-0277-4b81-966a-6b2970342d21)

![image](https://github.com/user-attachments/assets/c07f08a7-d3e7-4ac0-a0b3-c1cd69862568)

仓库我用的 https://github.com/RPAChat/workpro-getting-started

重装了这几个包（不确定是否是决定因素）：
```
    "@juzi/wechaty": "^1.0.99",
    "@juzi/wechaty-puppet": "^1.0.90",
    "@juzi/wechaty-puppet-service": "^1.0.100",
```

**Comment by mustcarrayout** [comment]
> 搞了半天调通了，希望对后面的同学有用：
> 
> ![image](https://private-user-images.githubusercontent.com/30831076/357727013-b04aeb0d-0277-4b81-966a-6b2970342d21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NzE3NzMsIm5iZiI6MTcyODQ3MTQ3MywicGF0aCI6Ii8zMDgzMTA3Ni8zNTc3MjcwMTMtYjA0YWViMGQtMDI3Ny00YjgxLTk2NmEtNmIyOTcwMzQyZDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEwNTc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYjExYmQ3Y2VjOGJmYmQ0ZTM3Yzk5ZWMzYjIxZTQ2ZDczOWE1YjNjOThkOTI3NjIyZjcxN2JhMDQwZDc0ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Si0tzbwdbgjvapnuTC7HqJ7iYtEXTx-cFJt8UQJ5N5M)
> 
> ![image](https://private-user-images.githubusercontent.com/30831076/357727081-c07f08a7-d3e7-4ac0-a0b3-c1cd69862568.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NzE3NzMsIm5iZiI6MTcyODQ3MTQ3MywicGF0aCI6Ii8zMDgzMTA3Ni8zNTc3MjcwODEtYzA3ZjA4YTctZDNlNy00YWMwLWEwYjMtYzFjZDY5ODYyNTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEwNTc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZjJmM2JjYWQ1YTlkOTA4YjU1OTU1NmE3ZDc5ZTBlMTlhMGUyYzQyZmRkZWFkNDhkYzEzZGI1Yzc2OTkyMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5MMrcGvE007fXBRa6YY7YzJWr_YNQKGd3xo5J6bbrNU)
> 
> 仓库我用的 https://github.com/RPAChat/workpro-getting-started
> 
> 重装了这几个包（不确定是否是决定因素）：
> 
> ```
>     "@juzi/wechaty": "^1.0.99",
>     "@juzi/wechaty-puppet": "^1.0.90",
>     "@juzi/wechaty-puppet-service": "^1.0.100",
> ```

参考这位同学的，加上，修改grpc的问题，解决了问题。接下来就是登录输入验证码的问题了。

修改 node_modules/@grpc/grpc-js/build/src/load-balancer-pick-first.js

从
`const rawAddressList = [].concat(...endpointList.map(endpoint => endpoint.addresses));`改为
`const rawAddressList = endpointList;`

**Comment by ekke765** [comment]
Thanks for the workaround and it works in my case. Is there any plan to fix the issue permanently?

**Comment by EvansYe2** [comment]
是不是已经不维护了？我参考网上人家的代码，改成如下的npm安装才能用了。
"@juzi/wechaty": "^1.0.108",
    "@juzi/wechaty-puppet": "^1.0.100",
    "@juzi/wechaty-puppet-service": "^1.0.105",  企微
"wechaty-puppet-matrix": "^0.0.21",     个微
