### ISSUE TITLE
[FEAT]WorkPro: silk 语音文件格式

### ISSUE THREAD

**Issue by bkidy** [wechaty/puppet-service-providers#367]
**Is your feature request related to a problem? Please describe.**

我们目前有一个场景，需要接收用户的语音消息，并将语音消息转换为文本。
目前测试中发现语音消息是上传到 workpro 云服务器的 *.silk 格式的文件，该文件目前没法直接被百度 AI、讯飞等主流语音转文字服务所支持

**Describe the solution you'd like**

workpro 是否有考虑提供上述转文字服务能够支持的格式，或者有比较好的解决方案推荐？

**Describe alternatives you've considered**

如果没有更好的解决方案的话，我们有考虑自己做格式转换，但是也会增加用户的等待时间

**Comment by su-chang** [comment]
@bkidy 访问语音消息的text属性，可以获取到转文字的内容。

**Comment by hcfw007** [comment]
无后续反馈，问题关闭。
