### ISSUE TITLE
WorkPro每次登录的时效性等

### ISSUE THREAD

**Issue by sgshy1995** [wechaty/puppet-service-providers#369]
1、WorkPro每次扫码的时效性有多久？每隔多久需要下一次扫码？

2、使用WorkPro是否有封号或警告的风险？

**Comment by su-chang** [comment]
1.二维码有效期10分钟左右
2. 不承诺一定不封号，主要是和账号的行为有关

**Comment by sgshy1995** [comment]
> 1.二维码有效期10分钟左右 2. 不承诺一定不封号，主要是和账号的行为有关

@su-chang 我的意思是扫码登陆成功后，可以保持在线多久？只要手机不掉线就可以吗

**Comment by su-chang** [comment]
是的

**Comment by hcfw007** [comment]
无后续反馈，问题关闭。
