### ISSUE TITLE
[BUG]WorkPro:getting-started报错

### ISSUE THREAD

**Issue by dotaZealot** [wechaty/puppet-service-providers#377]
![image](https://github.com/wechaty/puppet-supports/assets/1477413/4c3d3687-75e8-4537-9547-5d9deaafe8e5)
{
  'wechaty-getting-started': '1.18.11',
  npm: '10.2.4',
  node: '21.4.0',
  acorn: '8.11.2',
  ada: '2.7.4',
  ares: '1.23.0',
  base64: '0.5.1',
  brotli: '1.1.0',
  cjs_module_lexer: '1.2.2',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '9.1.3',
  modules: '120',
  napi: '9',
  nghttp2: '1.58.0',
  openssl: '3.2.0',
  simdutf: '4.0.4',
  tz: '2023c',
  undici: '5.28.1',
  unicode: '15.0',
  uv: '1.47.0',
  uvwasi: '0.0.19',
  v8: '11.8.172.17-node.17',
  zlib: '1.2.13.1-motley-5daffc7'
}

**Comment by hcfw007** [comment]
问题与workpro/puppet-service无关，请去wechaty相关仓库提问。
