### ISSUE TITLE
[BUG]WorkPro:引用消息解析报错

### ISSUE THREAD

**Issue by zhongyufan** [wechaty/puppet-service-providers#378]
报错信息如下
![image](https://github.com/wechaty/puppet-supports/assets/26425772/bd703392-5e98-44e0-8193-590ea6d095f7)

触发
电脑端企业微信给内部联系人员发送一个表情包，然后引用这个表情包，然后再选择一个表情包 发送出去，会出现这个错误。

**Comment by su-chang** [comment]
请提供对应的wechaty相关依赖的版本，如果有对应的代码片段截图最好不过了。

**Comment by hcfw007** [comment]
无后续反馈，问题关闭。
