### ISSUE TITLE
WXWork:服务地址出错，这是什么原因，该如何解决呢

### ISSUE THREAD

**Issue by ghost** [wechaty/puppet-service-providers#380]
![image](https://github.com/wechaty/puppet-supports/assets/139773783/7edc11e1-ee9d-4fb9-b9d9-f1b2250a96bb)

按照项目文档运行出现报错：https://wechaty.js.org/2022/12/23/introducing-workpro-puppet/

**Comment by su-chang** [comment]
关联issue: https://github.com/wechaty/puppet-supports/issues/379
