### ISSUE TITLE
下载项目https://github.com/RPAChat/workpro-getting-started.git下来运行登录报错workpro-getting-started\node_modules\@grpc\grpc-js\src\subchannel-address.ts:40   return 'port' in address;

### ISSUE THREAD

**Issue by xzc1366** [wechaty/puppet-service-providers#383]
在index.ts的这段代码里const bot = WechatyBuilder.build({
  puppet: 'wechaty-puppet-service',
  puppetOptions: {
    token:'puppet_workpro_a2c6bf66e4504ce79f87d529991e624a',
    tls: {
      disable: true
      // currently we are not using TLS since most puppet-service versions does not support it. See: https://github.com/wechaty/puppet-service/issues/160
    }
  }
})
添加了token，npm start 运行后，提示如下错误，请问怎么解决。
workpro-getting-started\node_modules\@grpc\grpc-js\src\subchannel-address.ts:40
  return 'port' in address;
               ^
TypeError: Cannot use 'in' operator to search for 'port' in undefined

**Comment by xzc1366** [comment]
问题补充：看过这边的回答并没能得到解决。https://github.com/wechaty/puppet-supports/issues/364#issuecomment-1952270004
步骤是
1克隆下项目
2npm install
3配置环境变量。WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true和WECHATY_PUPPET_SERVICE_AUTHORITY=token-service-discovery-test.juzibot.com  这两项
4代码中填写token
5npm start 
发生上述报错

**Comment by xzc1366** [comment]
问题补充：https://token-service-discovery-test.juzibot.com/v0/hosties/puppet_workpro_xxx可以获取host ip port三个值

**Comment by su-chang** [comment]
@xzc1366 请完整看下 #364 的上下文，看看是否有助于你解决该问题。

**Comment by xzc1366** [comment]
> @xzc1366 请完整看下 #364 的上下文，看看是否有助于你解决该问题。

364这篇问答并没有什么效果

**Comment by lijinliang1994** [comment]
> > @xzc1366 请完整看下 #364 的上下文，看看是否有助于你解决该问题。
> 
> 364这篇问答并没有什么效果

我遇到了同样的问题，参考 #364 可以解决。
我选的解决方案是 修改@grpc/grpc-js依赖的版本为1.8.12
