### ISSUE TITLE
出个微iPad协议/源码，代部署。比wechaty功能多，比wechaty性能稳定，无限号无限时永久免费调用。

### ISSUE THREAD

**Issue by RolloTomasiii** [wechaty/puppet-service-providers#386]
**联系方式微信：AIYLWL**

**Comment by huan** [comment]
I would love to hear from the community for feedback about how this code works.

**Comment by chenzhiqiang0518** [comment]
> **联系方式微信：AIYLWL**

AIYLWL，这个微信号添加显示用户不存在

**Comment by RolloTomasiii** [comment]
再试试

**Comment by RolloTomasiii** [comment]
再试试看

**Comment by RolloTomasiii** [comment]
> > **联系方式微信：AIYLWL**
> 
> AIYLWL，这个微信号添加显示用户不存在

再试试看

**Comment by huan** [comment]
Close this issue because it's unrelated to Wechaty Puppet Support.

However, if you want to create an Wechaty Puppet for your implementation, you are welcome to go ahead, and I'd like to know more about your plan on our Discord Server: https://discord.gg/7q8NBZbQzt
