### ISSUE TITLE
[BUG]WorkPro: on('room-invite')事件失效

### ISSUE THREAD

**Issue by tentacle-pro** [wechaty/puppet-service-providers#392]
"@juzi/wechaty": "^1.0.66",

最近没有动过线上生产环境代码，今天发现room-invite事件失效，也就无法调用对应函数。

在开发环境调试，确认是grpc服务端的问题，请尽快修复！如果要更新包版本，请给出具体版本号，谢谢

**Comment by su-chang** [comment]
提供对应的日志，这个是基础功能，我们这边暂时没有收到其他用户反馈类似案例。

需要先排查问题原因，同时建议也确认下是某些群聊不生效，还是都不生效。

**Comment by hcfw007** [comment]
无后续反馈，问题关闭。
