### ISSUE TITLE
[BUG]WorkPro:在运行过程中突然掉线，然后要求扫码登录

### ISSUE THREAD

**Issue by ComeyLi** [wechaty/puppet-service-providers#393]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**
在运行过程中自动掉线，然后开始要求重新扫码登录，以下为日志：

22:46:24 INFO PuppetService received grpc event EVENT_TYPE_MESSAGE on Tue Mar 12 2024 22:46:24 GMT+0800 (中国标准时间), content: "{\"messageId\":\"6802d2782d7b0e65e656c77a1112eaea\"}", seq: 67, timestamp: 1710254784846
22:46:24 INFO [yichuBot] on message: Message#Text[🗣Contact<李孟昕>@👥Room<loading...>]  xxxxxx 
22:46:25 INFO [yichuBot] room: xxxx,xxxx, id: R:10703665986125916
xxxxxx
22:46:28 INFO PuppetService received grpc event EVENT_TYPE_READY on Tue Mar 12 2024 22:46:28 GMT+0800 (中国标准时间), content: "{\"data\":\"data ready\"}", seq: 0, timestamp: 1710254788126
23:00:52 INFO PuppetService received grpc event EVENT_TYPE_LOGOUT on Tue Mar 12 2024 23:00:52 GMT+0800 (中国标准时间), content: "{\"contactId\":\"1688854645463005\",\"data\":\"你正在一台新设备上使用企业微信，需通过手机企业微信扫码进行安全验证\"}", seq: 0, timestamp: 1710255652192
23:00:52 INFO PuppetLoginMixin logout(你正在一台新设备上使用企业微信，需通过手机企业微信扫码进行安全验证)
23:00:52 INFO PuppetService received grpc event EVENT_TYPE_SCAN on Tue Mar 12 2024 23:00:52 GMT+0800 (中国标准时间), content: "{\"status\":2,\"qrcode\":\"https://work.weixin.qq.com/webapp/secondaryEquipment/index?bar_style_type=2&for_native=true&code=B989B267C6619F91527ABAD57D0A41DC\",\"type\":2,\"timestamp\":1710255652735,\"createTimestamp\":1710255652735,\"expireTimestamp\":1710255772735}", seq: 0, timestamp: 1710255652800

  ============================================================
  qrcode : https://work.weixin.qq.com/webapp/secondaryEquipment/index?bar_style_type=2&for_native=true&code=B989B267C6619F91527ABAD57D0A41DC, status: 2, data: 
  ============================================================

**Comment by su-chang** [comment]
企业微信的安全验证，需要在2分钟内及时扫码登录。
