### ISSUE TITLE
[BUG]WorkPro:在win设置环境变量后启动还是报错

### ISSUE THREAD

**Issue by ghost** [wechaty/puppet-service-providers#394]
![image](https://github.com/wechaty/puppet-supports/assets/139773783/6aa26a6d-bdc1-4614-bdb2-8629feb42ae6)
![image](https://github.com/wechaty/puppet-supports/assets/139773783/1f747bf7-ad86-4696-944e-9106dd1874d7)
Token地址也是有效的，这是什么原因？

**Comment by ghost** [comment]
在linux中跑的时候就不会出错，这是什么原因？求解答

**Comment by su-chang** [comment]
这里是环境变量配置错了，linux和win的环境变量配置的方式不同，请自行google。

**Comment by hcfw007** [comment]
无后续反馈，问题关闭。
