### ISSUE TITLE
[FEAT]WorkPro: ContactSelf.roomAlias

### ISSUE THREAD

**Issue by KAWATAAAAAA** [wechaty/puppet-service-providers#396]
**Is your feature request related to a problem? Please describe.**

希望能修改 bot 在外部群中的昵称，在个人微信中，看企业微信群中的企业微信联系人默认是员工实名制，
如果想要建立企业形象可能需要另外恰当的名字

**Describe the solution you'd like**

我看到 wechaty 包中有方法 ContactSelf.roomAlias， 但未实现，希望能实现这个功能

**Describe alternatives you've considered**

**Additional context**

<img width="761" alt="image" src="https://github.com/wechaty/puppet-supports/assets/19848575/bc7fd413-a3ab-41ce-8ff3-f9fd3714e0c8">

**Comment by su-chang** [comment]
推荐使用 @juzi/wechaty 这个包来使用该功能。

**Comment by KAWATAAAAAA** [comment]
我确实是使用这个包来进行开发的  `"@juzi/wechaty": "^1.0.81"`   只是上面的截图里的方法长得有点奇怪， 实际上是获取群聊后，再调用的 ContactSelf.roomAlias(Room,"alias")

**Comment by su-chang** [comment]
OK 理解了，那这个是暂不支持。

**Comment by KAWATAAAAAA** [comment]
嗯嗯， 所以提个RF 在此，静候佳音 😁

**Comment by su-chang** [comment]
你更新下最新版本再试下这个功能。

**Comment by KAWATAAAAAA** [comment]
最新版直接报错了，

TypeError: Cannot use 'in' operator to search for 'port' in undefined
    at isTcpSubchannelAddress (/Users/wuyuwei/MyWork/wechaty-workpro/node_modules/.pnpm/@grpc+grpc-js@1.10.3/node_modules/@grpc/grpc-js/src/subchannel-address.ts:40:16)

**Comment by KAWATAAAAAA** [comment]
经测试，@juzi/wechaty 1.0.97 版本可以支持此功能，👍，关闭 RF
