### ISSUE TITLE
[FEAT]WorkPro: 请求支持判断群聊类型

### ISSUE THREAD

**Issue by KAWATAAAAAA** [wechaty/puppet-service-providers#397]
**Is your feature request related to a problem? Please describe.**
无法通过群 id 长度来判断是否为外部群聊，格式不确定，内部/外部群 id 长度有长有短
需要对群聊进行过滤，得出外部群，进行精细化客户运营

**Describe the solution you'd like**
能通过某个字段获取群聊的类型， 如 全员群/外部群/内部群/部门群

**Describe alternatives you've considered**
none

**Additional context**

<img width="245" alt="image" src="https://github.com/wechaty/puppet-supports/assets/19848575/afc0886e-7e84-4792-859b-cad2fd253281">

> 图中群类型依次为： 内部群、部门群、全员群、外部群

**Comment by su-chang** [comment]
暂不支持，后续会补充字段来标识。

**Comment by su-chang** [comment]
可以临时先用长度进行匹配，绝大部分群聊都可以根据长度区分外部和内部群聊。

**Comment by KAWATAAAAAA** [comment]
不够精准，会有大概率误判，等待新特性

**Comment by KAWATAAAAAA** [comment]
另外请求支持企业微信中联系人的类型， 企业内部联系人/企业外部联系人 ，同样是没法用id长度等来判断，大概率会误判

**Comment by su-chang** [comment]
@KAWATAAAAAA 群聊类型已经支持了

```ts
room.payload.external // true 表示为外部群聊，false 表示为内部群聊
```

**Comment by su-chang** [comment]
> 另外请求支持企业微信中联系人的类型， 企业内部联系人/企业外部联系人 ，同样是没法用id长度等来判断，大概率会误判

这个可以用`contact.coworker()`这个方法进行判断。

**Comment by KAWATAAAAAA** [comment]
> @KAWATAAAAAA 群聊类型已经支持了
> 
> ```ts
> room.payload.external // true 表示为外部群聊，false 表示为内部群聊
> ```

目前 `"@juzi/wechaty": "1.0.97"` 中 room.payload.external还是 undefined， 请问是否要升级到指定版本？

**Comment by su-chang** [comment]
puppet和puppet-service也升级下。

**Comment by hcfw007** [comment]
无反馈，问题关闭。
