### ISSUE TITLE
PadLocal:  ask for a token 

### ISSUE THREAD

**Issue by xingx001** [wechaty/puppet-service-providers#4]
## Wechaty Puppet PadLocal

- Repo: <https://github.com/padlocal/wechaty-puppet-padlocal>
- Provider: [PadLocal](https://github.com/padlocal)
- Support: <https://github.com/padlocal/wechaty-puppet-padlocal/issues>

**Comment by padlocal** [comment]
@xingx001 Can you send me a direct email: oxddoxdd#gmail.com ? Then I can send you token and related materials.

**Comment by xingx001** [comment]
> @xingx001 Can you send me a direct email: oxddoxdd#gmail.com ? Then I can send you token and related materials.

hi i sent a Email  as you told. i am expecting i can  get a token  soon.  thank  you.
