### ISSUE TITLE
[BUG]WorkPro:通过本地文件更新验证码后，还是显示验证码无效，无法登录

### ISSUE THREAD

**Issue by xiaoxia1987** [wechaty/puppet-service-providers#400]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

**Info**

 - Platform[e.g. Windows/Mac/Linux]: 
 - Runtime version[e.g. node/JAVA]:
![QQ截图20240318154315](https://github.com/wechaty/puppet-supports/assets/163281159/1f2bd7cc-ff20-47e1-95c4-a0bbd8b960e1)

 - Wechaty version: 
 - Wechaty Puppet version: 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hcfw007** [comment]
你是怎么调用的，我们收到的验证码是undefined

**Comment by xiaoxia1987** [comment]
我把在自己手机企业微信的收到验证码放在本地文件中，然后再传给enterVertityCode，但是一直提示无效验证码
![QQ截图20240320133621](https://github.com/wechaty/puppet-supports/assets/163281159/6668ff5f-d3dc-4640-8e5d-2e5ae0967b80)

**Comment by hcfw007** [comment]
朋友，你这些方法都是同步方法，当收到事件的时候肯定你还没输入就发出去了啊。
你在39行和40行之间把验证码打印出来就知道了。

**Comment by xiaoxia1987** [comment]
已经处理好了，有没如何发送消息的api文档

**Comment by hcfw007** [comment]
请参考wechaty官网的文档，基本是一样的。不过那个文档有点过时了，如果是用IDE的话，可以先获取群或联系人，然后看看上面的say方法。

**Comment by hcfw007** [comment]
问题已解决。
