### ISSUE TITLE
[BUG]WorkPro: wechaty_puppet.exceptions.WechatyPuppetGrpcError: WechatyPuppetGrpcError('can"t fetch endpoint from chatie server. You can try it later, or make sure that your pc can connect to heroku server ', None, None)

### ISSUE THREAD

**Issue by JackLCL** [wechaty/puppet-service-providers#406]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

File "/usr/local/lib/python3.8/dist-packages/wechaty_puppet_service/puppet.py", line 884, in _init_puppet
    raise WechatyPuppetGrpcError(
wechaty_puppet.exceptions.WechatyPuppetGrpcError: WechatyPuppetGrpcError('can"t fetch endpoint from chatie server. You can try it later, or make sure that your pc can connect to heroku server ', None, None)

**Info**

 - Platform[e.g. Windows/Mac/Linux]: 
 - Runtime version[e.g. node/JAVA]:
 - Wechaty version: 
 - Wechaty Puppet version: 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hcfw007** [comment]
Please check the discover server of your token via https://tss.rpachat.com/ or by providing last 6 characters of your token.
Then check if you can get the endpoint by calling `${discoverServer}/0/hosties/${token}` with GET method.

**Comment by JackLCL** [comment]
@hcfw007 

my token: puppet_workpro_1d04e3 xxxxxxxxx

**Comment by hcfw007** [comment]
I have reset the connection between the token and api.chatie.io. Please try again.
