### ISSUE TITLE
[BUG]WorkPro:1、企业微信扫码登录之后 1分钟自动断开连接  2、接收图片类型报错

### ISSUE THREAD

**Issue by lizihao001** [wechaty/puppet-service-providers#410]
依赖:
wechaty==0.8.0
wechaty-grpc==0.20.19
wechaty-puppet==0.4.23
wechaty-puppet-service==0.8.10

![企业微信登录时长问题](https://github.com/wechaty/puppet-supports/assets/155125269/65595480-a394-4df4-98c8-aaa68817aa7b)

image_file_box = await msg.to_file_box() 接收图片文件报错
报错如下:
![企业识别图片问题](https://github.com/wechaty/puppet-supports/assets/155125269/2d49c0a8-ffe0-4547-a0be-39652b10aef5)

**Comment by su-chang** [comment]
请使用nodejs进行测试，python相关的问题请在对应的repo中提问。

**Comment by hcfw007** [comment]
无反馈，问题关闭。
