### ISSUE TITLE
[BUG]WorkPro:收到的小程序信息，appid 和username 参数值反了

### ISSUE THREAD

**Issue by leochen-g** [wechaty/puppet-service-providers#415]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

对于workpro 收到的小程序信息解析，发现appid 的值和username 的值是反的

**Info**

 - Platform:  Mac
 - Runtime version: node
 - Wechaty version: "@juzi/wechaty": "^1.0.96"
 - Wechaty Puppet version: "@juzi/wechaty-puppet-service": "^1.0.93",

**To Reproduce**

1. 使用token启动一个workpro 服务
2. 给机器人发送一个小程序，在代码里使用`await message.toMiniProgram()`转换小程序参数
3. 得到的参数值与小层序的实际值是反的

**Expected behavior**

应该是appid 和username是正确的对应关系

**Screenshots**
得到的appid 和username
![image](https://github.com/wechaty/puppet-supports/assets/20028566/e373463e-6249-4fc3-91b7-88bd516b6d5d)
实际的appid 和username 
![image](https://github.com/wechaty/puppet-supports/assets/20028566/a78a2449-4e29-492d-addf-5e673693f64e)

**Comment by hcfw007** [comment]
这个是历史原因，总之现在这个情况是没法改了的，需要自行编码来调整这两个值。。。

**Comment by hcfw007** [comment]
无反馈，问题关闭。
