### ISSUE TITLE
[BUG]WorkPro: 个人微信修改昵称后，机器人再采集好友以及群聊信息好友昵称都没有更新最新的昵称

### ISSUE THREAD

**Issue by zhl0101** [wechaty/puppet-service-providers#417]
在企业微信的外部群中，个人微信好友昵称修改后，机器人重新采集好友信息，以及群聊信息都不会采集到最新修改的昵称，还请尽快排查原因，和解决方案

**Comment by su-chang** [comment]
联系人信息变更后，会推送dirty事件，需要监听dirty事件后，自行调用 sync 方法进行同步更新缓存。

**Comment by hcfw007** [comment]
无反馈，问题关闭。
