### ISSUE TITLE
[BUG]WorkPro:发送附件类消息，偶尔会出现附件大小为0的情况

### ISSUE THREAD

**Issue by loaferxuan** [wechaty/puppet-service-providers#418]
**Describe the bug**

发送附件类消息，偶尔会出现附件大小为0的情况

**Info**

 - Platform[Windows]: 
 - Runtime version[node]:
 - Wechaty version: 
 - Wechaty Puppet version: 
    "@juzi/wechaty": "^1.0.66",
    "@juzi/wechaty-puppet": "^1.0.61",
    "@juzi/wechaty-puppet-service": "^1.0.69",

**To Reproduce**

1、根据路径加载出文件 const file = FileBox.fromFile(filePath)
2、发送文件 await contact.say(file);

**Expected behavior**
发送的文件大小为实际大小

**Screenshots**
![image](https://github.com/wechaty/puppet-supports/assets/108316185/5564c3c3-47f0-45e3-ae40-e991f37611c9)
我调用了3次接口发送消息，第2次出现了文件大小为0的情况。文件一直都是同一个文件。

![image](https://github.com/wechaty/puppet-supports/assets/108316185/b79fad98-6838-4e85-8735-3d0dc127e61d)
加载文件后我打印了日志，日志显示的文件大小一直也都是正常的

**Comment by su-chang** [comment]
这个能稳定复现么？其他文件用相同的方式发送看看是否也是一样的情况。

**Comment by loaferxuan** [comment]
> 这个能稳定复现么？其他文件用相同的方式发送看看是否也是一样的情况。

无法稳定复现。其他文件，包括格式不同的其他文件也会出现这样的情况，比如docx格式。

**Comment by loaferxuan** [comment]
@su-chang 你好，请问有任何进展吗？

**Comment by su-chang** [comment]
没有复现步骤，暂时无法修复。或者可以提供你测试过程中遇到的案例的详细信息，时间、文件名称、发送对象ID，我们这边再研究下日志看看。

最好还是有复现步骤，解决起来会比较快。

**Comment by hcfw007** [comment]
无反馈，问题关闭。

**Comment by 2424919976** [comment]
我也遇到了相同的问题
![image](https://github.com/wechaty/puppet-supports/assets/82091906/4bd5501d-f31f-445b-9de7-3044257c5227)
![1717118060309](https://github.com/wechaty/puppet-supports/assets/82091906/98445010-0583-45ef-9402-7803fd93285a)


你自己去多尝试几次，多发送几个链接，就可以稳定复现的

我遇到的问题是有的链接发送很多次，都是有内容的，有的链接，发送几次，就会有一次出现大小为0的情况

**Comment by 2424919976** [comment]
我这个是已经购买了很多个token的，希望早点修复
