### ISSUE TITLE
can you provide a sample to send miniprogram? [FEAT]WorkPro:

### ISSUE THREAD

**Issue by ciaovention** [wechaty/puppet-service-providers#419]
import { ScanStatus, WechatyBuilder,types} from '@juzi/wechaty'
if i do import { ScanStatus, WechatyBuilder,types, MiniProgram} from '@juzi/wechaty' doesn't seem to work.

// 6. send MiniProgram to bot itself
  // const miniPayload = new MiniProgram ({
  //   username           : 'gh_xxxxxxx',     //get from mp.weixin.qq.com
  //   appid              : '',               //optional, get from mp.weixin.qq.com
  //   title              : '',               //optional
  //   pagepath           : '',               //optional
  //   description        : '',               //optional
  //   thumbnailurl       : '',               //optional
  // }) 
  // message.say(miniPayload)

this thing from wechaty doesn't seem to work.

**Comment by hcfw007** [comment]
The best way is to receive a miniprogram and use the data to send.

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
