### ISSUE TITLE
[BUG]WorkPro:getting-started demo无法正常启动

### ISSUE THREAD

**Issue by imbooo** [wechaty/puppet-service-providers#425]
使用官方demo无法正常启动，使用的是试用token。

- [x] tls已关闭
- [x] authority已指定token-service-discovery-test.juzibot.com

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

**Info**

 - Platform: Mac
 - Runtime version: Node v18.19.0
 - Wechaty version:  "@juzi/wechaty": "^1.0.97"
 - Wechaty Puppet version: "@juzi/wechaty-puppet-service": "^1.0.95"

错误信息：
<img width="1426" alt="image" src="https://github.com/wechaty/puppet-supports/assets/6120414/92f3d64b-f801-44c7-aabc-50044e15ef0b">

**Comment by su-chang** [comment]
重试下是否正常？

**Comment by imbooo** [comment]
一直都不行，试过很多次了，查了很多文档都没有类似的现象。

**Comment by imbooo** [comment]
现在提示变成了does not exist，之前访问https://token-service-discovery-test.juzibot.com/v0/hosties/puppet_workpro_还是正常的。

**Comment by imbooo** [comment]
已解决，原因是本地使用了代理，导致报错，关闭后就可以看到其他异常详情了。
