### ISSUE TITLE
怎么获取bot.start()之后打印在控制台中的登录二维码

### ISSUE THREAD

**Issue by qcfengdaai** [wechaty/puppet-service-providers#428]
const bot = WechatyBuilder.build({
  puppet: 'wechaty-puppet-service',
  puppetOptions: {
    token,
    tls: {
      disable: true
      // currently we are not using TLS since most puppet-service versions does not support it. See: https://github.com/wechaty/puppet-service/issues/160
    }
  }
})
//怎么获取打印在控制台中的二维码
bot.start()

**Comment by su-chang** [comment]
`qrcode-terminal` 可以用这个包来处理二维码显示的问题

**Comment by qcfengdaai** [comment]
好的，已经会了！！谢谢！！qrcode 替换 qrcode-terminal，生成图片！

**Comment by heyiqian0831** [comment]
请问遇到的问题是：有二维码地址但是没有二维码吗
