### ISSUE TITLE
[BUG]WorkPro: 登录成功后有时拿到的企业微信用户 id 是个空值。

### ISSUE THREAD

**Issue by woai3c** [wechaty/puppet-service-providers#430]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

我监听了 `ready` 和 `login` 事件，然后在回调里读取企业微信用户的 id，但是有时读到的值是空值。
```ts
bot.on('scan', onQRCodeScan).on('verify-code', onVerify)
bot.on('login', onReadyOrLogin)
bot.on('ready', onReadyOrLogin)
bot.on('logout', onLogout)
bot.on('message', onMessage)
bot.on('room-join', onRoomjoin)
bot.on('error', onError)

// bot 就绪或登录事件操作
export const onReadyOrLogin = async (bot: Wechaty) => {
  const botUser: Contact = bot.currentUser
  log.info('当前登录的账号信息:', JSON.stringify(botUser.payload))

 console.log(botUser.payload?.id) // 这里有时是空值，偶发的。
}
```

**Info**

 - Platform[e.g. Windows/Mac/Linux]: 
 - Runtime version[e.g. node/JAVA]:
 - Wechaty version: 
 - Wechaty Puppet version: 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hcfw007** [comment]
你这里定义的方法里面传了一个bot参数，因此会覆盖全局的bot。所以你在方法内调用的bot并不是bot，而是事件传入的参数。根据事件的签名，他们的参数并非bot，因此你这样调用是错误的。

**Comment by woai3c** [comment]
> 你这里定义的方法里面传了一个bot参数，因此会覆盖全局的bot。所以你在方法内调用的bot并不是bot，而是事件传入的参数。根据事件的签名，他们的参数并非bot，因此你这样调用是错误的。

原来如此，能否给一个正确示例的例子。我那个函数是放在另外一个文件里的，事件回调里的第一个参数不是机器人 bot 吗？

**Comment by hcfw007** [comment]
所有事件的回调都不包含机器人自身。具体回调请参考 https://github.com/juzibot/wechaty/blob/dc5d4539ff009bbd782335f7492d5c28e528fb17/src/schemas/wechaty-events.ts#L47C1-L48C1

示例：
```ts
bot.on('login', async user => {
    console.log(JSON.stringify(user.payload))
    console.log(`
    ============================================
    user: ${JSON.stringify(user)}, friend: ${user.friend()}, ${user.coworker()}
    ============================================
    `)
  })
```

**Comment by woai3c** [comment]
> 所有事件的回调都不包含机器人自身。具体回调请参考 https://github.com/juzibot/wechaty/blob/dc5d4539ff009bbd782335f7492d5c28e528fb17/src/schemas/wechaty-events.ts#L47C1-L48C1
> 
> 示例：
> 
> ```ts
> bot.on('login', async user => {
>     console.log(JSON.stringify(user.payload))
>     console.log(`
>     ============================================
>     user: ${JSON.stringify(user)}, friend: ${user.friend()}, ${user.coworker()}
>     ============================================
>     `)
>   })
> ```

好的，感谢。
