### ISSUE TITLE
WXWork: getaddrinfo  这个是什么错

### ISSUE THREAD

**Issue by aidp12333** [wechaty/puppet-service-providers#431]
Please make sure you have read the [Wechaty Puppet Service: WXWork](https://wechaty.js.org/docs/puppet-services/wxwork) from Wechaty Official Website before you continue writting this issue.

## Question
0|www      |   errno: -3008,
0|www      |   code: 'ENOTFOUND',
0|www      |   syscall: 'getaddrinfo',
0|www      |   hostname: 'token-service-discovery-test.juzibot.com'
0|www      | }
0|www      | 06:54:01 WARN WechatyToken discover() retry.execute(discoverApi) fail: WechatyToken discover() endpoint<https://token-service-discovery-test.juzibot.com/v0/hosties/puppet_workpro_52acbf9e74e847f492d6291681608cd9> rejection: Error: getaddrinfo ENOTFOUND token-service-discovery-test.juzibot.com
0|www      | 06:54:01 WARN ResolverWechaty updateResolution() address not found target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_52acbf9e74e847f492d6291681608cd9: token does not exist
0|www      | 06:54:01 WARN ServiceCtl<PuppetServiceMixin> reset() ... rejection: 14 UNAVAILABLE: Wechaty service discovery / resolution failed for target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_52acbf9e74e847f492d6291681608cd9: token "puppet_workpro_52acbf9e74e847f492d6291681608cd9" does not exist
0|www      | 11:32:20 WARN GrpcManager initClient() TLS: disabled (INSECURE)
0|www      | 11:32:30 WARN Message from() is deprecated, use talker() instead. Call stack: Error
0|www      |     at WechatifiedUserClass.from (D:\dd\wxchat\node_modules\wechaty\dist\cjs\src\user-modules\message.js:242:103)
0|www      |     at WechatyImpl.onMessage (D:\dd\wxchat\weRobot.js:105:23)
0|www      | 11:32:30 WARN Message from() is deprecated, use talker() instead. Call stack: Error
0|www      |     at WechatifiedUserClass.from (D:\dd\wxchat\node_modules\wechaty\dist\cjs\src\user-modules\message.js:242:103)
0|www      |     at WechatyImpl.onMessage (D:\dd\wxchat\weRobot.js:123:24)

我本地跑了一晚上 起来机器人已经挂了 报错上面请问这是什么问题

**Comment by su-chang** [comment]
重复issue，关闭。
