### ISSUE TITLE
[BUG]WorkPro: 机器人启动 1 CANCELLED: Call cancelled

### ISSUE THREAD

**Issue by zx2289** [wechaty/puppet-service-providers#433]
09:01:18 VERB GrpcManager constructor() disableTls: "true"
09:01:18 VERB GrpcManager constructor() serverName(SNI): "puppet_workpro"
09:01:18 VERB PuppetService start() instanciating GrpcManager ... done
09:01:18 VERB PuppetService start() setting up bridge grpc event stream ...
09:01:18 VERB PuppetService bridgeGrpcEventStream(client)
09:01:18 VERB PuppetService start() setting up bridge grpc event stream ... done
09:01:18 VERB PuppetService start() starting grpc manager...
09:01:18 VERB GrpcManager start()
09:01:18 VERB GrpcManager start() initializing client ...
09:01:18 VERB GrpcManager initClient()
09:01:18 WARN GrpcManager initClient() TLS: disabled (INSECURE)
09:01:18 VERB GrpcManager initClient() ... done
09:01:18 VERB GrpcManager start() initializing client ... done
09:01:18 VERB GrpcManager start() starting stream ...
09:01:18 VERB GrpcManager startStream()
09:01:18 VERB GrpcManager startStream() grpc -> event() ...
09:01:18 VERB GrpcManager startStream() grpc -> event() ... done
09:01:18 VERB GrpcManager startStream() grpc -> event peeking data or timeout ...
09:01:20 VERB GrpcManager startStream() grpc -> event peeking data or timeout ... timeout
09:01:20 VERB GrpcManager startStream() grpc -> event peeking data or timeout ... data peeked
09:01:20 VERB GrpcManager startStream() initializing event stream ...
09:01:20 VERB GrpcManager startStream() initializing event stream ... done
09:01:20 VERB GrpcManager startStream() ... done
09:01:20 VERB GrpcManager start() starting stream ... done
09:01:20 VERB GrpcManager start() calling grpc server: start() ...
09:01:21 ERR StarterBot Error: 1 CANCELLED: Call cancelled

**Comment by su-chang** [comment]
现在是否恢复，有啥复现步骤么？

**Comment by hcfw007** [comment]
无反馈，关闭。
