### ISSUE TITLE
[BUG]WorkPro: 如何主动给一个好友推送消息

### ISSUE THREAD

**Issue by IvesQing** [wechaty/puppet-service-providers#434]
使用的是workpro，参考https://wechaty.js.org/docs/api/contact的api去给好友推送消息
 具体代码：
![image](https://github.com/wechaty/puppet-supports/assets/26543986/cdffdeda-084f-48eb-ba08-022d8dd40ccb)

版本:
     "@juzi/wechaty": "^1.0.65",
    "@juzi/wechaty-puppet": "^1.0.61",
    "@juzi/wechaty-puppet-service": "^1.0.69"
 
使用错了还是暂无提供api。

**Comment by su-chang** [comment]
@IvesQing  语法问题，`find`方法是异步的。

**Comment by hcfw007** [comment]
无反馈，关闭。
