### ISSUE TITLE
[BUG]WorkPro: 报 CALL cancelled Error 导致 crash

### ISSUE THREAD

**Issue by djfkue** [wechaty/puppet-service-providers#435]
![1714111713463](https://github.com/wechaty/puppet-supports/assets/1555336/5d602b13-b77d-4455-b231-0c01658e029e)

会报这个 Call cancelled error，然后 crash

**Comment by hcfw007** [comment]
说明bot与token之间的连接断开了，请检查网络是否稳定。

**Comment by hcfw007** [comment]
无反馈，关闭。
