### ISSUE TITLE
[BUG]WorkPro: Bot 启动失败

### ISSUE THREAD

**Issue by djfkue** [wechaty/puppet-service-providers#436]
![1714112058319](https://github.com/wechaty/puppet-supports/assets/1555336/8e6c33c7-ed63-4151-aad2-eec8782a895b)

**Comment by hcfw007** [comment]
请在环境中访问 https://token-service-discovery-test.juzibot.com/v0/hosties/{token} 以确认发现服务连通性。

**Comment by hcfw007** [comment]
无反馈，关闭。
