### ISSUE TITLE
[BUG]WorkPro: 发送消息报错

### ISSUE THREAD

**Issue by zhongyufan** [wechaty/puppet-service-providers#439]
报错如下：
Error: 13 INTERNAL: WorkproErrorCode: 23060, processSendMsgRsp(10842195060642100) contentType: Unknown send message failed! cgi error code: (-1) message: Unpack response body failed!.

![image](https://github.com/wechaty/puppet-supports/assets/26425772/64c846b6-d4ec-4b16-b01c-4ee99df39351)

**Comment by hcfw007** [comment]
因为你这时候已经因为 “你正在一台新设备上使用企业微信，需通过手机企业微信扫码进行安全验证” 的原因掉线了。请监听 logout事件并做相应处理。

**Comment by zhongyufan** [comment]
可以通过23060错误码判断属于这个原因吗

**Comment by hcfw007** [comment]
不可以，发消息失败都会是 23060

**Comment by hcfw007** [comment]
无反馈，关闭。
