### ISSUE TITLE
[BUG]WorkPro: 发送10M左右的大图片，会卡死，然后其他微信过来的消息就都收不到了。

### ISSUE THREAD

**Issue by qqwangyue** [wechaty/puppet-service-providers#440]
当我发送一个本地图片时(大小约8M，不太能压缩，因为要求图片质量)，代码如下
![image](https://github.com/wechaty/puppet-supports/assets/169335513/bca97a83-6db3-406e-94d3-7e5e683fc65d)

然后查看log，就发现卡住不动了，如下图
![image](https://github.com/wechaty/puppet-supports/assets/169335513/0a620932-78c3-4d63-84a7-8058b9752279)
到这里就不动了。

然后其他微信发过来的消息就都收不到了。请问是我哪里写出问题了吗？

**Comment by hcfw007** [comment]
图片发送成功了，后续无法收到消息是因为 11:00 的时候因为 “已在手机端退出登录” 的原因离线了。请监听 logout 事件并检查相应处理。

**Comment by qqwangyue** [comment]
> 图片发送成功了，后续无法收到消息是因为 11:00 的时候因为 “已在手机端退出登录” 的原因离线了。请监听 logout 事件并检查相应处理。

感谢您的回答，还有点问题期待您帮忙看一下
![image](https://github.com/wechaty/puppet-supports/assets/169335513/726d3990-1baf-4081-b737-e4a3767609d6)
我看其他发送成功了都会多两条日志，像问题中的那种情况都没有这两条日志。而且用户确实没有收到图片。

其次是11点退出登录是我手动退出登录的，退出后立马就又登录了。 所以我能保证在用户收不到图片的时候企业微信是登录状态

还有就是我这儿遇到一个问题： 当机器人给A发送一个大图片时(往往需要近10秒)，在这10秒期间起，用户B给机器人发消息，bot的message事件收不到B的消息，会被阻塞，一直等到机器人给A回复完成后，被阻塞的消息才会涌进来。

**Comment by qqwangyue** [comment]
> > 图片发送成功了，后续无法收到消息是因为 11:00 的时候因为 “已在手机端退出登录” 的原因离线了。请监听 logout 事件并检查相应处理。
> 
> 感谢您的回答，还有点问题期待您帮忙看一下 ![image](https://private-user-images.githubusercontent.com/169335513/329224813-726d3990-1baf-4081-b737-e4a3767609d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTc3OTUsIm5iZiI6MTcxNTI1NzQ5NSwicGF0aCI6Ii8xNjkzMzU1MTMvMzI5MjI0ODEzLTcyNmQzOTkwLTFiYWYtNDA4MS1iNzM3LWU0YTM3Njc2MDlkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxMjI0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzBmODU2Y2RmMDdlYTdlZGY1ZTkwMWFkNTNkZTdkZTA5NmJjOTQ2OWM5NDk1ZjZmNjM4NTg3NjE1YzZhYjUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oCkQFQieIN58PCv9hQLOPdil8zHCaPxlzV_0YIwRj98) 我看其他发送成功了都会多两条日志，像问题中的那种情况都没有这两条日志。而且用户确实没有收到图片。
> 
> 其次是11点退出登录是我手动退出登录的，退出后立马就又登录了。 所以我能保证在用户收不到图片的时候企业微信是登录状态
> 
> 还有就是我这儿遇到一个问题： 当机器人给A发送一个大图片时(往往需要近10秒)，在这10秒期间起，用户B给机器人发消息，bot的message事件收不到B的消息，会被阻塞，一直等到机器人给A回复完成后，被阻塞的消息才会涌进来。

补充：
我试用的是句子7天试用的token

![image](https://github.com/wechaty/puppet-supports/assets/169335513/6d38f09b-f68b-4814-ac09-eda178b10453)
这里我确定机器人处于登录状态

bot.on('message')收不到消息证明如下图： (在控制台没有log： [MJ-1 bot] message received step 1 get room 信息)
![image](https://github.com/wechaty/puppet-supports/assets/169335513/652c480e-9d88-4e4e-bf3e-6b875a7f0349)

图片发送代码及其简单，如下图：其中image.path为本地图片路径(确认存在)， message为on.bot('message') 第二参数回调函数的参数
![image](https://github.com/wechaty/puppet-supports/assets/169335513/27065fa8-d862-4018-bc13-4d0b8b2e1edf)

**Comment by hcfw007** [comment]
你框出来的地方，正是Wechaty内部处理消息事件的日志，因此肯定是没阻塞的，但具体是什么原因，没看到具体代码不太清楚。

**Comment by qqwangyue** [comment]
> 你框出来的地方，正是Wechaty内部处理消息事件的日志，因此肯定是没阻塞的，但具体是什么原因，没看到具体代码不太清楚。

我感觉是这个问题： https://github.com/wechaty/puppet-service/issues/80
发送大文件时候会阻塞其他调用。 但是我目前还没有完全解决这个问题，请问您那边有没有类似的问题。看文档说要使用FileBox.fromUuid来处理，但是我没看明白怎么使用

**Comment by qqwangyue** [comment]
> > 你框出来的地方，正是Wechaty内部处理消息事件的日志，因此肯定是没阻塞的，但具体是什么原因，没看到具体代码不太清楚。
> 
> 非常感谢您的回复

我感觉是这个问题： [wechaty/puppet-service#80](https://github.com/wechaty/puppet-service/issues/80) 发送大文件时候会阻塞其他调用。 但是我目前还没有完全解决这个问题，请问您那边有没有类似的问题。看文档说要使用FileBox.fromUuid来处理，但是我没看明白怎么使用

----------------------
为了清晰，我把所有多余的代码全部删除，如下图
![image](https://github.com/wechaty/puppet-supports/assets/169335513/22ff3171-8823-4b86-9c73-9b80a535bc6f)

问题依然存在，如下图所示：
![image](https://github.com/wechaty/puppet-supports/assets/169335513/9583f7cb-e63b-4700-903d-b17a555337af)

其中发送的图片大小约为10M。 其用时超过10分钟才把这个10M的图片发送出去

----------------------
用户微信向机器人发送四次消息截图：
![image](https://github.com/wechaty/puppet-supports/assets/169335513/43864e03-3d8f-4863-bb46-7554f2d2bebb)

----------------------
补充package版本：
    file-box:  "^1.5.5"
    wechaty: "^1.20.2"

期待您的再次回复

**Comment by liangzhicheng0423** [comment]
我发现这个发送大文件极其慢的问题集中出现在晚上7点以后，早晨和中午都比较快，请问这个是什么原因，可以通过类似于升级token啥的办法解决吗

**Comment by qqwangyue** [comment]
需要注意的是：我使用的是7天试用的token。

我现在基本能确定，由于时间段的不同，卡顿程度不同。拿一张10M的图片举例
早晨9点-10点： 发送速度在 5-10s之间
中午12点-2点： 发送速度在 1分钟-5分钟之间
晚上7点后： 发送速度惨不忍睹，20分钟都发不出去。

如果是试用token(体验服)有带宽限制或者队列资源竞争压力大，请及时告知，是否付费完就可以很好的解决次问题。

**Comment by hcfw007** [comment]
并不存在对试用token的资源分配歧视策略。
我本地测试中并未发现发送文件的时候监听消息阻塞的情况（我发送的是197MB的文件）。
晚上7点高峰期我会再测试一下。

**Comment by qqwangyue** [comment]
> 一下

非常感谢🙏

**Comment by hcfw007** [comment]
可以提供一下token后6位，帮你延长一些测试时间。

**Comment by qqwangyue** [comment]
> 可以提供一下token后6位，帮你延长一些测试时间。

867d11

**Comment by hcfw007** [comment]
给你延长了10天

**Comment by hcfw007** [comment]
![image](https://github.com/wechaty/puppet-supports/assets/13669999/29a8451a-95e5-4163-bf25-a114ddbff1ea)
测试结果：
发送耗时 2分钟多
期间未阻塞接收消息

考虑到现在一般宽带的上下行不对等，70MB的文件发送2分钟算是正常的。如果想节约发送时间，可以考虑先上传到CDN服务，这样还可以以后复用。
至于阻塞问题，建议缩减代码，提供一个可以公布代码的最小测试。

**Comment by aqpmzngldh** [comment]
> ![image](https://private-user-images.githubusercontent.com/13669999/329778827-29a8451a-95e5-4163-bf25-a114ddbff1ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MzI4NzQsIm5iZiI6MTcxNTUzMjU3NCwicGF0aCI6Ii8xMzY2OTk5OS8zMjk3Nzg4MjctMjlhODQ1MWEtOTVlNS00MTYzLWJmMjUtYTExNGRkYmZmMWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE2NDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMTlmMzZkYTU2ZDZjNzUxMTU1NTM1Yzc0MjljMzZiMjUzNzYyYzE0OTgyY2VmMmQ3ZDYyNjM0NTU5Y2M4OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2c6mFtBGg5lNzNZa_CTEEQZ9k0Uy3smrpXyBqENp_Bg) 测试结果： 发送耗时 2分钟多 期间未阻塞接收消息
> 
> 考虑到现在一般宽带的上下行不对等，70MB的文件发送2分钟算是正常的。如果想节约发送时间，可以考虑先上传到CDN服务，这样还可以以后复用。 至于阻塞问题，建议缩减代码，提供一个可以公布代码的最小测试。

请问这个是padplus吗，怎么获取这个的token和文档，我没找到入口

**Comment by hcfw007** [comment]
不是啊，这里说的都是workpro

**Comment by aqpmzngldh** [comment]
> 不是啊，这里说的都是workpro

workpro是企业微信的支持吗

**Comment by hcfw007** [comment]
是的

**Comment by sclihuiming** [comment]
这里联系到上面的开发者拿到了最小可运行代码。 发送图片的时候确实会出现阻塞的情况。
```javascript
const fileBox = FileBox.fromUrl(remoteUrls[indexRemoteUrl].path);
await fileBox.ready();
await message.say(fileBox);
```
最后发现仅仅是加载这个图片链接的时候会出现阻塞情况。 我将图片上传到我北京地区的ali oss上面后，发送速度处理正常区间内。
沟通后，知道上述案例图片链接实在**香港服务器**上， 由于token服务器在国内，访问香港服务器的图片可能会出现网络波动的情况。 建议将图片服务器放在大陆地区再测试

**Comment by hcfw007** [comment]
已解决，关闭。
