### ISSUE TITLE
[BUG]WorkPro:报错提示Token不存在

### ISSUE THREAD

**Issue by chenyl20170103** [wechaty/puppet-service-providers#445]
![image](https://github.com/wechaty/puppet-supports/assets/169233231/376fbc5f-76c3-4489-b508-7cf5186d7711)
启动的时候按照文档要求进行配置，但是一直报错。麻烦帮我看看，谢谢

**Comment by hcfw007** [comment]
没有配置正确，如果配置正确，发现服务地址会是 token-service-discovery-test.juzibot.com 而不是 api.chatie.io

**Comment by chenyl20170103** [comment]
![image](https://github.com/wechaty/puppet-supports/assets/169233231/398bfda8-b255-417a-b5ac-9887bfae19bd)
是按照文档要求配置的呢

**Comment by hcfw007** [comment]
请尝试这个demo https://github.com/RPAChat/workpro-getting-started/tree/latest-features

**Comment by chenyl20170103** [comment]
![image](https://github.com/wechaty/puppet-supports/assets/169233231/2a3ad618-00a2-4424-9f03-447c5fe5e8e8)
老师，您好，还是一样的问题，token不存在！

**Comment by hcfw007** [comment]
你用 echo 看看环境变量有没有配置成功吧。。。我不太了解Windows的环境变量配置

**Comment by chenyl20170103** [comment]
![image](https://github.com/wechaty/puppet-supports/assets/169233231/2c5f9c6a-b7a7-40a3-b47c-8423ecf9e723)
环境配置是没有问题的，这些配置项我都检查过。

**Comment by chenyl20170103** [comment]
生成二维码之后，用企业微信扫码登录，提示登录失败，是什么原因？

**Comment by hcfw007** [comment]
是手机提示还是workpro提示？截图或者录屏看看？

**Comment by chenyl20170103** [comment]
手机扫码的时候，在手机扫描区域提示，没法儿截图

**Comment by chenyl20170103** [comment]
问题已解决了，谢谢老师

**Comment by hcfw007** [comment]
解决了就好，那关闭了。
