### ISSUE TITLE
[FEAT]WorkPro:验证码已经输入过了，然后隔2分钟就要求扫码验证，扫完之后隔2分钟又来，一直重复

### ISSUE THREAD

**Issue by 1061168609** [wechaty/puppet-service-providers#446]
![04b0c63d7824bef09dd9ba42ba48d6a](https://github.com/wechaty/puppet-supports/assets/127094540/216a1a9b-fd12-45d7-87e3-0fbd2c8eadec)

**Comment by 1061168609** [comment]
![image](https://github.com/wechaty/puppet-supports/assets/127094540/d82fcc81-27f2-4033-8385-3277789593a8)
登录一会就掉线哎，麻烦看下是什么原因呢

**Comment by hcfw007** [comment]
这个是企微的安全机制，在异地登录就会这样。解决方法是每次掉线之后在2分钟之内上线就行。

**Comment by 1061168609** [comment]
每次都要扫码吗  那不得经常掉线了

**Comment by hcfw007** [comment]
2分钟以内上就算通过验证了，就不会再掉了

**Comment by 1061168609** [comment]
7点多到现在出现每隔10分钟左右就要求验证一次扫码，这是异常情况吗  这种要怎么处理呢

**Comment by hcfw007** [comment]
![image](https://github.com/wechaty/puppet-supports/assets/13669999/a4dbaa7d-fe82-483b-9d3b-326771f5b45f)
如企微通知所说，必须2分钟内登录上才行。

**Comment by 1061168609** [comment]
那这个还咋自动监听啊 不得一个人看着经常扫码   不然就掉线？

**Comment by hcfw007** [comment]
只要一次通过了验证，后续就不会掉了。你持续掉是因为你一直没在企微要求的时间内验证。

**Comment by 1061168609** [comment]
![56a94ca18f4a3190f2ff665ab76efc0](https://github.com/wechaty/puppet-supports/assets/127094540/a74cb083-bffd-485a-b7e5-54ca9a646bc8)
昨天15点验证之后，早上掉线了需要重新扫码登录，请问一下这是正常情况吗 每天都会掉线是吗

**Comment by hcfw007** [comment]
没听过这种反馈，正常通过验证后就不怎么掉了。（除非触发了人脸识别，导致手机端都掉线了，手机端如果掉了那PC端肯定也会掉）

**Comment by timfee2024** [comment]
遇到相同的问题，在2分钟内完成验证后，过段时间又会自动掉线

**Comment by timfee2024** [comment]
![17eb71a987d6dc4d20c21442a1ca209f](https://github.com/wechaty/puppet-supports/assets/169882140/1d2ae224-cb77-4029-bc3d-3d6a2a32c088)
完成验证后过了三分钟又提示验证，然后一直重复要验证

**Comment by hcfw007** [comment]
只能说你肯定没在2分钟内扫码

**Comment by 1061168609** [comment]
> 只能说你肯定没在2分钟内扫码

额 图片都在那显示已验证了，怎么可能没扫码呢，没扫码就直接掉线了

**Comment by hcfw007** [comment]
就是要离线后两分钟内再扫上线，不是要去点“是我操作”什么的

**Comment by hcfw007** [comment]
无反馈，关闭。
