### ISSUE TITLE
企业微信扫码一直提示输入验证码登录

### ISSUE THREAD

**Issue by JohnLi94** [wechaty/puppet-service-providers#447]
想把我的企业微信账号变成自动回复机器人，但是工程编译后出的码扫一直提示要验证码登录，不知道问题出在哪。

**Comment by JohnLi94** [comment]
@su-chang @hcfw007

**Comment by hcfw007** [comment]
没懂你意思。。需要验证码是正常的呀，现在企微在新设备登录就是要验证码的。

**Comment by JohnLi94** [comment]
> 没懂你意思。。需要验证码是正常的呀，现在企微在新设备登录就是要验证码的。

![image](https://github.com/wechaty/puppet-supports/assets/65105969/17364f62-7fc0-4411-ac17-92ba59827fdb)

昨天看了您写的demo尝试后发现报错，能帮忙分析一下吗

**Comment by hcfw007** [comment]
> > 没懂你意思。。需要验证码是正常的呀，现在企微在新设备登录就是要验证码的。
> 
> ![image](https://private-user-images.githubusercontent.com/65105969/330648231-17364f62-7fc0-4411-ac17-92ba59827fdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NDQyNzIsIm5iZiI6MTcxNTc0Mzk3MiwicGF0aCI6Ii82NTEwNTk2OS8zMzA2NDgyMzEtMTczNjRmNjItN2ZjMC00NDExLWFjMTctOTJiYTU5ODI3ZmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAzMzI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxODcxYTBiNjA4YjRlYTA2YmM4MDc0Y2U0ZGI1YTliYjFhYzEwYjk5OGI2NDg2MjE5NmU5ZDJkMWJkMGUyYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RPPQvCJNkVaAEJFhYBNHf4iO6h6GoV7Rfdrw3L4kn5w)
> 
> 昨天看了您写的demo尝试后发现报错，能帮忙分析一下吗

这个不是我写的哈。https://github.com/RPAChat/workpro-getting-started/tree/latest-features 这个是，可以试试。

你这个报错是QrcodeTerminal没引入导致的。
