### ISSUE TITLE
Other: 对接wechaty微信和whatsapp问题已解决，有需要可以私聊我

### ISSUE THREAD

**Issue by chenzhiqiang0518** [wechaty/puppet-service-providers#448]
Please make sure you have read the [Wechaty Puppet Service](https://wechaty.js.org/docs/puppet-services/) from Wechaty Official Website before you continue writting this issue.

## Question
踩坑一系列wechaty和puppet问题，终于部署运行正常

**Comment by JohnLi94** [comment]
请文有可以把企业微信账号变成机器人的例子吗

**Comment by huan** [comment]
close due to off-topic

**Comment by huan** [comment]
We have a Wechaty Discord server for non-issue-related conversations.

Join at https://discord.gg/7q8NBZbQzt
