### ISSUE TITLE
[BUG]WorkPro: 一段时间不活跃，发现grpc 报错： GError: no grpc manager

### ISSUE THREAD

**Issue by liangzhicheng0423** [wechaty/puppet-service-providers#449]
**Describe the bug**

在一段时间未活跃后，控制台相继报了一些错误信息，看起来是grpc断开链接了。请问这个问题是什么原因导致的，有什么解决办法？

** Info **
 - Platform: "Linux"
 - Runtime version: node v21.7.3
 - Wechaty version:  "@juzi/wechaty": "^1.0.66",
 - Wechaty Puppet version:  "@juzi/wechaty-puppet": "1.0.61",
 - Wechaty Puppet  Service version: "@juzi/wechaty-puppet-service": "1.0.69",

** 偶现步骤 **
Steps to reproduce the behavior: 约两小时没有消息活跃后，问题出现

** 预期行为 **
Expected behavior: 期望在不重启bot的情况下，长期运行

**Screenshots**
1. 先报了一个WatchDogAgent 的 error：
![image](https://github.com/wechaty/puppet-supports/assets/92916529/75ab2c44-4d81-4b70-a0f5-ffd672b82af9)
2. 看起来是自恢复了，之后又报了"no grpc manager"
![image](https://github.com/wechaty/puppet-supports/assets/92916529/e8baa759-1734-4937-a5cc-e1d1cfe38ea4)
3. 过了不到一分钟，控制台打印了新的错误信息
![image](https://github.com/wechaty/puppet-supports/assets/92916529/817f9437-e6f4-44f9-8822-a8a72c29a9b4)

**Comment by hcfw007** [comment]
连接断开是很正常的，例如我们平均每两周就会有更新，期间就会断开。需要监听 error 和 logout 事件，进行重启 bot 的处理。

**Comment by hcfw007** [comment]
无反馈，关闭。
