### ISSUE TITLE
微信语音有时播放不了

### ISSUE THREAD

**Issue by nicholasDxy** [wechaty/puppet-service-providers#452]
Please make sure you have read the [Wechaty Puppet Service](https://wechaty.js.org/docs/puppet-services/) from Wechaty Official Website before you continue writting this issue.

## Question
silk文件发送出去有的时候无法播放,我的方式是
```python
const fileBox = FileBox.fromFile(reply.audioPath)
fileBox.mimeType = "audio/silk";
talker.say(fileBox)
```

**Comment by rookiexun** [comment]
我遇到同样的问题，无法播放。企微端显示文件丢失。我的解决方案：猜测可能是跟tx文件存储有关，每次发送修改了文件名称。成功了

**Comment by su-chang** [comment]
@nicholasDxy 可以参考下 @rookiexun 的建议。
