### ISSUE TITLE
[BUG]WorkPro:emoji图片的URL拿不到

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#454]
![image](https://github.com/wechaty/puppet-supports/assets/168573378/20831c4a-47f1-4902-806c-d552ba0d61e7)
![image](https://github.com/wechaty/puppet-supports/assets/168573378/08228338-d9a4-4233-a6f0-883001ea0d51)

**Comment by hcfw007** [comment]
![image](https://github.com/wechaty/puppet-supports/assets/13669999/fc4e2091-2d66-4934-8562-b8631bdf8031)
这不是有吗

**Comment by IQZZ020501** [comment]
> ![image](https://private-user-images.githubusercontent.com/13669999/332714484-fc4e2091-2d66-4934-8562-b8631bdf8031.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzMxOTcsIm5iZiI6MTcxNjM3Mjg5NywicGF0aCI6Ii8xMzY2OTk5OS8zMzI3MTQ0ODQtZmM0ZTIwOTEtMmQ2Ni00OTM0LTg1NjItYjg2MzFiZGY4MDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEwMTQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MTQ0MzcyOWZhYjUyNGE2NzM1ZjA1OWM0OTZhMWFmZDNkNTEwMDNiYjZiMzgzN2Y3ZGFiZDViYjRiZDFiNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uIscWN4rFAq8zdf2Z-EldgrS3pShGfOHk3QODzW6QtE) 这不是有吗

我的意思是FileBox这个对象里面是有remoteURL这个值，但是我不能从FileBox这个对象中拿到remoteURL这个值

**Comment by hcfw007** [comment]
确实filebox没有提供暴露这个的方法。只能 (filebox as any).remoteURL

**Comment by IQZZ020501** [comment]
> 确实filebox没有提供暴露这个的方法。只能 (filebox as any).remoteURL

可以了，谢谢

**Comment by hcfw007** [comment]
已解决，关闭。
