### ISSUE TITLE
[BUG]WorkPro:刚从试用账号升级正式token，企业微信机器人显示“请到平台配置Openai apikey 参数方可使用”

### ISSUE THREAD

**Issue by SnailyJerry** [wechaty/puppet-service-providers#455]
<img width="709" alt="截屏2024-05-22 19 10 40" src="https://github.com/wechaty/puppet-supports/assets/43501688/079e614b-d4ba-4dc6-a6ae-65a40c77e1ef">
<img width="980" alt="截屏2024-05-22 18 57 10" src="https://github.com/wechaty/puppet-supports/assets/43501688/f987eead-f73f-4076-910e-7c46e628f777">
![5ac780bec773efd1981f7ff8b4af6ff4](https://github.com/wechaty/puppet-supports/assets/43501688/900575b0-bc3c-4876-9505-5d25b32aae07)

**Comment by su-chang** [comment]
@SnailyJerry 可以再试下看看

并且上述错误提示和企微微信并无关系，可能是你们内部对接了Openai的key，没有配置对导致的。

**Comment by hcfw007** [comment]
无后续反馈，issue关闭。
