### ISSUE TITLE
[BUG]WorkPro:GError: Wechaty Puppet Service requires a SNI as prefix of the token from version 0.30 and later

### ISSUE THREAD

**Issue by bdavidy** [wechaty/puppet-service-providers#457]
我下载了demo：  
https://github.com/RPAChat/workpro-getting-started
在index.ts 中填写了申请的免费7天token
执行完 
npm intall
npm start 
控制台报错： 
GError: Wechaty Puppet Service requires a SNI as prefix of the token from version 0.30 and later
You can add the "insecure_" prefix to your token
like: "insecure_32563467436536543564363ssd"
and try again.

当我在token中增加了前缀： "insecure_
再次运行时，又报错：
details: 'Wechaty service discovery / resolution failed for target wechaty://token-service-discovery-test.juzibot.com/insecure_32563467436536543564363ssd: token "insecure_32563467436536543564363ssd" does not exist

注： 上面的token是随便写的，不是真实token

请问如何解决？

**Comment by su-chang** [comment]
https://token-service-discovery-test.juzibot.com/v0/hosties/YOUR_TOKEN

先用这个试下能否获取到对应的ip和port吧

**Comment by hcfw007** [comment]
无后续反馈，issue关闭。
