### ISSUE TITLE
WXWork: 我联系客服续费，没有回应，在线等！！！

### ISSUE THREAD

**Issue by chenyl20170103** [wechaty/puppet-service-providers#458]
您好！我想续费，联系了客服老师，但是没有反应，能否帮我沟通一下呢？

**Comment by binsee** [comment]
收到，转交同事跟进

**Comment by su-chang** [comment]
@chenyl20170103 明天可以再和客服联系下，并提供该issue链接和要续费的token

**Comment by su-chang** [comment]
@chenyl20170103 使用的是个微token还是企微token呢？token的前缀发一下吧。
