### ISSUE TITLE
[FEAT]WorkPro:支不支持发送朋友圈消息

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#459]

**Comment by su-chang** [comment]
支持，使用@juzi/wechaty 来体验该功能。

**Comment by IQZZ020501** [comment]
> 支持，使用@juzi/wechaty 来体验该功能。
麻烦您可以给一个示例代码吗，我在文档中没有找到

**Comment by su-chang** [comment]
示例如下：

```ts
const builder = bot.Post.builder()
builder.add('这是一条图片朋友圈') // 文字内容
const imgUrl = '这里放对应的图片链接'
builder.add(FileBox.fromUrl(imgUrl))
builder.type(PUPPET.types.Post.Moment)
const post = await builder.build()
const publishedPost = await bot.publish(post)
```

**Comment by IQZZ020501** [comment]
> 示例如下：
> 
> ```ts
> const builder = bot.Post.builder()
> builder.add('这是一条图片朋友圈') // 文字内容
> const imgUrl = '这里放对应的图片链接'
> builder.add(FileBox.fromUrl(imgUrl))
> builder.type(PUPPET.types.Post.Moment)
> const post = await builder.build()
> const publishedPost = await bot.publish(post)
> ```

好的，谢谢

**Comment by IQZZ020501** [comment]
> 示例如下：
> 
> ```ts
> const builder = bot.Post.builder()
> builder.add('这是一条图片朋友圈') // 文字内容
> const imgUrl = '这里放对应的图片链接'
> builder.add(FileBox.fromUrl(imgUrl))
> builder.type(PUPPET.types.Post.Moment)
> const post = await builder.build()
> const publishedPost = await bot.publish(post)
> ```
还想请问一下，一次性可以指定多少张图片，指定多张照片只需要用逗号隔开就行了嘛？，支持发送视频、链接这两种类型吗

**Comment by su-chang** [comment]
和微信朋友圈要求一致。

**Comment by IQZZ020501** [comment]
> 和微信朋友圈要求一致。

一次性指定9张图片如何指定呢？

**Comment by hcfw007** [comment]
```ts
const builder = bot.Post.builder()
builder.add('这是一条图片朋友圈') // 文字内容
builder.add(FileBox.fromUrl(imgUrl1))
builder.add(FileBox.fromUrl(imgUrl2))
builder.add(FileBox.fromUrl(imgUrl3))
builder.add(FileBox.fromUrl(imgUrl4))
builder.add(FileBox.fromUrl(imgUrl5))
builder.add(FileBox.fromUrl(imgUrl6))
builder.type(PUPPET.types.Post.Moment)
const post = await builder.build()
const publishedPost = await bot.publish(post)
```

**Comment by IQZZ020501** [comment]
> ```ts
> const builder = bot.Post.builder()
> builder.add('这是一条图片朋友圈') // 文字内容
> builder.add(FileBox.fromUrl(imgUrl1))
> builder.add(FileBox.fromUrl(imgUrl2))
> builder.add(FileBox.fromUrl(imgUrl3))
> builder.add(FileBox.fromUrl(imgUrl4))
> builder.add(FileBox.fromUrl(imgUrl5))
> builder.add(FileBox.fromUrl(imgUrl6))
> builder.type(PUPPET.types.Post.Moment)
> const post = await builder.build()
> const publishedPost = await bot.publish(post)
> ```

谢谢

**Comment by binsee** [comment]
@IQZZ020501 使用 Workpro 方案强烈不建议使用朋友圈功能，有较大封号风险。

**Comment by IQZZ020501** [comment]
> @IQZZ020501 使用 Workpro 方案强烈不建议使用朋友圈功能，有较大封号风险。

那有什么规避或者减小这个风险的方法吗

**Comment by binsee** [comment]
> > @IQZZ020501 使用 Workpro 方案强烈不建议使用朋友圈功能，有较大封号风险。
> 
> 那有什么规避或者减小这个风险的方法吗

workpro 方案现在不能用此功能，除非官方在 win 平台客户端上开放了这个功能。

**Comment by IQZZ020501** [comment]
> > > @IQZZ020501 使用 Workpro 方案强烈不建议使用朋友圈功能，有较大封号风险。
> > 
> > 
> > 那有什么规避或者减小这个风险的方法吗
> 
> workpro 方案现在不能用此功能，除非官方在 win 平台客户端上开放了这个功能。

好的感谢
