### ISSUE TITLE
[BUG]WorkPro: 给联系人发送消息，调用消息发送函数，项目启动时报错。

### ISSUE THREAD

**Issue by chenyl20170103** [wechaty/puppet-service-providers#461]
源代码如下：
![image](https://github.com/wechaty/puppet-supports/assets/169233231/69940210-199c-4396-8c9c-429a2f27561f)

启动报错日志如下：
![image](https://github.com/wechaty/puppet-supports/assets/169233231/0673a9ac-5416-459e-9266-b6e091c4d433)

版本依赖如下：
![image](https://github.com/wechaty/puppet-supports/assets/169233231/28f82ba7-1238-4c06-a369-14e41b09a58f)

**Comment by sclihuiming** [comment]
这个可能就是你的toUser这个id没有传对，或者toUser对应的联系人就不存在。 项目启动后，需要等待ready事件后再进行发送消息操作

**Comment by chenyl20170103** [comment]
好的，谢谢！问题已解决，是TypeScript语法错误，跟咱们工具没关系
