### ISSUE TITLE
[BUG]WorkPro:报错Error: 0 total errors! 导致node进程退出 

### ISSUE THREAD

**Issue by Lyq0055** [wechaty/puppet-service-providers#464]
<img width="622" alt="image" src="https://github.com/wechaty/puppet-supports/assets/88149932/528c1918-5f0a-41e0-ac61-bfa8c44c8c6e"> 是什么原因？

**Comment by hcfw007** [comment]
哥们，我电脑开不开机是什么原因？
你得多提供点日志，最好讷讷共有报错的代码的上下文，要不然怎么知道你是怎么调用的。

**Comment by Lyq0055** [comment]
> 哥们，我电脑开不开机是什么原因？ 你得多提供点日志，最好讷讷共有报错的代码的上下文，要不然怎么知道你是怎么调用的。

我不知道调用哪个方法报错的 复现不出来 只知道这个报错导致进程退出了

**Comment by binsee** [comment]
> 我不知道调用哪个方法报错的 复现不出来 只知道这个报错导致进程退出了

比较简单的办法是点击 `at /home/wechaty ..... /contact.ts:235:17` 这行，去代码文件里看下报错的位置，找调用上下文。
光截图真没多大用，又无法复现现场，不知道你装的依赖版本也无法定位代码。
给的信息越全，越有助于查问题。

**Comment by Lyq0055** [comment]
> > 我不知道调用哪个方法报错的 复现不出来 只知道这个报错导致进程退出了
> 
> 比较简单的办法是点击 `at /home/wechaty ..... /contact.ts:235:17` 这行，去代码文件里看下报错的位置，找调用上下文。 光截图真没多大用，又无法复现现场，不知道你装的依赖版本也无法定位代码。 给的信息越全，越有助于查问题。

<img width="326" alt="image" src="https://github.com/wechaty/puppet-supports/assets/88149932/ef19c5ca-6bcf-42d1-b005-8d25b7754335">
<img width="377" alt="image" src="https://github.com/wechaty/puppet-supports/assets/88149932/edbaa56e-9df3-40fa-a95c-cc3f6c4779f5">
只有这两个地方用了Contact方法 依赖版本是这个
<img width="343" alt="image" src="https://github.com/wechaty/puppet-supports/assets/88149932/36129798-1bba-40f3-8d56-7afb45f2f78b">

**Comment by Lyq0055** [comment]
<img width="401" alt="image" src="https://github.com/wechaty/puppet-supports/assets/88149932/b41b555d-10ea-4f0f-a359-34dbcf8664ce">
发现是mentionText这个方法报的错

**Comment by su-chang** [comment]
提供详细的错误信息吧，或者最小代码试试是什么问题导致的。
