### ISSUE TITLE
[BUG]WorkPro:消息缓存的问题

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#465]
我原本在A电脑上登陆了企业微信，使用bot发了很多条消息，然后在A电脑把bot关掉了，但是企业微信没退。我又在B电脑登陆了，用的同一个bot token，然后在B电脑就会输出并推送我在A电脑上已经发过的消息，这是因为消息缓存没处理干净吗？

**Comment by hcfw007** [comment]
不是，这是设计如此。会缓存事件的seq并根据seq判断哪些事件没推过。如果是新环境没有seq，则会有限的推出部分历史事件。

**Comment by IQZZ020501** [comment]
> 不是，这是设计如此。会缓存事件的seq并根据seq判断哪些事件没推过。如果是新环境没有seq，则会有限的推出部分历史事件。

如果我在A设备关了bot退出了企业微信，重新在B设备登录企业微信，这种情况是不是就不会存在了

**Comment by hcfw007** [comment]
也是会的。

**Comment by IQZZ020501** [comment]
> 也是会的。

还想请教一下，发送朋友圈的时候可以指定多张图一起发送吗

**Comment by hcfw007** [comment]
可以啊，最多9张。

**Comment by IQZZ020501** [comment]
> 可以啊，最多9张。

请问如何同时发送9张

**Comment by su-chang** [comment]
参数是个数组，往数组添加9个图片素材即可。

**Comment by IQZZ020501** [comment]
> 参数是个数组，往数组添加9个图片素材即可。

链接也是使用同样的方式吗
