### ISSUE TITLE
如何使用更多的官方Wechaty接口

### ISSUE THREAD

**Issue by ppl-wei** [wechaty/puppet-service-providers#466]
例如官方提供的wechaty.logonoff()、wechaty.userSelf()。
我在@juzi/wechaty-puppet中并没有找到该接口。
我应该怎么做？目前我比较想使用这两个接口。
![image](https://github.com/wechaty/puppet-supports/assets/62246434/c415fa37-618b-4f03-943d-4e5a9e0dd691)

**Comment by hcfw007** [comment]
直接用就行。这两个接口是wechaty上面的，你在wechaty-puppet中肯定找不到丫。

**Comment by ppl-wei** [comment]
目前做的是企业微信开发，用的是这个 @juzi/wechaty
显示的是没有这个接口
![image](https://github.com/wechaty/puppet-supports/assets/62246434/1f3dd0dd-9c5e-4907-9218-91c1f50bd999)

**Comment by su-chang** [comment]
可以用 `bot.currentUser` 代替。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
