### ISSUE TITLE
[BUG]WorkPro:试用账号启动报错

### ISSUE THREAD

**Issue by wcljava2018** [wechaty/puppet-service-providers#471]
UNAVAILABLE: Wechaty service discovery / resolution failed for target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_ token "puppet_workpro_0" does not exist 本地环境也配置了，token也重启了有人遇到吗

**Comment by su-chang** [comment]
现在还有这个问题么？可以提供token的后六位。

**Comment by wcljava2018** [comment]
还是不行后六位1e3271



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月2日(周日) 晚上8:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wechaty/puppet-supports] [BUG]WorkPro:试用账号启动报错 (Issue #471)




 
现在还有这个问题么？可以提供token的后六位。

**Comment by wcljava2018** [comment]
> 现在还有这个问题么？可以提供token的后六位。

![Uploading image.png…]()

**Comment by wcljava2018** [comment]
> 现在还有这个问题么？可以提供token的后六位。
还是不行后六位1e327，启动报GrpcManager initClient() TLS: disabled (INSECURE)
12:50:19 WARN ResolverWechaty updateResolution() address not found target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_xxx1e3271: token does not exist

**Comment by hcfw007** [comment]
我这边测试是可以正常连接的。请尝试在运行环境中访问
https://token-service-discovery-test.juzibot.com/v0/hosties/puppet_workpro_xxx1e3271
看看能否获取到结果。

**Comment by wcljava2018** [comment]
> 我这边测试是可以正常连接的。请尝试在运行环境中访问 https://token-service-discovery-test.juzibot.com/v0/hosties/puppet_workpro_xxx1e3271 看看能否获取到结果。

获取的ip都是0.0.0这种正常吗

**Comment by hcfw007** [comment]
不正常

**Comment by hcfw007** [comment]
你有把 puppet_workpro_xxx1e3271 替换为你的token吧？

**Comment by wcljava2018** [comment]
> 你有把 puppet_workpro_xxx1e3271 替换为你的token吧？
有的不行

> https://token-service-discovery-test.juzibot.com/v0/hosties/puppet_workpro_xxx1e3271



> 你有把 puppet_workpro_xxx1e3271 替换为你的token吧？

{
    "host": "52.82.12.245",
    "ip": "52.82.12.245",
    "port": 4001
}
现在返回这个了

**Comment by wcljava2018** [comment]
> 你有把 puppet_workpro_xxx1e3271 替换为你的token吧？
有的不行

> https://token-service-discovery-test.juzibot.com/v0/hosties/puppet_workpro_xxx1e3271



> 你有把 puppet_workpro_xxx1e3271 替换为你的token吧？

{
    "host": "52.82.12.245",
    "ip": "52.82.12.245",
    "port": 4001
}
现在返回这个了

**Comment by hcfw007** [comment]
这个是对的，现在再运行你的bot试试？如果有错误日志，请多截一点。

**Comment by wcljava2018** [comment]
> 这个是对的，现在再运行你的bot试试？如果有错误日志，请多截一点。

![image](https://github.com/wechaty/puppet-supports/assets/37286062/c0f812fc-6ea9-42af-a86e-18e50b739477)

**Comment by wcljava2018** [comment]
> > 这个是对的，现在再运行你的bot试试？如果有错误日志，请多截一点。
> 
> ![image](https://private-user-images.githubusercontent.com/37286062/336021516-c0f812fc-6ea9-42af-a86e-18e50b739477.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDgxMTcsIm5iZiI6MTcxNzQwNzgxNywicGF0aCI6Ii8zNzI4NjA2Mi8zMzYwMjE1MTYtYzBmODEyZmMtNmVhOS00MmFmLWE4NmUtMThlNTBiNzM5NDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA5NDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZWY4YTM4ZTM2NDk1NDUyODRhNTA5ZTEwNWZjMzdkMjQ0ZGM5OTc4YjczZmE3YzQ5ZWM2MWEzZWUzNDQxYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.23biuJgKZL3r5RyMoyTdiifiEQ9oFkg_vaD7CfVe93I)



> > 这个是对的，现在再运行你的bot试试？如果有错误日志，请多截一点。
> 
> ![image](https://private-user-images.githubusercontent.com/37286062/336021516-c0f812fc-6ea9-42af-a86e-18e50b739477.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDgxMTcsIm5iZiI6MTcxNzQwNzgxNywicGF0aCI6Ii8zNzI4NjA2Mi8zMzYwMjE1MTYtYzBmODEyZmMtNmVhOS00MmFmLWE4NmUtMThlNTBiNzM5NDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA5NDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZWY4YTM4ZTM2NDk1NDUyODRhNTA5ZTEwNWZjMzdkMjQ0ZGM5OTc4YjczZmE3YzQ5ZWM2MWEzZWUzNDQxYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.23biuJgKZL3r5RyMoyTdiifiEQ9oFkg_vaD7CfVe93I)

还是不行呀

**Comment by wcljava2018** [comment]
> > > 这个是对的，现在再运行你的bot试试？如果有错误日志，请多截一点。
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/37286062/336021516-c0f812fc-6ea9-42af-a86e-18e50b739477.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDgxMTcsIm5iZiI6MTcxNzQwNzgxNywicGF0aCI6Ii8zNzI4NjA2Mi8zMzYwMjE1MTYtYzBmODEyZmMtNmVhOS00MmFmLWE4NmUtMThlNTBiNzM5NDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA5NDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZWY4YTM4ZTM2NDk1NDUyODRhNTA5ZTEwNWZjMzdkMjQ0ZGM5OTc4YjczZmE3YzQ5ZWM2MWEzZWUzNDQxYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.23biuJgKZL3r5RyMoyTdiifiEQ9oFkg_vaD7CfVe93I)
> 
> > > 这个是对的，现在再运行你的bot试试？如果有错误日志，请多截一点。
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/37286062/336021516-c0f812fc-6ea9-42af-a86e-18e50b739477.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDgxMTcsIm5iZiI6MTcxNzQwNzgxNywicGF0aCI6Ii8zNzI4NjA2Mi8zMzYwMjE1MTYtYzBmODEyZmMtNmVhOS00MmFmLWE4NmUtMThlNTBiNzM5NDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA5NDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZWY4YTM4ZTM2NDk1NDUyODRhNTA5ZTEwNWZjMzdkMjQ0ZGM5OTc4YjczZmE3YzQ5ZWM2MWEzZWUzNDQxYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.23biuJgKZL3r5RyMoyTdiifiEQ9oFkg_vaD7CfVe93I)
> 
> 还是不行呀

帮忙再看看，或是用我的token帮忙调试一下，这样可能会比较快吧

**Comment by hcfw007** [comment]
![image](https://github.com/wechaty/puppet-supports/assets/13669999/6315ba27-66ea-456c-94c0-5341e9fbe71e)
就是用你的 token 连接过的

**Comment by wcljava2018** [comment]
> ![image](https://private-user-images.githubusercontent.com/13669999/336029129-6315ba27-66ea-456c-94c0-5341e9fbe71e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDk0NjgsIm5iZiI6MTcxNzQwOTE2OCwicGF0aCI6Ii8xMzY2OTk5OS8zMzYwMjkxMjktNjMxNWJhMjctNjZlYS00NTZjLTk0YzAtNTM0MWU5ZmJlNzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDEwMDYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZTE4ODIyZWNhZWE1ZGMzMzY2NmUzYjI3NjE1YTFjZjk2NzdiMjAxNGNjZmMzNjZhYzc0ZDY1YzEwNjgzNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZOG9tCQ5CmuPGL-sPh4QF_4hDAkIU5I_6eEWbW6p5nI) 就是用你的 token 连接过的

那我为啥还好报错呢是不是node工程依赖不一样

**Comment by wcljava2018** [comment]
> > ![image](https://private-user-images.githubusercontent.com/13669999/336029129-6315ba27-66ea-456c-94c0-5341e9fbe71e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDk0NjgsIm5iZiI6MTcxNzQwOTE2OCwicGF0aCI6Ii8xMzY2OTk5OS8zMzYwMjkxMjktNjMxNWJhMjctNjZlYS00NTZjLTk0YzAtNTM0MWU5ZmJlNzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDEwMDYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZTE4ODIyZWNhZWE1ZGMzMzY2NmUzYjI3NjE1YTFjZjk2NzdiMjAxNGNjZmMzNjZhYzc0ZDY1YzEwNjgzNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZOG9tCQ5CmuPGL-sPh4QF_4hDAkIU5I_6eEWbW6p5nI) 就是用你的 token 连接过的
> 
> 那我为啥还好报错呢是不是node工程依赖不一样

能不能发一个工程报给我，我感觉你们的工程包跟官网的不一样

**Comment by wcljava2018** [comment]
> > ![image](https://private-user-images.githubusercontent.com/13669999/336029129-6315ba27-66ea-456c-94c0-5341e9fbe71e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDk0NjgsIm5iZiI6MTcxNzQwOTE2OCwicGF0aCI6Ii8xMzY2OTk5OS8zMzYwMjkxMjktNjMxNWJhMjctNjZlYS00NTZjLTk0YzAtNTM0MWU5ZmJlNzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDEwMDYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZTE4ODIyZWNhZWE1ZGMzMzY2NmUzYjI3NjE1YTFjZjk2NzdiMjAxNGNjZmMzNjZhYzc0ZDY1YzEwNjgzNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZOG9tCQ5CmuPGL-sPh4QF_4hDAkIU5I_6eEWbW6p5nI) 就是用你的 token 连接过的
> 
> 那我为啥还好报错呢是不是node工程依赖不一样

扫码登录后提示要输入验证码，但是没输入的地方，也没有登录的按钮？

**Comment by wcljava2018** [comment]
扫码登录提示请输入企业微信手机端展示的验证码，以继续登录

**Comment by hcfw007** [comment]
验证码问题请参考置顶Issue。

**Comment by AIAmber** [comment]
验证码问题我准备了一个最小demo版本, 稍后上传

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
