### ISSUE TITLE
[BUG]WorkPro: 获取机器人logon/logoff 的状态异常

### ISSUE THREAD

**Issue by chenyl20170103** [wechaty/puppet-service-providers#472]
我们服务器重启后，需要检测机器人登录状态，调用logonoff()函数，提示函数不存在。代码如下：
![1717403180430](https://github.com/wechaty/puppet-supports/assets/169233231/db087c55-65e8-4e23-a135-df095203ad5c)

报错内容如下：
![image](https://github.com/wechaty/puppet-supports/assets/169233231/9d9a08a9-224b-4166-ab8b-40961134d72f)

**Comment by hcfw007** [comment]
logonoff 已 deprecate ，现在请使用 isLoggedIn 
实际 logonoff 仍然存在，用 js 可以调用，但 ts 会提示类型错误。

**Comment by chenyl20170103** [comment]
有没有更新的文档呀？有的话麻烦提供一下，不然每次都需要等官方解释，很拖进度哦。

**Comment by chenyl20170103** [comment]
另外，bot.isLoggedIn有没有调用次数限制？我担心引起微信风控。因为我在机器人心跳检测里面加了判定登录状态的处理，调用会比较频繁。代码如下：
// 获取机器人登录状态
		const isLoggedIn = await bot.isLoggedIn;
		console.info(`机器人状态：${isLoggedIn ? '在线' : '离线'}`);
		// 离线处理
		if (!isLoggedIn) {

		}

**Comment by hcfw007** [comment]
没有更新的文档。没有次数限制，查询的是本地的状态。

**Comment by hcfw007** [comment]
更合理的实践是监听 login 事件 和 logout 事件，而不是采用心跳的方式

**Comment by chenyl20170103** [comment]
好的，非常感谢，我采取您建议的方案来处理

**Comment by chenyl20170103** [comment]
我在发送链接消息时出现报错。代码如下：
<img width="383" alt="1717484125965" src="https://github.com/wechaty/puppet-supports/assets/169233231/e50cc71d-cb33-4cb3-b226-b031a750a6c2">
报错内容如下：
![image](https://github.com/wechaty/puppet-supports/assets/169233231/da6e173f-d446-4eff-a0d3-3f3927696a79)
请问，是方法过时了吗？

**Comment by hcfw007** [comment]
请使用类似这种方法来创建链接实例
```ts
const urlLink = new bot.UrlLink({
  'description': '微伴AI新能力，能帮助企业客户赋能企业销售管理，通过助力企业客户资产沉淀，提升企业销售效率',
  'thumbnailUrl': 'https://donut-docker.s3.cn-northwest-1.amazonaws.com.cn/link_msg/c9845758-325f-46c1-9464-0ef9b43ddc2f/2dbdca0b-ae4f-4196-adfe-897ce3a79d22.jpg',
  'title': '微伴新探索 ：『AI智能』赋能企业销售管理',
  'url': 'http://mp.weixin.qq.com/s?__biz=MzI0ODU0OTA1OQ==&mid=2247493243&idx=1&sn=bfb894e81c6e4a14839812c98969e4f6&chksm=e99dbdd7deea34c10141ecd0f38b781f08d1ab6e87e8c25be166fea137af18974505a5873e5e#rd'
})
```

**Comment by chenyl20170103** [comment]
非常感谢，已经解决了！
