### ISSUE TITLE
[FEAT]WorkPro: 关于红包数据解析的需求

### ISSUE THREAD

**Issue by chenyl20170103** [wechaty/puppet-service-providers#474]
你好，我们有收款的场景，需要解析红包数据，获取红包金额，进行一些业务逻辑的处理。但是目前接收到的消息，只是告知了消息类型属于红包，没有红包金额之类的数据，无法满足我们实际业务需求。能否提供一下技术指导？谢谢了！

**Comment by hcfw007** [comment]
这个我们讨论过，为了规避风险不进行红包、转账等涉及金钱的消息解析，请理解。

**Comment by chenyl20170103** [comment]
好的，了解了，谢谢！
