### ISSUE TITLE
WXWork: 企业微信发送文本消息，图片，小程序卡片都返回这个异常

### ISSUE THREAD

**Issue by KendrickTom** [wechaty/puppet-service-providers#480]
WorkproErrorCode: 23060, processSendMsgRsp(10696049295018865) contentType: Unknown send message failed! cgi error code: (-3004) message: .

**Comment by KendrickTom** [comment]
@hcfw007

**Comment by KendrickTom** [comment]
部分失败，大部分失败，但少量能成功

**Comment by hcfw007** [comment]
-3004 一般发生在给已经退出的群发消息。

**Comment by KendrickTom** [comment]
好，我确认了确实是这个问题，麻烦了
