### ISSUE TITLE
[BUG]WorkPro:语音发送sil文件

### ISSUE THREAD

**Issue by rookiexun** [wechaty/puppet-service-providers#484]
我通过FileBox.fromFile发送语音成功。
但是duration没办法规定时间。加上现有功能需要远程获取文件，就改为FileBox.fromUrl
全代码：
    const fileBox = FileBox.fromUrl("https://ip/profile/audio/sil/1718165366185.sil")
    fileBox.metadata = {
      duration: 3000,
    };
    await message.say(fileBox);
该地址可以访问到文件。企业微信发送成功，但是发送的是真正的"sil"格式的文件，而不是语音

**Comment by rookiexun** [comment]
![f05fbcee317ee49d517d123cf650d24](https://github.com/wechaty/puppet-supports/assets/55046248/677a110c-4941-4e10-91fa-dd3c8fefe259)

**Comment by hcfw007** [comment]
语音文件的格式是silk，你得提供这个mime类型。要么通过content-type头提供，要么通过扩展名提供。

**Comment by rookiexun** [comment]
fileBox.mimeType = "audio/silk";
我加了这个是不行的。
如果加content-type 具体header格式是什么样子的。

**Comment by rookiexun** [comment]
> 语音文件的格式是silk，你得提供这个mime类型。要么通过content-type头提供，要么通过扩展名提供。

    const options = {
      headers: {
        'content-type': 'audio/silk',
        'content-length': '1000'
      },
    }
    const fileBox = FileBox.fromUrl("https://2cm900472pf1.vicp.fun/profile/audio/sil/wzx.sil",options)
    console.log(fileBox.mediaType) // 打印为 'audio/silk'
    fileBox.mimeType = "audio/silk";
    fileBox.metadata = {
      duration: 3000,
    };
    await message.say(fileBox).

也是用了各种方法吧。。都不太行。有示例吗

**Comment by hcfw007** [comment]
这个mimeType得从 https://2cm900472pf1.vicp.fun/profile/audio/sil/wzx.sil 这个链接通过 HEAD 获取到是这个值，而不是你自己设置的。
![image](https://github.com/wechaty/puppet-supports/assets/13669999/333031b1-08d1-406e-a15f-c4f33e8171da)

**Comment by rookiexun** [comment]
呃，你的意思是在资源响应头上添加"Content-type"？我试一下

**Comment by rookiexun** [comment]
> 这个mimeType得从 https://2cm900472pf1.vicp.fun/profile/audio/sil/wzx.sil 这个链接通过 HEAD 获取到是这个值，而不是你自己设置的。 ![image](https://private-user-images.githubusercontent.com/13669999/339296242-333031b1-08d1-406e-a15f-c4f33e8171da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODM2MTIsIm5iZiI6MTcxODI4MzMxMiwicGF0aCI6Ii8xMzY2OTk5OS8zMzkyOTYyNDItMzMzMDMxYjEtMDhkMS00MDZlLWExNWYtYzRmMzNlODE3MWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEyNTUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOTc5NDhiNjA0M2ZjOTgwZmRjYTE5ZjY1NzM4NDlhODc3NmMxYjJkZTJlYjFkMzEwOGJlZGI2MmQ2OWUxZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jgcWZKolAIYa9-QfVpTIMPrO2uXaeCTwxG0HLCKBoPk)

可以了。非常感谢！
