### ISSUE TITLE
WorkPro: 请问当企微群人满200时，room.qrCode()返回的是什么

### ISSUE THREAD

**Issue by niu2593222694** [wechaty/puppet-service-providers#486]
正常返回的是 https://c.weixin.com/g/* ，然后将其转为二维码可扫码入群
请问当满200人不可扫码入群时，返回的是什么，这种情况不好测试，感谢

**Comment by hcfw007** [comment]
> 正常返回的是 https://c.weixin.com/g/* ，然后将其转为二维码可扫码入群 请问当满200人不可扫码入群时，返回的是什么，这种情况不好测试，感谢

应该是会抛错。

**Comment by niu2593222694** [comment]
> > 正常返回的是 https://c.weixin.com/g/* ，然后将其转为二维码可扫码入群 请问当满200人不可扫码入群时，返回的是什么，这种情况不好测试，感谢
> 
> 应该是会抛错。

收到谢谢
