### ISSUE TITLE
[BUG]WorkPro:获取不到外部联系人列表

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#488]
![image](https://github.com/wechaty/puppet-supports/assets/168573378/b9fceeb0-ad12-488f-8c7b-2b8345c58653)
这种方式只能获取到企业内部联系人没办法获取到外部，可以给一个获取外部联系人的demo吗

**Comment by su-chang** [comment]
内外部都是从这个方法返回的，需要针对coworker字段进行区分是否为内部联系人。

**Comment by IQZZ020501** [comment]
> 内外部都是从这个方法返回的，需要针对coworker字段进行区分是否为内部联系人。

可以给个示例吗，谢谢

**Comment by su-chang** [comment]
```ts
allContacts.filter(c => c.coworker())
```
