### ISSUE TITLE
[BUG]WorkPro:Error: Wechaty Puppet Service requires a SNI as prefix of the token from version 0.30 and later

### ISSUE THREAD

**Issue by David-AIsx** [wechaty/puppet-service-providers#489]
![image](https://github.com/wechaty/puppet-supports/assets/172709173/8ae69fcd-3374-4e27-8808-bb7684240c3a)
我通过docker部署了wechaty:0.65的服务，以下是我的部署命令
docker run -it -d --name wechaty -e WECHATY_LOG="verbose" -e WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true -e WECHATY_PUPPET_SERVICE_AUTHORITY="token-service-discovery-test.juzibot.com" -e WECHATY_PUPPET_WORKPRO_TOKEN="我的token"  -e WECHATY_PUPPET_SERVER_PORT="80" -e WECHATY_TOKEN="我的token" -p "0.0.0.0:80:80" wechaty/wechaty:0.65
我将docker镜像中产生的二维码配置到程序中后，在运行程序时，并不能如期出现登录二维码，而是出现
Error: Wechaty Puppet Service requires a SNI as prefix of the token from version 0.30 and later.You can add the "insecure_" prefix to your token的错误。 
在我按照说明修正后，出现提示token does not exist

**Comment by hcfw007** [comment]
我们并非镜像提供方，所以无法提供支持。
