### ISSUE TITLE
[BUG]WorkPro:Wechaty Puppet Service requires a SNI as prefix of the token from version 0.30 and later

### ISSUE THREAD

**Issue by David-AIsx** [wechaty/puppet-service-providers#490]
我是用Docker 部署wechaty：0.65
curl https://api.chatie.io/v0/hosties/ 可获取有效返回
但在使用https://github.com/RPAChat/workpro-getting-started此链接的demo时，出现了Error: Wechaty Puppet Service requires a SNI as prefix of the token from version 0.30 and later.
我依照提示在token前加上insecure_后，出现了token does not exist

**Comment by hcfw007** [comment]
重复 Issue ，关闭。
