### ISSUE TITLE
[BUG]WorkPro:创建群聊报错 WorkproErrorCode: 25030

### ISSUE THREAD

**Issue by cindyuan** [wechaty/puppet-service-providers#493]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**Describe the bug**
创建群聊报错，一直在报错

PuppetService messageSend(xxx, Wechaty error: 13 INTERNAL: WorkproErrorCode: 25030, roomCreate(token: xxx) error! cgi error code: (-2003) message: .) grpc called, messageId: 5191db2beeec7ff1536de48af59a0179

**Info**

 - Platform[Linux]: Linux
 - Runtime version[node]: 20
 - Wechaty version:  "@juzi/wechaty": "^1.0.99"
 - Wechaty Puppet version:  "@juzi/wechaty-puppet": "^1.0.90",

**Comment by hcfw007** [comment]
请现在手机上确认你有创建外部群的权限。

**Comment by cindyuan** [comment]
> 请现在手机上确认你有创建外部群的权限。

是的，确定有创建外部群权限，直接在企微里手动创建没问题

**Comment by hcfw007** [comment]
PuppetService messageSend(xxx, Wechaty error: 13 INTERNAL: WorkproErrorCode: 25030, roomCreate(token: xxx) error! cgi error code: (-2003) message: .) grpc called, messageId: 5191db2beeec7ff1536de48af59a0179

你这个日志看起来像是复制岔行了，前后都是发消息 messageSend 的。

**Comment by cindyuan** [comment]
> PuppetService messageSend(xxx, Wechaty error: 13 INTERNAL: WorkproErrorCode: 25030, roomCreate(token: xxx) error! cgi error code: (-2003) message: .) grpc called, messageId: 5191db2beeec7ff1536de48af59a0179
> 
> 你这个日志看起来像是复制岔行了，前后都是发消息 messageSend 的。

日志截图如下
![企业微信截图_17186067346303](https://github.com/wechaty/puppet-supports/assets/1684476/92960747-b2e2-4f5b-bbc1-d7e209bf6670)

**Comment by hcfw007** [comment]
我查了日志，在所有创建失败的群聊中，群成员id都包含了一个 '1' 。你是怎么进行调用的？

**Comment by cindyuan** [comment]
> 我查了日志，在所有创建失败的群聊中，群成员id都包含了一个 '1' 。你是怎么进行调用的？

不好意思，测试把测试数据弄上去了
