### ISSUE TITLE
[BUG]WorkPro:直接推送公众号链接有问题

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#498]
![image](https://github.com/wechaty/puppet-supports/assets/168573378/94f046af-6519-4c31-a983-ebcb2f9a06ca)

### 以下是我的代码：
![image](https://github.com/wechaty/puppet-supports/assets/168573378/c49f2624-1f91-4586-abf7-8340877c410b)

**Comment by hcfw007** [comment]
哥们，你用发送图片的形式发送公众号链接当然有问题咯。连接的数据叫做 UrlLink

**Comment by IQZZ020501** [comment]
> 哥们，你用发送图片的形式发送公众号链接当然有问题咯。连接的数据叫做 UrlLink

这不不知道嘛，UrlLink是在FileBox包下面吗

**Comment by IQZZ020501** [comment]
已解决

**Comment by IQZZ020501** [comment]
还有个问题，怎么才能在第一时间知道我被我的好友删除了嘞，有没有这个监听事件呢？

**Comment by hcfw007** [comment]
friendship 事件是有多个类型的， 有一个 REMOVED 类型就是被删了。

**Comment by IQZZ020501** [comment]
> friendship 事件是有多个类型的， 有一个 REMOVED 类型就是被删了。

好的我研究一下

**Comment by IQZZ020501** [comment]
> friendship 事件是有多个类型的， 有一个 REMOVED 类型就是被删了。

可以了非常感谢！
