### ISSUE TITLE
[BUG]WorkPro:被好友删除后再添加不会收到好友请求的消息、通过名片分享添加也不会收到好友请求的消息

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#499]

**Comment by hcfw007** [comment]
我这边测试是可以的。
你是如何接收好友请求的呢？

**Comment by IQZZ020501** [comment]
> 我这边测试是可以的。 你是如何接收好友请求的呢？

![image](https://github.com/wechaty/puppet-supports/assets/168573378/c3950b2b-f139-418d-9530-2e2252a21b89)

**Comment by su-chang** [comment]
需要双向删除后，才能收到好友请求，仅单向删除后，再次添加是没有事件的。

**Comment by IQZZ020501** [comment]
> 需要双向删除后，才能收到好友请求，仅单向删除后，再次添加是没有事件的。

好的谢谢
