### ISSUE TITLE
[BUG]WorkPro:朋友圈推送链接消息怎么推送

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#503]

**Comment by hcfw007** [comment]
因为windows客户端原生不支持朋友圈功能，不建议使用此功能，封号风险较高。
如果坚持使用，方法如下：
```ts
const builder = bot.Post.builder()
const urlLink = new bot.UrlLink({
  // ... UrlLink Data
})

builder.add('这是一条朋友圈')
builder.add(urlLink)
builder.type(Post.Moment)
const post = await builder.build()

const publishedPost = bot.publish(post) // 返回一个postServer对象
```
需要注意的是链接朋友圈只能发送一条链接，且不能与图片、视频混发。

**Comment by IQZZ020501** [comment]
> 因为windows客户端原生不支持朋友圈功能，不建议使用此功能，封号风险较高。 如果坚持使用，方法如下：
> 
> ```ts
> const builder = bot.Post.builder()
> const urlLink = new bot.UrlLink({
>   // ... UrlLink Data
> })
> 
> builder.add('这是一条朋友圈')
> builder.add(urlLink)
> builder.type(Post.Moment)
> const post = await builder.build()
> 
> const publishedPost = bot.publish(post) // 返回一个postServer对象
> ```
> 
> 需要注意的是链接朋友圈只能发送一条链接，且不能与图片、视频混发。

好的感谢，了解了

**Comment by IQZZ020501** [comment]
> 因为windows客户端原生不支持朋友圈功能，不建议使用此功能，封号风险较高。 如果坚持使用，方法如下：
> 
> ```ts
> const builder = bot.Post.builder()
> const urlLink = new bot.UrlLink({
>   // ... UrlLink Data
> })
> 
> builder.add('这是一条朋友圈')
> builder.add(urlLink)
> builder.type(Post.Moment)
> const post = await builder.build()
> 
> const publishedPost = bot.publish(post) // 返回一个postServer对象
> ```
> 
> 需要注意的是链接朋友圈只能发送一条链接，且不能与图片、视频混发。

请问对url链接有要求吗？推送链接的时候报错

![image](https://github.com/wechaty/puppet-supports/assets/168573378/3cbc1be6-3b76-4554-b4fc-36b20d88a4df)

![image](https://github.com/wechaty/puppet-supports/assets/168573378/cda24cba-77a4-4aff-b7cd-769a82ac14dc)

**Comment by hcfw007** [comment]
url的数据应该包含以下4个字段。你可以接收一条url消息来看看具体内容。
url,
title,
description,
thumbnailUrl,

**Comment by IQZZ020501** [comment]
> url的数据应该包含以下4个字段。你可以接收一条url消息来看看具体内容。 url, title, description, thumbnailUrl,

所以我需要这样写吗？
![image](https://github.com/wechaty/puppet-supports/assets/168573378/11db84ac-223d-4b48-b5b9-1ac45250221f)

**Comment by IQZZ020501** [comment]
已解决
