### ISSUE TITLE
[BUG]WorkPro: 最近开发过程中遇到的问题，我逐一列举，麻烦帮我解答一下

### ISSUE THREAD

**Issue by chenyl20170103** [wechaty/puppet-service-providers#508]
> 问题1：获取机器人的二维码

我写的代码实例：
const self = bot.currentUser;
const qrcode = await self.qrcode();

执行报错，内容如下：
Error: 12 UNIMPLEMENTED: Wechaty gRPC unsupported API error

> 问题2：机器人主动退群

我写的代码实例：
const room = await bot.Room.find({ 'id': 'R:' + req.roomId });
if (!room) {
throw new Error(ErrorEnum.Room_not_exist);
}
const self = bot.currentUser;
if (!await room.has(self)) {
throw new Error('机器人不在群聊中');
}
await bot.puppet.roomQuit('R:' + req.roomId);
// 另外一种写法
// await room.quit();

执行报错，内容如下：
Error: 13 INTERNAL: WorkproErrorCode: 25042, roomQuit(10724201374841631) error! cgi error code: (-2003) message: .

**Comment by su-chang** [comment]
问题一：不支持
问题二：在手机端看看能否退群，这个应该是被限制了，或者就不在这个群里。

**Comment by chenyl20170103** [comment]
好的，谢谢解答！
