### ISSUE TITLE
[BUG]WorkPro:为什么启动服务的时候，报我的 token does not exist

### ISSUE THREAD

**Issue by ncushujian** [wechaty/puppet-service-providers#509]
在启动服务之前已经配置环境变量 WECHATY_PUPPET_SERVICE_AUTHORITY=token-service-discovery-test.juzibot.com  了

**Comment by su-chang** [comment]
https://token-service-discovery-test.juzibot.com/v0/hosties/TOKEN

通过这个访问下，看看是否能获取到对应的IP和PORT

**Comment by ncushujian** [comment]
> https://token-service-discovery-test.juzibot.com/v0/hosties/TOKEN
> 
> 通过这个访问下，看看是否能获取到对应的IP和PORT

我这边尝试了一下，访问返回的是 {"host":"0.0.0.0","ip":"0.0.0.0","port":0}

**Comment by ncushujian** [comment]
用 api.chatie.io 这个服务地址，是可以返回ip的

**Comment by hcfw007** [comment]
那说明你发现服务注册的地址就是 api.chatie.io，把那个环境变量去掉。
