### ISSUE TITLE
[BUG]WorkPro:为什么我的Token一直是处于离线状态

### ISSUE THREAD

**Issue by ncushujian** [wechaty/puppet-service-providers#510]
![image](https://github.com/wechaty/puppet-supports/assets/57358989/9c286ef0-6669-4336-990b-ba75685b9d5a)

**Comment by hcfw007** [comment]
你要扫码登录了才算做在线。

**Comment by ncushujian** [comment]
> 你要扫码登录了才算做在线。

那为什么启动服务的时候，报我的 token does not exist ?
我这边尝试访问了一下 https://token-service-discovery-test.juzibot.com/v0/hosties/TOKEN ，访问返回的是 {"host":"0.0.0.0","ip":"0.0.0.0","port":0}
这个有好的解决方案么？
