### ISSUE TITLE
[BUG]WorkPro: TypeError: Cannot use 'in' operator to search for 'port' in undefine 项目启动的时候报错

### ISSUE THREAD

**Issue by ncushujian** [wechaty/puppet-service-providers#513]
<img width="584" alt="image" src="https://github.com/wechaty/puppet-supports/assets/57358989/31a8efb2-970d-4f7e-a19c-920a3d4fc390">

**Comment by IQZZ020501** [comment]
node_modules/@grpc/grpc-js/build/src/load-balancer-pick-first.js的415行从const rawAddressList = [].concat(...endpointList.map(endpoint => endpoint.addresses));改为const rawAddressList = endpointList;，修改一下试试

**Comment by ncushujian** [comment]
> node_modules/@grpc/grpc-js/build/src/load-balancer-pick-first.js的415行从const rawAddressList = [].concat(...endpointList.map(endpoint => endpoint.addresses));改为const rawAddressList = endpointList;，修改一下试试

大佬太🐮了！！！！问题已解决！🙏
