### ISSUE TITLE
[BUG]WorkPro:错误代码-4048

### ISSUE THREAD

**Issue by FastCVer** [wechaty/puppet-service-providers#514]
如何避免企业微信错误代码-4048，连续往100多个群里发送文件消息，有些群接收不到文件消息，看日志报：企业微信错误代码-4048。是连续发送有什么限制吗？

**Comment by hanfangyuan4396** [comment]
请问具体什么样子的发送频率会触发此错误代码，如何避免触发此错误代码，增大消息发送间隔是否可以解决，如果可以的话消息发送间隔需要多大

**Comment by hcfw007** [comment]
是发送超频的错误。这个频率限制是企微进行的，我们并没有精确数据。在素材和目标之间增加一些随机延迟可以缓解这一情况。在出现这个错误码后，建议15分钟后重试，如果还有，建议1小时候再重试。

**Comment by hanfangyuan4396** [comment]
目前两个文件消息发送间隔是固定1s延迟，您的意思是改成随机的延时会好一些吗？

因为需要给几百个群发送文件，需要保证时效性，不能过很久才重试，目前有解决这个问题的方法吗



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月09日 18:24 |
| 收件人 | ***@***.***> |
| 抄送至 | Han ***@***.***>***@***.***> |
| 主题 | Re: [wechaty/puppet-supports] [BUG]WorkPro:错误代码-4048 (Issue #514) |

是发送超频的错误。这个频率限制是企微进行的，我们并没有精确数据。在素材和目标之间增加一些随机延迟可以缓解这一情况。在出现这个错误码后，建议15分钟后重试，如果还有，建议1小时候再重试。

**Comment by hcfw007** [comment]
没有，企微就是不想让你这样搞才限制的。

**Comment by hanfangyuan4396** [comment]
明白了，感谢解答
