### ISSUE TITLE
[FEAT]WorkPro: 关于Message.ts中createBroadcast函数的问题

### ISSUE THREAD

**Issue by chenyl20170103** [wechaty/puppet-service-providers#516]
![image](https://github.com/wechaty/puppet-supports/assets/169233231/cda6205b-5144-46fc-a091-e4a5ae03ae07)

老师好：
         请问createBroadcast函数的作用是什么？一般适用于哪些场景下？

**Comment by hcfw007** [comment]
这个是调用企微自带应用的群发助手创建群发。受到群发助手同等的发送条数限制，具体请参考企微的介绍。

**Comment by chenyl20170103** [comment]
请问，参数中POST对象如何获取？

**Comment by hcfw007** [comment]
使用 const buiilder = bot.Post.builder() 获取构造器，然后往里面添加内容，最后 await builder.build() 构造。
