### ISSUE TITLE
[BUG]WorkPro:从群聊里添加机器人怎么监听到好友请求消息

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#519]

**Comment by hcfw007** [comment]
没懂你的问题。
好友请求一般通过 firendship 事件接受。

**Comment by IQZZ020501** [comment]
> 没懂你的问题。 好友请求一般通过 firendship 事件接受。
就是B用户在群聊里添加了A机器人， firendship 事件中没监听到好请求消息

**Comment by hcfw007** [comment]
提供一下token后六位和时间点看看？最好也提供手机收到好友申请的截图

**Comment by IQZZ020501** [comment]
> 提供一下token后六位和时间点看看？最好也提供手机收到好友申请的截图

可以了
