### ISSUE TITLE
[FEAT]WorkPro: 申请了WorkPro试用token，但是通过企业微信扫码提示要跳转到普通微信扫码登陆

### ISSUE THREAD

**Issue by luojingwenaihemiao** [wechaty/puppet-service-providers#524]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

--- YES, I have checked with that already, but hadn't find any solution.

**Describe the bug**

I want to try the token for WorkPro(for WeCom). I have followed the instruction on this page: https://wechaty.js.org/2022/12/23/introducing-workpro-puppet/

Used the Github Codespace, input my 7 days puppet_workpro Token as the instruction guided.

The bot started normally, but when I scan the QR-code with WeCom App, it said the qrcode should be scanned with ordinary WeChat App, then the bot is logged as the WeChat account, NOT the intended WeCom account.

HOW to log on with WeCom account? Thanks!

我申请了WorkPro试用token，并在Github Codespace上按照指引设置了 token。bot能正常启动，但是通过企业微信扫码提示要跳转到普通微信扫码登陆，然后实际登陆的账号就是普通微信账号，而不是企业微信账号了。

如何正确登陆企业微信账号呢？谢谢！

**Info**

 - Platform[Linux]: [Github Codespace](https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=78732688)
 - Runtime version[node]: v20.15.1
 - Wechaty version: 1.20.2
 - Wechaty Puppet version: 1.20.2

**To Reproduce**

1. Go to [WorkPro announcement page of 2022](https://wechaty.js.org/2022/12/23/introducing-workpro-puppet/)
2. Scroll down to '使用 Codespace 运行'
3. Click on 'Github Codespace'
4. Follow the instructions to input puppet_workpro_token.
5. Save and run the code with 'nom start'
6. When the QR-code shows-up, scan the QR-code with WeCom App.
7. The WeCom App will notify that the QR-code should be scanned with ordinary WeChat App instead of WeCom App.

**Expected behavior**

This puppet_workpro_token should allow to log-on bot with WeCom account.

**Screenshots**

When scan the QR-code with WeCom App, it shows-up the QR-code can only be scanned with ordinary WeChat App.

![ScanQRcodeWithWeComApp](https://github.com/user-attachments/assets/75da7b70-660e-47e7-a600-076cb5b7d3b4)

**Comment by hcfw007** [comment]
请提供你的测试代码看看？
我们的token是没有个微登录的能力的，所以应该是token没应用上或者puppet配置不对。

**Comment by luojingwenaihemiao** [comment]
Nick：


您好！感谢回复！


附件里是我所使用的 dingdongbot 示例代码（ding-dong-bot.ts）。


我参考的是以下这个页面的指南输入我的WorkPro_token，并在Github Codespace上运行代码的。
https://wechaty.js.org/2022/12/23/introducing-workpro-puppet/


依赖都正确安装了，代码也运行正常，就是到了扫码阶段用企业微信扫码就提示必须得改用普通微信扫码，然后登陆的就是普通微信，而不是企业微信。我用苹果手机版和安卓手机版的企业微信app都试过了，都是这样。








此外，我的WorkPro token一直是离线状态。重启的两个服务发现地址我也都试过了，都不行。


是不是跟PadLocal一样，我还得自建一个云服务器虚拟机才能正常使用WorkPro？


顺颂夏安


罗景文


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wechaty/puppet-supports"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月19日(星期五) 下午2:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wechaty/puppet-supports] [FEAT]WorkPro: 申请了WorkPro试用token，但是通过企业微信扫码提示要跳转到普通微信扫码登陆 (Issue #524)





 
请提供你的测试代码看看？
 我们的token是没有个微登录的能力的，所以应该是token没应用上或者puppet配置不对。

**Comment by hcfw007** [comment]
不需要虚拟机的。
请使用 https://github.com/RPAChat/workpro-getting-started 这个项目。这个项目只需修改token即可。官方的示例项目需要修改puppet类型。

**Comment by luojingwenaihemiao** [comment]
感谢回复！我之前遇到的问题可能确实是官方ding-dong-bot示例的puppet类型不对。


我刚刚去试了这个workpro-getting-started项目，不过又遇到新问题了。以下是报错信息：


=================================
npm start


&gt; ***@***.*** start
&gt; ts-node index.ts


07:45:35 WARN GrpcManager initClient() TLS: disabled (INSECURE)
***@***.***/grpc-js/src/subchannel-address.ts:40
&nbsp; return 'port' in address;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^
TypeError: Cannot use 'in' operator to search for 'port' in undefined
&nbsp; &nbsp; at isTcpSubchannelAddress ***@***.***/grpc-js/src/subchannel-address.ts:40:16)
&nbsp; &nbsp; at subchannelAddressToString ***@***.***/grpc-js/src/subchannel-address.ts:65:7)
&nbsp; &nbsp; at ***@***.***/grpc-js/src/load-balancer-pick-first.ts:534:90
&nbsp; &nbsp; at Array.map (<anonymous&gt;)
&nbsp; &nbsp; at PickFirstLoadBalancer.updateAddressList ***@***.***/grpc-js/src/load-balancer-pick-first.ts:534:50)
&nbsp; &nbsp; at ChildLoadBalancerHandler.updateAddressList ***@***.***/grpc-js/src/load-balancer-child-handler.ts:137:19)
&nbsp; &nbsp; at onSuccessfulResolution ***@***.***/grpc-js/src/resolving-load-balancer.ts:302:34)
&nbsp; &nbsp; at processTicksAndRejections (node:internal/process/task_queues:85:22)





------------------&nbsp;原始邮件&nbsp;------------------





 
不需要虚拟机的。
 请使用 https://github.com/RPAChat/workpro-getting-started 这个项目。这个项目只需修改token即可。官方的示例项目需要修改puppet类型。

**Comment by hcfw007** [comment]
请参考 https://github.com/wechaty/puppet-supports/issues/364

**Comment by luojingwenaihemiao** [comment]
> 请参考 #364

非常感谢！

**Comment by luojingwenaihemiao** [comment]
> 不需要虚拟机的。
> 请使用 https://github.com/RPAChat/workpro-getting-started 这个项目。这个项目只需修改token即可。官方的示例项目需要修改puppet类型。

用了workpro-getting-started 这个项目确实可以通过企业微信扫码登陆了。问题已解决！赞！
