### ISSUE TITLE
[BUG]WorkPro:调用Room.quit()接口成功，但实际上还是在群聊中。

### ISSUE THREAD

**Issue by jmjoy** [wechaty/puppet-service-providers#530]
调用Room.quit()接口成功，但实际上还是在群聊中，但是调用Room.findAll()找出所有群又没有这个群。

其实我想是解散群聊的接口，但是wechaty并没有，所以先驱逐所有用户再自己退出群聊，结果遇到这个问题。

**Comment by hcfw007** [comment]
你是如何知道自己还在群聊中的？手机上还在群里？能在这个群里发消息吗？

**Comment by jmjoy** [comment]
手机上还在群里

**Comment by hcfw007** [comment]
这个现在还会这样吗？能提供一个新的案例，需要 token 后6位和操作时间（最好1周以内。）
