### ISSUE TITLE
[FEAT]WorkPro: 关于切号以后再登录，会读缓存这个问题有没有什么办法可以规避？每次切号重新登录，会有大量已有的数据，造成我们这边的数据污染。

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#540]

**Comment by hcfw007** [comment]
你这里的已有数据是指消息、联系人还是什么？用id做一下去重？

**Comment by IQZZ020501** [comment]
> 你这里的已有数据是指消息、联系人还是什么？用id做一下去重？

消息，切号重新登陆以后大概会有二十条左右的历史消息记录，塞到数据库，造成数据污染

**Comment by hcfw007** [comment]
这个是肯定会有的。这是为了短期离线时能不漏消息。可以把 messageId 设置为唯一键避免数据问题。
