### ISSUE TITLE
[FEAT]WorkPro: 有没有API可以获取到被引用的图片或者文件或者聊天记录

### ISSUE THREAD

**Issue by liangzhicheng0423** [wechaty/puppet-service-providers#542]
<img width="276" alt="image" src="https://github.com/user-attachments/assets/d5e2ec78-afaf-4d2d-b1d8-76cfb3b4eb1e">

**Comment by liangzhicheng0423** [comment]
我用： await message.getQuotedMessage(); 返回的都是undefined

**Comment by hcfw007** [comment]
需要看看你手机端那条消息的样子，企微接受引用消息根据版本不同有两种格式。

一种是 ———————— 分隔开的文本，这种就只是文本了。另一种是真正的可以点击上去的引用，这种如果是7天内的消息，应该是能获取到原消息的。

**Comment by hcfw007** [comment]
无回复，关闭了。
