### ISSUE TITLE
[BUG]WorkPro:为什么隔一段时间就会报心跳连接的错误，然后就接受不到消息

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#546]
![image](https://github.com/user-attachments/assets/5b353a57-7a6b-47f2-95bf-f9a842599857)

错误信息：
17:51:51 WARN PuppetWatchdogAgent start() reset() reason: {"data":"onGrpcStreamEvent(EVENT_TYPE_DONG)","timeoutMilliseconds":60000}
17:51:51 ERR Bot onError: Error: WatchdogAgent reset: lastFood: "{"data":"onGrpcStreamEvent(EVENT_TYPE_DONG)","timeoutMilliseconds":60000}"
17:51:51 WARN last event was 1171.878 seconds ago, will not request event cache
17:51:51 INFO GrpcManager startStream() connecting event stream with account 1688856370564037 and seq undefined
17:51:52 INFO PuppetService received grpc event EVENT_TYPE_LOGIN on Mon Aug 12 2024 17:51:52 GMT+0800 (中国标准时间), content: "{\"contactId\":\"1688856370564037\"}", seq: 0, timestamp: 1723456312688
17:51:52 WARN PuppetService this login event is ignored because the it is expected by event stream reconnect and this puppet is already logged in

**Comment by hcfw007** [comment]
因为你和服务器的网络连接不太好。

**Comment by IQZZ020501** [comment]
> 因为你和服务器的网络连接不太好。

[汗颜] 找到问题了

**Comment by rookiexun** [comment]
> > 因为你和服务器的网络连接不太好。
> 
> [汗颜] 找到问题了

什么问题？
