### ISSUE TITLE
[BUG]WorkPro:我在getting-started拉完项目之后修改完puppet和token报错大概意思找不到配置的@grpc/grpc-js

### ISSUE THREAD

**Issue by GiockL** [wechaty/puppet-service-providers#548]
Cannot find package '@grpc/grpc-js' imported from C:\Users\25819\Desktop\w\getting-started\node_modules\wechaty-puppet-service\dist\esm\src\auth\grpc-js.js

**Comment by su-chang** [comment]
可以尝试重新安装下依赖。

**Comment by GiockL** [comment]
还是不可以

**Comment by GiockL** [comment]
> 可以尝试重新安装下依赖。
还是不可以

**Comment by GiockL** [comment]
> 可以尝试重新安装下依赖。

还是不行
