### ISSUE TITLE
[FEAT]WorkPro:怎么才能拿到扫码事件中的type呢

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#551]
![image](https://github.com/user-attachments/assets/1b6d3f44-4344-446e-a16a-a8397ce1b17d)

我的代码：
![image](https://github.com/user-attachments/assets/66314bc3-6c75-4d60-aab4-f9da7e25a52d)
![image](https://github.com/user-attachments/assets/97394b24-213d-458f-aee7-2f34f6cd1e6f)

返回的数据：
![image](https://github.com/user-attachments/assets/b4a81fa5-39c3-4e6a-9948-0e6d64d3873f)

**Comment by su-chang** [comment]
目前还不支持通过方法获取对应的值

**Comment by su-chang** [comment]
也可以检查下wechaty的版本，看看回调数据

**Comment by IQZZ020501** [comment]
> 也可以检查下wechaty的版本，看看回调数据

好的谢谢
