### ISSUE TITLE
[BUG]WorkPro:转发合并消息报错

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#553]
我的代码：
![image](https://github.com/user-attachments/assets/7e58908c-426c-4603-a928-e66aad2ce9ea)

报错信息：
![image](https://github.com/user-attachments/assets/9fee5a08-555a-456a-bd5e-4cc91e0b63e7)

**Comment by hcfw007** [comment]
@su-chang

**Comment by IQZZ020501** [comment]
@su-chang 大佬可以回复一下么

**Comment by IQZZ020501** [comment]
> @su-chang

可以说一下mergeForward 方法的第二个参数应该怎么传吗，目前报错的原因是因为messageList 传的不对，拿不到消息ID导致的

**Comment by IQZZ020501** [comment]
> > @su-chang
> 
> 可以说一下mergeForward 方法的第二个参数应该怎么传吗，目前报错的原因是因为messageList 传的不对，拿不到消息ID导致的

这样传可以吗？
![image](https://github.com/user-attachments/assets/a0265129-a915-4b0e-b9c2-de01b8d48fe0)
