### ISSUE TITLE
[FEAT]WorkPro:为什么拿用户的handel会为空

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#557]
![image](https://github.com/user-attachments/assets/8bac4c6b-b1d9-40ce-a1ee-e9a560dd06bf)

![image](https://github.com/user-attachments/assets/45854b49-7092-4d34-b502-f5cd6fd2b2d3)

我的代码：
![image](https://github.com/user-attachments/assets/3021e55d-e133-46af-b85f-f2eb78b56b84)

**Comment by IQZZ020501** [comment]
我在本地可以拿到这个人的信息，但是放在服务器上就不行
本地
![image](https://github.com/user-attachments/assets/7b97810b-1440-44e9-a39c-2673f23fbfee)
线上
![image](https://github.com/user-attachments/assets/1227f3ad-7e0c-4248-b4b7-a63282101515)

相同的还有在本地拿到的好友关系是true，但是在线上就是false
线上：
![image](https://github.com/user-attachments/assets/60d393ae-f229-4ee1-b864-4f482ffd7e12)
本地：
![image](https://github.com/user-attachments/assets/1b6753ed-7fd0-49fc-b741-c9026e3d5384)

**Comment by hcfw007** [comment]
因为不是同一个联系人啊，至少看头像信息不是。

**Comment by IQZZ020501** [comment]
> 因为不是同一个联系人啊，至少看头像信息不是。

是同一个人线上和线下的区别。ps:用的是同一个token 

这个人是线下可以拿到handle 线上拿不到
![image](https://github.com/user-attachments/assets/802969e7-cccf-4a45-97e7-d1a224b0eb66)

这个人是在线下是好友关系在线上不是
![image](https://github.com/user-attachments/assets/374fd2d1-49f9-4fb2-b3ce-0738594c3e95)

目前找到的解决方案是把代码重新部署一次，拿到的信息正确了，但是我想知道这个原因是什么？

**Comment by hcfw007** [comment]
不清楚，看起来像是环境问题。

**Comment by IQZZ020501** [comment]
> 不清楚，看起来像是环境问题。

还发现一个问题就是，假如我掉线了一段时间以后，再登录不是会从消息缓存中获取消息吗，这时候获取到发送消息的人的handle也是空的

**Comment by hcfw007** [comment]
服务器端一旦一个联系人有了handle，是不太可能会变成没有的状态的。这种情况可以考虑获取之前调用一下 contact.sync()，以排除本地过期缓存的问题。

**Comment by IQZZ020501** [comment]
> 服务器端一旦一个联系人有了handle，是不太可能会变成没有的状态的。这种情况可以考虑获取之前调用一下 contact.sync()，以排除本地过期缓存的问题。

好的感谢，请教一下合并转发文件图片视频消息的时候，这个messageList我该如何去传呢？
![image](https://github.com/user-attachments/assets/3005a9ce-b7a0-4975-9431-2c4f4c3a4122)

文本消息目前是做的是从消息缓存中查找，但是同样的方法没办法找到图片视频等内容
![image](https://github.com/user-attachments/assets/a272b42c-cc6d-4e43-8ce9-be2c10bdca37)
所以请教一下合并转发文件图片视频消息我该怎么做？

**Comment by hcfw007** [comment]
你可以用把要转发的消息的 id 记下来，然后用
```
await bot.Message.find({ id })
```
来获取消息实例放到数组里。

**Comment by IQZZ020501** [comment]
> 你可以用把要转发的消息的 id 记下来，然后用
> 
> ```
> await bot.Message.find({ id })
> ```
> 
> 来获取消息实例放到数组里。

好的感谢！
