### ISSUE TITLE
[BUG]WorkPro: 怎么可以获取到朋友圈的评论数和点赞数？发朋友圈怎么设置可见范围？

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#560]

**Comment by hcfw007** [comment]
没有直接的方法可以获取到，但可以监听 post-tap 和 post-comment 事件自行统计。但只能统计到账号在线期间收到的评论与点赞。

**Comment by IQZZ020501** [comment]
> 没有直接的方法可以获取到，但可以监听 post-tap 和 post-comment 事件自行统计。但只能统计到账号在线期间收到的评论与点赞。

好的谢谢
