### ISSUE TITLE
[BUG]WorkPro:findAll如何不获取到群成员或者对其有区分

### ISSUE THREAD

**Issue by 233312-ship-it** [wechaty/puppet-service-providers#563]
findAll 全部成员都获取到了

findAll如何不获取到群成员或者对其有区分

**Comment by IQZZ020501** [comment]
const allContacts = await wechat.Contact.findAll();
const externalContacts = allContacts.filter(c => c.payload?.friend === true && c.payload?.type === 1 && !c.coworker());
这个是获取到企微外部联系人的，获取到内部的把后面的判断去掉就好了
