### ISSUE TITLE
[BUG]WorkPro:登录不稳定总超时，接收几条消息就卡住了

### ISSUE THREAD

**Issue by xh211314** [wechaty/puppet-service-providers#564]
使用的试用Token
1、想知道是试用的服务器不稳定，还是其他问题
2、如果试用的发几条信息就不行了，很难选择购买付费服务

部分日志：
09:31:19 WARN PuppetService this ready event is ignored because the it is expected by event stream reconnect and this puppet is already ready
09:32:50 WARN PuppetWatchdogAgent start() reset() reason: {"data":"regular heartbeat","timeoutMilliseconds":60000}
GError: WatchdogAgent reset: lastFood: "{"data":"regular heartbeat","timeoutMilliseconds":60000}"
    at Watchdog.reset (/workspaces/workpro-getting-started/node_modules/@juzi/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:519:28)
    at Watchdog.emit (node:domain:488:12)
    at Timeout._onTimeout (/workspaces/workpro-getting-started/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"regular heartbeat","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (/workspaces/workpro-getting-started/node_modules/@juzi/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:519:28)\n' +
    '    at Watchdog.emit (node:domain:488:12)\n' +
    '    at Timeout._onTimeout (/workspaces/workpro-getting-started/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:581:17)\n' +
    '    at processTimers (node:internal/timers:519:7)'
}
09:32:50 WARN last event was 411.506 seconds ago, will not request event cache 
09:32:50 INFO GrpcManager startStream() connecting event stream with account 1688856320354046 and seq undefined
09:32:51 INFO PuppetService received grpc event EVENT_TYPE_LOGIN on Thu Sep 05 2024 09:32:51 GMT+0000 (Coordinated Universal Time), content: "{\"contactId\":\"1688856320354046\"}", seq: 0, timestamp: 1725528771027
09:32:51 WARN PuppetService this login event is ignored because the it is expected by event stream reconnect and this puppet is already logged in

09:33:06 INFO PuppetService received grpc event EVENT_TYPE_READY on Thu Sep 05 2024 09:33:06 GMT+0000 (Coordinated Universal Time), content: "{\"data\":\"data ready\"}", seq: 0, timestamp: 1725528786027
09:33:06 WARN PuppetService this ready event is ignored because the it is expected by event stream reconnect and this puppet is already ready

**Comment by IQZZ020501** [comment]
可能是你这边网络不稳定，或者是原本使用token启动了这个服务，然后那个服务没有关掉，又使用该token重新启动了一个服务就会有这个连接的问题（ps：自己在测试环境中偶然发现的）
