### ISSUE TITLE
[BUG]WorkPro:使用wechaty 版本没问题,切换成@juzi/wechaty就报错

### ISSUE THREAD

**Issue by hq199908** [wechaty/puppet-service-providers#576]
![image](https://github.com/user-attachments/assets/c034d1c1-9dbc-4d38-8eab-54c8df63baf2)
![image](https://github.com/user-attachments/assets/1e7249e8-07e4-4c8a-8317-39fc83d793e6)

**Comment by hcfw007** [comment]
提供 package.json 的依赖版本

**Comment by hq199908** [comment]
> 提供 package.json 的依赖版本

我的问题  不好意思 我在其他文件里面引入的还是 wechaty这个包 其他文件里面的没有更新
