### ISSUE TITLE
[FEAT]WorkPro:想请问一下怎么使用企微官方的群发

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#580]
看到Post支持：
![image](https://github.com/user-attachments/assets/fd695879-2085-433c-9181-6c46aeee1dc6)

怎么使用这个群发？

**Comment by IQZZ020501** [comment]
@hcfw007 @su-chang 可以回复一下么

**Comment by IQZZ020501** [comment]
> @hcfw007 @su-chang 可以回复一下么

@hcfw007 @su-chang

**Comment by hcfw007** [comment]
先用 postBuilder 创建一个 post，类型为 broadcast，然后用 message.createBroadcast 创建

**Comment by IQZZ020501** [comment]
> 先用 postBuilder 创建一个 post，类型为 broadcast，然后用 message.createBroadcast 创建

好的谢谢
