### ISSUE TITLE
[BUG]WorkPro: I can't log in wechaty again after my session expired on my mobile phone

### ISSUE THREAD

**Issue by junmo1215** [wechaty/puppet-service-providers#587]
**Describe the bug**

I can't log in wechaty again after my session expired on my mobile phone

**Info**

- Platform[e.g. Windows/Mac/Linux]: Docker (Base image node:21.5.0)
- Runtime version[e.g. node/JAVA]: node
- Wechaty version: "wechaty": "^1.20.2"
- Wechaty Puppet version: wechaty-puppet-service-1.19.9

**To Reproduce**

1. This morning, I found that I was logged out of the WeCom app on my mobile phone.
2. After re-logging into the Enterprise WeChat app on my mobile phone, I tried to log into Wechaty.
3. After scanning the Wechaty QR code with my phone, Wechaty progressed to Status 3 (Scanned) and then Status 4 (Confirmed).
4. Then the QR code reappeared, and the status changed back to 2 (Waiting).

**Expected behavior**

Login normal

**Screenshots**

![image](https://github.com/user-attachments/assets/d4d8023a-9dbe-4f65-a992-d5112603f677)

**Comment by mojo-bo-coder** [comment]
好像是企微更新导致的，我也是这样，客服说他们正在处理兼容性的事儿

**Comment by mustcarrayout** [comment]
> 好像是企微更新导致的，我也是这样，客服说他们正在处理兼容性的事儿

 哥们，你也在基于这个开源项目对接企业微信吗？目前是测试阶段还是已经投产了，生产环境的稳定性如何？

**Comment by mojo-bo-coder** [comment]
@mustcarrayout 嗯对，稳定性其实可以的。已经生产环境用了一段时间了，突然企业微信升级一下子无法登录了。主要是我有几个账户，有的能有的不行，估计是被微信灰度升级了

**Comment by mojo-bo-coder** [comment]
已经恢复了

**Comment by mustcarrayout** [comment]
> 已经恢复了

多谢提醒。

**Comment by mustcarrayout** [comment]
> @mustcarrayout 嗯对，稳定性其实可以的。已经生产环境用了一段时间了，突然企业微信升级一下子无法登录了。主要是我有几个账户，有的能有的不行，估计是被微信灰度升级了

方便加好友聊一下你们是怎么用的吗？

**Comment by junmo1215** [comment]
I verified today that the service has been restored. Thank you, everyone.

I will close this issue.
