### ISSUE TITLE
[BUG]WorkPro:发送小程序消息报错 Code 13, Invalid URL

### ISSUE THREAD

**Issue by cindyuan** [wechaty/puppet-service-providers#588]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

群聊发送小程序消息报错
![image](https://github.com/user-attachments/assets/ea1c52d9-ed1b-4152-a775-8eae4054e3b6)

参数如下
```
const miniProgram = new bot.MiniProgram({
                        username: "gh_1138ac00c2bd", 
                        appid: "wx710087d3a838159e", 
                        title: "院外管家",
                        pagepath: "subPackages/doctor/pages/patient-detail",
                        thumbnailurl: "https://page.xinluomed.com/scr_pic/6_05.png",
                    });
const room = await bot.Room.find({ id: "R:10859503770548841" });
                        await room ?.say(miniProgram)
```

**Info**

 - Platform[e.g. /Mac/Linux]: Windows
 - Runtime version[e.g. /JAVA]:node
 - Wechaty version: juzi+wechaty@1.0.100
 - Wechaty Puppet version: juzi+wechaty-puppet@1.0.91

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cindyuan** [comment]
排查到了，是参数不对引起的，已参考下面的链接修改了小程序消息体的参数，文档实在是不好找
 https://github.com/wechaty/puppet-supports/issues/349
https://github.com/wechaty/puppet-padlocal/wiki/API-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3-(TypeScript-JavaScript)#%E5%8F%91%E9%80%81%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%8D%A1%E7%89%87

**Comment by IQZZ020501** [comment]
> 排查到了，是参数不对引起的，已参考下面的链接修改了小程序消息体的参数，文档实在是不好找 #349 https://github.com/wechaty/puppet-padlocal/wiki/API-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3-(TypeScript-JavaScript)#%E5%8F%91%E9%80%81%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%8D%A1%E7%89%87

puppet-padlocal和workPro的参数好像也有不一样的，建议先把消息发送到bot上面查看一下消息格式
