### ISSUE TITLE
[FEAT]WorkPro: 企微扫码登录后，是否有获取所有包含当前账号的群的方法

### ISSUE THREAD

**Issue by WWj5921** [wechaty/puppet-service-providers#589]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by IQZZ020501** [comment]
const group = await wechat.Room.findAll()
console.log("group>>>>>", group);
