### ISSUE TITLE
我续费token，客服已经四天不回消息了，钱也汇过去三天了，token已经过期无法使用，导致公司业务滞停，公司还要对我进行处罚，请你们给我一个解释。

### ISSUE THREAD

**Issue by shuangyangshui** [wechaty/puppet-service-providers#591]
Please make sure you have read the [Wechaty Puppet Service](https://wechaty.js.org/docs/puppet-services/) from Wechaty Official Website before you continue writting this issue.

**Comment by shuangyangshui** [comment]
打电话也不接

**Comment by su-chang** [comment]
提供下token的后6位，我来确认下。

**Comment by su-chang** [comment]
@shuangyangshui 同时将该issue链接发送给客服。

**Comment by shuangyangshui** [comment]
@su-chang 78fae4,客服不理我，需要我把我的付款凭证给你

**Comment by su-chang** [comment]
@shuangyangshui 我这边临时处理了，你再重连下看看。

**Comment by shuangyangshui** [comment]
@su-chang 已经好了，谢谢，我续费的费用已经付过去了请帮我尽快处理，很急。你临时给了我几天？

**Comment by su-chang** [comment]
先按从今天开始，续费一年进行处理。我们内部沟通完后，再和你同步下信息。

**Comment by shuangyangshui** [comment]
好的，谢谢

**Comment by shuangyangshui** [comment]
@su-chang 你好，能把增票开一下吗

**Comment by hcfw007** [comment]
你是跟哪位微信联系的呢，一直联系不上？

**Comment by shuangyangshui** [comment]
RPAchat  这个客服，企业微信实名龙

**Comment by shuangyangshui** [comment]
转账记录我怎么发你，帮忙开一下增票谢谢！然后把token显示的时长可视化，也更新一下

**Comment by shuangyangshui** [comment]
@hcfw007

**Comment by su-chang** [comment]
@shuangyangshui 你再联系下客服，同时把该issue发给客服
