### ISSUE TITLE
[BUG]WorkPro:Error: no grpc manager

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#592]
![image](https://github.com/user-attachments/assets/2e019b71-ad85-43e7-9c87-0a1f7a632d66)

![image](https://github.com/user-attachments/assets/9dbcba1e-e8e1-4c19-9590-9ceed9595d22)

![image](https://github.com/user-attachments/assets/0deb5486-d291-44c1-bc18-56761918ed23)

突然抛出来这么多异常是我这边的网络问题吗？

**Comment by IQZZ020501** [comment]
这个报错今天抛了两次。会导致程序直接终止。有没有什么补救机制？

**Comment by su-chang** [comment]
可以增加超时时间看看，同时也关注下这个问题的出现频次，以及出现时有啥特殊行为么？
```ts
puppetOptions: {
  timeoutSeconds: 4 * 60 
}
```

**Comment by IQZZ020501** [comment]
> 可以增加超时时间看看，同时也关注下这个问题的出现频次，以及出现时有啥特殊行为么？
> 
> ```ts
> puppetOptions: {
>   timeoutSeconds: 4 * 60 
> }
> ```

目前只有我发起这个issues当天出现了三四次次，所有的bot同时出现了。没有对bot操作，突然就弹出来了报错，重启以后还会弹出。

**Comment by IQZZ020501** [comment]
> 可以增加超时时间看看，同时也关注下这个问题的出现频次，以及出现时有啥特殊行为么？
> 
> ```ts
> puppetOptions: {
>   timeoutSeconds: 4 * 60 
> }
> ```

请问一下这个timeoutSeconds 是超时不做处理还是什么作用？

**Comment by su-chang** [comment]
延长默认超时时间，从默认的1分钟超时调整为4分钟

**Comment by IQZZ020501** [comment]
> 延长默认超时时间，从默认的1分钟超时调整为4分钟

谢谢
