### ISSUE TITLE
[BUG]WorkPro:设置群管理员的时候报错

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#595]
![image](https://github.com/user-attachments/assets/1580e75b-76ad-48d3-beda-dd8b6e795f91)

报错信息：
![image](https://github.com/user-attachments/assets/14d7a8df-0ea0-4960-9b87-92d923e7cb43)

**Comment by hcfw007** [comment]
如报错所说，并非所有要添加为管理员的人都是这个企业的员工。

**Comment by IQZZ020501** [comment]
> 如报错所说，并非所有要添加为管理员的人都是这个企业的员工。

嗷嗷，明白了
