### ISSUE TITLE
[BUG]WorkPro:合并转发报错

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#600]
![image](https://github.com/user-attachments/assets/1b02da45-1215-4b51-95fa-12eef2a93b7a)

我的代码：
![image](https://github.com/user-attachments/assets/8a43702b-7ee2-4a12-bf5f-2b413ff4a562)

**Comment by IQZZ020501** [comment]
@hcfw007 @su-chang 可以回复一下这个问题吗

**Comment by su-chang** [comment]
企业微信相关逻辑有所调整，目前该功能还在适配中。

**Comment by IQZZ020501** [comment]
> 企业微信相关逻辑有所调整，目前该功能还在适配中。

大概什么时候可以适配好呢

**Comment by su-chang** [comment]
暂时没有明确排期，并行企微升级后，对接内容比较复杂，大概会在明年1月底适配完成。

**Comment by IQZZ020501** [comment]
> 暂时没有明确排期，并行企微升级后，对接内容比较复杂，大概会在明年1月底适配完成。

好的
