### ISSUE TITLE
[BUG]WorkPro:托管账号退出登录后怎么清除掉这个账号的缓存？

### ISSUE THREAD

**Issue by IQZZ020501** [wechaty/puppet-service-providers#606]
![image](https://github.com/user-attachments/assets/0623c366-2b6b-4adc-ae87-4f8d855e2bef)
这是我在login事件打印的。第一个人和第二个人使用的是同一个token。第二个人退出登录后第一个人有使用这个token去登录了，然而在login事件中还能打印出来第二个人的信息。

退出是直接在手机上退出的没走bot.logout()

**Comment by IQZZ020501** [comment]
> ![image](https://private-user-images.githubusercontent.com/168573378/384255382-0623c366-2b6b-4adc-ae87-4f8d855e2bef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDIxMTYsIm5iZiI6MTczMTQwMTgxNiwicGF0aCI6Ii8xNjg1NzMzNzgvMzg0MjU1MzgyLTA2MjNjMzY2LTJiNmItNGFkYy1hZTg3LTRmOGQ4NTVlMmJlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQwODU2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjI3YmZmMTlmNTYyNWM1OThhYmFiYjE5ZjQyMTU1NmU2NjRlMjMzMWRjNjM2ODUyMzY3ZWU4NDU0OThjMDc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UOslE4vVC2RYxuvYFRRzgp595D1t4LTncp09mRWEDSg) 这是我在login事件打印的。第一个人和第二个人使用的是同一个token。第二个人退出登录后第一个人有使用这个token去登录了，然而在login事件中还能打印出来第二个人的信息。
> 
> 退出是直接在手机上退出的没走bot.logout()

同一个人登录多次就会出现这种情况
![image](https://github.com/user-attachments/assets/ae9baefd-e50b-4ff7-95b7-1f5a9e8f3df6)

**Comment by su-chang** [comment]
建议一个token只绑定一个企微账号进行使用。可以删除.wechaty缓存文件清理掉。

**Comment by IQZZ020501** [comment]
> 建议一个token只绑定一个企微账号进行使用。可以删除.wechaty缓存文件清理掉。

就是一个token绑定一个账号的，上述问题是当这个账号退出登录以后再重新登陆就会出现的问题。

**Comment by IQZZ020501** [comment]
> 建议一个token只绑定一个企微账号进行使用。可以删除.wechaty缓存文件清理掉。

是不是只有在实例化wechaty的时候指定了name才会有.wechaty的文件呢，目前没指定name没发现.wechaty的文件

**Comment by su-chang** [comment]
需要扫码登录看看

**Comment by IQZZ020501** [comment]
> 需要扫码登录看看

扫码登陆成功以后没有看到该文件
