### ISSUE TITLE
[BUG]WorkPro: 通过say(FileBox)发送的图片，在重庆区域的企微客户端均无法显示

### ISSUE THREAD

**Issue by JellyBo** [wechaty/puppet-service-providers#610]
如图，通过say(FileBox)发送的图片，在广州地区访问手机端/PC端都是正常的，重庆地区访问则图片无法显示。
已经经过一轮排查：
- 通过接口发送的图片，在广州地区内部群/外部群均可显示和保存，在重庆地区均不可显示
- 通过企微客户端发送的图片则可正常显示
- 在重庆手机端（电信）、PC端（联通宽带）均无法显示
- 通过say(FileBox)发送文件可以正常下载，只有图片不行
- 非个例，重庆多个用户均无法显示图片

<img width="605" alt="image" src="https://github.com/user-attachments/assets/ae7bc10c-5b97-4b01-9e43-11896469c73a">
<img width="446" alt="image" src="https://github.com/user-attachments/assets/8157c9a6-f9e8-42ab-b56a-183ab441ecee">
<img width="628" alt="image" src="https://github.com/user-attachments/assets/342f8f35-ec00-4309-a0fa-767c447d62b0">

版本：
"@juzi/wechaty": "^1.0.99",
"@juzi/wechaty-puppet-service": "^1.0.99",

token后8位：5b0ad7e7

**Comment by su-chang** [comment]
这个是CDN服务有点问题，目前已经恢复

**Comment by JellyBo** [comment]
> 这个是CDN服务有点问题，目前已经恢复

已正常，谢谢
