### ISSUE TITLE
[BUG]WorkPro:bot启动失败

### ISSUE THREAD

**Issue by qiangqiesheng** [wechaty/puppet-service-providers#611]
输出信息：
![image](https://github.com/user-attachments/assets/0e49018a-5aef-4f8c-90bf-0e6e3372d8cf)

token后六位：
81b572、7e2e7d、5d4ae8

**Comment by IQZZ020501** [comment]
> 输出信息： ![image](https://private-user-images.githubusercontent.com/165547913/389340460-0e49018a-5aef-4f8c-90bf-0e6e3372d8cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTE0MjEsIm5iZiI6MTczMjUxMTEyMSwicGF0aCI6Ii8xNjU1NDc5MTMvMzg5MzQwNDYwLTBlNDkwMThhLTVhZWYtNGY4Yy05MGJmLTBlNmUzMzcyZDhjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwNTA1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2IzZDZmYjdjYjBlOGQxOTI1NGYxNTAxM2U0NjRkMWJhZGM4Yjc1YjU2NWRhNTU4NjU2MTUyYTI1ZTYxODQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tuMqe2a1SWOt1SPJZJqCUk0FK811C81lkDaha4G7uD4)
> 
> token后六位： 81b572、7e2e7d、5d4ae8

**Comment by su-chang** [comment]
@qiangqiesheng 现在是否正常？

**Comment by qiangqiesheng** [comment]
> @qiangqiesheng 现在是否正常？

昨天把token重启了一下就可以正常使用了
