### ISSUE TITLE
[BUG]WorkPro: send video but got file in wechat

### ISSUE THREAD

**Issue by junmo1215** [wechaty/puppet-service-providers#620]
I send a video in 企业微信 to wechat via workpro, but what I received in wechat is displayed as file

**Info**

- Platform[e.g. Windows/Mac/Linux]: Docker (Base image node:21.5.0)
- Runtime version[e.g. node/JAVA]: node
- Wechaty version: "wechaty": "^1.20.2"
- Wechaty Puppet version: wechaty-puppet-service-1.19.9

**To Reproduce**

1. I upload my video into S3, generate a public url,
2. put it into a filebox object (Tested fill md5, metadata, and name properties, but it didn't work)
3. using Contract.say(filebox) to send this video

the filebox object is looked like:
```
FileBox {
  version: '1.5.5',
  _type: 2,
  _size: -1,
  md5: '44abd6c69b8506bd5bfda793efe662ad',
  mimeType: 'application/unknown',
  _mediaType: 'video/mp4',
  _name: 'daily_summary.mp4',
  _metadata: { duration: 82 },
  base64: undefined,
  remoteUrl: 'https://xxxx/d26eba94db254290b6da71f90151c2d0.mp4',
  qrCode: undefined,
  uuid: undefined,
  buffer: undefined,
  localPath: undefined,
  stream: undefined,
  headers: undefined
}
```

**Expected behavior**

At the receiver's end, it should looked like a video and could be played directly, but somehow it appeared as a file instead of video

**Screenshots**

![image](https://github.com/user-attachments/assets/20829850-da4b-428f-91d0-ed3262240c07)

**Comment by IQZZ020501** [comment]
It seems to be designed like this. Anything larger than 10 MB or 20 MB is sent as a file.

**Comment by junmo1215** [comment]
> It seems to be designed like this. Anything larger than 10 MB or 20 MB is sent as a file.

Thank you for your response, that might be the explanation.

I tested some videos smaller than 20 MB, and they seem to work fine.
